### ISSUE TITLE
This scroll bar should disappear

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1355]
**Describe the bug**
![image](https://user-images.githubusercontent.com/62053368/118864134-f904ef00-b8df-11eb-98a5-e53ef51b3976.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tommygonzaleza** [comment]
This has been solved already
