### ISSUE TITLE
You cant see all video and cannot scroll down

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1356]
**Describe the bug**

![image](https://user-images.githubusercontent.com/62053368/118867174-1091a700-b8e3-11eb-9174-b2ed67d77567.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Khrisefzm** [comment]
This issue was solving.
