### ISSUE TITLE
This is not the correct font and dont mention that we are the best of spain according to Premios Excelencia Educativa

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1357]
**Describe the bug**

Change Font
Add information about Premios Excelencia educativa in spain
There are 2 points at the end of the phrase 

![image](https://user-images.githubusercontent.com/62053368/118867923-e68cb480-b8e3-11eb-9135-c8aff30c11dd.png)

**To Reproduce**
1. Go to https://next.4geeksacademy.com/es/coding-bootcamp/full-stack-part-time

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Khrisefzm** [comment]
This issue was solved.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/9c3bec99-cabd-4012-9928-61fcc228d684)
