### ISSUE TITLE
Testing is not mentioned here

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1358]
**Describe the bug**
We should talk about testing that we have included in the program

![image](https://user-images.githubusercontent.com/62053368/118868234-3ff4e380-b8e4-11eb-9b95-ece071d68d0e.png)

For both, part-time and full-time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2135
