### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1359]
**Describe the bug**

Should be "por el resto de tú vida" instead of "por el resto de su vida"

Carefull with the spanglish, "Compare 4Geeks with other bootcamps." must be changed to "Compara 4Geeks con otros bootcamps"

![image](https://user-images.githubusercontent.com/62053368/118868480-864a4280-b8e4-11eb-8390-e0a8603a01c9.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Khrisefzm** [comment]
This issue was solved.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/87e9c96d-fe4b-49c4-a4c0-a244cb0658bc)
