### ISSUE TITLE
Dice que el full-time dura 16 semanas y no indica que el part-time es en formato part-time

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1361]
**Describe the bug**
Debe indicar 9 semanas en vez de 16 y el Part-time debe indicar que es part-time

![image](https://user-images.githubusercontent.com/62053368/118868996-22744980-b8e5-11eb-803c-fe3cbc2ee64f.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jatv93** [comment]
@alesanchezr esto es urgente, lo puedes revisar? Tengo gente preguntando si aumentamos las semanas por esto

**Comment by Khrisefzm** [comment]
This issue was solved
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/9472b235-6652-49ef-98a9-71c864814383)
