### ISSUE TITLE
<VideoPlayer> higher order component

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#1394]
Integrate with the Youtube Player API using React.js to augment the functionalities that come with the youtube player, focusing on education.

- [ ] Videos tutorials will load from repository API with type=VIDEO
- [ ] Play, pause, mute, control volume, jump ahead using the timeline.
- [ ] Fast forward (2x & 3x)
- [ ] Table of contents: Show a list of topics discussed in the video and be able to jump to that particular moment (you can get that from the api).
- [ ] Listen to Jump event from the website: When the video is embeded in a website it can listen to a "jump_video" event and jump to the position the event information contains, this will be mainly used to click in a word in the video transcript and be able to jump to the moment in the video when that word was said.

This library can be useful, I have used it successfully before: https://cookpete.com/react-player/

**Comment by tommygonzaleza** [comment]
We already developed this componenet
