### ISSUE TITLE
Logos cortados y pixelados

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1452]
**Describe the bug**
estos logos de los medios están pixelados y el de cnn cortado
![image](https://user-images.githubusercontent.com/62053368/120645778-1b1e7580-c479-11eb-92c6-d53648bdc669.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
No logro replicarlo, en que navegador y sistema operativo?

**Comment by victormgomezp** [comment]
Windows y Chrome

**Comment by veljzs** [comment]
No se logro replicar
