### ISSUE TITLE
Todos los estudiantes de los TESTIMONIOS son de miami y uno está repetido

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1454]
**Describe the bug**
Tiene que haber estudiantes de todas las academias, no solo miami.

Tampoco funciona el clic de view review y no se traduce al español

![image](https://user-images.githubusercontent.com/62053368/120646760-21f9b800-c47a-11eb-825f-e7ebf3806526.png)

**To Reproduce**
1. Go to https://next.4geeksacademy.com/es/testimonios

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by G-code7** [comment]
https://github.com/breatheco-de/breatheco-de/issues/6359

vale ya tenía este otro issue.  lo dejo acá com referencia para hacer ambas cosas
