### ISSUE TITLE
REST APIs lesson is not following naming convention correctly

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#1462]
[REST APIs lesson](https://content.breatheco.de/lesson/understanding-rest-apis) is not following naming convention correctly: https://restfulapi.net/resource-naming/. For example: it's using low dashes, instead of dashes.

**Comment by Khrisefzm** [comment]
There exists low dashes instead of dashes:
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/1b040bfd-d525-4423-b49b-770a8cf72abe)
