### ISSUE TITLE
Add endpoints to get support about coding errors

### ISSUE THREAD

**Issue by jefer94** [breatheco-de/breatheco-de#1709]
This endpoints have divide in two sections:

1. `support/answer` is a answer to a ticket, this endpoint can be use for teachers and mentors to answer or do question about the problem and the owner of ticket, this owner generally is a student can use this endpoint to do questions about this ticket
2. `support/tutorial` is a general answer to each ticket of this style, this pretend feed a frontend that render a simple tutorial in format of blog

This issue is related to https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1708

## The requirements to the `support/answer` is:

- [ ] Add auth with `capable_of` to `AnswerView`
- [ ] GET `v1/support/ticket/{ticket_id}/answer`
  - [ ] add `user_id` in querystring and this must support pass many element using comma `,`
  - [ ] paginate the response
- [ ] GET `v1/support/ticket/{ticket_id}/answer/{answer_id}`
- [ ] GET `v1/support/academy/{academy_id}/ticket/{ticket_id}/answer` (the same as `v1/support/ticket/{ticket_id}/answer`)
- [ ] GET `v1/support/academy/{academy_id}/ticket/{ticket_id}/answer/{answer_id}`
- [ ] POST `v1/support/ticket/{ticket_id}/answer`
  - [ ] `user_id` must be set
  - [ ] `ticket_id` must be set
  - [ ] `answer` must be set
  - [ ] notify to the ticket owner and the current agent with slack and email each new answer
- [ ] PUT `v1/support/ticket/{ticket_id}/answer/{answer_id}`
- [ ] DELETE `v1/support/ticket/{ticket_id}/answer/{answer_id}`
  - [ ] just can be deleted by the owner`
- [ ] GET `v1/support/ticket/{ticket_id}/tutorial`
- [ ] POST `v1/support/ticket/{ticket_id}/tutorial`
- [ ] PUT `v1/support/ticket/{ticket_id}/tutorial/{tutorial_id}`
- [ ] each requirement need be cover with a test

The `Answer` specification
```python
{
    "user_id": 1,
    "ticket_id": 1,
    "answer": "Additional details to resolve this issue",
}
```

The `TicketAgent` specification
```python
{
    "user_id": 1,
    "ticket_id": 1,
}
```

The `TicketTutorial` specification
```python
{
    "tutorial_id": 1,
    "ticket_id": 1,
}
```

## The requirements to the `support/tutorial` is:

- [ ] The data must be save with Google Cloud Datastore
- [ ] Add auth with `capable_of` to `TutorialView`
- [ ] GET `v1/support/tutorial`
  - [ ] add `author_id`, `academy_owner_id`, `name`, `description`, `status_code`, `status_text`, `stack_trace`, `log`, `command` and `library` in querystring and this must support pass many element using comma `,`
  - [ ] we can get all the tutorials from the current academy and the public tutorials of the other academies
  - [ ] paginate the response
- [ ] GET `v1/support/tutorial/{tutorial_id}`
- [ ] POST `v1/support/tutorial`
  - [ ] `author_id` must be set
  - [ ] `academy_owner_id` must be set
  - [ ] `name` must be set
  - [ ] `description` must be set
  - [ ] `content` must be set
  - [ ] `status_code`, `status_text`, `stack_trace` or `log`  must be set
  - [ ] `command` or `library`  must be set
- [ ] PUT `v1/support/tutorial/{tutorial_id}`
  - [ ] prevent `status_code`, `status_text`, `stack_trace` and `log` to be empty at once
  - [ ] prevent `command` and `library` to be empty at once
- [ ] DELETE `v1/support/tutorial/{tutorial_id}`
  - [ ] just can be deleted by the academy owner
- [ ] each requirement need be cover with a test

The `Tutorial` specification
```python
{
    "author_id": 1,
    "academy_owner_id": 1,
    "private": False,
    "description": "Additional details to resolve this issue",
    "name": "title of tutorial",
    "content": "body of tutorial", 
    "command": "yarn start" or None,
    "library": "react" or None,
    "status_code": 100 or None,
    "status_text": "ENOTFOUND" or None,
    "stack_trace": "stack trace for the error as string" or None,
    "log": "command output" or None,
}
```

**Comment by alesanchezr** [comment]
Will not get done.
