### ISSUE TITLE
el campo de correos no acepta 2 puntos en la dirección (ejemplo .com.ve)

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#1740]
el campo de correo electrónico de los formularios no acepta direcciones como vgomez@stcsolutions.com.ve
si debe aceptar porque hay muchas direcciones de correo que tienen dos puntos en el dominio. 

el ejemplo lo hemos descubierto en las landings de las becas https://4geeksacademy.com/es/landing/becas-landing-jobs-spain aunque seguro es del componente.

**Comment by Khrisefzm** [comment]
This issue was solved.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/2bdbf612-efcc-4af2-882e-d92910b1d927)
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/23905a72-c9e0-4c15-9779-b8f7373c9858)
