### ISSUE TITLE
When creating a new cohort, the default timezone should be the same as the academy timezone unless specified otherwise

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#1832]
- [ ] Fix the POST /cohort  endpoint to make timezone matches the academy timezone if None
- [ ] Create a new test to verify that it works.

**Comment by tommygonzaleza** [comment]
This issue has been solved here: https://github.com/breatheco-de/apiv2/blob/7390419c64de19faf464a676c58a92042ca788c4/breathecode/admissions/views.py#L1241C8-L1242C48
