### ISSUE TITLE
Student profile page > github username link for external window with github profile

### ISSUE THREAD

**Issue by ColbyWTaylor** [breatheco-de/breatheco-de#1844]
A small request but would be preferable to have an "external link" icon next to the github name to more smoothly access github information, instead of needing to copy the username, open up a new tab, start typing github, paste the name, and hit enter. I'm ready for a nap just typing that out!

**Comment by alesanchezr** [comment]
![BreatheCode-Academy-Admin (4)](https://user-images.githubusercontent.com/426452/136618177-e0ce807d-84a3-4dd4-8c0e-9f78ad09a17c.png)

**Comment by JParedesArtica** [comment]
Según la imagen mostrada, ya existe el botón que te redirige al github del estudiante al hacer click
