### ISSUE TITLE
Assignment status not checking for submission

### ISSUE THREAD

**Issue by ColbyWTaylor** [breatheco-de/breatheco-de#1851]
On Student Assignments page (https://assignments.breatheco.de/XXXXXXXX), if the assignment has not been delivered, it should not be possible to review. A solution is to either grey it out until the assignment has been submitted or not show the button at all until it has been submitted.

**Comment by alesanchezr** [comment]
When the button is pressed, let's show a modal saying: The student has not delivered this assignment yet. Send the following URL to the student for delivery.

**Comment by JParedesArtica** [comment]
La solución ya fue planteada
