### ISSUE TITLE
Diseñar la modal para instigar a pagar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#3007]
Everything you will access once you upgrade:

- Unlimited mentorships, 5 released every week.
- Access to read, watch and practice all content.
-

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4370%3A11971

**Comment by alesanchezr** [comment]
Se actualizaron los requerimientos.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4597%3A16579

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4597%3A16579

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4633%3A14329

**Comment by alesanchezr** [comment]
@ArielCalisaya ya esta modal esta lista para codificarla.

Esto vamos a montarlo en storybooks y luego la usaremos para instigar a pagar en las partes pagas del dashboard.

**Comment by tommygonzaleza** [comment]
Los planes de pago y los bullets deben ser customizables desde un json en el storybook: https://breatheco-de.github.io/app/?path=/story/components-upgradeaccessmodal--default&args=open:false&globals=locale:en;locales.en:English;locales.es:Spanish

**Comment by tommygonzaleza** [comment]
Esto ya fue implementado
