### ISSUE TITLE
Text: What Leads Expect After Applying

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#3040]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/31259790?key=2294d49d5ab9e99237399780c69c52d8&size=orig) 

 Text: What Leads Expect After Applying

---
**Source URL**:
[https://4geeksacademy.com/us/apply](https://4geeksacademy.com/us/apply)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1932



![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/53906fd6-b4a7-44d3-8be9-4ee90492a2f0)
