### ISSUE TITLE
El contenido del nuevo programa de Node.js Full-Stack Part-Time contiene contenido en Python y Flask

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#3195]
![Screenshot 2022-09-06 at 19-31-38 Join this video meeting](https://user-images.githubusercontent.com/410890/188702025-c3aa2c8c-41fd-41ce-acbd-75cd66eecb2e.png)
![Uploading Screenshot 2022-09-06 at 19-34-05 Join this video meeting.png…]()

**Comment by tommygonzaleza** [comment]
Deberia cambiar la verison del syllabus en el admin de django? O que se deberia hacer para que ya este publico con la nueva version?

**Comment by tommygonzaleza** [comment]
@alesanchezr
