### ISSUE TITLE
Rediseñar componente que explica geekforce/geekpal

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#3480]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35317-edf5acb1acb3828da5801aaa2313caa9) 

 Mostrar graficamente la interseccion entre ambos servicios y como se complementan para darte la educacion y apoyo que necesitas.

---
**Source URL**:
[https://8000-4geeksacademy-websitev2-vnm80h5ve04.ws-us71.gitpod.io/es/coding-bootcamps/curso-datascience-machine-learning/?lang=es](https://8000-4geeksacademy-websitev2-vnm80h5ve04.ws-us71.gitpod.io/es/coding-bootcamps/curso-datascience-machine-learning/?lang=es)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1444x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ali5uarez5** [comment]
Colocar explicacion breve sobre que es Geekpal y Geekforce

**Comment by alesanchezr** [comment]
Esperando logos de yerden.

**Comment by alesanchezr** [comment]
@ali5uarez5 y esto que paso?

**Comment by alesanchezr** [comment]
no se entiende, tiene que mostrar que la combinacion de ambos servicios es la formula perfecta
