### ISSUE TITLE
Modify landing pages of technologies

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#3492]
https://www.figma.com/file/dIrKd954bGA0eNROoYeTWh/Technologies-Landing-Page?node-id=0%3A1

En este figma hay una descripcion de mas o menos lo que se quiere diseñar, en los comentarios se describe un poco mas cada cosa

**Comment by alesanchezr** [comment]
- [ ] Mejorar tema de los logos.
- [ ] El roadmap de móvil que no sea el mismo de desktop.

**Comment by tommygonzaleza** [comment]
Ali! Aqui te dejo un ejemplo de roadmap de python:
![image](https://user-images.githubusercontent.com/56565994/200339738-14420a30-17b8-4e18-a2f1-e952ee727732.png)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5068%3A15545

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/201178261-c851105b-25df-4dfc-b8b8-09d2f51510c3.png)

**Comment by tommygonzaleza** [comment]
The url for this page should be `/technology/python`

**Comment by tommygonzaleza** [comment]
- [ ] Waiting for technologies icons
- [ ] Waiting for roadmap from technologies

**Comment by alesanchezr** [comment]
Descartado
