### ISSUE TITLE
Actualizar los premios de 4Geeks Academy en https://dev.4geeksacademy.com/es/premios

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/breatheco-de#3674]
Se deben actualizar los Premios Excelencia Educativa en 
https://dev.4geeksacademy.com/es/premios

Estos son todos los premios que ha ganado españa
Premios Excelencia Educativa al Mejor programa de inserción profesional (2021)
Premios Excelencia Educativa a la Mejor innovación (2021)   
Premios Excelencia Educativa al Mejor trayectoria internacional (2021 y 2022)
Premios Excelencia Educativa al Mejor bootcamp presencial (2022)
Premios Excelencia Educativa al Mejor plan de becas internacional (2022)
Premios Excelencia Educativa al Mejor programa educativo (2022)
Premios Excelencia Educativa Especial al mejor Coding Bootcamp
(2021 y 2022)

**Comment by G-code7** [comment]
- [ ] Estos son todos los premios que ha ganado españa
- [ ] Premios Excelencia Educativa al Mejor programa de inserción profesional (2021)
- [ ] Premios Excelencia Educativa a la Mejor innovación (2021)
- [ ] Premios Excelencia Educativa al Mejor trayectoria internacional (2021 y 2022)
- [ ] Premios Excelencia Educativa al Mejor bootcamp presencial (2022)
- [ ] Premios Excelencia Educativa al Mejor plan de becas internacional (2022)
- [ ] Premios Excelencia Educativa al Mejor programa educativo (2022)
- [ ] Premios Excelencia Educativa Especial al mejor Coding Bootcamp (2021 y 2022)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2069
