### ISSUE TITLE
Add students massively using a csv

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#3782]
We should be able to upload a CSV with all the students that we would like to add, the CSV should contain the following information from each user:

- Name
- Lastname
- Email
- Phone number (Only numbers)
- Address
- cohort slug

Expected time: 8 - 10

**Comment by pbullor** [comment]
@tommygonzaleza cerrar éste ticket, lo puedo hacer directo con zapier, no lo necesitamos.
