### ISSUE TITLE
Add deep anchor links to markdown reader

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#3816]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36100-799d09b20444e6a75de4e0832400be12) 

 There are libraries like [anchorjs](https://www.bryanbraun.com/anchorjs) that enable the use of dynamic anchors on all headings and paragraphs.

We need the same behaviour in our markdown reader because its important to be able to send students to a particular paragraph or section of the reading.

The easies way is to show an icon on the left side of the content being hovered, when that icon its clicked it copies a link to the lessons but incuding the hash stirng at the end that points to the content. For example: The following URL contains a hash string `#wait-what-is-a-selector`, the browser will automatically scroll down to that element id when it renderst he page.

- [ ] Add anchors to headings.
- [ ] Add anchors to code examples.
- [ ] Add anchors to paragraps
- [ ] It should work on public lessons or private ones.

https://4geeks.com/lesson/what-is-css-learn-css#wait-what-is-a-selector

---
**Source URL**:
[https://4geeks.com/lesson/what-is-css-learn-css#wait-what-is-a-selector](https://4geeks.com/lesson/what-is-css-learn-css#wait-what-is-a-selector)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x709</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
No se ve bien con este tipo de comentarios
![Screenshot 2024-01-09 at 12 14 00 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/91c45131-a859-4ab3-9739-fbec385875aa)

**Comment by ArielCalisaya** [comment]
La imagen debería tener un alt para que funcione
