### ISSUE TITLE
Bulk upload leads into the admin

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4034]
Using [this backend services](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2576) (`PUT /v1/marketing/academy/upload`) lets implement the front-end functionality for bulk upload.

- [ ] When the "add new lead" button is pressed it should show [two options for single lead or bulk](https://tinyurl.com/2kuhlbh2), similar to [how it works](https://recordit.co/PKSVYm414U) on the [media gallery pipeline](https://admin.4geeks.com/media/article_issues).
- [ ] If you click in bulk it takes you to a "bulk upload manager" page where can drag & drop your CSV file and choose what are you uploading in a dropdown, [here is a sample design on how the UI should look](https://tinyurl.com/2gmo5uun).
- [ ] The dropdown will only show one option for now: "Form Entries"
- [ ] When the "start upload" button is pressed, it will start uploading and refresh the list of recent uploads, it show should now how the new upload is started but still pending.
- [ ] This are the columns in the table below: File name, status (when you hover it shows status message), created at, button to download the original csv
- [ ] The colors for the status: PENDING (yellow), ERROR (red), DONE (green)
- [ ] Modify the list of [MIME_ALLOW](https://github.com/breatheco-de/apiv2/blob/42800a9508d0d52050e2f15cc02d01779a382301/breathecode/media/views.py#L24) to allow csv files. The name of the csv files is `text/csv`

You can get the uploads like this: `GET /v1/monitoring/upload`

Expected time: 10 - 14

**Comment by aayalapalacin** [comment]
https://8000-aayalapalacin-apiv2-dudt9xqg0mm.ws-us84.gitpod.io/v1/monitoring/upload

**Comment by aayalapalacin** [comment]
@tommygonzaleza Here is the PR: [https://github.com/breatheco-de/admin/pull/358](url)

**Comment by aayalapalacin** [comment]
- export download file in utils folder
- research icon in editabletextfield.js
- create button for extra column in bulktags.jsx

**Comment by tommygonzaleza** [comment]
- [ ] Change the service `/marketing/academy/upload` from  monitoring to marketing
- [ ] In the dropdown where you select the upload type, upload type option should be disabled and the default option should be form entry

**Comment by aayalapalacin** [comment]
@tommygonzaleza new PR: https://github.com/aayalapalacin/admin/pull/5/files

> * [ ]  Change the service `/marketing/academy/upload` from  monitoring to marketing
> * [ ]  In the dropdown where you select the upload type, upload type option should be disabled and the default option should be form entry
> * [ ]  You shouldn't refresh the page when uploading the files
> * [ ]  You should GET the uploads when you upload new files
> * [ ]  Add a validation similar to the one used in the service `/v1/media/upload` to validate that the user only uploads CSV files and not other type of files. You can check the behavior on the media gallery, trying to upload files that are not images or PDFs, it's going to show an error. (Backend and Frontend)
> * [ ]  Sort the uploads from lates to oldest

**Comment by tommygonzaleza** [comment]
Check the PR review, I left some comments there

**Comment by aayalapalacin** [comment]
@tommygonzaleza PR review ready: https://github.com/breatheco-de/admin/pull/358

**Comment by tommygonzaleza** [comment]
<hrs>14</hrs>

**Comment by aayalapalacin** [comment]
<hrs>14</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>14</hrs>
