### ISSUE TITLE
`<Quote>` component for the markdown reader

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4048]
This is how the quote will look like inside the article:

<img width="872" alt="Screen Shot 2023-01-20 at 10 39 49 AM" src="https://user-images.githubusercontent.com/426452/213741258-c1b2306d-0313-4a35-a046-5a5b18e38b1e.png">

Here is a [link to the figma design](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6268%3A22834&t=JbBhDifT04fUbnH7-0).

## Example usage inside the markdown:

```
<quote>Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it -- Brian Kernighan</quote>.
```

Note: you have to look for the ` -- ` to find the quote author.

Expected time: 2 - 4

**Comment by aayalapalacin** [comment]
@alesanchezr Am I inserting the above quote from Brian Kerningham into this page?[ https://4geeks.com/lesson/agile-development](url)?
If so, where?

the figma design just has the quote displayed various times on the page 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/95265085/214994080-613415b3-d75f-45e8-ad19-a186ec307e3a.png">

**Comment by tommygonzaleza** [comment]
Hey! No, you are only going to create the component, we'll start using it later in the articles

**Comment by aayalapalacin** [comment]
PR: https://github.com/breatheco-de/app/pull/987

**Comment by tommygonzaleza** [comment]
I added a review in the PR

**Comment by aayalapalacin** [comment]
@tommygonzaleza comments addressed, ready for review: https://github.com/breatheco-de/app/pull/987

**Comment by tommygonzaleza** [comment]
- [ ] It must take 100% of the width like the other components
![Screenshot 2023-07-25 at 2 48 17 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/a254adeb-
355a-4f96-b0e1-3a62c2b85d62)

**Comment by aayalapalacin** [comment]
@tommygonzaleza ready for review, width adjusted

**Comment by aayalapalacin** [comment]
<hrs>4</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>4</hrs>
