### ISSUE TITLE
Showcase markdown components in storybook

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4069]
Here is a [list of all the MDX Components](https://github.com/breatheco-de/app/blob/main/src/common/components/MarkDownParser/MDComponents/index.jsx) we have developed for the markdown content.

We need to create examples on these cases:

1. `<before-after />`
2. [Check Box](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3077)
3. [`<only-for />`](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3182)

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36631-cc73ab4f925f09cd26d6ecf72501b08c) 

---
**Source URL**:
[https://breatheco-de.github.io/app/?path=/story/components-markdownparser--default&globals=locale:en;locales.en:English;locales.es:Spanish](https://breatheco-de.github.io/app/?path=/story/components-markdownparser--default&globals=locale:en;locales.en:English;locales.es:Spanish)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1450x703</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table> 

Expected time: 4 - 8

**Comment by aayalapalacin** [comment]
@alesanchezr what is the repo for this?

**Comment by tommygonzaleza** [comment]
Hey! This is on the app repo: https://github.com/breatheco-de/app

**Comment by aayalapalacin** [comment]
PR: https://github.com/breatheco-de/app/pull/1053

**Comment by tommygonzaleza** [comment]
These are the roles that you can use in the only for:
<img width="1111" alt="Screenshot 2023-09-05 at 3 45 56 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/13b0b93a-1989-47e3-a863-5abf80bd8f9a">

These are the permissions:
https://github.com/breatheco-de/apiv2/blob/main/breathecode/authenticate/management/commands/set_permissions.py

**Comment by aayalapalacin** [comment]
PR: https://github.com/aayalapalacin/app/pull/1
@tommygonzaleza

**Comment by aayalapalacin** [comment]
PR: [https://github.com/breatheco-de/app/pull/1164](url)
@tommygonzaleza

**Comment by tommygonzaleza** [comment]
<hrs>8</hrs>
