### ISSUE TITLE
Author pages

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4116]
In both pages 4GeeksAcademy.com como en 4Geeks.com we need to generte one page to showcase the content authors.

## Authors at 4GeeksAcademy.com
We are including a small section at the end of each blog post article to talk about the author.
We are also creating a new page for each author the url will be `/us/author` and `/es/author` (both languages)

### Properties to show on each article and also on the author page
- Full Name
- 50 to 100 characters Bio
- The bio will always start with `<full name> is `, for example: `Jon Doe is a guru of software development...`
- Picture
- The following links are optional but the must show up if they exist: Link to website, twitter and linkedin.

Note: Information will be shown in the language of the article.

### Additional properties to show only on the author page.
- Long background article.
- List of articles the author has written.

## Author page in 4Geeks.com => The Profile
4Geeks.com is already a social website were people have profile information and bio, we will use that information to display it publicly in a profile page with the URL: `4geeks.com/u/<user_hash>`

We should also include the same small author box on the lessons, exercises, etc. 
In this case we want to implement "co-authors" so the box may show other people as well.

### Other implementation notes to developers:

- [ ] All author links to website and socialmedia must have ` rel=”noopener noreferrer nofollow”`
- [ ] We have to add the `<META name="Author" content="Author Information">` tag to the blog posts.
- [ ] We need to add a link to the opengraph information to each article including the author, w'll address that in this other issue #4114.
- [ ] On the 4GeeksAcademy website, we now need an `./src/data/author/<username>.<lang>.yml` with the author information (one for each language).
- [ ] On the 4Geeks.com website the information will come from the API.

**Comment by ali5uarez5** [comment]
Blog - profile: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6758%3A7324&t=vXj0vNU1PKBMnz1g-1

**Comment by ali5uarez5** [comment]
Blog - article: (le coloqué abajo del card del perfil el componente de related articles que habiamos diseñado antes) https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6785%3A7078&t=vXj0vNU1PKBMnz1g-1

**Comment by ali5uarez5** [comment]
Blog- profile 4Geeks
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6425%3A23282&t=t75lLTdkZvVBu3iv-1

Blog - Article 4Geeks
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6425%3A23282&t=t75lLTdkZvVBu3iv-1

**Comment by tommygonzaleza** [comment]
No se va a desarrollar
