### ISSUE TITLE
Video not according to the screen layout

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4151]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/36432243?key=234360940ff22385f0bfcd83d0b856d0&size=orig) 

 Not responsive to screen format
Also happens in LPs

---
**Source URL**:
[https://4geeksacademy.com/es/geekpal/?lang=es](https://4geeksacademy.com/es/geekpal/?lang=es)

**Comment by tommygonzaleza** [comment]
Ya el error fue resuelto
