### ISSUE TITLE
Mejoras a workshops

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4426]
- [x] Generar landing para cada workshop, con 4 versiones

- Usuario anonimo, se le pide registrarse en 4Geeks.
- Usuario logeado que no se ha registrado en el workshop, boton de join workshop (tabla event checking).
- Usuario logeado que ya `se registro en el workshop` y le sale cuenta regresiva.
- Usuario logeado cuando el workshop ya empezo y le sale para entrar el boton.

Nota: si te registrar por eventbrite, te auto registramos internamente nosotros.

- [x] Armar una estratégia de email marketing para workshops y documentarla. Hace el research.
- [ ] Armar un articulo sobre comó utilizar bluejeans para hacer workshops, esa guía sera la base de los entrenamientos para los mentores.
- [ ] #5243
- [x] Utilizar codespaces en el workshop (discutirlo con el mentor).

**Comment by tommygonzaleza** [comment]
Workshops Landing pages: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7031%3A32971&t=Ap41XZXKQrUrKZ1V-1
