### ISSUE TITLE
Foto no se ve bien en mobile

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4652]
En el home de 4geeksacademy.com la inagen se ve bien en destop pero no mobile
![image](https://user-images.githubusercontent.com/426452/225632843-1647642f-7bde-4e06-a4c8-439f7f6c0001.jpeg)

**Comment by tommygonzaleza** [comment]
Se ve bien en el inspector pero si lo abres con un Iphone no muestra bien la imagen, averigua por que pasa

**Comment by tommygonzaleza** [comment]
Funcionando bien, esperando a que se acepte el PR
