### ISSUE TITLE
Los correos para evaluar las mentorías no les llegan a los estudiantes

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#4659]
### Bug description

Después de una hora de haber terminado una mentoría he consultado a la estudiante y me ha dicho que no tiene ningún correo para evaluar la mentoría (revisó su bandeja de entrada y también la de no deseados)

### Steps to reproduce

Un perfil de estudiantes, reservar una mentoría, tenerla con un profesor, y al terminar no llegará el correo.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1410
