### ISSUE TITLE
Botón dice Aplicar y en Chile se dice Postular

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/breatheco-de#4674]
### Bug description

En Chile se dice Postular, todos los botones que digan aplicar deben decir Postular si la persona accede desde Chile porque no se entiende la palabra Aplicar. 

![image](https://user-images.githubusercontent.com/48845580/226034727-65f3c1a8-15b6-46f5-b883-df620588b8c3.png)

### Steps to reproduce

Ir a https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack?lang=es 

Bajar a Próximas Fechas y ahí aparecen los botones.

### Expected behavior

Los botones deben decir Postular en vez de Aplicar

**Comment by alesanchezr** [comment]
Esto no lo habiamos arreglado permitiendole a cada location definir el nombre del boton en su location yml? @gustavomm19 @jatv93

**Comment by tommygonzaleza** [comment]
Estoy en santiago de chile y se sigue mostrando APLICAR aunque en el YML diga POSTULATE
![Screenshot 2023-06-06 at 2 34 23 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/a1ba2f44-cad6-4c3e-802a-c4e7de46475e)

**Comment by tommygonzaleza** [comment]
Si entras por campus, muestra aplicar en vez de postulate

![Screenshot 2023-06-06 at 4 25 12 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/ac22261a-119e-459a-bbc4-a60a73257034)

**Comment by tommygonzaleza** [comment]
Cuando se cambie el idioma en la pagina, debe cambiarse en la sesion tanto el language como el location

**Comment by tommygonzaleza** [comment]
Puse un VPN en Chile y entre por el campus de chile pero sigue mostrando aplicar en vez de postular
