### ISSUE TITLE
Low quality and a lot of typos in image of HTML tags

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#4751]
in the lesson https://github.com/breatheco-de/content/blob/master/src/content/lesson/what-is-html-learn-html.md

the image inside this lesson is hard to read even when zoomed in and has a lot of typos:
https://github.com/breatheco-de/content/blob/master/src/assets/assets/assets/Cheat-Sheet-HTML.jpg?=true

**Comment by tommygonzaleza** [comment]
@Lorenagubaira crea la imagen de nuevo con los typos corregidos y mejora la calidad de la imagen
