### ISSUE TITLE
Missing example in a lesson

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#4755]
there seems to be a missing example in lesson what-is-css-learn-css:

https://github.com/breatheco-de/content/blob/master/src/content/lesson/what-is-css-learn-css.md
https://github.com/breatheco-de/content/blob/master/src/content/lesson/what-is-css-learn-css.es.md

![missing example](https://user-images.githubusercontent.com/109150320/228646551-6fc266c3-15ec-4e33-93f0-f7a1eebcd12d.png)

**Comment by Khrisefzm** [comment]
This stale was already solved.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/7c76b98d-93d3-497c-965a-f3d2800b08ae)
