### ISSUE TITLE
Affiliate marketing growth proposal for 4Geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4780]
We have an affiliate marketing program in place:

1. We are about to release [this landing page explaining it](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4439).
2. Here is an [internal link explaning it for the staff](https://www.notion.so/4geeksacademy/Affiliate-Program-ed35b6a29ed441d797cf66e30c5dbc32).

# What is needed?

A proposal to start growing it aggresively:
- Do we need to put adds?
- Can we growing organically by possitioning ourselves on some keywords?
- Can we list ourselves in the current affiliate marketing sites.
- Are there any affiliate marketing listings or referal sites?
- What is the best way to grow it?

**Comment by URubino4Geeks** [comment]
We spoke with sales reps of ShareASale and Clickbank and how their platform operates its affiliates is not compatible with the business model of 4GeeksAcademy. 

We will adapt this strategy for 4Geeks instead.
