### ISSUE TITLE
Bug - Website - Upcoming Cohorts Dates

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/breatheco-de#4844]
### Bug description

The upcoming dates in English and Spanish show invalid dates

![image](https://user-images.githubusercontent.com/48845580/230196408-d557f7c4-4b02-4d28-bd93-7b4c8041601c.png)

![image](https://user-images.githubusercontent.com/48845580/230196435-7684b3e5-39df-406a-a2e3-754e4e0028bf.png)

### Steps to reproduce

Go to: https://4geeksacademy.com/es/proximas-fechas/?lang=es or to https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-santiago

In every section that has upcoming dates is this error 

Apply to every campus 

### Expected behavior

Show the dates uploaded in the Admin

**Comment by Khrisefzm** [comment]
This issue was already solved.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/2a263347-4f76-4e48-ae79-1d521605c809)

![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/bf9fdf98-61d3-4696-bc62-8805484369d2)
