### ISSUE TITLE
Links are not marked in blue at the Blog

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/breatheco-de#4858]
### Bug description

In this Blog Post, some links are not marked in Blue as they should be: https://4geeksacademy.com/us/machine-learning-engineer/machine-learning-engineer

**
![image](https://user-images.githubusercontent.com/118853358/230411857-351ed489-a0b6-4aa7-8ba7-2b1beac8deaf.png)
**

### Steps to reproduce

1 - Open the blog post
2 - Go into the Machine Learning Outlook section
3 - Look for Keywords with the backlink (image)

### Expected behavior

The link should be different from the rest of the page (marked in Blue)(

**Comment by tommygonzaleza** [comment]
Waiting for the PR to be accepted
