### ISSUE TITLE
Bug in "answer" type of lesson

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#4870]
### Bug description

there is a bug in the "answer" type of lessons where if I click back after entering in these exercises it will then load all of the other quizes instead of just going back

### Steps to reproduce

https://www.loom.com/share/382afd35ad644bc8a6e940f8b3286271

### Expected behavior

it should go back to the previous url I was in, or maybe show a warning that if I go back I may lose my progress on the questions that I was in

**Comment by JParedesArtica** [comment]
El bug sigue existiendo.

![image](https://github.com/breatheco-de/breatheco-de/assets/126907318/1bfd6c29-8115-4cb2-abb2-8f5e56cb880e)
![image](https://github.com/breatheco-de/breatheco-de/assets/126907318/2be00216-add3-45f8-864d-3d10598ba7ae)
