### ISSUE TITLE
list of questions start at 0 in answer/quiz type of exercise

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#4890]
It should start at 1

![empieza en 0 en vez de 1](https://user-images.githubusercontent.com/109150320/231530151-4d0ef1f6-2a96-4fb9-b216-13defa664642.png)

**Comment by JParedesArtica** [comment]
El bug sigue existiendo 
![image](https://github.com/breatheco-de/breatheco-de/assets/126907318/11421e68-3888-4470-a5e3-a73dad74842e)
