### ISSUE TITLE
En seccion de courses debe decir "Course details"

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#4936]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/39033828?key=a582f39e64cca907c1d6425bc7c50916&size=orig) 

---
**Source URL**:
[https://4geeks.com/learn-to-code](https://4geeks.com/learn-to-code)

**Comment by Khrisefzm** [comment]
The navbar of 4geeks.com has no longer SOCIAL AND LIVE LEARNING, but in the course section you can see the courses and the boton that is still saying Start Coding and no Course Detail.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/464c8adc-1daf-44fe-9948-11f8400c660a)
