### ISSUE TITLE
proyectos que no se hacen en el curso

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#5021]
en https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer

![Captura de pantalla 2023-04-28 002455](https://user-images.githubusercontent.com/109150320/235004068-92e4ca3b-3c38-4ca4-81d8-cdb63be56073.png)

![Captura de pantalla 2023-04-28 002804](https://user-images.githubusercontent.com/109150320/235004532-38432d73-c48b-41e9-b2e5-24bba18a0bed.png)

en la pagina de fullstack se dice que se hacen proyectos como flappy bird, clon de coursera, etc y no es así

quitar esos textos y poner correctamente los que sean

**Comment by Khrisefzm** [comment]
Es cierto, en la página continúan apareciendo proyectos que en el curso no se ven
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/d080a2b0-3059-4a3e-a317-7af8ab832fe4)
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/3e0d460d-15ba-4bf5-beb6-837f1220bd69)

**Comment by tommygonzaleza** [comment]
@G-code7 revisa los proyectos que se hacen en el syllabus en esta etapa de react y actualiza el YML en el website

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2135
