### ISSUE TITLE
Usar la propiedad `course_translation.short_description` en `MktSideRecommendedCourses`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5043]
Quedamos a la espera de este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5042) para que se agregue en el serializador.

Una vez recibido, se debe mostrar esa descripcion corta en vez de la actual

**Comment by ArielCalisaya** [comment]
Este issue se puede dar por terminado puesto que existe una condición que aplica este cambio sin comprometerse con el backend
[ejemplo](https://github.com/breatheco-de/app/blob/main/src/common/components/MktSideRecommendedCourses.jsx#L126):
```jsx
{course?.course_translation?.short_description || course?.course_translation?.description}
```
