### ISSUE TITLE
Agregar landing page de press

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5078]
[Aqui](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6894%3A8975&t=ueblS9ycewksFWNc-1) esta el link del diseño del landing

**Comment by gustavomm19** [comment]
Issue repetido: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4461
