### ISSUE TITLE
Revisar articulos en ingles de santiago en el admin

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5114]
Casi todos los articulos que estan en ingles en la academia de Santiago, estan con el contenido en español, pasa uno a uno y traduce aquellos que tengan contenido en español

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/4GeeksAcademy/code-rest-api-with-node-and-jwt-authentication/pull/2
