### ISSUE TITLE
Reporte de ads

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5115]
### Una tabla con:
- Nombre de la campaña
- Origen de la campaña (si es Meta o si es Google)
- Leads totales por cada campaña
- País o Mercado

### Charts
- Torta de campañas con mas leads
- Torta: Campañas con mas won/lost

#### Filtros para la tabla
- Lost reason: Doesn't answer, No money, etc.

**Comment by mafecasvi** [comment]
- en el caso de los won,  yo lo que hago normalmente es que me bajo todos los won leads o deals, con todos sus campos
y hago una tabla dinámica, donde el campo es campaign ID y hago una cuenta de emails que tienen ese campaign ID, 
- en el caso de click en alguna campania, hago la consulta en el crm "has clicked on a link", "any email"
mi columna siempre es el campaign ID, y mis columnas son counts de correos para distintos casos: won, has clicked on a link, lost reason doesnt answer, hasnt opened any email, y lost reason no money
idealmente, para ver evolución, la cuenta de correos debe corresponder a períodos, como semanas o meses
porque si dejamos la info como una foto de un solo período no se puede ver evolución
