### ISSUE TITLE
Crear vista de checkout de workshops y mentorias

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5126]
Los workshops y mentorias se pueden comprar de forma individual una vez que se le acaban al usuario. Necesitamos una vista muy similar a la que actualmente existe para comprar cursos pero esta vez seria para comprar los workshops y/o mentorias. Se van a poder comprar en grupos de 5 unidades, ejemplo:

Puedes comprar 5 mentorias por 100$ (20$ c/u), 10 mentorias por 190$ (19$c/u), 20 mentorias por 360$ (18$ c/u).

Podemos mostrar esas opciones en esta vista para que el usuario escoga cuantas quiere de cada uno.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&t=3cuML7FOgLH7iEog-1

**Comment by alesanchezr** [comment]
No tenemos info para mostrar sobre descripcion del lo que compras, quitarsela en todos los apsos.
No utliziar colores chillones para fondos.
En el paso de confirmacion te muestro solo lo que ya seleccionaste sin las demas opciones, pero peudes carle a "cambiar" y regresar al paso anterior.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9059%3A43762&t=y9sRt6menoZ172HF-1

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-06-14 at 4 39 53 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/33c75de9-59e7-432e-a7a4-b0b72a744ce0)

Con esta informacion sabras cual es el slug del service del mentorship service set que el usuario desea comprar de nuevo. En la siguiente vista (La vista del diseño donde se muestran las opciones de compra), utilizaras el slug del service (Que obtuviste en la vista anterior) para obtener los academyservice (De donde sacaras las opciones de compra), con el siguiente servicio: `GET /payments/v1/academy/academyservice/<slug:service_slug>`.

Este servicio te retornara el objeto del academy service que se ve tal como en la imagen. Las opciones de compra dependen del `academy_service.bundle_size` y del `academy_service.max_items`. La cantidad de opciones sera `max_items / bundle_size`, obteniendo solo la parte entera. (Por ejemplo, si tenemos `bundle_size=7` y `max_items=20`, entonces la cantidad de opciones es `20/7=2.86`, por lo que la cantidad de opciones es 2). Siempre las opciones seran los multiplos del `bundle_size` hasta llegar al `max_items` (Pero nunca mayor que `max_items`).

Luego tambien importante para el precio, debes utilizar esta funcion (agregala al proyecto) para poder descubrir el precio de cada uno de las opciones de compra:

```js
function getDiscountedPrice(num_items, max_items, discount_ratio, bundle_size, price_per_unit){
        if (num_items > max_items):
            console.log('num_items cannot be greater than max_items');
        }

        let total_discount_ratio = 0;
        let current_discount_ratio = discount_ratio;
        let discount_nerf = 0.1;
        let max_discount = 0.2;

        for (let i = 0; i < Math.floor(num_items / bundle_size); i++){
            total_discount_ratio += current_discount_ratio;
            current_discount_ratio -= current_discount_ratio * discount_nerf;
        }

        if(total_discount_ratio > max_discount){
            total_discount_ratio = max_discount;
        }

        let amount = price_per_unit * num_items;
        let discount = amount * total_discount_ratio;

        return amount - discount;
}
```

Y con cada una de las opciones de compra, ya puedes permitir seleccionarla y comprarla, para comprarla debes utilizar el siguiente endpoint `POST /payments/v1/consumable/checkout`, en el body debes pasar:

```js
{
     "service": service_slug,
     "academy": academy_id,
     "total_items": total_items,
     "mentorship_service_set": mentorship_service_set_id,
     "event_type_set": event_type_set_id
}
```

> Se envia `mentorship_service_set` o `event_type_set` segun sea el caso.

**Comment by tommygonzaleza** [comment]
- [ ] Al darle click a Get more mentorships esta redireccionando a checkout sin el querystring del service que se va a comprar.
- [ ] Si la cohort en la que se esta mostrando el componente de mentorias es `available_as_saas=false`, entonces te traes todos los mentorships services de la academia de esta cohort y los muestras (Tal como pasa ahora)
- [ ] Si la cohrot en la que se esta mostrando el componente de mentorias es `available_as_saas=true`, entonces vas a buscar la subscripcion cuyo selected cohort sea la misma que la cohort en la que esta, y vas a mostrar los mentorship services del mentorship service set de esa subscripcion.
- [ ] Si no tiene consumibles, no muestra los +3 mentors available.

**Comment by tommygonzaleza** [comment]
- [ ] Cambia `You are getting for` por `You are getting`
- [ ] Cambia el flujo del componente en el caso de que no tenga consumibles para que permita escoger cual mentoria quiere ver y en ese momento que escoge, chequeas si tiene consumibles para este mentorship_service, de no tener, entonces muestras la parte del flujo que dice que no tiene mas mentorias. Al darle al boton de `Get more mentorships` debes chequear si ese mentorship service forma parte de uno o mas mentorship service set de los planes que adquirio. Si forma parte de mas de un mentorship service set (Deben ser mentorship service set diferentes), entonces lo redireccionas a la vista de checkout. Si solo forma parte de un mentorship service set, entonces lo redireccionas a la vista de checkout pasando el mentorship service set y junto al plan al que pertenece ese mentorship service set, a traves del query string: `4geeks.com/checkout?service_set=mentorship-service-set-slug&plans=slug-plan-1`. Si el mentorship service pertenece a mas de un mentorship service set (Por lo tanto a mas de un plan), entonces lo redireccionas a la vista de checkout pasando por query string los planes y mentorship_service_sets a los que pertenece este mentorship_service_set, asi: `4geeks.com/checkout?service_set=mentorship-service-set-slug-1,mentorship-service-set-slug-2&plans=slug-plan-1,slug-plan-2`, en una vista nueva previa a lo que se tiene, se le debe pedir al usuario que escoja a cual plan (De los que se pasaron a traves de querystrings) va a comprarle mas consumibles, luego sabiendo cual plan escogio, debes obtener el slug del mentorship service set del plan escogido, para utilizarlo en el request que te trae la informacion de los academy services (Ya no pasaras service), pasando a traves de querystring `?mentorship_service_set=mentorship_service_set_slug`, de no tener que escoger el plan (Por haber recibido solo uno), utilizas el mentorship_service_set que recibiste en la URL y ese es el que pasaras a traves de los querystrings del request al API.

**Comment by tommygonzaleza** [comment]
Luego de comprar, en el ultimo paso para agendar una mentoria me dice que no tengo consumibles aunque el servicio de consumibles retorno que si tengo

https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/9eb46db0-9388-44f1-b2c3-ce43279d5eab

**Comment by tommygonzaleza** [comment]
- [ ] Cambiar el querystring que recibe actualmente como `?service_set`, por `?metorship-service-set=<mentorship-service-set-slug>` (En el cas de un mentorship service set), y por `?event-type-set=<event-type-set-slug>` (En el caso de que compren workshops)

**Comment by tommygonzaleza** [comment]
Fui redireccionado desde el landing de workshops pero parece que todavia no esta funcionando esta parte de los query string. De todas maneras, te pedi el cambio en el otro issue, cerrare este
