### ISSUE TITLE
Revisar porque las estadisticas de website analytics no se estan reportando en active campaign

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5148]
tenemos un tema con active campaign y el [site tracking de la pagina web](https://help.activecampaign.com/hc/en-us/articles/221493708-How-to-set-up-Site-Tracking) que parece no estar registrando ningun evento, a pesar de que tag manager si esta incluyendo el script de active campaign para site trakcing. 

Tal vez peudas chatear con ellos a ver que pasa? o escribirles a soporte?

**Comment by URubino4Geeks** [comment]
Hablamos con el soporte de ActiveCampaign y no dan asistencia si tenemos instalado su tracking code por un tercero (En este caso, Google Tag Manager). 

Vamos a instalar el tracking de AC manualmente: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5159
