### ISSUE TITLE
Ad a padding to the component

### ISSUE THREAD

**Issue by Charlytoc** [breatheco-de/breatheco-de#5155]
![Image](https://user-images.githubusercontent.com/107764250/237511313-81583b92-a824-4a64-8803-f8139fc89087.png)

- Get list of delivered assets and look for the repositories
- Maintain the text component because the implementation will be slowly
- Add a featureFlag: Mandatory code reviews
- app.release.enable_mandatory_code_reviews
- If the feature flag is true, button are hidden, else not
- Only dissapear if codereviews < 3 and its true the flag
-  The fetch must be in the in the mount of the modal component
- The loading animation is a Rigobot face, look for it

**Comment by ArielCalisaya** [comment]
Este issue esta relacionado a 
[Modal de Code Reviews #5559](https://github.com/breatheco-de/breatheco-de/issues/5559)
