### ISSUE TITLE
Endpoint para obtener token de rigobot

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5184]
`GET /v1/auth/me/token?breathecode_token=<bc_token>`

- [ ] El metodo devuelve un token de rigobot, con su informacion de token como fecha de expiracion etc.
- [ ] Si no se encontro a nadie con ese BC Token entonces 404.

```json
{
     "key": "",
     "token_type": "",
     "expires_at": "",
     "created_at": ""
}
```

**Comment by Charlytoc** [comment]
- [ ] Format responses to satisfy HTTP status

**Comment by Charlytoc** [comment]
1. [ ] You must use exception for all cases
2. [ ] Solo hay dos maneras de responder, con una exception o con un serializer
3. [ ] Use the Breathecode.utils.validation_exception
4. [ ]
