### ISSUE TITLE
Endpoint to invite a 4Geeks user to join Rigobot

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5185]
`GET /v1/auth/signup?callback=<url>&referrer=4geeks`

## Si NO TIENE referrer=4geeks

- [ ] Colocar campos de email, password, confirmar.
- [ ] Colocar checkbox de [terminos y condiciones](https://4geeks.com/terms-and-conditions), si no se acepta no puede entrar.
- [ ] Agregar el usuario a la organization `default` si no los credenciales no existen en 4Geeks.

## Si tiene un referrer=4geeks

```
You have been invited to join 4Geeks Organization on Rigobot AI, by sign up you will be giving access to Rigobot to your 4Geeks account information to provide you with the following features:

- Get your code reviewed by expert mentors and receive details feedback.
- Get your code reviewed by Rigobot, an artificial intelligence developed by 4Geeks.
- Ask Rigobot for feedback when completing LearnPack exercises.

Please login with your [4Geeks.com](http://4geeks.com/) credentials to approve this use.
```

- [ ] Once you get their login information, look for the 4Geeks user thru the API and check if they have GitHub, if they do have 4Geeks user and Github connection then proceed to create the Rigbot user and add it to the 4geeks organization.
- [ ] If the 4geeks user does not have a GitHub connection, show an error saying: `You 4Geeks.com user is not connected to Github, please go back to 4Geeks.com and connect it to Github before joining Rigbot AI. You can close this window now.`
- [ ] Save the Github information on the `BreatheCodeCredential.github_username`.
- [ ] Ask to accept the terms and conditions.
- [ ] If everything goes smoothly and the Rigobot user is created and added to the 4Geeks Organization, you show this message: 

```
Congratulations!
You have successfully opt-in to Rigobot; we are preparing to start reviewing your code and send you fantastic feedback! You can close this tab now.
```
- [ ] If there is an unknown error:

```
Ooops. Something went wrong!

There was a problem connecting your [4Geeks.com](http://4geeks.com/) account to Rigobot, this error has been notified. Close this window and try again later.
```

**Comment by alesanchezr** [comment]
Cuando todo ocurra exitosamente no deberias mostrarle para elegir un purpose, sino para que cierre la ventana.

**Comment by Charlytoc** [comment]
I'm getting this errror:

![Image](https://github.com/breatheco-de/breatheco-de/assets/107764250/0e284cc8-598e-441c-805e-36cd1fb8b171)
