### ISSUE TITLE
GET /v1/finetuning/me/coderevision

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5254]
Devuelve todos los reviews hechos por me o que me han hecho a mi.

El [endpoint debe ser paginado](https://github.com/breatheco-de/apiv2/blob/e06d0097b16d7b96050bbdbf37e425ed17c35707/breathecode/certificate/views.py#L156).

Filtros del querystring:

- reviewer=`<user_id>`: solo obtener reviews de autoria de ese user, tambien peude ser "me".
- github_username: Permite obtener reviews hechos a uno o mas github usernames separados por comma.
- read=`<bool>`: si quiero solo los no leidos.
- rating=`<bool>`: true si quero los utiles, false si quiero los inutiles.
- repo=`<url>`: solo revisiones de este repo

# Serializador

Tener uno BIG para todo el coderevision con detalles.

Tener uno small con los detalles minimos:

```
code revision id
Reviewer id and first name and last name, if no first or last then "Someone".
Datetime when it was read.
Date time when it was rated.
Date when the review was posrted... created at?
```

**Comment by Charlytoc** [comment]
Check this view in details

**Comment by alesanchezr** [comment]
falta la paginacion
