### ISSUE TITLE
POST /v1/finetuning/me/repository

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5256]
Agrega un repo a un watcher.

- [ ] Validar que solo si eres commite tambien peudes agregar el repo.
- [ ] Validar que tengan profile todos los watcher, TODOS.
- [ ] Poner automatico a `me` como commiter.

Return

Devuelves el repo con bigserializer y sus commiters.

**Comment by Charlytoc** [comment]
- [ ] You must return the watchers without profile in order to know which are the conflictive watchers that need to create a Rigobot user

**Comment by Charlytoc** [comment]
- [ ] Don't include automatically "me" as watcher
