### ISSUE TITLE
Solo mostrar alumnos activos en el reporte de assignments

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5259]
Para hacer que el teporte cargue mas rapido solo incluir usuarios activos, el servidor debe solo responder los activos.

En los filtros del reporte se puede cambiar esta configuracion y se volvera a pedir al servidor todos los alumnos con los nuevos status que se hayan especificado.

[Slack Message](https://4geeksacademy.slack.com/archives/C03HCMRC41F/p1685023912705919?thread_ts=1685023912.705919&cid=C03HCMRC41F)

**Comment by gustavomm19** [comment]
La conversacion de slack referenciada ya no es accesible 
![image](https://github.com/breatheco-de/breatheco-de/assets/47191295/365ec938-2d42-4fe1-b670-a919e45cb064)
