### ISSUE TITLE
Refrescamiento del template de landings 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5262]
Refrecamiento del template de landings ubicado en la page de landings en figma.

Uno de los landings que usa este template es: https://4geeksacademy.com/us/landing/united-way

Esto es sólo para los landings de Google Ads

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=6835%3A7497&mode=design&t=twho4W8kbP035Vur-1
