### ISSUE TITLE
Better loading when generating completions

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5265]
Instead of displaying "rigo is thinking" on the chrome extension, lets open the completion window right from the beginning but since the completion its not ready you can display a "Rigo is thinking" and loading animation and refresh every 4 seconds.

```
Rigo is thinking
Give us a few seconds to generate this text for you, you can try reloading in a bit.
```

**Comment by Charlytoc** [comment]
- [ ] Also, the rich text editor must be hidden while Rigo is thinking

**Comment by Charlytoc** [comment]
- [ ] Add the Rigo animation while loading
