### ISSUE TITLE
Agregar lnk para ver completion job

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5266]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/40179797?key=5416f5fb7b4eeee8474a417d17f98972&size=orig) 

---
**Source URL**:
[https://rigobot.herokuapp.com/admin/prompting/completionjob/](https://rigobot.herokuapp.com/admin/prompting/completionjob/)

**Comment by alesanchezr** [comment]
Agregale el token para que no me mande a login:
https://www.awesomescreenshot.com/image/40943454?key=ceef1bef36b30add1dd831c615d92a8e

**Comment by Charlytoc** [comment]
Getting an error: 



![Image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/107764250/1db28505-5ea9-4141-9b73-35c69f1b3e88)

**Comment by alesanchezr** [comment]
buscar la manera de resolver esto usando sessions: https://docs.djangoproject.com/en/4.2/topics/http/sessions/
