### ISSUE TITLE
Cambios en el diseño del Dashboard

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5316]
En este [figma](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&t=y9sRt6menoZ172HF-1) puedes encontrar los cambios en el diseño, principalmente se cambió el diseño de los componentes de la derecha (Widgets)

Por ahora lo haremos sin el componente de Feedback.

**Comment by tommygonzaleza** [comment]
Puedes ver el flujo completo de cada componente dandole click derecho y luego `Go to main component`
![Screenshot 2023-11-27 at 4 14 50 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/1e29069e-deac-4f4a-8f7b-1ac1cc72b9d1)

**Comment by tommygonzaleza** [comment]
No se esta mostrando el componente de mentorias desde el dashboard

**Comment by ArielCalisaya** [comment]
Corregido!

**Comment by tommygonzaleza** [comment]
No esta mostrando el componente de mentorias en el dashboard
![Screenshot 2023-12-04 at 1 27 12 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/a3442041-8b6b-40af-9542-1f8a3cf74319)

**Comment by tommygonzaleza** [comment]
- [ ] Son de diferente tamaño peero no deberia, deben ser iguales
<img width="706" alt="Screenshot 2023-12-19 at 10 35 46 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/94cddb13-4f68-48d8-930f-f9827b51e113">

**Comment by tommygonzaleza** [comment]
Me aparece que no tengo consumibles incluso en los servicios que no son saas
https://github.com/breatheco-de/breatheco-de/assets/56565994/6e002be0-2d22-4754-afce-9dbeca2f47e4

**Comment by tommygonzaleza** [comment]
- [ ] Obten los mentorship services de las academys de los roles que sean `student`. (Lo obtienes en el metodo `me`)
- [ ] En el dashboard de la cohort toma solo el academy de la cohort, tal como funciona ahora mismo.
