### ISSUE TITLE
Crear componente `Feedback` y agregar a StoryBook

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5317]
[Este](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&t=lCBevHci90Bhfv2x-1) es el diseño del componente. Todavia no estan listos los servicios a consumir para poder mostrarlo por lo que queda en espera por el backend

**Comment by tommygonzaleza** [comment]
Ve creando el componente y agregandolo a storybook, luego le agregamos los servicios que consumira. Si tienes dudas de posibles escenarios del componente dejame saberlo

**Comment by tommygonzaleza** [comment]
[Aqui](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&mode=design&t=ikvzxmCtASyZkDAG-1) esta como se ve en el dashboard y de donde debes obtener cada cosa. Revisa las variaciones del componente en figma, ahi se muestra como se ve cuando no tiene ningun code review

**Comment by alesanchezr** [comment]
- El base64 decode tiene que tener utf-8 para evitar simbolos raros.
- Intentar que la altura del componente de codigo llegue hasta abajo aunque hallan pocas lineas de codigo.
- Si le doy skip cuando estoy haciendo rate del code review (cuando le doy a la manito) me dice que se envio el feedback pero no pasa nada en la pestaña network del inspector.
- Dale acceso al json para la traduccion `code-reviewcomment-was-sent-successfully`
