### ISSUE TITLE
Issue related to uncompleted Learnpack website migration issue

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5328]
You didn't finished the issue as the website still have some bugs. There are some images missing in the website, please add them as soon as possible.

The images missing are:

- (About Us) The problem/The solution section
![Screenshot 2023-06-02 at 4 10 31 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/52046764-9296-4524-89ec-60e5de308703)
- (About us) Change the icon to Learnpack's instead of 4Geeks'
![Screenshot 2023-06-02 at 4 11 10 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/898536f1-2f19-4fb7-a07e-90667521cdd2)
- (About us) Alejandro's and Tomas' picture
![Screenshot 2023-06-02 at 4 11 38 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/caf89a43-5959-405e-a323-ef34bba07ee4)
- (Home) A GIF of how to open LearnPack.
![Screenshot 2023-06-02 at 4 12 04 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/80074dc4-df3b-454b-b525-5b99e1d54e70)

**Comment by aayalapalacin** [comment]
@tommygonzaleza still waiting on GIF

**Comment by tommygonzaleza** [comment]
I sent you the image for the about us section through slack

**Comment by aayalapalacin** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
