### ISSUE TITLE
Que pasa si un usuario ya esta en el waiting list

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5337]
Segun [esta lineas de codigo](https://github.com/breatheco-de/apiv2/blob/bd733078e9fbd0d569290705bea32eaac6fc33dc/breathecode/authenticate/serializers.py#L1078) un usuario que ya esta en el waiting list no puede volver a estarlo, esto tiene sentido, sin embargo veamos que pasa en este caso:

1. El usuario intenta hacer signup via [signup](https://4geeks.com/login) y se le crea su waiting list.
2. Luego se entera del curso de javascript (que no tiene waiting list = true, y es avaiable_as_saas=true) y decide registrarse.

Podrá registrarse? O le va a decir que ya esta en el waiting list?

Si vuelve a subscribirse pero con un curso cuyo `waiting_list=False` y `available_as_saas=true` se deberia autoaceptar el invite (auto aceptar el invite).

Importante

Los demas invites que esten PENDING deben permanecer igual.

**Comment by jefer94** [comment]
Pues, si compro primero un plan disponible, y despues intento comprar uno en waiting list, el flujo de compra se esta aceptando, pero el endpoint de backend evita poder proceder con el pago, deberia verificarse si tiene waiting list el plan y restringirse en ese caso, pero agregarlo al waiting list, en este caso, al estar disponible, recibira una notificacion por websocket, un objeto persistible con descripcion y link, en el caso inverso, esta rechazando la solicitud de unirse a el waiting list, le falta una edicion el query

Esto no esta funcionando aun
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/3018142/52ba4b87-ce06-44c0-a532-3d755a638954)

Esto tampoco
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/3018142/0a4530f9-b0bd-4110-b484-9132deb1654d)

![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/3018142/2273e8aa-5545-432e-b9bb-b3a490faba6a)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/977

**Comment by jefer94** [comment]
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/3018142/c4283589-5f98-41af-bceb-a3c99a77b15f)

**Comment by jefer94** [comment]
Agregar status cancelled si se implementa notificaciones para el caso en el que el plan o el curso este listo, y el usuario decide ignorar la notificacion

**Comment by tommygonzaleza** [comment]
> Pues, si compro primero un plan disponible, y despues intento comprar uno en waiting list, el flujo de compra se esta aceptando, pero el endpoint de backend evita poder proceder con el pago, deberia verificarse si tiene waiting list el plan y restringirse en ese caso, pero agregarlo al waiting list, en este caso, al estar disponible, recibira una notificacion por websocket, un objeto persistible con descripcion y link, en el caso inverso, esta rechazando la solicitud de unirse a el waiting list, le falta una edicion el query
> 
> Esto no esta funcionando aun ![image](https://user-images.githubusercontent.com/3018142/252616030-52ba4b87-ce06-44c0-a532-3d755a638954.png)
> 
> Esto tampoco ![image](https://user-images.githubusercontent.com/3018142/252616217-0a4530f9-b0bd-4110-b484-9132deb1654d.png)
> 
> ![image](https://user-images.githubusercontent.com/3018142/252616445-2273e8aa-5545-432e-b9bb-b3a490faba6a.png)

@ArielCalisaya revisa este bug por favor

**Comment by tommygonzaleza** [comment]
Estos bugs se le reportaron a Ariel en otro issue.
