### ISSUE TITLE
Usar el nombre de la cohort en el componente del LiveClass.

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5341]
Cuando en el componente de LiveEvents haya un live class, usar el nombre de la cohort en vez de `Upcoming Live Class`
![Screenshot 2023-06-05 at 3 53 05 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/f62c90dd-033a-4e94-b3a6-9a68a0025b48)
Tiempo esperado: 0.25 hrs - 0.5 hrs

**Comment by JennGuz** [comment]
Done in this PR

https://github.com/breatheco-de/app/pull/1595

**Comment by MadamSagas** [comment]
when using this cohort: latam-pt-cr-forte-1
the live class component does not show the name of the cohort 
**Here is a screen shoot:**
![Image](https://github.com/user-attachments/assets/0f476ec4-b53b-4a76-8915-b897aef25ba5)

**Comment by JennGuz** [comment]
done in this PR
https://github.com/breatheco-de/app/pull/1618

**Comment by tommygonzaleza** [comment]
This is not working as a person may have more than one cohort and the live event can be about any of those. You should get the cohort from the live event.

**Comment by JennGuz** [comment]
done in this PR: https://github.com/breatheco-de/app/pull/1651
