### ISSUE TITLE
Reporte de actividad de un alumno en una cohort

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5346]
Porcentaje de completación:

- Nombre completo.
- Cuantas lessons lleva del total, si en el syllabus eran 350 cuantas ha completado.
- Cuantos proyectos, si en el syllabus eran 150 cuantas ha completado.
- Porcentaje de inasistencias/asistencias.
- Progreso de LearnPack (porcentaje de completacion de cada uno los ejercicios).
- Timeline de actividades: [estas son las posibles actividades](https://www.awesomescreenshot.com/image/40588793?key=24c10586a0858ae517f548aaac92e0c8).

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9492%3A44403&t=JLbfyhr8x14RqvSH-1

**Comment by tommygonzaleza** [comment]
- [ ] Poner activities y los entregables uno al lado del otro.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9499%3A45994&t=o5iHNGpjOTQp9Uv4-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar iconos a las actividades. Cada actividad debe tener un icono propio que la describa. Estas son las actividades que se van a registrar por ahora:
![Screenshot 2023-06-21 at 11 57 51 AM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/3e744968-cde5-46d2-9f2e-68c64560193d)

**Comment by alesanchezr** [comment]
Sobre los colores de los punticos

- [ ] El lesson tiene 4 colores: gris (cuando el alumno no ha abierto el modulo y la lesson ni le aparece), rojo (cuando ya la lesson le aparece pero nisiquiera la ha abierto), amarillo (cuando la abrio pero no la marco como completada), verde (abierta y completada).
- [ ] El proyecto tiene 5 colores: blanco con borde gris (cuando el alumno no ha abierto el modulo y el proyecto ni le aparece), gris solido (cuando abrió el modulo pero no ha abierto el proyecto), rojo (cuando lo entrego pero fue rechazado), amarillo (cuando lo entrego pero no se ha aprobado), verde (cuando fue aprobado por el mentor).
- [ ] La asistencia tiene 4 colores: gris (No se paso asistencia), rojo (no asistió), amarillo (no hay informacion del alumno para este dia), verde (si asistió)
- [ ] Learnpack tiene 4 colores: blanco con borde gris (cuando el alumno no ha abierto el modulo y la practica ni le aparece), gris solido (cuando abrió el modulo pero no ha abierto los ejercicios), rojo (lo abrio pero el porcentaje de completación es < 30%), amarillo (lo abrio pero el porcentaje de completación es > 30% pero < 80%), verde (completación en 100%).

Si haces hover en los punticos:
- [ ] El lesson: muestra status, fecha y titulo del lesson.
- [ ] El projecto: status, fecha y titulo del lesson.
- [ ] Asistencia: status, el numero de dia en la cohort y la fecha.
- [ ] Learnpack: el titulo del ejercicio y cuantos han sido completados del total (Ejemplo: 12/20)

Si haces click en los punticos:

- [ ] El lesson no se puede hacer click.
- [ ] El proyecto: Muestra la modal de detalles de un proyecto [que tambien se usa en la visa de assingments](https://www.awesomescreenshot.com/image/40940818?key=8f339d5fdae528a9d5aa54a3954e3aa0) pero sin ningun call to action, es solo lectura y solo se puede cerrar con la x.
- [ ] La asistencia: No se le puede hacer click.
- [ ] Learnpack: AL darle click muestra la lista de ejercicios completados y no completados.

![reporte de alumno](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/7831ed3f-3eb0-456a-9cbc-e402201d553d)

**Comment by tommygonzaleza** [comment]
- [ ] Agregar los cambios con mucho detalle de lo que se pide en el comentario anterior de Alejandro. Se debe detallar en lo que pasa cuando se hace hover en los puntos.
- [ ] Se debe detallar los casos del student rating, para ver en que casos se muestra cual cara segun el porcentaje de rating

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9499%3A45994&mode=design&t=3fBC3AkUp47bNvtw-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar modal para caso de los proyectos en los que no ha abierto el modulo y para en los que no ha leido el proyecto
- [ ] Agregar status de que el assignment esta pendiente por ser revisado en la modal que ya existe para este status

**Comment by tommygonzaleza** [comment]
Agregar status de que el assignment esta pendiente por ser revisado por el profesor en la modal que ya existe para este status

**Comment by tommygonzaleza** [comment]
## Servicios a utilizar:
- Para obtener el attendance del usuario: `/v1/admissions/academy/cohort/<cohort_slug>/log?academy=<academy_id>`
- Para obtener los assignments (Lesson, Projects y Exercises): `/v1/assignment/academy/cohort/<cohort_id>/task?limit=1000&task_type=PROJECT,LESSON,EXERCISE&student=<user_id>`
- Para obtener los activities: Debes obtenerlo del history log que proviene del cohort_user: 


---

- [ ] En este reporte no se va a poder modificar nada de los datos. Las modales no deben incluir los botons (Agregale una propiedad `readOnly=true` al componente)

**Comment by jefer94** [comment]
```py
def query(table, *, select=[], **kwargs):
    if select:
        query = f'SELECT {", ".join(select)} FROM {table}'

    else:
        query = f'SELECT * FROM {table}'

    exact = []
    gt = []
    gte = []
    lt = []
    lte = []

    for key in kwargs:
        if key.endswith('__gt'):
            gt.append({'k': key.replace('__gt', ''), 'v': kwargs[key]})

        elif key.endswith('__gte'):
            gte.append({'k': key.replace('__gte', ''), 'v': kwargs[key]})

        elif key.endswith('__lt'):
            lt.append({'k': key.replace('__lt', ''), 'v': kwargs[key]})

        elif key.endswith('__lte'):
            lte.append({'k': key.replace('__lte', ''), 'v': kwargs[key]})

        else:

            exact.append({'k': key, 'v': kwargs[key]})

    if gt or gte or lt or lte or exact:
        query += ' WHERE '

        for o in gt:
            query += f'{o["k"]} > {o["v"]} AND '

        for o in gte:
            query += f'{o["k"]} >= {o["v"]} AND '

        for o in lt:
            query += f'{o["k"]} < {o["v"]} AND '

        for o in lte:
            query += f'{o["k"]} <= {o["v"]} AND '

        for o in exact:
            query += f'{o["k"]} = {o["v"]} AND '

        if query.endswith(' AND '):
            query = query[:-5]

    print(query)


query('table', select=['name', 'age'], age__gt=18, age__lt=30, name='John')

```

**Comment by tommygonzaleza** [comment]
- [ ] La modal aparece muy arriba, debe haber cierto margin con el tope de la pagina
- [ ] Utiliza esta primera version para los exercises: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9706%3A45745&mode=design&t=qGI9zkFNkIAWQJH4-1 (Luego se cambiara una vez se reciba la informacion de learnpack en el backend)
- [ ] Falta mostrar attendance

**Comment by tommygonzaleza** [comment]
- [ ] Ya puedes obtener los activities del usuario con este servicio `GET /v1/activity/academy/activity/<str:activity_id>?user_id=<user_id>`. Y puedes encontrar los iconos de los activities aqui: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9556%3A47692&mode=design&t=eiJIncSUAJonTi08-1

**Comment by pbullor** [comment]
@alesanchezr le agregué la etiqueta de PM Scrum para verlo y seguirlo desde nuestro Scrum tmb.

**Comment by alesanchezr** [comment]
Ya el backend termino de recolectar las actividades, ahora falta integrar eso con el reporte de front end.

**Comment by tommygonzaleza** [comment]
- [ ] Agregar capacidad de agrupamiento a la funcion de Jeferson y convertir en un endpoint que permita recibir los parametros por querystring. Siendo dos parametros por querystring `by` y `grouping_function` (`Sum`, `Count`, `Avg`).

**Comment by tommygonzaleza** [comment]
No muestra nada en el reporte, probe con los datos de produccion. Igual a la derecha se muestran unos errores en dos endpoints por no pasarle el academy_id, quizas es por eso
<img width="1435" alt="Screenshot 2023-12-05 at 4 18 26 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/1dd50e9a-1209-46a2-a357-3e4b085c8329">

**Comment by tommygonzaleza** [comment]
- [ ] Las cajas de arriba deben cubrir todo el espacio como en el diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9499%3A45994&mode=design&t=ezGG9hWiZ2rll5wi-1
- [ ] El borde de las cajas debe ser un azul mas claro

**Comment by tommygonzaleza** [comment]
- [ ] Al darle a apply filters debe cerrarse la modal
<img width="1470" alt="Screenshot 2023-12-12 at 9 56 13 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/66d0104e-d806-4d58-932c-b9b6e3b83cf1">
- [ ] El calendario no esta filtrando por las fechas
