### ISSUE TITLE
Agregar datos a vista de todos los entregables de una cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5352]
Falta agregar por cada estudiante en la vista de la lista de los estudiantes los siguientes datos:

- % de entregado
- Fecha de ultima entrega

### % de Entregado:

Para calcularlo se debe utilizar la misma lista que se muestra actualmente (Ya que esta filtrando por los proyectos) y sumar la cantidad de tasks que no tienen status `PENDING`, multiplicar ese valor por 100 y luego dividirlo entre la cantidad total de elementos en la lista. `(cantidad_no_pending * 100) / cantidad_total`

### Fecha de Ultima entrega:

- [ ] Agregar en el admin de Django el valor `updated_at` en los tasks.
- [ ] Agregar el valor `updated_at` al serializador [TaskGETSmallSerializer](https://github.com/breatheco-de/apiv2/blob/98ecdab6686428738a70b6f225d1417a0b6d1c0f/breathecode/assignments/serializers.py#L50)
- [ ] (FRONTEND) Comparar el `updated_at` con el tiempo actual, para mostrar hace cuanto subio su ultimo task. Si fue hace menos de una hora, muestras hace cuantos minutos (`25 minutes ago`). Si fue hace menos de 24 horas, muestras hace cuantas horas se hizo (`3 hours ago`). Si fue hace mas de 24 horas entonces muestras hace cuantos dias se hizo (`14 days ago`)

**Comment by alesanchezr** [comment]
pero updated_at ya esta, solo tienes que utilizarlo.

**Comment by tommygonzaleza** [comment]
Si no puse agregarlo al modelo, falta es agregarlo al admin para poder visualizarlo y agregarlo en el serializador

**Comment by alesanchezr** [comment]
- [ ] Poner un small pa q se vea mas pequeño
- [ ] Separarlos con una rayita (ver foto)
- [ ] Es "delivery" no "deliver"
![Screenshot 2023-09-05 at 5 39 17 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/b41b41ab-6e4d-4f0b-ae4b-0c16967ed2ea)
