### ISSUE TITLE
Profile picture can’t be uploaded 

### ISSUE THREAD

**Issue by minervaDutta** [breatheco-de/breatheco-de#5413]

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/272aa2be34e62976347969995b4f9a9bf7cf2a3d

**Comment by jefer94** [comment]
Done

**Comment by tommygonzaleza** [comment]
Continua dandome este error: `requests.exceptions.ReadTimeout`

**Comment by tommygonzaleza** [comment]
![e94a2c6a-f28e-4788-8c31-a620e7b69385](https://github.com/breatheco-de/breatheco-de/assets/56565994/2012fe11-0fc8-42db-bd3a-dbb96dcbf560)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/compare/43559ec5...47e1393a
