### ISSUE TITLE
Enviar tasks con status DELIVERED a RigoBot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5417]
- [ ] Al momento en que un task se marca con status DELIVERED, se debe utilizar este endpoint de RigoBot para que RigoBot pueda utilizarlo para revisarlo: `POST /v1/finetuning/me/repository/`
- [ ] Si un task que estaba con status DELIVERED se cambia el status, entonces se debe usar este endpoint `PUT /v1/finetuning/me/repository` para dejarle saber a RigoBot que ya no debe revisarlo mas.
- [ ] El endpoint a veces retornara 404 ya que varios tasks de usuarios legacy no van a tener sus repositorios en RigoBot aunque tengan status DELIVERED

**Comment by jefer94** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/3018142/e6d9d6b4-30b4-4a7c-9855-8a0cb7c0cd70)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/973/files

**Comment by jefer94** [comment]
https://github.com/breatheco-de/rigobot/pull/46
