### ISSUE TITLE
Agregar servicio para `GET /v1/assignments/task/<int:task_id>/code_revision`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5418]
Esta URL debe ser un Proxy que funcione como intermediario entre RigoBot y el frontend.

- [ ] [Este](https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#87843ea3-3dc8-48d8-a290-40d3dfb5f4f9) es el servicio con el que obtienes los code reviews de un task. El repositorio que debes usar para saber cual code revision debes obtener es el de `github_url` del task
- [ ] Tambien se debe agregar el servicio `GET /v1/assignments/me/code_revision`, para obtener todos los code revisions de un user. [Este](https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#d7d4ebee-953f-483b-9b2d-b0ebc20a240c) es el servicio de RigoBot

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/973/files

**Comment by jefer94** [comment]
https://github.com/breatheco-de/rigobot/pull/46
