### ISSUE TITLE
Agregar interlinks a las siguientes lecturas

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5469]
Las siguientes lecturas no han sido indexadas por google, tenemos que resolverlo buscando donde publicar links hacia ellas:

1. Buscar lecturas actuales que si estan indexadas por google para interlinking.
2. Buscar en redit donde incluirlas.
3. Que mas podemos hacer?

- [ ] https://4geeks.com/how-to/github-clone-repository
- [x] https://4geeks.com/how-to/How-to-print-in-javascript
- [ ] https://4geeks.com/es/how-to/clonar-array-javascript
- [ ] https://4geeks.com/how-to/what-is-float-in-python
- [ ] https://4geeks.com/how-to/how-to-run-javascript
- [ ] https://4geeks.com/how-to/how-to-comment-out-multiple-lines-in-python
- [ ] https://4geeks.com/how-to/how-to-update-python-in-terminal
- [ ] https://4geeks.com/how-to/how-to-exit-python-in-terminal
- [ ] https://4geeks.com/es/how-to/como-instalar-javascript
- [ ] https://4geeks.com/es/how-to/metodo-foreach-javascript
- [ ] https://4geeks.com/es/how-to/metodo-reduce-javascript
- [ ] https://4geeks.com/how-to/what-does-double-equal-mean-in-python
- [ ] https://4geeks.com/es/how-to/ejemplos-expresiones-regulares
- [ ] https://4geeks.com/how-to/sqlalchemy-join
- [ ] https://4geeks.com/how-to/how-to-split-a-string-in-python
- [ ] https://4geeks.com/how-to/convert-list-to-string-in-python
- [ ] https://4geeks.com/how-to/how-to-check-python-version
- [ ] https://4geeks.com/how-to/how-to-update-python-version
- [ ] https://4geeks.com/how-to/how-to-square-a-number-in-python
- [ ] https://4geeks.com/how-to/python-list-extend-method
- [ ] https://4geeks.com/how-to/javascript-array-every
- [ ] https://4geeks.com/how-to/what-is-the-difference-between-java-and-javascript
- [ ] https://4geeks.com/es/how-to/como-habilitar-javascript
- [ ] https://4geeks.com/how-to/how-to-reverse-a-list-in-python
- [ ] https://4geeks.com/es/how-to/array-vacio-javascript
- [ ] https://4geeks.com/how-to/how-to-concatenate-strings-on-python
- [ ] https://4geeks.com/how-to/javascript-array-some-method
- [ ] https://4geeks.com/how-to/javascript-array-intersection
- [ ] https://4geeks.com/how-to/what-does-double-slash-mean-in-python-floor
- [ ] https://4geeks.com/how-to/how-to-call-a-function-in-javascript
- [ ] https://4geeks.com/es/how-to/como-clonar-un-repositorio-de-github
- [ ] https://4geeks.com/how-to/regex-for-whitespace
- [ ] https://4geeks.com/es/how-to/regex-para-no-match
- [ ] https://4geeks.com/how-to/how-to-disable-javascript-in-tor
- [ ] https://4geeks.com/how-to/how-to-multiply-in-Python

**Comment by Jsolis4geeks** [comment]
preparé este Google Sheet para tener un mejor tracking de esto

**Comment by alesanchezr** [comment]
Estos articulos tambien deben ser linkeados desde nuestras paginas que ya fueron rankeads por google, sobretodo aquellas que tienen buen ranking o son longevas.

**Comment by Jsolis4geeks** [comment]
- [x]  https://4geeks.com/how-to/github-clone-repository
- [x] https://4geeks.com/how-to/How-to-print-in-javascript
- [x] https://4geeks.com/es/how-to/clonar-array-javascript
- [x] https://4geeks.com/how-to/what-is-float-in-python
- [x] https://4geeks.com/how-to/how-to-run-javascript
- [x] https://4geeks.com/how-to/how-to-comment-out-multiple-lines-in-python
- [x] https://4geeks.com/how-to/how-to-update-python-in-terminal
- [x] https://4geeks.com/how-to/how-to-exit-python-in-terminal
- [x] https://4geeks.com/es/how-to/como-instalar-javascript
- [x] https://4geeks.com/es/how-to/metodo-foreach-javascript**
- [x] https://4geeks.com/es/how-to/metodo-reduce-javascript
- [x] https://4geeks.com/how-to/what-does-double-equal-mean-in-python
- [x] https://4geeks.com/es/how-to/ejemplos-expresiones-regulares
- [x] https://4geeks.com/how-to/sqlalchemy-join
- [ ]  https://4geeks.com/how-to/how-to-split-a-string-in-python
- [ ]  https://4geeks.com/how-to/convert-list-to-string-in-python
- [ ]  https://4geeks.com/how-to/how-to-check-python-version
- [ ]  https://4geeks.com/how-to/how-to-update-python-version
- [ ]  https://4geeks.com/how-to/how-to-square-a-number-in-python
- [ ]  https://4geeks.com/how-to/python-list-extend-method
- [ ]  https://4geeks.com/how-to/javascript-array-every
- [ ]  https://4geeks.com/how-to/what-is-the-difference-between-java-and-javascript
- [ ]  https://4geeks.com/es/how-to/como-habilitar-javascript
- [ ]  https://4geeks.com/how-to/how-to-reverse-a-list-in-python
- [ ]  https://4geeks.com/es/how-to/array-vacio-javascript
- [ ]  https://4geeks.com/how-to/how-to-concatenate-strings-on-python
- [ ]  https://4geeks.com/how-to/javascript-array-some-method
- [ ]  https://4geeks.com/how-to/javascript-array-intersection
- [ ]  https://4geeks.com/how-to/what-does-double-slash-mean-in-python-floor
- [ ]  https://4geeks.com/how-to/how-to-call-a-function-in-javascript
- [ ]  https://4geeks.com/es/how-to/como-clonar-un-repositorio-de-github
- [ ]  https://4geeks.com/how-to/regex-for-whitespace
- [ ]  https://4geeks.com/es/how-to/regex-para-no-match
- [ ]  https://4geeks.com/how-to/how-to-disable-javascript-in-tor
- [ ]  https://4geeks.com/how-to/how-to-multiply-in-Python

**Comment by URubino4Geeks** [comment]
Vamos a buscar las referencias de los links que ya se agregaron @Jsolis4geeks

**Comment by URubino4Geeks** [comment]
Vamos a enviar el listado de los interlinks a Alejandro para que los revise antes de cerrar el issue

**Comment by URubino4Geeks** [comment]
Todavía tenemos que enviar el listado
