### ISSUE TITLE
Pagar la referencia de Hubflix

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5486]
@Jsolis4geeks

**Comment by URubino4Geeks** [comment]
Estamos esperando por la cuenta de Zelle para hacer el pago

**Comment by Jsolis4geeks** [comment]
No han dado la cuenta de Zelle, la verdad que los mas interesados en que les paguen son ellos y no me han dicho nada, asi que no voy a estar insistiendo

**Comment by Jsolis4geeks** [comment]
Ya enviaron otra vez su información de pago y se les pudo calmar, esperemos que no se desesperen, xq no nos van a dar tiempo hasta agost, teniendo en cuenta que esta negociacion viene desde Mayo

**Comment by URubino4Geeks** [comment]
Estamos esperando por Marcelo para ver si se resuelve el problema con el pago
