### ISSUE TITLE
Hacer branding de redes sociales

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5492]
Crear las imagenes para los perfiles de twitter y youtube. Busca cuales son los tipos de imagenes de cada red social por ejemplo el header de twitter, foto de perfil, etc.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2683%3A4527&mode=design&t=lLKvMpP0DPgqYs1T-1

**Comment by tommygonzaleza** [comment]
- [ ] No esta funcionando bien el tamaño para youtube: https://www.awesomescreenshot.com/image/41476459?key=28120705c49a1ad9b9dbf902da379edf
- [ ] Tambien se debe agregar el avatar de youtube y twitter

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2683%3A4527&mode=design&t=SRmS3DpwMVywAXPB-1
