### ISSUE TITLE
Mostrar consumibles disponibles en vista de subscriptions

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5528]
Deben haber tnatos KPIs como tipos de consumibles hayan, por ahora son workshops y mentorias

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&mode=design&t=LkKd0n4kuvuMqAJL-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9798%3A46211&mode=design&t=hy99gTo4GqnhwNW7-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar cuantos sessions quedan por grupo de tipo de workshops, es decir, tendras 5 tipo de workshops en los que te quedan 5 entradas, estos deben verse agrupados

**Comment by tommygonzaleza** [comment]
- [ ] Se debe agregar cuantos hay por grupo de workshops, los grupos de workshops van a ser por ejemplo workshops tecnicos (En el que estan los workshops de javascript, python, java, etc) o workshops de carrera

**Comment by tommygonzaleza** [comment]
- [ ] Agrega version para los mentorship services. Estos deben mostrar los distintos mentorship services a los que puedes acceder y cuantos te quedan de cada mentorship service (Puede ser 0, mas de 1, o infinito).

**Comment by tommygonzaleza** [comment]
- [ ] Mejorar iconos en la [seccion de mentoring sessions](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10139%3A47239&mode=design&t=zqHFHUWNkxJipB9V-1)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10139%3A47239&mode=design&t=nTVJSJBLB97Wso2n-1

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-02-06 at 6 46 53 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/728e7451-0495-4585-95a0-77c4e289e396)

- [ ] Luego con este endpoint puedes obtener los mentorship services de ese mentorship_service_set: `GET /v1/payments/mentorshipserviceset/<mentorshipserviceset_id>` o para event_type_set: `GET /v1/payments/eventtypeset/<eventtypeset_id>`

**Comment by tommygonzaleza** [comment]
- [ ] Si el consumible dice -1, debes poner el icono de infinito
![Screenshot 2024-02-23 at 2 07 36 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/d6c61e94-0a4e-405c-8044-cb30b3604e53)
- [ ] Aqui debe decir services en vez de sessions.
![Screenshot 2024-02-23 at 2 11 15 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/cada19b6-a82a-4022-bd89-9bc8781bfc1c)
