### ISSUE TITLE
Agregar nuevos backlinks

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5557]
Necesitamos agregar 10 nuevos backlinks, todos en español: 6 para España y 4 para Estados Unidos.

**Comment by Jsolis4geeks** [comment]
Lo dividí en 2 ordenes diferentes, una para ingles y otra para español

La de español ya esta lista, seria entrar y pagar

**Comment by Jsolis4geeks** [comment]
Estamos teniendo problemas con el pago de las ordenes, pero ya estan añadidas a la espera de un pago

**Comment by URubino4Geeks** [comment]
Ya no se realizarán estas referencias con Motherlink por los problemas con la plataforma de pago. Se realizarán con Paper.Club

**Comment by Jsolis4geeks** [comment]
En Motherlink hay un saldo disponible con el cual puedo comprar 4 enlaces, estoy pendiente a respuesta para proceder con esta orden.

**Comment by URubino4Geeks** [comment]
Vamos a usar el crédito disponible para pagar lo que teníamos pendiente desde hace tiempo

**Comment by URubino4Geeks** [comment]
Paper.Club ya publicó 3 de los 4 que se solicitaron.

**Comment by Jsolis4geeks** [comment]
Ya los 4 articulos de Motherlink están enviados y optimizados, actualmente estamos esperando a que se publiquen.
Queda 1 artículo por publicar por parte de Paper.club, pero podemos ir creando una nueva orden de momento
