### ISSUE TITLE
Modal de Code Reviews

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5559]
En la modal de review de los assignments, los profesores pueden hacer un code review al darle click a un boton, esto debe abrir una modal en donde el profesor puede hacer un code review.

En esta modal, se va a mostrar un codigo, el cual el profesor puede seleccionar varias lineas del mismo y agregar un comentario relacionado a esas lineas, luego de agregarlo, debe permitir agregarlo y salir o agregarlo y crear otro review, la idea es que cuando sea agregarlo y crear otro review sea muy smooth y rapido.

Actualmente se ve asi: https://rigobot.herokuapp.com/review/repo?repo=https://github.com/Charlytoc/chatbot-cli-template&file=4&token=cd39e73b3880aec32f0f01f760d77f938f886c27

Chequea las funcionalidades que tiene para que se reflejen en el diseño

**Comment by tommygonzaleza** [comment]
- [ ] Construir la modal en donde va el code review

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6939%3A42080&mode=design&t=hy99gTo4GqnhwNW7-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar logo de rigobot
- [ ] Agregar como se ve el texto seleccionado
- [ ] En el campo de texto donde describe el code review, se debe agregar cuantos caracteres lleva (65/280). Si lleva menos de 60 caracteres entonces se muestra en rojo esta cuenta y el boton de submit queda inhablitado.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=zX22Edyb6uLTo60e-1

**Comment by tommygonzaleza** [comment]
- [ ] Quitar dark mode del lado derecho de la modal

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=lbULihR2PjHaKEiv-1

**Comment by tommygonzaleza** [comment]
Agregar modal para crear los code reviews (Si eres profesor) y agregar modal para ver lo code reviews que te han hecho (Si eres estudiante)

**Comment by tommygonzaleza** [comment]
Aqui esta todo el flujo de la modal: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10352%3A34772&mode=design&t=4AsD8xKfEHbjlHzQ-1

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=E5bOnVnjnG3BsPIi-1

**Comment by tommygonzaleza** [comment]
Debes usar estos servicios: https://github.com/breatheco-de/apiv2/blob/main/breathecode/assignments/urls.py#L18:L28

**Comment by tommygonzaleza** [comment]
Mira lo que ocurre al cambiar de host y ponerle un token
https://github.com/breatheco-de/breatheco-de/assets/56565994/d4c914d7-9f5f-4add-baaf-d661a48fb9cb

**Comment by tommygonzaleza** [comment]
Revisa las modificaciones en el diseño, ademas le agregue una mejor explicacion a cada detalle del flujo @ArielCalisaya

**Comment by tommygonzaleza** [comment]
Por ahora esperamos por este issue para poder obtener los code revision y commit files de los estudiantes

**Comment by tommygonzaleza** [comment]
### Vista como Teacher:

- [ ] En la modal para revisar la entrega no muestra el link al repositorio entregado por el alumno
- [ ] Mira como se esta viendo la modal para hacer el code review
<img width="1357" alt="Screenshot 2024-02-02 at 2 09 42 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/f590514d-4c2c-4729-a32f-2c771a0a18a5">
- [ ] Haz la modal mas pequeña para que se pueda ver completa sin hacer scroll
<img width="1357" alt="Screenshot 2024-02-02 at 2 12 51 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/3a056631-fc44-42bb-9915-5402ea390f6b">
- [ ] Cambios en modal para donde el profesor ve los code reviews de un proyecto:
<img width="1357" alt="Screenshot 2024-02-02 at 2 13 53 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/ed6349f9-e027-4347-b99b-b0da1041aca9">
- [ ] Estas mostrando la parte del markdown donde te dice que tecnologia es la del archivo, no debes mostrarlo
<img width="1357" alt="Screenshot 2024-02-02 at 2 18 29 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/60ba140d-1ac7-43a8-9b1b-49b0cbd994f8">

### Vista de estudiante:

- [ ] Cambios en modal para ver sus code reviews de un proyecto:
<img width="1357" alt="Screenshot 2024-02-02 at 2 22 33 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/f7be110a-e829-4ace-a01e-3230268ccd68">
- [ ] Los botones de feedback deben estar opacados cuando no se ha seleccionado ninguno
<img width="1357" alt="Screenshot 2024-02-02 at 3 05 43 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/62c46bbd-f426-4d39-b7b1-e5eb9ca51518">
- [ ] Luego de dar feedback sobre alguno de los comentarios de los code reviews, cuando accedo otra vez a ese comentario,  deberia mostrar el que se selecciono con color.
- [ ] No deberia permitir seleccionar el codigo como estudiante
<img width="1357" alt="Screenshot 2024-02-02 at 3 11 34 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/cc8ff670-f356-4132-9d6f-21b79228e97a">
- [ ] Cambia este mensaje por: "The teacher's feedback will be shown here if it's approved"
<img width="1357" alt="Screenshot 2024-02-02 at 3 19 13 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/2b1baf54-d4ec-425d-ae50-ce415e7e91ac">

**Comment by tommygonzaleza** [comment]
- [ ] Permitir abrir el preview de cualquier code review solo con darle click en cualquier lugar del tab y no solo en el boton de review
![Screenshot 2024-02-06 at 2 12 59 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/38db3a1f-58da-4eab-98c8-4cd28360241a)

**Comment by tommygonzaleza** [comment]
- [ ] Si el task ya tiene `revision_status` marcado como `APPROVED` y `task_status` como `DONE`, y ademas no tiene ningun coderevision, podemos tomarlo como un task viejo, entonces no debes mostrar informacion de los code reviews sino mostrarlo como accepted como se mostraba antes.

**Comment by tommygonzaleza** [comment]
- [ ] Vamos a permitir por ahora (Luego lo haremos obligatorio por lo que no quites el codigo que tienes ahora) aceptar tareas que no tengan code reviews. Asi que el flujo debe funcionar como estaba antes, las tareas pueden ser aceptadas o rechazadas y los code reviews se deben permitir hacer pero no son obligatorios

**Comment by tommygonzaleza** [comment]
Se seta mostrando siempre este error al abrir el dashboard de la cohort


![Image](https://github.com/breatheco-de/breatheco-de/assets/56565994/4002d095-e72c-4ca2-9ac0-bf8416926a40)

**Comment by tommygonzaleza** [comment]
- [ ] Se esta mostrando el feedback del code review como malo a pesar de que todavia no tiene ningun feedback (De hecho no tiene code reviews). Por defecto se debe mostrar ambas opciones de feedback, con cierta opacidad como aparece en el diseño.
- [ ] Se esta mostrando que tiene un code review a pesar de que todavia no se ha hecho ningun code review
![Screenshot 2024-02-20 at 11 56 26 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/5e17dcc9-7fd8-49ee-b492-5bd456f40071)
