### ISSUE TITLE
Los emails deben guardarse siempre lowercase en el invite

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5575]
Por no guardarse todos lowercase, la validacion del email es case sensitive por lo que permite tener emails repetidos si tienen mayusculas o minusculas diferentes.

- [ ] En el [metodo save()](https://github.com/breatheco-de/apiv2/blob/4ba3a8c78ff08854fd9ca6cb03c8b0265306dc47/breathecode/authenticate/models.py#L180) del modelo se debe guardar el email siempre minuscula.
- [ ] En el `validate()` del serializador cuando se valida si el email ya existe, debe validar ambos en lower().

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1012
