### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Newux** [breatheco-de/breatheco-de#5594]
The following error occurs when trying to access the program courses.

<img width="1430" alt="Screen Shot 2023-07-06 at 11 33 49 PM" src="https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/39223283/47dd7a20-a175-46df-8d12-256b5fb36b5d">

**Comment by tommygonzaleza** [comment]
This bug has been fixed already. I wasn't able to replicate it
