### ISSUE TITLE
Learn-in-public

### ISSUE THREAD

**Issue by Lorenagubaira** [breatheco-de/breatheco-de#5618]
Fix the images of the learn-in-public project 

https://4geeks.com/syllabus/full-stack-fake-6/project/learn-in-public-project

![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/102861577/9075e536-1515-43e0-8c2e-b051220d532f)

**Comment by Khrisefzm** [comment]
Image fixed
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/e9d69691-bca0-4667-a61f-d4619a20bd42)
