### ISSUE TITLE
Implement translation link (if available) on the blog

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/breatheco-de#5620]
### Bug description

When I click on the translation at this [blog Post](https://4geeksacademy.com/us/full-stack-developer/full-stack-developer) it should lead to this other [blog post in spanish](https://4geeksacademy.com/es/desarrollador-full-stack/desarrollador-full-stack-developer) but it does not, instead redirects me to the Home Page.

Note that when I say click on translation I am referring to this section of the website:

![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/118853358/6f6a3c3d-cc72-4629-b634-75c82628a2dd)

### Steps to reproduce

1 - Go to https://4geeksacademy.com/us/full-stack-developer/full-stack-developer
2 - Click on the translation for Spanish

### Expected behavior

When I click on the translation at https://4geeksacademy.com/us/full-stack-developer/full-stack-developer leads me to the blog post in Spanish which is https://4geeksacademy.com/es/desarrollador-full-stack/desarrollador-full-stack-developer it should include the `hreflang` in the head of the html

**Comment by tommygonzaleza** [comment]
- [ ] Cuando el post no tiene una traduccion asociada, debe enviarte al home del blog en el otro idioma, actualmente te envia al home de la pagina como tal en el otro idioma

**Comment by tommygonzaleza** [comment]
waiting for the PR to be accepted
