### ISSUE TITLE
Agregar a venezuela como alias de de latam en el reporte de leads consolidated

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5623]
<img width="965" alt="Screenshot 2023-07-13 at 12 14 54 PM" src="https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/13bc3d83-48e3-42bc-b899-838952066ca5">

**Comment by Charlytoc** [comment]
Entonces Venezuela va a tener dos locations, Caracas y Maracaubo, ¿no?
