### ISSUE TITLE
Crear componente de Financing

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5624]
Queremos un componente de Financing (/financing/), principalmente para usarlo en el homepage, y además que podamos utilizarlo en los landings.

Este es el copy: 

**Finance your future**
We’re all about making our high-quality education affordable to everyone. That's why we offer multiple options to help you fund our coding bootcamps stress-free. Whether it's an ISA, scholarship, payment plan or Job Guarantee we're here to guide you every step of the way. 
See all financing options (Link to /financing/)

El botón debe ser opcional ya que lo queremos en el homepage pero no en los landings

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7975%3A14623&mode=design&t=DIE61YbGDOPenoZB-1
