### ISSUE TITLE
Agregar imagen para learnpack en pagina de about us

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5625]
Hace falta agregar la imagen para este espacio en la pagina de [learnpack.co/about](http://learnpack.co/about)
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/78da157f-6460-4201-aa00-a99413fde718)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10165%3A48290&mode=design&t=gNQwtklSWXYIxTIF-1
