### ISSUE TITLE
Revisar que los filtros de Next Dates que traigan la data correcta de BreatheCode

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5626]
Las fechas de los próximos programas no se están mostrando correctamente en la mayoría de campus (Miami se muestra bien pero no España, Toronto, Orlando, etc.)

**Comment by tommygonzaleza** [comment]
- [ ] Obten el academy del alias y traete las cohorts de esa academia

**Comment by tommygonzaleza** [comment]
Esta funcionando bien
