### ISSUE TITLE
SEO para landing de workshops y eventos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5628]
- [ ] Hacer un nuevo sitemap `https://4geeks.com/events-sitemap.xml`
- [ ] El URL canonico de un evento deberia ser consistente con la implementacion de idioma que tenemos en los assets, los eventos en ingles no tienen `es` sino que son direcamente: `https://4geeks.com/workshops/<event_slug>`
- [ ] Los eventos en español o cualquier otro idioma son `https://4geeks.com/<lang>/workshops/<event_slug>`
- [ ] Los eventos no tienen traduccion, por lo tanto la bandera de idioma no debe tener para cambiar a otro idioma.
- [ ] El sitemap debe ser consistente.
- [ ] Adicionalmente seria ideal que si el evento NO es en ingles el landing page `https://4geeks.com/workshops/<event_slug>` tenga una redireccion permanente a `https://4geeks.com/<lang>/workshops/<event_slug>`

Asegurarse de que los landings de los workshops cumplan con las mejores practicas
- [ ] etiqueta canonica.
- [ ] Hreflangs
- [ ] el meta description debe ser el `event.excerpt`.
- [x] Corregir las etiquetas sociales. https://i.imgur.com/gkLqeNP.png
- [ ] las etiquetas heading estan mal, desde el punto de vista de SEO [solo deberían existir estas etiquetas](https://www.awesomescreenshot.com/image/41485830?key=2db54bcc52609349268e8ef3adf8e85f), todas las demas deberian desaparecer, aunque el landing debe verse igual a como se ve ahorita.
- [ ] Agregar structured data para describir el evento [con todas las propiedades que peudas](https://schema.org/Event),  y utilizar el [debugger de google para segurarse que este correcto](https://developers.google.com/search/docs/appearance/structured-data).

**Comment by tommygonzaleza** [comment]
- [ ] Los eventos no tienen traduccion, por lo tanto la bandera de idioma no debe tener para cambiar a otro idioma.
