### ISSUE TITLE
Optimizar para moviles call to action de workshop landing

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5630]
El call to action puede ser una barra inferior que te siga.

Que tenga el cintador regresivo y un boton de registrarme.

Si le doy al boton me aparece el formulario de ser necesario.

![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/acc72d4d-6832-42ab-a4cb-8a778ef11465)

![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/bcf4cecf-021a-4197-9f76-17d40c167fa3)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10085%3A48330&mode=design&t=qVggdUfs4SoN3nVt-1

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/breatheco-de/breatheco-de/issues/5790)
