### ISSUE TITLE
Propuesta de interfaz para feedback de Rigobot en ejercicios de Learnpack isolated

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5643]
Este es el [Figma ](https://www.figma.com/file/d125akVdljVYGZ82DBarMx/New-UI?type=design&node-id=406-2&mode=design&t=2hZx9l50TsMdxsxr-0)de Learnpack

Este es el [repositorio ](https://github.com/learnpack/ui)donde se puede ver la documentación:

Y [aquí ](https://tinyurl.com/2jygvg8f)hay una captura de la sección que compete a este ticket

**Comment by Charlytoc** [comment]
Explicación: Learnpack es una aplicación con distintas funcionalidades, una que se va a aplicar en un futuro próximo es el feedback. Se requiere que en el componente del screenshot se pueda recibir un feedback. Se me ocurre que el input/output esté en la misma altura, y antes de eso aparezca el resultado del test y también el feedback de la IA.
