### ISSUE TITLE
En learnpack refactorizar comando login para que use el login de 4Geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5644]
Hay que cambiar el CLI, [especificamente por estos codigos](https://github.com/learnpack/learnpack-cli/blob/main/src/utils/api.ts#L65), para que haga login con 4geeks.com y no con learnpack.'

Luego usaremos el token apra hacer llamadas a ambas APIs

**Comment by Charlytoc** [comment]
- [ ] De momento nos vamos a loggear por el CLI
- [ ] En el futuro vamos a tener que implementar un front
- [ ] Y poder recibir una variable de entorno, y si no la tiene, se loggea
