### ISSUE TITLE
Bus en el chat de rigobot

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5645]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/41620524?key=6309934e205e2b4143345a9659860eeb&size=orig) 

 - [ ] SI cambio el dropdown de documento no pasa nada
- [ ] Poder darle a enter para enviar el mensaje
- [ ] Antes de que llegue una respuesta, mientras esta cargando, ya puedes ir agregando un bubble de la respuesta que diga "Thinking..."
- [ ] By default, pick any document from the dropdown.
- [ ] 

---
**Source URL**:
[https://rigobot.herokuapp.com/v1/conversation/chat/?document_id=1](https://rigobot.herokuapp.com/v1/conversation/chat/?document_id=1)

**Comment by Charlytoc** [comment]
- [ ] Just show the purposes that can be indexed
