### ISSUE TITLE
Crear componente de Financing

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5649]
Este componente se quiere utilizar en el homepage y en los landings. El botón debe ser opcional ya que sólo queremos que se muestre en el homepage y no en los landings

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7975%3A14623&mode=design&t=DIE61YbGDOPenoZB-1

**Comment by alesanchezr** [comment]
sto se cierra porque es un two column right
