### ISSUE TITLE
Ultimos ajustes para poder estabilizar las facturas de ProvisioningBills

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5650]
- [ ] Las facturas solo deben permitir actividades de un solo mes, y debe guardarse dentro de la factura la fecha de inicio y la fecha fin sobre la que se encontraron actividades, ninguna otroa factura en el futuro de la misma academia puede pertenecer al mismo periodo.

Para gitpod
- [ ] Si un usuario tiene mas de un ProfileAcademy a la vez debe revisarse el CohortUser para asegurarse que la fecha del consumo este dentro de cohort start o end date. 
- [ ] Si no ese encuentra ninguna cohort en esa fecha revisaremos si tiene pertenecio a alguna cohort never_ending=False y se lo cobraremos a la ultima que perteneció. 
- [ ] Si no ha pertenecido a ninguna cohort never_ending=False en su vida, entonces le dividimos cobro de forma random a todas las academias a las que pertenece.

Para codespaces

- [ ] Si un usuario tiene status PAYMENT_CONFLICT porque no pudimos determinar a que academia pertenecia durante sus consimos, entonces se revisa el storage status que tiene en GithubAcademyUser y se le cobra sus consumos a todas las academias que no hayan marcado el status como DELETED.
- [ ] Si un GithubAcademyUser fue markado como DELETED por todas las academias, pero tiene un consumo, se debe buscar a que CohortUser pertenece durante ese periodo y facturarle el consumo a esa academia aclarando el siguiente mensaje de error: `We found activity from this user while he was studying at one of your cohort <cohort_slug>`.
- [ ] Cuando marquemos un cobro con PAYMENT_CONFLICT a una factura ([ver este ejemplo](https://www.awesomescreenshot.com/image/41624645?key=c0b18ee9a22df43c99308d8c389cc409)), el mensaje de error debera decir: `We could not find enough information about <email>, mark this user user as deleted if you don't recognize it`.
- [ ] Pareciera que se estan duplicando las facturas. Solo subi el CSV de codespaces para el mes de mayo y sin embargo me genero dos facturas, una de las dos nunca salio del status PENDING. [revisa esta foto](https://www.awesomescreenshot.com/image/41625210?key=d42553ff25314dcb7297fede61819320).
- [ ] Debemos crear un monitoring script para recordarle a las academias sobre aquellos GithubAcademyUsers que no han marcado como delete or add.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1010
