### ISSUE TITLE
Agregar un captcha a los landing page

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5684]
@alesanchezr Necesitamos verificar que el captcha automatizado esté funcionando o agregar una verificación manual para los usuarios dentro de los formularios en los landing pages. 

Están reportando de que han entrado varios leads desde los anuncios de Ads que al llamarlos no tienen idea de quién es 4Geeks ni cómo obtuvimos sus datos.

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/breatheco-de/breatheco-de/issues/6985)
