### ISSUE TITLE
Broken Pages (404) in 4Geeks.com

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/breatheco-de#5686]
### Bug description

Several Broken Pages (404) at 4Geeks.com need to be redirected and fixed.

You can find the whole list with the Broken URLs at the left and the URLs linking to them in the Right.

[4geeks_26-jul-2023_404-page_2023-07-27_11-54-58.csv](https://github.com/breatheco-de/breatheco-de/files/12185494/4geeks_26-jul-2023_404-page_2023-07-27_11-54-58.csv)

An example of a Broken link is: https://4geeks.com/interactive-coding-tutorials/technology/REST
And the page linking to it is: https://4geeks.com/interactive-coding-tutorial/family-tree-static-api

### Steps to reproduce

Open the following URL: https://4geeks.com/interactive-coding-tutorial/family-tree-static-api

Click here:
![image](https://github.com/breatheco-de/breatheco-de/assets/118853358/32f22a1b-96d2-44f5-a912-340865625916)

### Expected behavior

Not to be a 404 error

**Comment by ArielCalisaya** [comment]
Este issue ya ha sido solucionado
