### ISSUE TITLE
Buscar más escritores en inglés para el blog

### ISSUE THREAD

**Issue by URubino4Geeks** [breatheco-de/breatheco-de#5687]

**Comment by G-code7** [comment]
conseguí un escritor en inglés que puede ser capaz de entregarnos un articulo a la semana. 
si me das el visto bueno, puedo empezar a enviarles promps esta misma semana para publicarlo la semana entrante. 

con este tendríamos un total de 4 escritores. 

1- español 
1- español / ingles
2 en ingles.
