### ISSUE TITLE
Organizar los landings

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5689]
- [ ] Borrar todos los compoenntes que se puedan usar como `twocolumright` o `twocolumnleft`, por ejemplo `Finance`. En su lugar dejarlos como un ejemplo para que vean que cosas se peuden hacer con un twocolumnright o left.
- [ ] Revisar los componetnes que ya estaban y los nuevos se llamar igual pero con una a minuscula por delante para saber que son los nuevos de Ali.
- [ ] Tener la lista completa haciendo match del nuevo con el viejo, para luego borrar los vielos.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8124%3A6175&mode=design&t=zStdZQXrigyKrDRY-1
