### ISSUE TITLE
Open in collab button

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5725]
Some lessons need to have two different buttons at the same time: `Edit on github` and `Open In Collab`.

[This is how the open in collab link looks right now.](https://www.awesomescreenshot.com/image/41892321?key=ddc8b23e1669afabc5c735afcf066d12).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/41892120?key=14a21adde9cbc1efb403124938af5468&size=orig) 

---
**Source URL**:
[https://4geeks.com/lesson/hypothesis-testing](https://4geeks.com/lesson/hypothesis-testing)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10350%3A31688&mode=design&t=nTVJSJBLB97Wso2n-1

**Comment by tommygonzaleza** [comment]
- [ ] Cuando el asset es un jupyter notebook, debe mostrar ambos botones ("Open in collab" y  "Edit on github")
- [ ] El boton de edit on github ahora debe ser con el fondo gris como se muestra en el diseño

**Comment by tommygonzaleza** [comment]
No esta detectando esta formula de latex:
<img width="1470" alt="Screenshot 2023-08-07 at 6 32 18 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/86bf24c9-5a9c-42a5-a495-7531ed6cdc5a">

**Comment by tommygonzaleza** [comment]
- [ ] No se debe agregar el `.<lang>` en ningun momento, debes utilizar el nombre del archivo como lo recibas
