### ISSUE TITLE
Attributed Events Pipeline

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5730]
We need to create a dataset that registers all the user events in google analytics and maps them with our own attribution ids.

Sources: 
There is a dataset with all the events in google analytics here: `analytics_281853246.events_*`
There is a dataset with all the form_entries and their respective attribution_ids here: `dataflow.clean_form_entries__form_entry`

Creating the new dataset:
- [ ] First, we filter all the records in the `dataflow.clean_form_entries__form_entry` dataset that are `status=WON`. These are the contracts sold. The column `attribution_id` will be used as `user_id` to match records in the next dataset and step.
- [ ] Now we query the dataset `analytics_281853246.events_*` for any record with `user_id` = `attribution_id`.
- [ ] For each of those records, we get the `user_pseudo_id` and save them into a list called `pseudo_ids`.
- [ ] We query all the records with `user_pseudo_id` inside `pseudo_ids`, and set the same `attribution_id` to all of them.
- [ ] This table/dataset we be called `attributed_events`.

**Comment by alesanchezr** [comment]
No haz logrado que corra en dataflow.

Alternativamente se puede hacer el query en bigquery si sale mas facil.

**Comment by Charlytoc** [comment]
For some reason, certain ids are not working correctly when checking the report in Looker
