### ISSUE TITLE
Agregar una vista previa en modal de code review

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5744]
Agregar una vista previa en esta [modal](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=6G2aseF137eYN4OA-1) en la que permita escoger que archivo quiere revisar (Por lo tanto la vista siguiente debe tener un boton para escoger otro archivo o regresarse al paso anterior).

A la izquierda deben aparecer los archivos que se pueden revisar, y a la derecha unas instrucciones que diga  que debe escoger el archivo al que quiere hacerle el code review.

El diseño de los archivos que se deben escoger debe ser algo similar a github para que sea familiar para los profesores. Algo asi:
<img width="1096" alt="Screenshot 2023-08-01 at 7 47 25 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/01a8df6c-b006-4e2c-a9b7-7e3ec8bd3b0b">

> Basate un poco en esto

**Comment by Charlytoc** [comment]
- [ ] El diseño debe ser similar al de los assignments: 
![así](https://github.com/breatheco-de/breatheco-de/assets/107764250/7e4a744b-1d77-4141-b8ed-02f323916d79)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=WMrzb3q8b3KuRPnk-1

**Comment by tommygonzaleza** [comment]
Reutiliza este componente: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10412%3A29768&mode=design&t=3z9h3DJO6kn8BzKZ-1

Actualmente estas mostrando los archivos todos juntos, muestralos separados como en ese componente par apoder reutilizarlo igual en el codigo

**Comment by tommygonzaleza** [comment]
- [ ] Cambiar icono de cuando hay varios reviews en un mismo commit.
- [ ] Poner el commit abajo del nombre del archivo
- [ ] Poner el feedback (icono de Bueno o malo) en los code revision del estudiante

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=B8KV4BEHowiVgMtj-1

**Comment by alesanchezr** [comment]
- La barra de scroll cuando lees el code review es generalizada.
- El boton de back "reviewing" ocupa mucho espacio, no se puede fusionar ocn el titulo? Para darle mas espacio al contenido del code review.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=UezhrULI5mBShX2S-1

**Comment by tommygonzaleza** [comment]
- [ ] En el componente donde se muestran los archivos, en uno de los casos de los que se muestra el commit abajo del nombre del archivo, se esta mostrando el numero del commit abajo del icono.
- [ ] Agregar el caso en el que debe haber scroll en este [componente](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=WJydWOjVc6oEhIuy-1)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=hD6NusT7nHD3jK8L-1
