### ISSUE TITLE
Crear modal que muestre que se adquirio un plan

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5749]
La idea es que cuando una persona se registre en la pagina web, queremos que automaticamente inicien el free trial sin que tengan que aceptar nada a parte, para esto queremos mostrarles que es lo que estan adquiriendo (La informacion del plan), tiene que ser como una breve modal un poco emotiva porque muestra que esta adquiriendo algo y que le muestre la info del plan:

<img width="481" alt="Screenshot 2023-08-02 at 11 04 31 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/7b265715-315c-4d63-8529-88f88f5133a5">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10303%3A28421&mode=design&t=dNofjFU8GM6TxCpT-1

**Comment by tommygonzaleza** [comment]
Revisa como se veria en la vista de un workshop para ver si hace falta modificar o hacer mas oscuro el fondo

**Comment by ali5uarez5** [comment]
El modal iria sobre un overlay negro con opacidad

**Comment by tommygonzaleza** [comment]
- [ ] Cuando el usuario acepte la modal se debe volver a hacer el request que chequea sus consumibles para que le aparezca la informacion actualizada
