### ISSUE TITLE
Fixed mistakes in answer/bootstrap-quiz

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#5750]
las oraciones a cambiar aparecen 2 veces, hay que colocar la de abajo
tambien hay comentarios, leerlos

Archivo inglés:
https://docs.google.com/document/d/1-tyg3bTAe51vixzbcLxn9YxwSK-oVvxdk0ruL2Ocd58/edit?usp=sharing

Archivo español:
https://docs.google.com/document/d/153dRMsioUcoA64WL2l7kp-D0HwoUX_jibyK6vHJ7MJo/edit?usp=sharing

**Comment by tommygonzaleza** [comment]
Resuelto!
