### ISSUE TITLE
Se estan mostrando repetidos los assignments de los alumnos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5753]
Cuando un profesor filtra por estudiante en la vista de assignments de una cohort, se ven repetidos 4 veces cada assignment

<img width="1445" alt="Screenshot 2023-08-02 at 4 26 00 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/b0d0a5d7-7b96-401f-9f79-33f5ae690d8c">

**Comment by gustavomm19** [comment]
https://github.com/breatheco-de/apiv2/pull/1031
