### ISSUE TITLE
Boton Get feedback en Learnpack

### ISSUE THREAD

**Issue by Charlytoc** [breatheco-de/breatheco-de#5758]
- [ ] En Learnpack en vez de el botón de Test debería estar un dropdown que diga: **Feedback**
- [ ] En el dropdown tenemos dos botones: **AI feedback**, **Test** y una descripción: **Feedback plays an important role when learning technical skills. Learn why.**
- [ ] Componente similar al feedback de Code Reviews
Este ícono estaría dentro del pill del botón
![Icon](https://github.com/breatheco-de/breatheco-de/assets/107764250/cfca0bc2-5630-478f-bde2-a631229559ef)

- [ ] Una vez se obtiene una respuesta del servidor, se despliega una modal que muestra el  feedback de la AI en markdown y tiene dos botones para marcar la respuesta como USEFUL o NOT USEFUL similar a 
![esta](https://github.com/breatheco-de/breatheco-de/assets/107764250/8bc1b3ed-2203-451b-a388-abaf254a9d5e)

- [ ] Usar los colores de Learnpack en la modal, la anterior es solo un ejemplo

[Aquí](https://www.figma.com/file/d125akVdljVYGZ82DBarMx/New-UI?type=design&node-id=610-479&mode=design) tienes el Figma de Learnpack

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?type=design&node-id=406%3A2&mode=design&t=ujCaSdjZ5o47tyFB-1

**Comment by tommygonzaleza** [comment]
- [ ] Falta mostrar un status si el feedback fallo
