### ISSUE TITLE
Report datalayer events to tagmanager

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5759]
We need to implement a new front end singleton module called `EventTracking`, this module will contain the necessary code to report custom and recommended events to google tag manager.

The following events must be reported:

- [ ] [Begin checkout](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#begin_checkout): Happens when the `/checkout` view is rendered and the checkout will start.

- [ ] [Add payment info](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#add_payment_info): When the [payment information is being set.](https://www.awesomescreenshot.com/image/41958360?key=f6c6075d4d71f0f211217f1867b05138).

- [ ] [Purchase](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#purchase): When the credit card has successfully been charged. For buying a plan or buying consumables.

- [x] [Login](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#login): When the login form is successfully submitted (status: 200)

```
method: [github,native]
```

- [ ] [Share](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#share): When any of the share icons is clicked on the ["share progress" modal window](https://www.awesomescreenshot.com/image/41958496?key=fd29552038ce3438802817c2d1f6cf03).

```
method: [twitter,linkedIn,copy_link] (depending on the button that was clicked)
content_type: [lesson,project,exercise,quiz,image,video] (usually the asset type)
item_id: the asset slug (do not use the id)
```

- [ ] [Signup](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6541754067982165976-NA&client_type=gtm#sign_up).

```
method: [github,native]
```

**Comment by alesanchezr** [comment]
Faltan datos en la compra, que metodo de pago uso? pago anual o menusal? que plan?
Revisa los demas recomedned events y pasale todo lo que puedas.

**Comment by alesanchezr** [comment]
El objeto que le pasas a dataLayer tiene la siguiente info:

## En el dashboard:
`available_as_saas=true` si al menos una sola cohort de la que el estudiante es education_status=ACTIVE es available as saas.
`cohorts=slug1,slug2,etc.` Crear un string con todos los slugs de todas las cohorts, TODAS.
`academies=slug1,slug2,etc.` Crear un string con todos los slugs de todas las academias, TODAS.

## En dashboard de la cohort
```
current_cohort: {
    "id": 484,
    "slug": "land-a-job-in-tech",
    "name": "Career Support: Land a Job in Tech",
    "kickoff_date": "2022-10-20T15:54:13Z",
    "ending_date": null,
    "intro_video": null,
    "current_day": 0,
    "current_module": null,
    "syllabus_version": {
        "version": 2,
        "status": "PUBLISHED",
        "slug": "land-a-job-in-tech",
        "name": "Land a Job in Tech",
        "syllabus": 151,
        "duration_in_hours": 14,
        "duration_in_days": 4,
        "week_hours": 7,
        "github_url": null,
        "logo": null,
        "private": false
    },
    "academy": {
        "id": 4,
        "slug": "downtown-miami",
        "name": "4Geeks Academy Miami",
        "country": {
            "code": "us",
            "name": "USA"
        },
        "city": {
            "name": "Miami"
        },
        "logo_url": "https://storage.googleapis.com/admissions-breathecode/location-downtown-miami",
        "is_hidden_on_prework": true
    },
    "stage": "STARTED",
    "is_hidden_on_prework": null,
    "available_as_saas": false
}

```

**Comment by tommygonzaleza** [comment]
- [ ] En el evento de signup se debe enviar toda la `conversion_info` que se esta registrando en la sesion del usuario. En este issue se define el objeto `conversion_info` y la informacion que contiene: https://github.com/breatheco-de/breatheco-de/issues/5792

**Comment by tommygonzaleza** [comment]
Esta dando este error en la vista de interactive exercises
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/e8a33c39-9afc-4612-82f7-de911c5de713)

Creo que viene por esto:
![Screenshot 2023-10-24 at 10 46 33 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/b7fc4d70-3535-4e5d-b105-eb84ec449081)
