### ISSUE TITLE
Modificar las siguientes URLs en cuanto a Canonical y H1s

### ISSUE THREAD

**Issue by Jsolis4geeks** [breatheco-de/breatheco-de#5761]
Después del audit que hice me di cuenta que estas URLs están apuntando a un canonical tag con "/" cuando la URL original no lo tiene, por lo tanto está dando un error de apuntando a un canonical con redirección, lo que al final se convierte en un Loop. Por lo tanto se debería cambiar el canonical tag de las siguientes URLs para que apunte a esa misma URL, pero sin el "/".

![image](https://github.com/breatheco-de/breatheco-de/assets/118853358/2525c8b4-c4cd-4fce-bf15-29a0af2b9f63)

Hay un problema con los H1, que el que debería ser el H1 se está contando como un H2.

![image](https://github.com/breatheco-de/breatheco-de/assets/118853358/eb59479c-23db-4578-9172-e453c58c6d4e)

Action Plan:

- [ ] Actualizar el Canonical Tag para eliminar el "/" de este
- [ ] Actualizar la estructura para que el heading principal sea un H1

Aquí el listado de URLs:

- https://4geeksacademy.com/us/blog/trends-and-tech
- https://4geeksacademy.com/es/blog-en-espanol/tendencias-y-tecnologia
- https://4geeksacademy.com/us/blog/full-stack-developer
- https://4geeksacademy.com/es/blog-en-espanol/aprender-a-programar
- https://4geeksacademy.com/us/blog/coding-bootcamp
- https://4geeksacademy.com/es/blog-en-espanol/desarrollador-full-stack
- https://4geeksacademy.com/us/blog/python-bootcamp
- https://4geeksacademy.com/es/blog-en-espanol/curso-programacion
- https://4geeksacademy.com/es/blog-en-espanol/cuanto-gana-un-programador
- https://4geeksacademy.com/us/blog/career-growth
- https://4geeksacademy.com/us/blog/online-coding-bootcamp
- https://4geeksacademy.com/us/blog/data-science-bootcamp
- https://4geeksacademy.com/us/blog/software-engineer
- https://4geeksacademy.com/us/blog/machine-learning-course
- https://4geeksacademy.com/us/blog/miami-coding-bootcamp
- https://4geeksacademy.com/es/blog-en-espanol/carrera-de-programacion
- https://4geeksacademy.com/us/blog/software-engineer-salary
- https://4geeksacademy.com/us/blog/machine-learning-bootcamp
- https://4geeksacademy.com/us/blog/coding-bootcamp-berlin
- https://4geeksacademy.com/us/blog/machine-learning-engineer
- https://4geeksacademy.com/us/blog/full-stack-developer-jobs
- https://4geeksacademy.com/es/blog-en-espanol/bootcamp-de-programacion

**Comment by tommygonzaleza** [comment]
Esta aprobado, falta hacer merge del PR
