### ISSUE TITLE
Error al levantar bolier de Flask REST

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#5781]
### Bug description

Al levantar el boilerplate https://github.com/4GeeksAcademy/flask-rest-hello , da error en los puertos.
<img width="997" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/fb1be481-88f8-4977-85a4-8b592b57d847">
<img width="883" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/7d9f68dc-5242-442c-91d8-c9a80ab8b064">

### Steps to reproduce

Ingresar con codespaces y ejecutar pipenv install;
psql -U root -c 'CREATE DATABASE example;'
pipenv run init;
pipenv run migrate;
pipenv run upgrade; 
y luego pipenv run start

**Comment by alesanchezr** [comment]
corregido
