### ISSUE TITLE
Agregar `assignment.task.last_opened_at` 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5783]
- [ ] Agregar `assignment.task.opened_at` el cual debe registrar el momento en que se abre un task por primera vez
- [ ] Si el task ya se abrio, debe ignorar y no modificar el `opened_at`
- [ ] Incluir en serializador
- [ ] Desde el frontend avisar cuando se abra un task al backend si el valor `task.opened_at` esta vacio, enviandole el valor de `opened_at`

**Comment by tommygonzaleza** [comment]
- [ ] El deployment fallo, revisa el error

**Comment by gustavomm19** [comment]
Listo
