### ISSUE TITLE
Actualizar servicio para obtener activities

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5785]
Actualmente se tiene una tabla Activity en el API, se debe crear un dataset de Activity basandote en la tabla existente y agregando los datos que consideres mas importantes de la actividad del usuario. Las actividades mas comunes son: 
- Cuando se reciben respuestas del nps
- Cuando se loggea
- Cuando abre un modulo
- Cuando abre un task
- Cuando marca un task como done
- Cuando se registre a un evento
- Cuando asiste a un evento
- Cuando entra al landing de un evento
- Cuando se le genera un bag
- Cuando hace un pago
- Cuando agenda una mentoria*
- Cuando entra a una mentoria
- Cuando sale de una mentoria
- Cuando revisa un academyservice (Observa los precios del consumible)
- Cuando compilas codigo exitosamente
- Cuando compilas codigo fallidamente
- Cuando pasas un test de LearnPack
- Cuando falla un test de LearnPack

Debes resolver como funciona el schema de bigquery. Chequea analytics para tomar ideas

**Comment by tommygonzaleza** [comment]
Bloqueando a este [issue](https://github.com/breatheco-de/breatheco-de/issues/5346)

**Comment by jefer94** [comment]
# kinds
invite_created
invite_status_updated
nps_answered
login
open_syllabus_module
read_assignment
assignment_review_status_updated
assignment_status_updated
event_checkin_created
event_checkin_assisted
bag_created
checkout_completed
mentoring_session_scheduled
mentorship_session_checkin
mentorship_session_checkout

# Managed by others
Cuando entra al landing de un evento
Cuando revisa un academyservice (Observa los precios del consumible)
Cuando compilas codigo exitosamente
Cuando compilas codigo fallidamente
Cuando pasas un test de LearnPack
Cuando falla un test de LearnPack

**Comment by tommygonzaleza** [comment]
- [ ] El servicio para obtener los activities de una academia no debe filtrar por el usuario que esta haciendo el request, sino que deberia permitir recibirlo por query string para traer todas las activitidades del usuario que se especifique
