### ISSUE TITLE
Convertir el formulario para descargar acceder a un tutorial en un signup como el de los eventos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5789]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42095696?key=df9f79206265c6cc107cb2b4755fa5f2&size=orig) 

 Ahora mismo para descargar el tutorial lo que haces es darnos tus datos y lo guardamos en form_entry, esto ya no se quiere hacer.

Se quiere replicar la misma funcionalidad que existe para acceder a un evento desde el landing del evento.

Si quieres acceder al tutorial debes registrarte en 4Geeks.com y lo puedes hacer alli mismo.

- [ ] Utilizar el mismo componente que ya se usa en el landing del evento.
- [ ] Pasar el asset id en el payload del metodo subscribe.

---
**Source URL**:
[https://4geeks.com/interactive-exercise/pandas-exercises-tutorial](https://4geeks.com/interactive-exercise/pandas-exercises-tutorial)

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/5895
