### ISSUE TITLE
Como deberia verse en movil el landing del evento?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5790]
Veo que tienes [este diseño](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10085-48330&mode=design&t=at1uFsghLv7zxCzR-0) pero me surgen preguntas.

- El boton para unirte al evento y la cuenta regresiva son un bottom bar que te sigue?
- Como se ve si el evento esta justo ocurriendo en este momento?
- Como se ve si el evento ya ocurrio?

**Comment by ali5uarez5** [comment]
Aqui puedes ver como se veria el botón: https://www.figma.com/proto/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?page-id=6565%3A25094&type=design&node-id=10085-48109&viewport=-8800%2C-6906%2C1&t=jJUv2PQTB7dSHxa4-1&scaling=scale-down&mode=design

**Comment by ali5uarez5** [comment]
Aqui estan las opciones para los diferentes escenarios, estoy colocando una opcion para ver la grabación del evento por si ya terminó, pero no se si eso es posible https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10534%3A25195&mode=design&t=Aftwxpamdd9uZNqC-1

**Comment by alesanchezr** [comment]
- Que pasa si ya me registre pero no ha empezado.

**Comment by ali5uarez5** [comment]
Prototipo:  https://www.figma.com/proto/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?page-id=6565%3A25094&type=design&node-id=10085-48109&viewport=-8800%2C-6906%2C1&t=iwpCgqaJ18R7ZnPN-1&scaling=scale-down&mode=design

**Comment by tommygonzaleza** [comment]
@ArielCalisaya el boton de registrarte (registrarte, Unirte o ver recording) te debe acompañarte, en el diseño estan los diferentes escenarios

**Comment by ali5uarez5** [comment]
Sticky button: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6565%3A25094&mode=design&t=AoLNZF3kbnSr3I0u-1

**Comment by tommygonzaleza** [comment]
- [ ] Quitar seccion donde sale la señora y hello bob en mobile
- [ ] Cuando el evento ya culmino, se debe mover la seccion del host a la derecha abajo de quienes asistieron
- [ ] Cuando el evento ya culmino, la seccion de quienes estan registrados a la derecha, debe decir quienes atendieron, en vez de cuantos registrados van.
- [ ] Agregar assets del evento a version de vista mobile

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10085%3A48109&mode=design&t=mPG7ZCuvCSK1gtQZ-1

**Comment by tommygonzaleza** [comment]
@gustavomm19 Aqui estan unos cambios que deberian incluirse en el landing del workshop en mobile

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11845%3A6079&mode=design&t=VkUAnlGZMbJjPBZo-1

**Comment by tommygonzaleza** [comment]
Cambie algunas cosas en el diseño e hice mas visible cada uno de los escenarios en el figma. Revisalos
<img width="1455" alt="Screenshot 2023-11-21 at 9 10 14 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/5152769c-3b53-4300-a8e6-e0f2cdfff293">

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-11-21 at 4 41 14 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/71192d0f-ccb6-4b02-b9f8-ff946fcadf6d)

**Comment by tommygonzaleza** [comment]
- [ ] Vamos a cambiar el boton de unirse cuando esta live, de resto esta bien por ahora

**Comment by tommygonzaleza** [comment]
Aqui esta el diseño de como se ve cuando esta live: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12201%3A35184&mode=design&t=k7QARA85nZEFeFf0-1
