### ISSUE TITLE
Mejoras a version móvil del landing de event

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5791]
Estamos esperando que la version movil este totalmente diseñada en este issue: #5790

[Asi es como debe verse el landing de events.](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10085-48330&mode=design&t=at1uFsghLv7zxCzR-0).

- [ ] Tiene un bottom bar que te sigue mientras haces scroll y tiene la cuenta regresiva.
- [ ] Si el evento esta justo ocurriendo ahora?
- [ ] Si el evento ya termino?

<img width="290" alt="Screenshot 2023-08-09 at 1 15 25 AM" src="https://github.com/breatheco-de/breatheco-de/assets/426452/3763609f-839e-4e5e-9b4f-db018841a80d">

**Comment by tommygonzaleza** [comment]
Ya se agregaron estos cambios
