### ISSUE TITLE
Include marketing consent on ShowOnSignUp component

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5792]
Everywhere the user signs up we need to have a marketing consent. The `<ShowOnSignUp>` component needs to be fixed to include a small checkbox at the bottom after the inputs (before the button).

Also make sure the component sends the conversion_info to the API when calling the `/subscribe` endpoint.

Conversion Info:
```
{
      "placement": "", // the ad placement
      "medium": "", // facebook, tiktok, Instagram, google
      "source": "",   // cpc, organic, etc.
      "term": "",  // keyword from cpc
      "content": "", // banner or add id
      "conversion_url": "", // last URL the user saw before starting the checkout process.
      "landing_url": "", // first URL the user saw when coming into the website
      "user_agent": "", // front end user agent
      "plan": "",   // plan bought (if any)
      "location": "" // academy_slug (if any)
      "internal_cta": "" // CTA inside 4geeks.com
}
```

https://github.com/breatheco-de/breatheco-de/issues/5279

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/breatheco-de/breatheco-de/issues/5280), leelo para obtener una descripcion mas amplia

**Comment by tommygonzaleza** [comment]
The conversion_info should be a property of the request, which value is the dictionary of shared in the first comment

**Comment by tommygonzaleza** [comment]
Esta dando este error en la vista de interactive exercises
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/e8a33c39-9afc-4612-82f7-de911c5de713)

**Comment by tommygonzaleza** [comment]
Valida para que el backend reciba conversion_info, event y asset

**Comment by tommygonzaleza** [comment]
- [ ] Debes registrar la sesion del usuario en el local storage apenas el usuario entra en la pagina.

**Comment by tommygonzaleza** [comment]
- [ ] No esta registrando el `conversion_url`

**Comment by tommygonzaleza** [comment]
Los utm se pierden cuando se cambia de vista o se refresca la pantalla
