### ISSUE TITLE
Agregar endpoint para obtener los commit files 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5798]
Para obtener los commitfiles de un repositorio, se utiliza este endpoint de Rigobot:
https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#8db0bce0-ad60-4782-99c0-008b8c27e74f

Debes crear el equivalente en APIv2 para poder ser utilizado por usuarios de 4Geeks

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1035

**Comment by tommygonzaleza** [comment]
Solo se pueden obtener los commit files de un repo, por esto, debemos obtener el URL del repo del task.

- [ ] Este endpoint debe recibir el id del task. Luego con el id del task, debe obtener la URL del repo en github, de no encontrarla, debe dar un error, si la encuentra, entonces la utiliza y la envia como query string.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1037

**Comment by tommygonzaleza** [comment]
Se agrego en este [issue](https://github.com/breatheco-de/breatheco-de/issues/5803)
