### ISSUE TITLE
Agregar endpoint para obtener un commit file

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5800]
Para obtener los commitfiles de un repositorio, se utiliza este endpoint de Rigobot:
https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#392127e4-e18d-4584-9f1c-d94479cad952

Debes crear el equivalente en APIv2 para poder ser utilizado por usuarios de 4Geeks

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1035

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1037

**Comment by tommygonzaleza** [comment]
Se migro a este [issue](https://github.com/breatheco-de/breatheco-de/issues/5803)
