### ISSUE TITLE
Agregar endpoint para rate un code revision

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5805]
Para agregarle rate a un code revision, se utiliza este endpoint de Rigobot:
https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#3f728b0e-6aeb-4013-9ff4-a9b7179cf8e9

Debes crear el equivalente en APIv2 para poder ser utilizado por usuarios de 4Geeks

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1035

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1037

**Comment by tommygonzaleza** [comment]
Se agrego en este [issue](https://github.com/breatheco-de/breatheco-de/issues/5803)
