### ISSUE TITLE
Repensar info organizers para atraer mas gente a los eventos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5808]
Esta es la info del organizador:
https://www.awesomescreenshot.com/image/42114727?key=5ae8fa3577875887ba982d60d6085de6

Este es un buen ejemplo de promt:
https://chat.openai.com/share/763a05ad-df2b-42f8-8b18-e2960dfe94b2

**Comment by alesanchezr** [comment]
Algunas se borraron y otras tiene mucho espacio en blanco, revisalas todas para asegurar q esten bien.

**Comment by tommygonzaleza** [comment]
Organizer BIO: ¡Hola, geeks de todo el mundo! Bienvenidos a 4Geeks Academy. Una escuela de codificación galardonada que se especializa en programas de Desarrollo Web y Data Science (part-time y full-time) y completamente acelerados con el propósito de enseñarte las habilidades para cambiar e impulsar tu carrera en solo unas pocas semanas. En 4Geeks Academy, nos dedicamos a ayudar a las personas a dominar las habilidades necesarias en el mercado del sector, potenciar sus carreras y navegar por el dinámico panorama tecnológico. Con pasión por fomentar la innovación, organizamos eventos atractivos que cierran la brecha entre el aprendizaje, el crecimiento personal y el éxito profesional.

Description for event pages: ¡Bienvenido a 4Geeks Academy! Nos entusiasma organizar eventos increíbles y útiles y compartir nuestro conocimiento y experiencia contigo. En 4Geeks Academy, nos apasiona brindar educación en programación accesible y de alta calidad. Nuestros eventos están diseñados para capacitar a las personas con las habilidades que necesitan para sobresalir en la industria tecnológica. Únete a nosotros para vivir una experiencia inolvidable, repleta de talleres interactivos, oportunidades para establecer contactos y conocimientos valiosos. Ya sea que eres un principiante o un profesional experimentado, nuestros eventos están diseñados para satisfacer tus necesidades específicas, asegurando que te sientas inspirado y listo para enfrentar nuevos desafíos.
