### ISSUE TITLE
New `<CodeViewer>` component that will be used inside the MarkdownParser

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5814]
We need a new component to show code on the markdown lessons, the idea is to show the code example but also to add a button to run the code, you will also be able to make little changes to the code if you want.

[Here is an example](https://www.awesomescreenshot.com/video/19822586?key=2c1f78a6d4f2f2e65c73cf5da8a08761) of the code examples that you can run on the eloquent javascript book.

We don;t need to replicated exactly that, lets use our own ideas.

If you find multiple code examples next to each other, is it possible to display one container with one tab for each code?

For example:

```python
def calculate_discount(item, quantity):
    if item.category == 'clothing':
       return 2
```
```javascript
const calculate_discount = (item, quantity) => {
    if(item.category == 'clothing'){
       return 2
    }
}
```

Should show like this:

![Bootstrap Tutorial_ Learn Bootstrap 5 in 10 minutes _ 4Geeks](https://github.com/breatheco-de/breatheco-de/assets/426452/506a5999-d488-4c2b-b442-93a4dd4332f5)

- [ ] The button to run the code will ask to login.
- [ ] If you are already logged in the run code will show the results using the bottom area.

**Comment by alesanchezr** [comment]
- [ ] No haz mostrado como se ve el output.
- [ ] No haz mostrado como se ve el login cuando no estas logeado y quieres compilar.

**Comment by alesanchezr** [comment]
La modeal tiene que decir claramente porque te estoy obligando a registrarte:

`In order to run code on public lessons, you have to register an account or login`.

**Comment by alesanchezr** [comment]
Para el output debajo puedes poner un mensaje que diga: `The code you just run resulted in the following terminal output`

**Comment by alesanchezr** [comment]
Cmo se veria en pantalla movil la modal de login y el resto del flujo?

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=9oA0neOg3oKa2Vkc-1
