### ISSUE TITLE
Nueva manera de desplegar un syllabus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5815]
Queremos una vista mucho mas ligera para mostrar cursos mucho mas pequeños, en lugar de [lo que tenemos ahora](https://www.awesomescreenshot.com/image/42125501?key=1efb0a8f0860874b5bac593944a4a203) nos gustaria tener algo [como esto](https://swimm.io/learn/code-documentation/code-documentation-benefits-challenges-and-tips-for-success) pero con el diseño de 4Geeks.com

Esta vista va a vivir bajo el URL: https://domain.com/wiki/<wiki_slug>

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10350%3A31688&mode=design&t=TglVB2vxxa2DwsOk-1

**Comment by alesanchezr** [comment]
- [ ] No lleva numero
- [ ] No lleva tipo de contenido.
- [ ] Es un knowedge base.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10350%3A31688&mode=design&t=c55WJsP2el4W93cM-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10350%3A31688&mode=design&t=5tWLhJsFkaW4QUvR-1

**Comment by tommygonzaleza** [comment]
@ArielCalisaya:
- [ ] Debe ser un componente nuevo para mostrar syllabus
- [ ] Este componente nuevo se usara en una vista de knowledge base, en la que se mostraran los assets de tipo ARTICLE, y category knowledge-base,base-de-conocimientos

**Comment by tommygonzaleza** [comment]
Los syllabus no se mostraran de manera estatica, sino que al ingresar la url `/docs/<syllabus_version>/<asset_slug>`, se debe mostrar la nueva manera de desplegar el syllabus en el articulo que se especifico por la URL, tal como funciona en el syllabus interno de las cohorts

**Comment by tommygonzaleza** [comment]
- [ ] El modulo al que pertenece el asset que se esta mostrando deberia estar abierto a la izquierda
<img width="1428" alt="Screenshot 2023-09-21 at 10 37 37 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/afceddb3-2e24-4e8e-bf23-2bd6d46f3dd7">
- [ ] Si el syllabus es private=true o no es documentation, entonces no se deberia traer el syllabus ni mostrarlo

**Comment by tommygonzaleza** [comment]
- [ ] Si accedo a `/docs/<syllabus_slug>` debe redireccionar al primer asset de ese syllabus
