### ISSUE TITLE
Configurar LiveChat para estar pendiente

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5816]
Es hora de activar el live chat para los usuarios, aqui lo puedes encontrar.
https://my.livechatinc.com/team/agent/support%404geeks.com

- [ ] Deberiamos tratar de ocular el chat para aquellos que no tengan available_as_saas.
- [ ] Deberiamos configurarlo para ver como nos ayuda a traer mas leads o convertir actuales.

**Comment by tommygonzaleza** [comment]
Se esta nombrando en el otro issue para que se tome en cuenta
