### ISSUE TITLE
Mostrar cosas nuevas en el landing de un evento cuando ya se culmino

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5817]
Cuando el workshop ya se culmino se debe mostrar:

- [ ] Ver la grabacion del workshop.
- [ ] Te dice si asististe al workshop.
- [ ] Los assets (articulos, ejercicios y lecturas) relacionados a este workshop.
- [ ] Mostrar tecnologias del workshop

**Comment by alesanchezr** [comment]
- [ ] Nadie se puede bajar los documentos si no te logueas.
- [ ] No peudes ver los documentos ni la grabacion si no atendiste, estan ocultos.

Los mensajes que deben salir:
- [ ] Si el evneto no ha pasado, el project dice: We'll build the following project during the workshop.
- [ ] Si el evento ya paso, el project dice: This is the project was was built during the workshop.
- [ ] Solo si atendiste ya paso: Documents shared during the workshop.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=7192%3A33824&mode=design&t=AoLNZF3kbnSr3I0u-1

**Comment by tommygonzaleza** [comment]
Esperando por este [issue](https://github.com/breatheco-de/breatheco-de/issues/5818)
