### ISSUE TITLE
ADMIN - En la creación de encuesta dejar solo cortes activas.

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#5824]
### Bug description

Cuando queremos crear una encuesta aparecen todas las cortes sin importar su estado. Deberían aparecer solo las cortes activas.

<img width="751" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/2bb2a930-4c5d-4937-81c3-664eb0f698df">

<img width="1151" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/9194d567-2d62-44aa-9c06-1357ac35a361">

### Steps to reproduce

Ir a crear encuesta y fijarse que aparecen todas las cortes sin importar su estado.

**Comment by alesanchezr** [comment]
Esto ya se termino.
