### ISSUE TITLE
Cuando el servicio de `/v1/payments/pay` falla, se debe mostrar una modal

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5825]
Si el pago fue rechazado ya sea porque puso los datos incorrectos de la tarjeta de credito o porque simplemente fue rechazado, se debe mostrar una modal para indicarle al usuario

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6141%3A23263&mode=design&t=B8KV4BEHowiVgMtj-1

**Comment by tommygonzaleza** [comment]
@ArielCalisaya arriba esta el diseño de la modal. El mensaje dependera del `silent_code` que recibas del backend

**Comment by alesanchezr** [comment]
![Screenshot 2023-08-29 at 5 16 11 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/da632ab3-fae1-4d9d-8d23-fc692166a55f)

**Comment by tommygonzaleza** [comment]
Estos son los mensajes que debes mostrar segun el silent-slug que recibes:
- `card-error`: "Card Declined".
- `rate-limit-error`, `invalid-request`, `authentication-error`, `payment-service-are-down`, `stripe-error`: "Payment could not be processed". (Para los 5 mostrar el mismo mensaje)
- `unexpected-exception`: "An unexpected error occurred during the payment process, please contact support"

**Comment by tommygonzaleza** [comment]
Esperando por el backend a que se resuelva la razon por la que no se esta enviando el silent code

**Comment by tommygonzaleza** [comment]
- [ ] Recibe este json pero no muestra la modal
![Screenshot 2024-02-01 at 12 16 13 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/62ee5da6-d9f0-437e-94c5-c3f943ad180c)
