### ISSUE TITLE
Extender el tiempo de duración de una encuesta

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#5827]
A veces, enviamos las encuestas a estudiantes con un máximo de 48 horas de duración pero si una persona no va e intenta responderla otro día, generalmente ya está vencida.

Al extenderlo a 72h damos la oportunidad de que en la siguiente clase, la encuesta sea respondida con éxito.

**Aprovechar y revisar si está funcionando el período de dos días, porque da la impresión de que no.**

**Comment by tommygonzaleza** [comment]
Resuelto, se puso 72hrs
