### ISSUE TITLE
Revision de notificaciones de los eventos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5832]
Rellenar estos 4 correos con el texto que les vas a enviar.

- **When they register for the event**: Primero agradecerles, si vienen por eventbrite hay que recordarles que deben registrarse para el evento en 4geeks.com, ademas, si no tienen una cuenta en 4geeks.com tendrian que crearse la cuenta.

- 2 days before the event.
- 2 hours before the event.
- 5 min before the event.

**Comment by tommygonzaleza** [comment]
Zap for reminders: https://zapier.com/editor/214097022/published
