### ISSUE TITLE
Cambios al landing de Miami Tech Works

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5838]
Este es el landing:
https://dev.4geeksacademy.com/us/landing/miami-tech-talent-coalition

bullets en gris claro?
la sección de reviews está toda rara
No es Ai and Machine learning, sino Data Science
El ready to start your journey está de más

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1738
