### ISSUE TITLE
FS - Error en práctica de Python con codespaces

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#5842]
### Bug description

Al alumno Javier Paredes (paredesjavier23@gmail.com) del part time 20, cuando quiere hacer la práctica de python y se ejecuta el comando learnpack start le da node/internal error 478.

![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/4dbbb68f-7c5c-42b0-849b-7b066d30f01c)

### Steps to reproduce

Iniciar la práctica de python.

**Comment by alesanchezr** [comment]
Me confirma Javier que esta solucionado.
