### ISSUE TITLE
Corregir funcionamiento de la pagina sin JS

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5845]
Solamente nos interesa la parte publica de la pagina.

- [x] El top navbar tiene q functiona con CSS.
- [x] Background [color del footer esta negro](https://www.awesomescreenshot.com/image/42234680?key=412f48cd89b0c15545083925eae9d8f2).
- [ ] #5948

**Comment by tommygonzaleza** [comment]
Para la paginacion faltan botones que permitan moverse entre las paginas cuando JS esta desactivado. (No se si esto es necesario para seo)
