### ISSUE TITLE
Compartir enlaces a lecturas/projectos internos.

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5846]
Los alumnos comparten constantemente enlances como estos:

```
https://4geeks.com/es/syllabus/spain-ds-pt-1/read/exploring-decision-trees
```

El problema es que la persona que recibe el enlace solo podra leerlo si pertenece a la cohort `spain-ds-pt-1`.
Se me ocurre que `si no perteneces a esa cohort` o `no estas logeado` podamos redireccionarte con un redireccionamiento permanente (301) al link publico de la lesson:

```
https://4geeks.com/lesson/exploring-decision-trees
```

- [ ] Habria que hacer lo mismo con los proyectos y los ejercicios.
- [ ] Hay que tomar en cuenta que las lessons privadas solo se pueden ver cuando haz iniciado session, llevaria a un 404 lo cual esta bien.

**Comment by tommygonzaleza** [comment]
Me esta redireccionando a pricing. Prueba con esta url: https://app-iikj1ysni-geeksacademy.vercel.app//es/syllabus/miami-prework/read/what-is-css-learn-css
