### ISSUE TITLE
Mostrar modal introductoria a 4Geeks

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5847]
Esta modal introductoria debe contener un mensaje y un link a un video explicativo de como utilizar 4Geeks.com. 

Reutiliza el componente de modal que ya tenemos:

<img width="917" alt="Screenshot 2023-08-15 at 6 30 12 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/180a4419-363b-4280-94bd-4ae0e913b2cf">

Este es el link del video: https://www.loom.com/share/9fbe5af774ff40fdafb0a3693abc85ba

Solo debes mostrar esta modal en el dashboard las primeras 48 horas luego de haberse creado el user (Utiliza el valor de created_at que recibes del backend)

**Comment by alesanchezr** [comment]
Meter el video dentro de la modal mejor, no hay necesidad de sacarlos.

**Comment by tommygonzaleza** [comment]
El deployment del PR fallo, revisalo para poder ver lo que agregaste

**Comment by tommygonzaleza** [comment]
- [ ] Se esta mostrando en el dashboard de la cohort en vez del dashboard general del alumno, por lo que ademas se esta mostrando es cuando se crea el cohort user y no cuando se crea el user, recuerda que puede crearse un user sin tener una cohort

**Comment by tommygonzaleza** [comment]
No esta mostrando la modal
![Screenshot 2023-09-26 at 9 33 43 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/082e2ded-9c1c-4e6c-8c81-cd7a43830300)
