### ISSUE TITLE
Agregar testominiales y casos de exito de chile

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#5850]
A este [landing](https://4geeksacademy.com/es/20-millones?lang=es) meter información de estudiantes de chile para poderla usar con credibilidad en el campus.

Aquí la [información](https://docs.google.com/document/d/1MOIsv_AuBgU0S-s46rBDvyc37vB4aXdXV8HBY88P2yI/edit) de los estudiantes a anexar en aparte de "Casos de Exito"

**Comment by Khrisefzm** [comment]
Aún no se a agregado información de chile

**Comment by G-code7** [comment]
estos testimonios ya han sido agregados a la pagina, pero los que presentan proyectos se van a agregar a  el componente de proyectos.
