### ISSUE TITLE
Mejor manejor de promtps internos con variables y contenidos dinamicos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5853]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42270702?key=f2fdbefab43a4b07190dd02ac7b0010e&size=orig) 

 Utilizar un modelo OrganizationVariable que van a ser variables definidas para usar en cualquier parte de la orgnizacion.

Por ejemplo: 

Si el prompt de la trivia cmapaign tiene la variable organizational brief asi: {organization_brief}

Sera reemplazado por esto al momento de guardar:

This is the organization brief value

Pero en el caso de las variables dinamicas, como el purpose objective que es diferente siempre, no podras ver el valor sino esto:

 

---
**Source URL**:
[https://rigobot.herokuapp.com/admin/finetuning/triviacampaign/5/change/](https://rigobot.herokuapp.com/admin/finetuning/triviacampaign/5/change/)

**Comment by Charlytoc** [comment]
{{self.purposes[].objectve}}

To access
