### ISSUE TITLE
El reporte de estudiante no funciona

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#5857]
Ninguna de las opciones muestra contenido y antes sí lo hacía.

![Captura de pantalla de 2023-08-17 11-01-29](https://github.com/breatheco-de/breatheco-de/assets/410890/16267e5a-20ae-498d-b9aa-6b83394b9142)

**Comment by tommygonzaleza** [comment]
A partir de ahora se puede acceder al reporte de actividades de un alumno en una cohort desde 4geeks.com, si entras desde los assignments, puedes darle click al nombre del estudiante y acceder.

De todas formas creo el requerimiento para que se pueda entrar desde el admin de manera directa a este reporte: https://github.com/breatheco-de/breatheco-de/issues/6645
