### ISSUE TITLE
No filtra los proyectos por estudiante

### ISSUE THREAD

**Issue by jseiglie** [breatheco-de/breatheco-de#5858]
### Bug description

Al filtrar los proyectos por estudiante, no está mostrando nada y la consola muestra este error
![Captura de pantalla 2023-08-17 110740](https://github.com/breatheco-de/breatheco-de/assets/96433186/0a8b9059-52d5-4c57-8df3-06258f684636)

### Steps to reproduce

Me sucedió en el curso EU-FS-PT-11 y 13
Acceder como reviewer
Ir a proyectos
pasar a vista de lista
filtrar por alumno

### Expected behavior

Debería mostrar los proyectos del alumno

**Comment by alesanchezr** [comment]
Hola @jseiglie no logro replicarlo. Que cohort y que estudiante ?

**Comment by tommygonzaleza** [comment]
El bug ya esta resuelto
