### ISSUE TITLE
Borrar landings que no se usan

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5860]
- [ ] Preguntar a todas las sedes para que te digan cuales landings se pueden borrar. Tenemos que borrarlos, consumen browling budget y ademas con el paso del tiempo se van volviendo mas feos por falta de mantenimiento.
- [ ] Eliminar el landing YML
- [ ] Agregar un redirect a al lugar que mas tiene sentido que vaya.

Nota: Comenta aqui en esta lista para el proximo scrum todos los que vayas a eliminar a donde los vas a redirigir, los revisamos el proximo scrum.

**Comment by G-code7** [comment]
Actualización: 
 -En chile están utilizando todas las landings  (no borrar ninguna de chile)

**Comment by G-code7** [comment]
Actualización: 
- En USA 
       https://4geeksacademy.com/us/landing/coding-classes
       https://4geeksacademy.com/us/landing/coding-school
       https://4geeksacademy.com/us/landing/coding-course
       https://4geeksacademy.com/us/landing/learn-to-code
       https://4geeksacademy.com/us/landing/programming-courses
       https://4geeksacademy.com/us/landing/summer-discount

**Comment by G-code7** [comment]
Actualización:
-En España están utilizando todas las landings (no borrar ninguna de España)

**Comment by alesanchezr** [comment]
- [ ] Agregar `meta_info.visibility: hidden`
