### ISSUE TITLE
Organizar para activar SEO de alemania

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#5861]
1. -Identificar las keywords
2. -Identificar las websites en Alemania
3. -Validar Cluster que tenemos disponibles tiene más trafico en Alemania
4. -Validar si es necesario crear nuevo cluster para redirigir trafico aleman

Enfocarnos en el publico en alemania que hable ingles

**Comment by Jsolis4geeks** [comment]
2 - 

https://4geeksacademy.com/
https://4geeksacademy.com/us/software-engineer-salary/software-engineer-salary-germany
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-munich-germany
https://4geeksacademy.com/us/index
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-hamburg-germany
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-berlin-germany
https://4geeksacademy.com/us/coding-campus/online-coding-bootcamp
https://4geeksacademy.com/us/coding-bootcamps/machine-learning-engineering
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-dublin-ireland
https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-argentina-buenos-aires
https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer
https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero
https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-miami
https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-madrid
https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-colombia
https://4geeksacademy.com/es/desarrollador-full-stack/cuanto-gana-un-desarrollador-full-stack
https://4geeksacademy.com/us/coding-bootcamps/datascience-machine-learning
https://4geeksacademy.com/us/trends-and-tech/rip-ruby-on-rails
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-lisbon-portugal
https://4geeksacademy.com/us/coding-campus/coding-bootcamp-barcelona-spain

**Comment by Jsolis4geeks** [comment]
3 - 

software engineer
coding bootcamp
full stack developer

**Comment by Jsolis4geeks** [comment]
4 - De momento no parece necesario para el público en inglés
