### ISSUE TITLE
ADMIN - Cuando se responde el NPS con puntaje menor a 6 poner comentarios como obligatorios.

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#5874]
### Bug description

Pasa mas de una vez que ponen notas bajas en los NPS y no hay comentarios de los motivos, con esto obligamos a que si o si pongan algo por lo menos.

### Steps to reproduce

Enviar encuesta a un alumno y validar que cuando se quiera poner un 4 te obligue a poner comentarios.

**Comment by alesanchezr** [comment]
Lo que quedamos en hacer es configurar zapier para enviar un slack y/o email para preguntarle al contacto porque nos ha dado esa puntuacion. De esa manera no desalentamos al estudiante a enviar la encuesta pero automatizamos la investigacion para saber porque.

**Comment by alesanchezr** [comment]
Voy a cerrar este ticket en detrimento de un trigger de zapier para cuando una encuesta es concluida.
