### ISSUE TITLE
Aclaratoria de datastore

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5877]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42322915?key=bb1b4ce3be1d000177b21559fc28f690&size=orig) 

 No coinciden los regestrees del evento en diferentes charts de la misma pagina.

Vienen el mismo datasource.

---
**Source URL**:
[https://lookerstudio.google.com/u/0/reporting/9eee7bf1-f800-4f15-a63d-0539cbbb1b0e/page/p_386pv6hr8c/edit](https://lookerstudio.google.com/u/0/reporting/9eee7bf1-f800-4f15-a63d-0539cbbb1b0e/page/p_386pv6hr8c/edit)

**Comment by Charlytoc** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/107764250/8c90d976-0ffc-4255-ba3a-c941d023a881)

A mí me dice 9 en ambos lados
