### ISSUE TITLE
El slug de los eventos no se puede modificar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5884]
Por ninguna razón o circunstancia el slug de un evento se puede modificar.

- Implementemos uuid para los [slugs de los eventos](https://chat.openai.com/share/ada7d9eb-696f-4baf-9344-5e7d92c0ae92).
- Garanticemos que los uuid sean parte del slug cuando el evento se esta creando unicamente.
- Si el evento ya se creo y se le hace `save` no debería tener el slug modificado, levantar una excepcion para prevenir el save a toda costa.
- En el admin.py permitir buscar los eventos por uuid y mostrar el uuid como una columna por defecto en el listado de events.

**Comment by tommygonzaleza** [comment]
https://github.com/breatheco-de/apiv2/pull/1046
