### ISSUE TITLE
Help with the pre-work platform

### ISSUE THREAD

**Issue by helenaraimundo91** [breatheco-de/breatheco-de#5887]
Hello,
Due, I think, to a fault with my Internet, the platform with the exercises asked me to do a refresh. When I did, the tab with the instructions for each exercise disappeared. Do you know how to put it back?
Thank you,
Helena Raimundo
![WhatsApp Image 2023-08-21 at 11 45 42 AM](https://github.com/breatheco-de/breatheco-de/assets/139161478/548eaf64-0b92-4b8f-8c7f-fdc801f49f97)

**Comment by tommygonzaleza** [comment]
Hello! You have to open the terminal and run the command `learnpack start`
