### ISSUE TITLE
Logos en el white label

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5891]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42393643?key=e2ac613368c094ec4680eec398f9e2bc&size=orig) 

---
**Source URL**:
[https://miami-tech-works-1nbf-asn91zl8f-alesanchezr.vercel.app/login](https://miami-tech-works-1nbf-asn91zl8f-alesanchezr.vercel.app/login)

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/5882
