### ISSUE TITLE
Agregar certificado de 4Geeks en cursos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5892]
Actualmente solo tenemos diseño de certificados para 4Geeks Academy, necesitamos uno de 4Geeks que sera utilizado por defecto para los cursos que no tengan su propio certificado.

Este es el de 4Geeks Academy: https://storage.googleapis.com/certificates-breathecode/default.png

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10908%3A51134&mode=design&t=twoWS08wbpsHtidM-1

**Comment by alesanchezr** [comment]
- Darle mas formalidad
- Poner un badge.
- Que se vean las 2 firmas.
- Incluir titulo del programar
- Inlcuir url de verificacion.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=5371%3A19042&mode=design&t=H1aquCjldiXVQ7RY-1

**Comment by tommygonzaleza** [comment]
Ya se agrego el certificado
