### ISSUE TITLE
Los tutoriales interactivos deben usar el componente `ShowOnSignUp`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5895]
El componente de registro de la derecha se debe reemplazar por `ShowOnSignUp` 
![Screenshot 2023-08-22 at 4 45 06 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/f9b1639e-1fc7-4071-9ec1-4a8d36816c77)

Asi se ve el ShowOnSignUp:
![Screenshot 2023-08-22 at 4 47 31 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/fc659bd0-8c82-47f8-8e97-2ae229a1ef54)

Si el usuario esta loggeado se debe mostrar el boton nuevo de abrir con learnpack que luego muestra la modal para escoger el provisioning vendor

**Comment by tommygonzaleza** [comment]
Lee el otro issue que se cerro, contiene informacion importante de la implementacion

**Comment by alesanchezr** [comment]
Evitar tener borde dos veces y quitar ese padding.

**Comment by tommygonzaleza** [comment]
El texto debe estar centrado
![Uploading Screenshot 2023-09-05 at 3.09.14 PM.png…]()

**Comment by alesanchezr** [comment]
- Hace falta ponlerle el checkbox de consent a show on signup

**Comment by gustavomm19** [comment]
https://github.com/breatheco-de/app/pull/958

**Comment by tommygonzaleza** [comment]
- [ ] Debes usar este link para las instrucciones de como clonar un repo en la modal cuando estas en español: https://app-bphgpnnb0-geeksacademy.vercel.app/es/how-to/como-clonar-un-repositorio-de-github
