### ISSUE TITLE
Refrescamiento pagina de finantials

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5902]
Modificar la [seccion de financing](https://4geeksacademy.com/us/financials) para que se parezca a esta.

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7620-13570&mode=design&t=Qyk1XfG2ypLRdd7O-0

**Comment by alesanchezr** [comment]
https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/financial.js

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1854

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/6397
