### ISSUE TITLE
Al aceptar el invite de una cohort saas, se debe crear la subscripcion

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5907]
Si se invita a un estudiante desde el admin, quiere decir que el estudiante realizo el pago por otro medio (Efectivo, transferencia, etc) por lo tanto al aceptar este invite se le debe crear no solo el cohort user, profile academy, etc, sino tambien lo referente al modulo de pagos como es la subscripcion, consumibles, etc.

**Comment by tommygonzaleza** [comment]
- [ ] He intentado hacerlo invitando a un estudiante desde el admin y aceptando el invite, etc. Pero no ha funcionado

**Comment by jefer94** [comment]
The front-end must send the plan selected, auto select it should be harmful in this context 
```http
{
    "plans": [5]
}
```
https://github.com/breatheco-de/apiv2/pull/1112
