### ISSUE TITLE
Payment Exceptions are not handling errors properly

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5915]
I get a 500 error in the backend instead. What error code should we use?

<img width="1192" alt="Screenshot 2023-08-24 at 11 47 01 PM" src="https://github.com/breatheco-de/breatheco-de/assets/426452/f4f1d5f7-f1b9-4871-90c3-c848c2e28cf8">

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/breatheco-de/breatheco-de/issues/5894)
