### ISSUE TITLE
Borrar proyectos finales

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5922]
- [x] Agrega la una lesson de Github en el [knowled database](https://github.com/breatheco-de/knowledge-base/tree/main/content), explicando que en 4geeks academy los proyectos de los alumnos se van a eliminar.
- [x] En esa lessons reiterar de forma dramatica que porfavor hagan sus proyectos publicos o sino van a perder acceso a ellos algraduarse.
- [x] Incluir esa lesson tambien en todos los syllabus en el dia de github.
- [x] Agregar otra lessons en el knowledge base de como evitar que borren tu proyecto (tienen que hacerle fork con su cuena persnal al repo que quieren guardar), y las consecuencias de no hacerlo.
- [ ] #5923

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/knowledge-base/pull/33

**Comment by pbullor** [comment]
@alesanchezr veo esto pero está en ingles. Debería estar en español no? https://github.com/breatheco-de/knowledge-base/blob/main/content/keep-your-projects.es.md

**Comment by alesanchezr** [comment]
Ya pablo lo hizo, falta que los demas PM repliquen.
