### ISSUE TITLE
Clonar landing para curso de python.

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#5927]
https://4geeksacademy.com/es/downloadable/guia-de-python  Clonar esta landing para usarla en ADS con otro PDF que se promocionara como un curso básico descargable de python. Agregarle el logo verde del lazo de best coding bootcamp 2023.

**Comment by G-code7** [comment]
Ya está copiada!  quedo atento  con el PDF

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1748
