### ISSUE TITLE
Actualizar recomendaciones de cursos para que solo sean de las white label academies y features

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5928]
- [ ] MktRecommendedCourses
- [ ] MktSideRecommendedCourses
- [ ] Eviar que aparezcan si el curso no esta featured.
- [ ] Evitar que aparezcan si el curso no es de una de las white label academies.

**Comment by alesanchezr** [comment]
- [ ] Primer te traes solo los cursos de esas academias que estan en el white label y que esten featured, si no hay, no muestras el componente.
- [ ] Filtras los cursos restantes por las mismas tecnologias que tenga el asset, si no hay, recomiendas cualquier otro.
- [ ] Si si hay cursos featured y que ademas de las mismas tecnologias, entonces haces un sort de los cursos por el "sort priority" de la tecnologia y agarras el que tenga el mas bajo. Sort priority: 1.

**Comment by tommygonzaleza** [comment]
- [ ] No se esta mostrando ningun curso a la izquierda en algunos casos

**Comment by tommygonzaleza** [comment]
Sigue sin mostrarse los recommended courses

**Comment by ArielCalisaya** [comment]
@tommygonzaleza  La variable de entorno WHITE_LABEL_ACADEMY solo estaba activa en `development` faltó activarla en `preview`

Intenta de nuevo

**Comment by tommygonzaleza** [comment]
El SideRecommendedCourses no lo esta mostrando en dev y ya se hizo merge, si puedes revisalo porfa
