### ISSUE TITLE
Palabras en ingles en vista de plans en español

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5936]
En lugar de una lista con checks poner un poco mas de espacio para describir cada feature. Parecido a scrimba.

![Screenshot 2023-08-28 at 11 56 46 AM](https://github.com/breatheco-de/mdc/assets/426452/4670b5f8-4958-4e62-86b4-6419f82e33a0)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10892%3A25140&mode=design&t=4miS1zpyYpknFuLv-1

**Comment by alesanchezr** [comment]
- [ ] Agregar toggle para precios yearly.
- [ ] Agregar iconos.
- [ ] Agregar opcion de letra (I) para tooltip con mas información.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=H1aquCjldiXVQ7RY-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=ReBFUTF5zDLPNmmL-1

**Comment by tommygonzaleza** [comment]
- [ ] Si el plan es gratis se debe tomar en cuenta como si tuviera yearly y se muestra en el lado de yearly. Si el plan basico (El de la izquierda) tiene precio por mes, entonces solo se muestra la seccion de yearly si ambos planes tiene precio anual. 
<img width="1072" alt="Screenshot 2023-09-20 at 12 16 15 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/73408372-0b3b-45b2-8979-4d472dfa9ce0">
- [ ] La vista de pricing debe permitir recibir el plan por querystring, de no recibirlo, debe funcionar con el plan `4geeks-standard` por defecto.
- [ ] En la vista de checkout no se le debe pasar el querystring nuevo que agregaste de plan_id, con el `plan=<plan_slug>` basta.

**Comment by tommygonzaleza** [comment]
- [ ] Dice totalmente gratuito en la pagina en ingles
<img width="906" alt="Screenshot 2023-09-20 at 4 02 24 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/b90f5b17-af16-4153-a161-f8ecf989a818">

**Comment by ArielCalisaya** [comment]
Ya lo arreglé

**Comment by tommygonzaleza** [comment]
- [ ] Hay mensajes en ingles en la vista de español
![Screenshot 2023-09-26 at 4 41 07 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/74514f85-6fe1-4efe-aa38-1fec684f7474)
