### ISSUE TITLE
Cambiar diseñod de vista de waiting list

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5938]
- En esta vista se debe mostrar el contenido del plan, los mismos datos que se muestran en la vista de checkout de un plan.
- Se debe decir que entro a un waiting list para formar parte del plan nombre_del_plan y que le dejaremos saber una vez se haya aceptado

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=4miS1zpyYpknFuLv-1

**Comment by alesanchezr** [comment]
El waiting list va a ir en esta vista:

https://miamitechworks.4geeks.com/checkout?plan=applied-ai-apprenticeship

Similar como cuando te regaña roque ya tienes la subscripcion, pero ahora que diga que estas en el waiting list.

**Comment by alesanchezr** [comment]
En lguar de una modal ali sugiere hace run redirect a una vista de waiting list y pasar el plan para que esa vista peuda mostrarle la info

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=H1aquCjldiXVQ7RY-1

**Comment by tommygonzaleza** [comment]
El link esta expirado @ali5uarez5

**Comment by ali5uarez5** [comment]
En este artboard esta todo lo relacionado a esa tareañ pero el link deberia ser este:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62640&mode=design&t=MchKImDGmNKudYFX-1
