### ISSUE TITLE
Verificar que el sitemap y los redirects de la pagina no incluyas assets sino solamente de las academias en `WHITE_LABLE_ACADEMY`.

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5945]

**Comment by tommygonzaleza** [comment]
El deployment fallo, se debe solucionar y hacer un PR nuevo

**Comment by tommygonzaleza** [comment]
El sitemap del redeploy de la branch de miami tech works muestra los assets de la academia 4geeks.com
<img width="1470" alt="Screenshot 2023-09-12 at 2 56 25 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/27ba8ae1-78c1-45ac-821d-fbb636fe93cb">
