### ISSUE TITLE
Cambios Solicitados por marcelo a la pag. 

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#5954]
Acá dejare los pull request y solicitudes que me  ha solicitado marcelo para la pag

1. crear 3 landings por pais para mexico, colombia, costa rica, ecuador y venezuela con 3 distintas keywords

- curso de programación
- aprender a programar
- bootcamp de programación

Ejemplo de las landings que existen y estan en uso. 
https://4geeksacademy.com/es/landing/bootcamp-mexico
https://4geeksacademy.com/es/landing/bootcamp-costa-rica
https://4geeksacademy.com/es/landing/bootcamp-colombia-jg
https://4geeksacademy.com/es/landing/aprende-a-programar-ve
https://4geeksacademy.com/es/landing/bootcamp-ecuador-quito

- [x] mexico
- [x] costa rica
- [x] colombia
- [x] Venezuela
- [x] Equador 

2. editar landing https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami

- [x]  -done

**Comment by G-code7** [comment]
cambio location component justo antes del footer #1748

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1748

**Comment by alesanchezr** [comment]
- [ ] Agregar `meta_info.visibility: hidden`

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1754
