### ISSUE TITLE
Wont at debe ser un timestamp como las demas fechas

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5961]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42642956?key=81540e67e80014af27c11f37596c79db&size=orig) 

 Por alguna razon, el pipeline d dataflow no lo convierte en datetime

---
**Source URL**:
[https://console.cloud.google.com/bigquery?project=breathecode-197918&ws=!1m13!1m4!4m3!1sbreathecode-197918!2sdataflow!3scleaned_events_and_checkins!1m3!8m2!1s533541562873!2sb3e97b999cab4542879e70bf953714ee!1m3!8m2!1s533541562873!2sdaaef39badf846c6bfe72875319c75c8](https://console.cloud.google.com/bigquery?project=breathecode-197918&ws=!1m13!1m4!4m3!1sbreathecode-197918!2sdataflow!3scleaned_events_and_checkins!1m3!8m2!1s533541562873!2sb3e97b999cab4542879e70bf953714ee!1m3!8m2!1s533541562873!2sdaaef39badf846c6bfe72875319c75c8)

**Comment by Charlytoc** [comment]
- [ ] Sigue siendo un string, hacer pruebas hasta obtener el resultado correcto, ya tienes permiso para hacer PR
