### ISSUE TITLE
Componente <CodeViewer> a storybook

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5969]
Cuando se va a mostrar código en un markdown vamos a utilizar un componente llamado `<CodeViewer>` que:

- [ ] Tiene tantas tabs como codigos se van a mostrar, por ejemplo podemos mostrar un codigo en python otro tab para javascript.
- [ ] Tiene un boton para "run code".
- [ ] Muestra el resultado de la terminal.
- [ ] Si la persona no ha iniciado session le pedimos que lo haga para poder compilar codigo.

Aqui vas a encontrar todos los detalles e informacion: #5814

Aqui esta el diseño:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=9oA0neOg3oKa2Vkc-1

**Comment by tommygonzaleza** [comment]
- [ ] Si el usuario no esta loggeado, entonces al darle a run, debes mostrar esta modal, los botones deben decir (en este orden) `LOGIN` y `SIGN UP`. El texto debe decir:
```txt
In order to compile the code you have to login or create an account for FREE
```
<img width="655" alt="Screenshot 2023-12-19 at 6 23 21 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/0bf1153d-9778-4073-abc3-fb6e0293742e">

**Comment by tommygonzaleza** [comment]
Aqui esta el diseño actualizado con el resultado de correr el codigo

**Comment by tommygonzaleza** [comment]
Aqui hay mas ajustes del diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=Hpm7g8ZqIelkI2l4-1

**Comment by tommygonzaleza** [comment]
Fallo el deployment de storybook, revisa los errores en el log: https://github.com/breatheco-de/app/actions/runs/7546693270/job/20544995244

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-01-19 at 5 40 21 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/c0fec2db-7bee-483e-95cd-f661bdcb49e9)

**Comment by tommygonzaleza** [comment]
- [ ] Agregar componente de markdown para `CodeViewer`

**Comment by tommygonzaleza** [comment]
No puede ser una etiqueta, ya que no es soportado por GitHub y el contenido dejaria de funcionar en GitHub.

Tu recibes el markdown y ahi puedes identificar lo del prop que te puse en el otro [issue](https://github.com/breatheco-de/breatheco-de/issues/6775), detectas si hay mas code blocks justo despues de ese, y de ser `runable=true`, entonces los agrupas adentro del code-viewer y se lo pasas al parser.

**Comment by tommygonzaleza** [comment]
No esta cargando bien la lesson con codeviewers en el contenido:

Este es el contenido: https://dev.admin.4geeks.com/media/asset/fake-tomas-code-viewer
![Screenshot 2024-01-23 at 1 40 34 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/9290b181-f100-4ff6-aea0-528510fe88ea)

![Screenshot 2024-01-23 at 1 39 41 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/677e457d-dcd4-4768-a204-d25d44d7ba8d)

**Comment by tommygonzaleza** [comment]
- [ ] No esta funcionando con este caso:
![Screenshot 2024-01-24 at 6 13 35 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/8403442e-c282-4315-8930-2d45238304d8)
![Screenshot 2024-01-24 at 6 13 45 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/61e66be9-384c-47ca-8669-f7c0b338531b)
