### ISSUE TITLE
Componente multicolumn de landings pages

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5981]
- [ ] Agregar el componente a la paleta de componentes, se va a llamar `<MultiColumn>`.
- [ ] Haz un ejemplo con tener una, dos, tres o cuatro columnas.
- [ ] Cada columna puede tener una foto, texto y boton (opcional).
- [ ] Hay un header principal, un subheading, un text y un button al final.

![68747470733a2f2f7777772e617765736f6d6573637265656e73686f742e636f6d2f7765622f696d6167652f7468756d626e](https://github.com/breatheco-de/breatheco-de/assets/426452/c7952f43-4c41-427e-8c5a-1c5e694856e6)

---
**Source URL**:
[https://website-v2-git-fork-kelvinruizdev-mejoras-t-6ea4d8-geeksacademy.vercel.app/us/landing/miami-tech-talent-coalition](https://website-v2-git-fork-kelvinruizdev-mejoras-t-6ea4d8-geeksacademy.vercel.app/us/landing/miami-tech-talent-coalition)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8736%3A10555&mode=design&t=vSwj7DqYVEIqcLwK-1

**Comment by alesanchezr** [comment]
En movil no me gusta, vamos a plantear dos opciones para moviles:

- [ ] Que se vea como un carousel y con el dedo puedas hacer swipe para ver las otras opciones.
- [ ] Que se vean uno debajo del otro (como lo tienes ahorita) pero que la imagen este a la izq y el texto a la derecha [mira este ejemplo](https://www.awesomescreenshot.com/image/42763337?key=72379ae7c9b25fb4d601dc3ff8489a63)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8736%3A10555&mode=design&t=a1jgbupv9BUQlY5W-1
