### ISSUE TITLE
Reimplementar componente iconocram para que se vea como el nuevo diseño

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5982]
Este es el diseño de iconogram:
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7831-13248&mode=design&t=OoQQXDGU14vgPgyX-0

Este es un ejemplode un landing que lo usa y hay que arreglarlo:

https://website-v2-git-fork-gustavomm19-landings-geeksacademy.vercel.app/us/landing/miami-tech-talent-coalition

**Comment by tommygonzaleza** [comment]
Tiene un conflicto en el PR

**Comment by tommygonzaleza** [comment]
- [ ] Los iconos deben tomar el espacio completo (`1366px`) y dejar gap entre ellos, sin importar si son 3, 4 o mas. Sin embargo no deberia tomar menos espacio ni mas que ese max-width.

**Comment by kelvinruizdevel** [comment]
Ya esta actualizada la rama con estos cambios

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1758/
