### ISSUE TITLE
Revisar todo YML de miami-tech-coalition para que cumpla con el nuevo diseño

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5983]
Este es el landing:
https://website-v2-git-fork-gustavomm19-landings-geeksacademy.vercel.app/us/landing/miami-tech-talent-coalition

**Comment by tommygonzaleza** [comment]
- [ ] Quitar espacios en blanco entre secciones de la pagina. Algunas secciones tienen espaciados muy grande

**Comment by tommygonzaleza** [comment]
- [ ] Deben cubrir el 100% del width los componentes que tienen un background de color
