### ISSUE TITLE
Pregunta: Ya existe la posibilidad de ocultar las instrucciones como un paywall?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5985]
Este diseño permite poner un paywall en el componente de markdown para usuarios no registrados o que no tengan cierto plan.

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10965%3A52036&mode=design&t=aAO1HgltavDWsUx3-1

Creo que ya tenemos algo parecido implementado???

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10965%3A52036&mode=design&t=aAO1HgltavDWsUx3-1

**Comment by ArielCalisaya** [comment]
@alesanchezr Si, ya existe en contenidos tipo markdown, para cortar cualquier texto dentro del tag `<onlyfor>`, solo debo actualizar a el nuevo estilo del componente

**Comment by ArielCalisaya** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/51676628/797429b8-47fd-48c6-9578-23a884941ff6)
