### ISSUE TITLE
Los planes deben tener cohort sets en vez de available_cohorts

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5988]
Este cambio se debe a que ahora los planes se adquieren por los consumibles y no por acceso a un curso, los cursos seran incluidos hasta en los planes gratuitos, a excepcion de algunos premium.

- [ ] Se debe crear la tabla cohort_set similar a la de event_type_set o mentorship_service_set.
- [ ] Se debe quitar available_cohorts de los planes y agregar cohort_set.
- [ ] Se debe agregar un servicio para unirte en una cohort, el cual debe validar contra el cohort_set de las subscripciones y plan financing adquiridos por el usuario, de pertenecer a alguno de sus cohort_set, entonces se debe agregar a la cohort (crear cohort user, etc). De no pertenecer se debe retornar un error. Este servicio va a poder recibir el id del plan que se cree que el usuario adquirio y el id de la cohort a la que se va a unir si es que el curso le entrega esa informacion.
- [ ] Agregar cohort a la tabla course. Se debe validar que la cohort sea never_ends=True, available_as_saas=True, el syllabus debe ser uno de los del curso

**Comment by tommygonzaleza** [comment]
- [ ] Se debe agregar una validacion que si una de las cohorts escogidas en el cohort set si tiene inicio y fin, entonces no debe permitir agregar otra cohort que si tiene inicio y fin.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1078

**Comment by tommygonzaleza** [comment]
- [ ] En la vista de checking esta fallando si no se especifica el cohort_set, ya que esta pidiendo que se especifique el cohort_set porque sino toma en cuenta como que el plan no tiene cohort_set y falla a la hora de buscar el plan, lo solucione o por lo menos agregue un parche [aqui](https://github.com/breatheco-de/apiv2/commit/f8baa7f5db048da27bfc3f55b9e1046de3c0472f). Se debe revisar si hacen falta otros cambios necesarios relacionados a lo que antes era selected_cohort, se encontraron otros bugs relacionados a esto tambien pero en el modulo de eventos
