### ISSUE TITLE
No se genera la factura de agosto de provisioning bill

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5989]
Se queda pending en la base de datos.
Estste es el CSV

[github-usage-august.csv](https://github.com/breatheco-de/breatheco-de/files/12529282/github-usage-august.csv)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1100

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1103/files

**Comment by jefer94** [comment]
try again
