### ISSUE TITLE
Propuesta de optimizaciones

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5991]
Haz un propuesta seria de optimizaciones para el APIv2

**Comment by jefer94** [comment]
- Optimizador de queries
- Optimizaciones de Celery
- Escoger el worker asíncrono que por ahora el más estable es Uvicorn
- Migraciones de elementos que bloqueen el hilo a funciones asíncronas
- SSR (no es un decir, es literal SSR)
