### ISSUE TITLE
Agregar varias pruebas unitarias para PromptFormatter

### ISSUE THREAD

**Issue by Charlytoc** [breatheco-de/breatheco-de#5994]
- [x] Necesito chequear con varios ejemplos que la función esté reemplazando correctamente los comentarios de HTML por strings vacíos al momento de guardar. 
- [x] Y agregando el comentario de HTML en caso de que esté en el administrador de Django
- [x] En la generación se reemplaza por el valor actual de la variable

**Comment by JParedesArtica** [comment]
Las tareas ya fueron realizadas.
