### ISSUE TITLE
Can't open the 30DAYSOFGEEKCODING

### ISSUE THREAD

**Issue by vancieta** [breatheco-de/breatheco-de#5997]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/116301809/4e1efc15-ee85-4e3f-b78e-33119bfffaf5)

### Steps to reproduce

When I click on the 30DAYSOFGEEKCODING nothing happens

### Expected behavior

It should open the 30DAYSOFGEEKCODING

**Comment by Khrisefzm** [comment]
30DAYSOFGEEKCODING is not longer abailable, and all the footer items work
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/a3c30103-8a2e-4180-b3dd-beafadb909e8)
