### ISSUE TITLE
No aparece el boton de editar en github en lecciones en español

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6000]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/34c10294-2580-4de2-88ce-d2e6ef008dd5)

Tambien cuando el titulo es muy largo se muestra el boton de editar en github abajo
<img width="794" alt="Screenshot 2023-09-06 at 5 44 25 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/8602cb89-5344-4e3a-b918-10931f027249">

**Comment by alesanchezr** [comment]
La tabla de contenidos si deberia ocupar todo el with
