### ISSUE TITLE
Correguir backlinks que no apunten al home sino a la pagina de la sede

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6005]
- [ ] [Las conde (Chile)](https://www.lascondes.cl/convenios/educacion/901/detalle/4geeks-academy)
- [ ] [Zoom tecnologico (Chile)](https://www.zoomtecnologico.com/2023/08/22/demanda-profesionales-en-ti/) 
- [ ] [Opground (Maria)](https://opground.com/article/4geeksacademy-y-opground)

**Comment by G-code7** [comment]
Actualización: 
 -Listo Opground (redirige a madrid), y listo zoomtecnologico (redirige a santiago)
 
 - ya les escribí a lasconde estoy esperando que me atiendan, de todas formas hoy seguiré insistiendo.

**Comment by G-code7** [comment]
enlace actualizado en lasconde
