### ISSUE TITLE
En vista de assigments de student view cambiar color cuando un proyecto está rechazado.

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6020]
Cuando un projecto se encuentra en estado rechazado se lo marca con color rojo (mismo color que se utiliza para el no entregado). Se desea cambiar el color para los casos de reject y que sea en violeta, naranja u otro color que no sea ni rojo (no entregado) , ni verde (corregido ok), ni amarillo (entregado y sin corregir) ni gris (no abrió el módulo).

Graicas.

<img width="1048" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/b9eb616e-d0ab-4482-8b1a-8042338b55dd">

**Comment by pbullor** [comment]
@tommygonzaleza y @alesanchezr cargó este pequeño cambio

**Comment by alesanchezr** [comment]
Esto lo voy a cerrar porque ya esta implementandose aqui:

https://github.com/breatheco-de/breatheco-de/issues/5346#issuecomment-1601414564
