### ISSUE TITLE
Modal para mostrar Pending mandatory projects

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6022]
Vamos a hacerlo como en la modal de projecto final, a la izquierda pones una animacion de como usar los filtros de tareas en el dashboard de la cohort. A la izquierda va a decir:

```md
# Required tasks before graduation

You must complete all the mandatory assignments to graduate and receive a certificate.

Use the filter at the top tasks to focus on all of them.
```

El boton va a decir `"Back to dashboard"`

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=4nqXiwz1FGMbEHs3-1

**Comment by alesanchezr** [comment]
listo pa programar

![Image](https://github.com/breatheco-de/breatheco-de/assets/426452/ca268220-3490-4295-99c2-1ce77bc6ae48)

**Comment by alesanchezr** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782-47912&mode=design&t=msK6BY9J6Ic1TjGw-0

**Comment by tommygonzaleza** [comment]
@ali5uarez5 Que boton te lleva a la modal de pending mandatory projects? Como haces para abrir la modal?

**Comment by ali5uarez5** [comment]
la modal de mandatory projects se ve desde esa barra


![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/dac57eba-fdb2-44a9-baef-fdea11604679)

**Comment by tommygonzaleza** [comment]
- [ ] Prueba con un titulo de un proyecto mas largo
- [ ] Muestra ejemplos de exercises y projects, no solo de lessons
- [ ] El boton debe decir read lesson, o lo que dice normalmente si es exercise o project. Actualmente dice Complete here

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A47912&mode=design&t=bXMKUOW0BtLvGjhV-1

**Comment by tommygonzaleza** [comment]
Se asigno para programarlo aqui: https://github.com/breatheco-de/breatheco-de/issues/6845
