### ISSUE TITLE
Agregar disclaimer en vista de rigobot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6023]
En la vista de rigobot que funciona para entrenarlo, se debe agregar un disclaimer en la parte superior que diga: This answer was generated as part of the training for Rigobot, our new internally developed AI Bot training as the best possible coding mentor. You can read more about Rigobot here.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9874%3A45887&mode=design&t=JuvLnFUFzRTTcVs3-1
