### ISSUE TITLE
Modificar landing de example

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6026]
El landing de example debe tener cada uno de los componentes con cada una de sus diferentes versiones. De esa manera se puede apreciar como se ven los componentes. Antes de cada componente puedes ponerle un titulo del nombre del componente para que sepan cual es el que se esta mostrando

**Comment by tommygonzaleza** [comment]
- [ ] Todavia le hacen falta varias modificaciones para que parezca un landing, empezando por la imagen gris de fondo en el landing ya hace que se vea mal

**Comment by alesanchezr** [comment]
Falta el header
