### ISSUE TITLE
Acomodar landings ya existentes pero con el diseño nuevo

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6027]
Debes agregar los ymls de estos landings:
- https://4geeksacademy.com/us/coding-campus/coding-bootcamp-colombia (Cuyo diseño esta [aqui](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7951%3A24869&mode=design&t=i9vNVRsR6u02Qvuo-1))
- https://4geeksacademy.com/es/landing/academia-programacion (Cuyo diseño esta [aqui](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7952%3A25612&mode=design&t=7agxwMkR748NaYGD-1))

Y revisar si con el rediseño que tienes de los componentes se ve exactamente como en el figma. Si no se ve igual, entonces debes modificar los componentes para que si se vea

**Comment by tommygonzaleza** [comment]
- [ ] Acomodar detalles del landing como el boton del form (Tiene un tamaño fijo), la foto en el heading, etc.
- [ ] En mobile la estructura del syllabus debe ser como estaba antes, como un acordion donde seleccionas que etapa del syllabus quieres ver y se despliega

**Comment by alesanchezr** [comment]
- [ ] La marquesina [debe llegar hasta el final](https://www.awesomescreenshot.com/image/43028817?key=c604fb5c8c4e33a3763b9f6b5f6a44eb).
- [ ] Porque [esto esta tan grande](https://www.awesomescreenshot.com/image/43028817?key=c604fb5c8c4e33a3763b9f6b5f6a44eb).

**Comment by tommygonzaleza** [comment]
Listo para ser aceptado, ya se ve bien

**Comment by tommygonzaleza** [comment]
- [ ] Debes alinear todos los componentes, algunos tienen un padding de mas
![Screenshot 2023-09-26 at 10 26 40 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/22189ce1-80a3-4e9c-a6a2-eb590d6724c9)

**Comment by alesanchezr** [comment]
falta el header

**Comment by alesanchezr** [comment]
- [ ] Todavia el header no llega hasta el margen de la derecha.
- [ ] Ahora desaparecio el premio: `header.badge`

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1814

**Comment by tommygonzaleza** [comment]
Eata funcionando bien, falta aceptar el PR
