### ISSUE TITLE
Las NPS no están mostrando todos los estudiantes

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6033]
### Bug description

El curso tiene más de 8 estudiantes pero solo muestra 5 estudiantes (entre quienes respondieron y quienes no)

### Steps to reproduce

Ir a la encuesta y marcar "Include unanswered"

### Expected behavior

Deberían aparece los más de 8 estudiantes con la puntuación que respondieron o un ? en caso de que no.

### Anything else?

Enviada captura por Slack, debido a que contenía nombres,

**Comment by alesanchezr** [comment]
No tengo screenshot de tu reporte de bug, pero prueba marcando ["include unanswered"](https://www.awesomescreenshot.com/image/42894552?key=48351397faa2b37b23842b05dac9dc00) y si no te funciona vuelves a abrir este bug.

**Comment by ehiber** [comment]
En este link https://admin.4geeks.com/feedback/surveys/spain-fs-pt-44/1012?&location=madrid-spain
Se muestran solo 5 alumnos y el curso tiene 14 (cuando das opcion a include unanswered") 

El global externo muestra 8.6 pero el interno tiene solo 1 respuestas con 10, y me parece que esta relacionado con los alumnos que no se muestran. 

![image](https://github.com/breatheco-de/breatheco-de/assets/56272634/fc51a9f4-c0af-4687-aa07-23c853289504)
![image](https://github.com/breatheco-de/breatheco-de/assets/56272634/30016231-6427-4c8c-83fc-801b06d3686c)

**Comment by marcogonzalo** [comment]
> No tengo screenshot de tu reporte de bug, pero prueba marcando ["include unanswered"](https://www.awesomescreenshot.com/image/42894552?key=48351397faa2b37b23842b05dac9dc00) y si no te funciona vuelves a abrir este bug.

Dije en el mensaje inicial que había pasado la captura por Slack
![Screenshot 2023-09-13 at 20 10 52](https://github.com/breatheco-de/breatheco-de/assets/410890/420026f4-f198-4c00-9522-f2b188fecb17)
