### ISSUE TITLE
Traducir lessons del syllabus Algoritmos y Programacion

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6034]

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/breatheco-de/content/pull/1810
- [ ] https://github.com/breatheco-de/content/pull/1815/files
- [ ] https://github.com/breatheco-de/content/pull/1823
- [ ] https://github.com/breatheco-de/content/pull/1825
- [ ] https://github.com/breatheco-de/content/pull/1826
- [ ] https://github.com/breatheco-de/content/pull/1833
