### ISSUE TITLE
problema con la página de módulos

### ISSUE THREAD

**Issue by Bforti** [breatheco-de/breatheco-de#6036]
Hola. Tengo una situación con la página en donde se inicializan los módulos. Y es que cada vez que inicio sesión, tengo que iniciar sesión en varios módulos que yo ya había modificado antes. Además, tengo un proyecto entregado que parece que no termina de actualizarse y no puedo entregar nuevos proyectos. Espero su respuesta, gracias

**Comment by veljzs** [comment]
No se pudo replicar el error

**Comment by AngelesRocks** [comment]
No se pudo verificar el error
