### ISSUE TITLE
ADMIN - Bug adding manually to github organization

### ISSUE THREAD

**Issue by ehiber** [breatheco-de/breatheco-de#6037]
### Bug description

Antiguamente al colocar un estudiante activo en el prework se agregaba a lista de envio de invitaciones a github.
Actualmente no es así y se debe enviar manual mediante el modal de la imagen agregada, el bug es que no salen todos los alumnos activos. 

![image](https://github.com/breatheco-de/breatheco-de/assets/56272634/3af261a1-1886-47e1-add9-84e37dd45f91)

### Steps to reproduce

Ingresar desde la sede de españa. ingresar un alumno activo en el prework con 3 meses dado de alta. 

### Expected behavior

Todos los alumnos que se encuentren activos, deben aparecer en ese listado.

**Comment by pbullor** [comment]
Está resuelto.
