### ISSUE TITLE
La búsqueda de proyectos por estudiante no permite buscar por todos los estudiantes

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6038]
### Bug description

En el filtro por estudiante no aparecen todos los estudiantes del curso, ni al listar, ni al escribir el nombre.

En estas vistas se ve que el estudiante E no aparece en el listado de opciones pero sí que tiene proyectos entregados, aprobados y rechazados.
<img width="1766" alt="Captura de pantalla 2023-09-14 a las 11 11 13 a  m" src="https://github.com/breatheco-de/breatheco-de/assets/410890/f6a904b6-e03d-4dca-935a-3f1ff8fb0baa">
<img width="1200" alt="Captura de pantalla 2023-09-14 a las 11 11 34 a  m" src="https://github.com/breatheco-de/breatheco-de/assets/410890/76bc06d1-88b5-4be8-b6a3-f9cd05d24bda">

### Steps to reproduce

Ir al curso de "Building your tech profile" de España, a la parte de proyectos entregados, y escribir "Enrique"

### Expected behavior

Que se pueda filtrar por toda persona que esté registrada en el curso

**Comment by marcogonzalo** [comment]
Este fallo nos está afectando negativamente en todas las áreas:

- GeekFORCE no pude verificar la entrega de CV y otras asignaciones entre más de 50 estudiantes y el trabajo se está acumulando.
- Profesores y TAs no pueden corregir de forma eficiente, les hacemos perder el tiempo y termina costando horas extra.
- Program Managers no pueden revisar los proyectos entregados por estudiantes que están esperando por su certificado, lo que genera que los estudiantes presionen y se quejen.

**Comment by marcogonzalo** [comment]
Se ha cerrado pero sigue sucediendo
![Screenshot 2023-10-11 at 11 11 51](https://github.com/breatheco-de/breatheco-de/assets/410890/b17b2d68-3964-4447-8485-e3d734999d3f)

**Comment by marcogonzalo** [comment]
De hecho, el problema también se presenta con el desplegable de proyectos

**Comment by gustavomm19** [comment]
Hola Marco. Con la data que tengo no he podido replicar el error y el comportamiento parece ser el esperado. Ese filtro filta todos los miembros de la cohorte que tengan rol de estudiante. Podria ser que el usuario que estes buscando tenga otro rol asignado?
