### ISSUE TITLE
No aparece opción en botón de entregar proyecto

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6039]
### Bug description

Antes aparecía la opción para entregar el proyecto y ahora no aparece.
![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/232569ab-9703-44fc-b0cc-2e6539ff7f10)

### Steps to reproduce

IG Photo Feed por ejemplo

**Comment by ArielCalisaya** [comment]
@pbullor No he podido replicar este bug en los entornos de producción y desarrollo.
Puedes revisar si aun te ocurre este problema?
