### ISSUE TITLE
No aparecen módulos en PreWork

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6040]
### Bug description

Hay varios modulos que fiugura que no hay nada para mostrar y en los que si muestra, faltan algunos modulos,practicas y proyectos.

![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/f2576b7f-356a-450c-a4e0-c1abf1ea2d0e)

### Steps to reproduce

Ingresar en prework, por ejempli con el usuario cmoralesbenavides65@gmail.com

**Comment by tommygonzaleza** [comment]
Este bug ya lo resolvimos, habia un problema que afectaba a varios requests del API
