### ISSUE TITLE
En el módulo de begginer JS aparece el proyecto de Excuse que corresponde al último módulo

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6041]
### Bug description

Aparece el proyecto donde no corresponde.

https://files.slack.com/files-pri/T0BFXMWMV-F05S3J0D34M/screenshot_capture_-_2023-09-13_-_10-54-22.png

### Steps to reproduce

Ingresar en Prework

**Comment by pbullor** [comment]
El alumno que reportó esto es FARRERAJOSE96@GMAIL.COM

**Comment by alesanchezr** [comment]
la todo no abre @pbullor

**Comment by pbullor** [comment]
<img width="1142" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/d56716c8-87b6-4577-843b-362bcd30dfe0">

**Comment by pbullor** [comment]
Esta ok , consensuamos que quede así.
