### ISSUE TITLE
Un alumno hizo click en la practica de JS begginer y lo llevo al Master JS

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6042]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/b611d6fd-b868-475f-83e2-70833d85f188)

![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/b1e16ecd-ce24-40ce-b934-300ebc93160e)

### Steps to reproduce

Usuario FARRERAJOSE96@GMAIL.COM

**Comment by tommygonzaleza** [comment]
El link esta correcto, creo que le dio a continue exercises y escogio el codespace que no era

**Comment by tommygonzaleza** [comment]
Entre con su usuario y tuve ese problema

**Comment by pbullor** [comment]
Estaría solucionado.
