### ISSUE TITLE
Al confirmar un email luego de registrarte te lleva a una vista blanca

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6050]
![image 358](https://github.com/breatheco-de/breatheco-de/assets/56565994/b0da3a02-97ed-41ea-9bb3-3755f243e1d7)

Deberia mostrar un formulario para agregar su password, name, lastname, telf, etc

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1121
