### ISSUE TITLE
Home - Boton de sign up for free deberia llevar a los planes

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6052]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42923302?key=c7da20479ca60bee55260cc640592baa&size=orig) 

---
**Source URL**:
[https://4geeks.com/](https://4geeks.com/)

**Comment by JParedesArtica** [comment]
El bug ya fue resuelto, el boton sign up for free lleva a la vista de planes
