### ISSUE TITLE
No puedo crear un mentor para dar mentorías de Data Science

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6054]
### Bug description

La opción del Syllabus de Data Science no aparece disponible
![Screenshot 2023-09-14 at 20 53 55](https://github.com/breatheco-de/breatheco-de/assets/410890/19f47b6c-f3ae-41b7-b64e-b5f7c7c258e9)

### Steps to reproduce

Ir a Mentors > Add new mentor > Syllabus 

Al listar las opciones, no se ve la de Data Science and Machine Learning, y  al buscar, obviamente, tampoco aparece.

### Expected behavior

Al escribir Data o Machine, debería aparecer la opción del syllabus

**Comment by tommygonzaleza** [comment]
Prueba ahora a ver si ya funciona, a mi si me aparece:
[87aa5c6af0a8c3313e4638a069a912cc3c6e5249](https://breathecode.herokuapp.com/admin/authenticate/token/760847/change/)

**Comment by marcogonzalo** [comment]
Sí, ahora logro ver el programa
