### ISSUE TITLE
Revisar como optimizar el uso del API por el deploy de 4Geeks Academy

### ISSUE THREAD

**Issue by jefer94** [breatheco-de/breatheco-de#6061]
`v1/admissions/cohort/all` and many endpoints related to the tasks, assets (`v1/registry/asset`) and technologies (`v1/registry/academy/technology`) are slower, these should return a timeout destroying the user experience, the call thought of api rest must have as limit 300ms to be considered acceptable, just the endpoints that manage files should break this rule

First build the cache and the pagination if this does not have it, then is required improve its performance when the cache and the pagination is not working, it's possible adding random params in the url and setting the `limit` in `30000`, GraphQL should be good for this purpose, thanks to write GraphQL is a task that a frontend should hate, so, if each one of them hate it they won't add unnecessary queries that could add a overhead on the api rest

New item that is slower (`09-20-2023`):
- `v1/feedback/academy/answer`

**Comment by tommygonzaleza** [comment]
@gustavomm19 
- [ ] Revisar los requests que se estan haciendo en el website de 4geeks academy. Listarlos
- [ ] Intentar reducir la cantidad de requests que se estan haciendo.
- [ ] Agregar cache a los requests que tengan mayor consumo

**Comment by gustavomm19** [comment]
1. En deploy y en pruebas: [Pruebas de Downloadables](https://github.com/4GeeksAcademy/website-v2/blob/master/src/test/test.downloadable.js#L46)  `v1/marketing/downloadable`
2. En deploy y en pruebas: [Pruebas en Clusters](https://github.com/4GeeksAcademy/website-v2/blob/master/src/test/test.cluster.js#L34) `v1/registry/academy/keywordcluster`
3. En el deploy: [Obtener todos los assets](https://github.com/4GeeksAcademy/website-v2/blob/master/bc-source-plugin/gatsby-node.js#L23) `v1/registry/academy/asset?limit=500&offset=0&category=blog-es,blog-us&status=published&visibility=public`
4. En el deploy: [Obtener el markdown por cada asset](https://github.com/4GeeksAcademy/website-v2/blob/master/bc-source-plugin/gatsby-node.js#L35) `v1/registry/asset/${slug}.raw`
5. On refresh: [Obtener academy alias](https://github.com/4GeeksAcademy/website-v2/blob/master/src/worker.js#L261) `v1/marketing/alias?academy=2,4,5,6,7,8,9,10,11`
6. En vista `/us/next-dates`: [Obtener cohortes](https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/calendar.js#L86) `v1/admissions/cohort/all`
7. En vistas de locations: [Obtener cohortes](https://github.com/4GeeksAcademy/website-v2/blob/master/src/components/UpcomingDates/index.js#L145) `v1/admissions/cohort/all`
8. En vista `/us/next-dates`: [Obtener eventos](https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/calendar.js#L87) `v1/events/all`

**Comment by tommygonzaleza** [comment]
Falta aceptar el PR, esta listo

**Comment by tommygonzaleza** [comment]
- [ ] Traete el markdown de cada asset directamente desde la url de GitHub
