### ISSUE TITLE
Inconsistencias en el Footer

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6066]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42985377?key=510e43958d0e7ba821ed6a8a07d5328d&size=orig) 

 Hay que actualizar el logo de 4Geeks y el icono de Data science, además todos los links que estan del lado derecho te llevan a el home. 
También el Media Kit, social & live learning te llevan al home. 

---
**Source URL**:
[https://4geeks.com/](https://4geeks.com/)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/b81fbc7d-aa9a-42f5-bb49-50f99e8ddf65)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/048d0a7f-3e86-4cf1-8465-2bb9d2dafbf6)

**Comment by ali5uarez5** [comment]
![logo_footer](https://github.com/breatheco-de/breatheco-de/assets/105449728/06031675-7557-4a5f-a212-69187610d380)
![logo_login-register](https://github.com/breatheco-de/breatheco-de/assets/105449728/36e44e48-5458-43b0-8eca-ff2351919cbe)
![logo_navbar](https://github.com/breatheco-de/breatheco-de/assets/105449728/f460122b-dfac-4c9e-8794-92e77d991b64)
![datya science](https://github.com/breatheco-de/breatheco-de/assets/105449728/ec0dad6c-ba66-46cd-bf8f-c7795f835d7f)

**Comment by tommygonzaleza** [comment]
Se van a reemplazar intro to coding por el curso de javascript (Utiliza la descripcion del curso), 30daysofgeekcoding por el curso de python (Poner la descripcion del curso de marketing), y se reemplazaran data science y el de machine learning por estos dos:
<img width="619" alt="Screenshot 2023-10-17 at 6 16 38 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/01bba582-9a3c-4dbd-a21a-6a0f2a231d0a">
