### ISSUE TITLE
Landing workshops - Add CTA

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6069]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42985711?key=215458f700382229f8655a1500ed31f3&size=orig) 

---
**Source URL**:
[https://4geeks.com/workshops](https://4geeks.com/workshops)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/ff53b793-43e9-4044-9c6a-45745dc6b667)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/293d63ae-97b8-485b-b623-cbb124e8e3d4)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/654d342c-de94-48c4-ac0a-d7a6fbc667d6)
