### ISSUE TITLE
Home - header image

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6073]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42986418?key=7a3366c1d51d6a60aa5c08a2d05545a6&size=orig) 

---
**Source URL**:
[https://4geeks.com/](https://4geeks.com/)

**Comment by ali5uarez5** [comment]
https://drive.google.com/file/d/1EP4cpk6XZyN2_L2QCFg40TMvMo9fIlzO/view?usp=drive_link

**Comment by tommygonzaleza** [comment]
Podrias comprimir el GIF? Actualmente ocupa 4 mb

**Comment by ali5uarez5** [comment]
Esto se le iba a preguntar a Ariel no?
