### ISSUE TITLE
Cambiar imagen en landing de workshops

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6074]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/42986723?key=d6f7539632addc0ec895843731bdc163&size=orig) 

 Cambiar esa imagen por esta: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=4682%3A14848&mode=design&t=SFu0LxCaSZl55QKJ-1

---
**Source URL**:
[https://4geeks.com/workshops](https://4geeks.com/workshops)

**Comment by tommygonzaleza** [comment]
Si agrego esa imagen no se logra ver de tan buena calidad, yo creo que es por el tamaño de la imagen, crees que puedas hacerla un poco mas grande?
<img width="1225" alt="Screenshot 2023-09-21 at 12 54 33 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/8bddd274-2ace-406b-b4e7-fcd501c80263">

**Comment by ali5uarez5** [comment]
Prueba con esta a ver

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11200%3A36268&mode=design&t=T40faKrFhY1prVpQ-1

**Comment by tommygonzaleza** [comment]
Queda asi
<img width="1225" alt="Screenshot 2023-09-21 at 1 02 16 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/f8d68a29-9d26-4e28-90d1-a656b6cae43f">

**Comment by alesanchezr** [comment]
Tiene que ser animado, enfocate solo en la parte de workshoips.

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/da376cdc-f580-4c87-876f-75e7965113a0)

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/da376cdc-f580-4c87-876f-75e7965113a0)
