### ISSUE TITLE
La vista de entrega de proyectos no está haciendo la carga correctamente

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6075]
### Bug description

Cuando entro a la vista de proyectos e intento ver más entregas, desplazándome hacia abajo, se ejecuta la acción de carga pero no se ve ninguna llamada en el navegador y la pantalla se queda bloqueada en la animación de carga.
<img width="2106" alt="Captura de pantalla 2023-09-18 a las 11 43 34 a  m" src="https://github.com/breatheco-de/breatheco-de/assets/410890/aa395a2b-d13a-41ef-8450-6236db1a3d6c">
<img width="2002" alt="Captura de pantalla 2023-09-18 a las 11 43 52 a  m" src="https://github.com/breatheco-de/breatheco-de/assets/410890/e1dcb170-67d1-441f-a82a-c90111f5dcec">

### Steps to reproduce

Ir a la vista de proyectos y desplazarse hacia abajo para que intente cargar más proyectos

### Anything else?

Esto puede estar relacionado con este otro fallo reportado días atrás en la misma vista: https://github.com/breatheco-de/breatheco-de/issues/6038

**Comment by marcogonzalo** [comment]
Actualización: Yoani ha notado que si el scroll se hace "muy lentamente" sí logra cargar algunas veces.

**Comment by AngelesRocks** [comment]
Ya no sucede
