### ISSUE TITLE
Agregar validacion en modelo de `payments.CohortSet`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6081]
- [ ] Se debe validar desde el modelo que no se permitan agregar cohorts `available_as_saas=False`

**Comment by jefer94** [comment]
https://github.com/jefer94/apiv2/blob/d6a4df462399200e3cf6e94c7665d87204366915/breathecode/payments/models.py#L339
https://github.com/jefer94/apiv2/blob/d6a4df462399200e3cf6e94c7665d87204366915/breathecode/payments/models.py#L372
