### ISSUE TITLE
Landing workshops - Responsive 

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6085]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43043825?key=274fe33c7bd0057a9aaf213f5649f751&size=orig) 

 -No se muestra la nav bar, es imposible navegar el sitio en mobile desde esa página. 
-La info sobre el workshop y el CTA están muy abajo, hay que agregar el sticky buttom o en cualquier caso arreglar la vista para que se muestre así: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11172%3A7628&mode=design&t=R0sRrYkWeGWmfMqw-1

---
**Source URL**:
[https://4geeks.com/workshops/create-an-api-with-python-flask-803](https://4geeks.com/workshops/create-an-api-with-python-flask-803)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/cff8e665-b41c-4bf0-bd45-1228d0c6fbb5)
 Solo se ve el nav bar cuando clicas en tu perfil, hay que corregirlo y actualizar el nav bar.

**Comment by tommygonzaleza** [comment]
A mi si se me muestra el navbar desde mobile
![IMG_9477](https://github.com/breatheco-de/breatheco-de/assets/56565994/2ee76a14-3baa-4f5a-9bad-a32f6e26a367)

**Comment by tommygonzaleza** [comment]
El bug ya fue resuelto, no se pudo replicar el problema
