### ISSUE TITLE
Dashboard - Courses card

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6086]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43043986?key=867c2a21607a961a86e82ee5e04116e9&size=orig) 

 Me anoté en el curso gratuito y dice que lo inicié hace 5 meses. 

---
**Source URL**:
[https://4geeks.com/choose-program](https://4geeks.com/choose-program)

**Comment by tommygonzaleza** [comment]
@gustavomm19 Si la cohort es never end, entonces muestra la fecha en la que se crea el cohort_user
