### ISSUE TITLE
Schedule a mentoring session

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6087]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43044055?key=f53ccf95e9c7529e283fc9f10b54a41b&size=orig) 

 Se puede estilizar lo que está fuera de la experiencia de calendly? cambiar el logo, la tipografía y el texto?

---
**Source URL**:
[https://breathecode.herokuapp.com/mentor/tgonzalez-o0o?utm_campaign=geekpal-1-1-javascript&utm_source=4geeks&salesforce_uuid=7538](https://breathecode.herokuapp.com/mentor/tgonzalez-o0o?utm_campaign=geekpal-1-1-javascript&utm_source=4geeks&salesforce_uuid=7538)

**Comment by tommygonzaleza** [comment]
Si se puede cambiar, @ali5uarez5 crea el diseño de esta vista de que queda al rededor de lo de calendly

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11389%3A27549&mode=design&t=JBpHtOprn3FMIl1D-1

**Comment by tommygonzaleza** [comment]
Tienes que ponerle object-fit: cover a la imagen para que no se distorsione
<img width="851" alt="Screenshot 2024-02-28 at 5 05 46 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/1e763bb3-1932-41ca-93ec-51f306fee179">
