### ISSUE TITLE
Mostral tooltip del mentor

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6088]
El componente de tooltip ya esta desarrollado, solo hay que usarlo.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43044090?key=1a71f8643f500a8132bea0c4be7e0846&size=orig) 

 Se deberia mostrar info sobre el mentor en el bubble cuando haces hover. En este momento eso no pasa. 

---
**Source URL**:
[https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2](https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2)

**Comment by tommygonzaleza** [comment]
Agregar en el diseño version del componente en la que se hace hover y se muestra la pequeña ventana con info del mentor. Reutilizar el componente de la ventanita que ya tenemos

**Comment by ali5uarez5** [comment]
Este es el bubble 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6592%3A25284&mode=design&t=T40faKrFhY1prVpQ-1
