### ISSUE TITLE
Start coding using javascript - You have reached the end... modal

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6090]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43044227?key=9e3c766e3b4f4fbc5165a235563397c5&size=orig) 

 Hay que rediseñar el mensaje de este modal y hacerlo mas accesible

---
**Source URL**:
[https://4geeks.com/syllabus/start-coding-using-javascript-1/read/what-is-learnpack](https://4geeks.com/syllabus/start-coding-using-javascript-1/read/what-is-learnpack)

**Comment by tommygonzaleza** [comment]
Propongo que sea:

```
You just finished the module "LearnPack".

Click the button below to start de next module (JavaScript Basics)
```

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10985%3A39651&mode=design&t=mkN7r3DV7bcgNgIt-1

**Comment by tommygonzaleza** [comment]
Este es el diseño nuevo: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62640&mode=design&t=j3RMGhTKzqhrntmr-1
