### ISSUE TITLE
Crear diseño de vista de pricing en dark mode

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6094]
<img width="906" alt="Screenshot 2023-09-20 at 10 26 01 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/e27518c7-6607-457a-8d4f-73c7cd373e4b">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11189%3A30512&mode=design&t=uCyrDjUUKjeAnelV-1
