### ISSUE TITLE
Organizar en un drive material de apoyo para Algoritmos y Programacion

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6098]
El material puede ser:

- [ ] Parciales antiguos
- [ ] Quizzes viejos
- [ ] Proyectos viejos
- [ ] Demas material relevante

**Comment by Lorenagubaira** [comment]
https://drive.google.com/drive/folders/1LYfpL-g_Gra-We_q2v7bEDJZNLgFGF7p?usp=drive_link

**Comment by tommygonzaleza** [comment]
Pon el drive publico
