### ISSUE TITLE
errores ortográficos en párrafos entre módulos

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6099]
![cambiar your por sure](https://github.com/breatheco-de/breatheco-de/assets/109150320/6297a50e-0911-4c68-9779-bfaffa6a5887)

cambiar "your" por "sure"

![cambiar using por with](https://github.com/breatheco-de/breatheco-de/assets/109150320/077f49c1-638e-4fc5-9def-06f75a47cd25)

cambiar "using" por "with"

![cambiar thru y poner punto antes de Today](https://github.com/breatheco-de/breatheco-de/assets/109150320/9fdbb4ae-133d-47a8-82f0-1d8bcb7fe0f1)

cambiar "thru" por "through" y cambiar la "coma" por un "punto" y poner "Today" con la T mayúscula

![falta el punto](https://github.com/breatheco-de/breatheco-de/assets/109150320/4a5dab16-cd73-451c-86d7-9ca3b4c21133)

poner el "punto" final

![quitar las comillas y la coma](https://github.com/breatheco-de/breatheco-de/assets/109150320/7026e32a-4b2c-4bc9-82c2-00a3b54aa722)

quitar la comilla " y la "coma" del final que están de más

![thinking esta mal](https://github.com/breatheco-de/breatheco-de/assets/109150320/03a23647-ea03-4dfa-8ab8-a01a084afe83)

la palabra "thinking" tiene los backslash para escapar los caracteres de las comillas pero no es necesario. Quitar esos backslash

**Comment by tommygonzaleza** [comment]
Resuelto!
