### ISSUE TITLE
Hacer pull en el admin de los siguientes assets

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6101]
- https://4geeks.com/syllabus/full-stack-fake-5/practice/forms-exercises
- https://4geeks.com/syllabus/full-stack-fake-5/project/exercise-terminal-challenge
- https://4geeks.com/syllabus/full-stack-fake-5/project/learn-in-public-project
- https://4geeks.com/syllabus/full-stack-fake-5/project/fix-the-misspell
- https://4geeks.com/syllabus/full-stack-fake-5/project/collaborative-html-website
- https://4geeks.com/syllabus/full-stack-fake-5/project/domain-generator
- https://4geeks.com/syllabus/full-stack-fake-5/project/conditional-profile-card
- https://4geeks.com/syllabus/full-stack-fake-5/practice/javascript-events-exercises

**Comment by Lorenagubaira** [comment]
All done!
