### ISSUE TITLE
El email de validacion del correo no se esta enviando

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6103]
No se esta enviando el email de vlalidacion del correo, le tienen que dar a reenviar para que se les envie

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1121

**Comment by jefer94** [comment]
I can't replicate it

**Comment by tommygonzaleza** [comment]
It's working for me as well
