### ISSUE TITLE
Agregar card de Bootcamp en `/pricing`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6109]
- [ ] Todo lo que tiene el pro pero infinito, de por vida y para un solo curso
- [ ] Job guarantee
- [ ] Lifetime Career support

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10892%3A25140&mode=design&t=JBpHtOprn3FMIl1D-1
