### ISSUE TITLE
Make backend emails white label

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6127]
Right now, the backend emails are being sent with the [hard coded logo in the base.html template](https://github.com/breatheco-de/apiv2/blob/56039bc5c55112fd85e43f8a63fec16241e458ba/breathecode/notify/templates/base.html#L161).

We need to find a way to send these emails from the school that is sending you the email.

For example:

1. If you receive an invitation, the logo should be from the school that invited you.
2. If you are getting a survey, the logo should be from the school that sent you the survey.
3. If you are picking a password, the logo should be from the academy of the invitation, if there are many invitations there should be several separated emails for each invitation, each email with the respective academy lgoo that belongs to that invite.

**Comment by jefer94** [comment]
Check these properties in all academies

- logo_url
- icon_url

Many of them like 4geeks.com have the defaults switched

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1215

**Comment by tommygonzaleza** [comment]
Se van a hacer pruebas en development, el codigo parece estar bastante bien. A partir de ahora todos los templates son white label, es decir, utilizaran los datos de la academia

**Comment by alesanchezr** [comment]
lo deo en QA para que tomas pruebe
