### ISSUE TITLE
Centralizar la funcion para hacer console.log

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6131]
Para evitar tener console.logs en produccion es mejor crear un modulo `logging.js` o also similar que se importe en todos los archivos donde se quiera hacer logging. Puede ser algo como esto:

```js
// logging.js

const isDevelopment = process.env.NODE_ENV === 'development';

export function log(...args) {
  if (isDevelopment) {
    console.log(...args);
  }
}

export function warn(...args) {
  if (isDevelopment) {
    console.warn(...args);
  }
}

export function error(...args) {
  if (isDevelopment) {
    console.error(...args);
  }
}

export function info(...args) {
  if (isDevelopment) {
    console.info(...args);
  }
}

export function debug(...args) {
  if (isDevelopment) {
    console.debug(...args);
  }
}


```

**Comment by tommygonzaleza** [comment]
- [ ] Esta validacion agregada en el navbar esta mala ya que selected_cohort_set.slug no lo puedes comparar con el slug de una cohort, debes hacer esa comparacion para cada cohort adentro del cohort_set
![Screenshot 2023-09-26 at 5 26 42 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/1fab9984-b79c-4391-9e81-311de08eec9e)

**Comment by tommygonzaleza** [comment]
- [ ] Esta frenando los cambios que estan en development para poder pasarse a main

**Comment by tommygonzaleza** [comment]
Estos cambios se agregaron en otro PR hacia dev
