### ISSUE TITLE
Crear vista para a agregar a user a una cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6133]
Ahora el estudiante se puede unir a las cohorts por su cuenta, por lo que al darle click a un boton ya podra unirse a la cohort.

El endpoint para unirse a una cohort es `POST /v1/admissions/cohort/<cohort_id>/join`, y el backend se encargara de agregarlo a la cohort.

Debemos agregar una vista que reciba el id de una cohort a la que se va a unir y que ejecute el request al presionar el boton de join o sin necesidad de precionarlo si ya estoy unido (ver comentarios mas abajo), al endpoint anterior para que intente unirse, luego si el request pasa correctamente lo redireccione al dashboard.

**Comment by tommygonzaleza** [comment]
- [ ] Si el usuario ya es miembro de una cohort con el mismo syllabus que el syllabus de la cohort del landing, entonces debe hacer un redirect al dashboard de la cohort a la que es miembro y cuyo syllabus es el mismo.
- [ ] Si el usuario tiene una subscripcion cuyo selected cohort set incluye a la cohort de este landing, entonces el landing debe verse asi: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=3142%3A9481&mode=design&t=t0fAXTMhI8hXlyLl-1
- [ ] Si el usuario no tiene una subscripcion cuyo selected_cohort_set incluya la cohort de la pagina, entonces debe el landing debe verse asi: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11374%3A28583&mode=design&t=t0fAXTMhI8hXlyLl-1
- [ ] En esta vista, sin importar el caso de los anteriores, recibiras un plan a traves de querystring: `?plan=<plan_slug>`, este plan sera utilizado para que en caso de que el usuario no tenga acceso a esta cohort con su plan actual, sea redireccionado a la vista de pricing pasando por query string este plan: `/pricing?plan=<plan_slug>`.

**Comment by alesanchezr** [comment]
Si la cohort no se encontro entonces muestras un error diciendo: 

`This cohort does not exist or you don't have access to join it with your current plan`.

**Comment by alesanchezr** [comment]
Si voy a la vista de `/join/cohort/380` logeado con el usuario=1 en desarrollo, deberia redireccionarme al dashboard de la cohort porque ya soy miembro.

**Comment by alesanchezr** [comment]
Lo mismo aplica con todas las demas validaciones, hay que mover las validaciones de la vista de `/checkout` a la vista de `/join/cohort/`
