### ISSUE TITLE
Student View Assignament no calcula bien la fecha de última entrega.

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6138]
### Bug description

Levanto un error que me comentó Astrid: 
Un detalle para tener en cuenta, esta alumna entrego este code hace 9 dias y se lo rechacé, y ayer lo volvió a entregar corregido (aun no lo revise) pero me marca la fecha de la primera vez que lo entrego, y justo ayer la ayude a entregar asi que estoy segura que no fue hace 9 dias. en el caso de los codes que vuelven a enviar esta marcando la primera fecha. :eyes:
![image](https://github.com/breatheco-de/breatheco-de/assets/70356168/48464bcc-05a9-4d25-bcdf-765459ed41e9)

### Steps to reproduce

Ingresar en Student View Assignament

**Comment by pbullor** [comment]
@tomasg2704 aquí uno de los errores levantados.

**Comment by tommygonzaleza** [comment]
- [ ] Agrega el campo `delivered_at`

**Comment by pbullor** [comment]
@tommygonzaleza esto ya está corregido?
