### ISSUE TITLE
Student View Assignament - Se actualiza la fecha cuando se corrije o rechaza por parte de un TA 

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6139]
### Bug description

No debe cambiar la fecha de última entrega cuando el proyecto es corregido o rechazado.
<img width="348" alt="image" src="https://github.com/breatheco-de/breatheco-de/assets/70356168/14f4496b-ac15-4217-a6ce-ab3179632b40">

### Steps to reproduce

Ingresar al Assignament, ver la fecha de última entrega, corregir el code y ver si cambió. No debería.

**Comment by pbullor** [comment]
@tomasg2704 éste es otro.

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/6138

**Comment by tommygonzaleza** [comment]
- [ ] No se esta marcando en verde aunque tenga el revission status ACCEPTED
<img width="1445" alt="Screenshot 2023-12-19 at 11 12 21 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/887baa49-bfe9-42e7-b2aa-043cba3c3d2b">
