### ISSUE TITLE
Quitar request que trae tecnologias en deployment

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6141]
Actualmente se esta haciendo un request para traerse las tecnologias de los assets y poder ver la prioridad de cada tecnologia y el titulo para poder mostrarlo en los filtros de los assets. Deberiamos quitar ese request e incluir estos datos de las tecnologias en el serializador usado en el request que trae todos los assets.

- [ ] Crear un serializador nuevo que sea utilizado en la vista que se encarga de traer todos los assets (Usada en el deployment)
- [ ] Modificar las funciones utilizadas en el momento de hacer el deployment para que ya no haga un request para traerse las tecnologias sino que utilice las tecnologias traidas en el endpoint para traerte losa assets

**Comment by gustavomm19** [comment]
breathecode/payments/tests/urls/tests_academy_plan.py
test_lookup_extension

**Comment by alesanchezr** [comment]
Falta un test basado en test_lookup_extension
breathecode/payments/tests/urls/tests_academy_plan.py
test_lookup_extension
