### ISSUE TITLE
Utilizar cache en vercel para el APP

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6142]
- [ ] Crear un endpoint llamado `PUT /update/asset` adentro de vercel (En el APP) que se encargue de actualizar redis, este debe recibir el slug y el readme

Este es el codigo para obtener y guardar cosas en la cache:

```
import { kv } from "@vercel/kv";
await kv.set("user_1_session", "session_token_value");
const session = await kv.get("user_1_session");
```

En este [link](https://vercel.com/dashboard/geeksacademy/stores/kv/store_ODmnpIGUqwUWEJgG/cli) puedes ver mas sobre informacion del storage en redis.

- [ ] Si se modifica el readme, el title o el slug, entonces se debe avisar a vercel a traves del endpoint que crearas en el front (Lo que se especifico de primero en el issue), con un task llamado: `async_notify_asset_update_to_vercel`, esto esta siendo detectado en estos receivers: https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/receivers.py

**Comment by gustavomm19** [comment]
https://github.com/breatheco-de/apiv2/blob/6170da87a70de3244f6632def3f8a5b5be272a4a/breathecode/registry/receivers.py#L65C5-L65C31

https://github.com/breatheco-de/apiv2/blob/6170da87a70de3244f6632def3f8a5b5be272a4a/breathecode/registry/receivers.py#L65C5-L65C31

**Comment by alesanchezr** [comment]
EL request que se trae la lista de assets es medio irrelevante, son solo 10 request (suponiendo que son 1000)

Lo que tenemos que evitar el el request que trae el readme del asset.

Este es el flujo:

Te traes toda la lista de assets y vas uno por uno viendo si los tienes en la cache, si no lo tienes entonces vas y lo buscas.
