### ISSUE TITLE
Plans and prices

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6149]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43279586?key=b6f7cd579647c6141235746e9fd28d42&size=orig) 

 -Debe ser mas ancho, llegar hasta el borde, Hay que hacer que respetar los margenes, tomar de referencia la sección nex dates. 
-La descripción de los planes está en bold, hay que hacerla en medium. 
-Tomar de referencia el componente original para ajustar el tamaño de los precios, el componente está aquí https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9357%3A14867&mode=design&t=Xu6QL3ktYgkSTn50-1
-Agregar el desplegable para elegir location donde está ubicado en el diseño. 

---
**Source URL**:
[https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/231dd3a7-8608-45b8-83ad-84c80743542d)
Cuando los planes no están seleccionados el outline es en negro.

**Comment by tommygonzaleza** [comment]
- [ ] Todavia no esta tomando el width completo del padre
- [ ] La seccion que dice "Select the location and payment option that best suits you" y tiene el dropdown deben estar en el centro (No deben crecer con el componente de abajo)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1813
