### ISSUE TITLE
Actualizar el logo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6153]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43294005?key=bba37256f02612285f0040251b7195d8&size=orig) 

 -En en el nav bar
- En el footer

---
**Source URL**:
[https://4geeksacademy.com/us/index](https://4geeksacademy.com/us/index)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9376%3A13380&mode=design&t=9aiz3dwI3nmir3XN-1

**Comment by Khrisefzm** [comment]
El logo en la navbar se ve borroso en comparación con el log del footer.

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1875
