### ISSUE TITLE
Actualizar logo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6154]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43294070?key=a9adff617df468e7faa987b91560abf5&size=orig) 

 En el footer de las landings

---
**Source URL**:
[https://website-v2-3emhbtaqy-geeksacademy.vercel.app/es/landing/aprende-a-programar-ve](https://website-v2-3emhbtaqy-geeksacademy.vercel.app/es/landing/aprende-a-programar-ve)

**Comment by tommygonzaleza** [comment]
It's confirmed, the logo is not updated yet

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1943

**Comment by tommygonzaleza** [comment]
Todo bien. Esperando a que se acepte el PR
