### ISSUE TITLE
Enable a new endpoint to accept invite publicly by passing invite token

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6161]
We should allow accepting an invite by passing a token.
The endpoint is public because the invite token is enough security.
We should abstract the logic of accepting the invite to re-use it in both views (the one that accepts the invite via HTML or via API JSON).

Look at this PR for the requirements.
https://github.com/breatheco-de/apiv2/pull/1104

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1115

**Comment by jefer94** [comment]
You must use the header `Accept` to receive a response in `JSON` format
