### ISSUE TITLE
Modal que me recuerda que debo unirme a la cohort antes de poder leer el contenido

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6164]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43336635?key=569e319f0338c275d1dff4b05b4e9dc6&size=orig) 

 Cuando el usuario haga click en una lesson, project, etc. Pero sin haberse unido a la cohort:

Please join the cohort in order to the access the program content.

---
**Source URL**:
[https://dev.4geeks.com/join/cohort/541?plan=4geeks-standard](https://dev.4geeks.com/join/cohort/541?plan=4geeks-standard)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10985%3A39651&mode=design&t=28ITnaWwt06BsUz0-1
