### ISSUE TITLE
Si trato de entrar en una vista privada, y no estoy logeado, mejor mandame al checking en lugar del login

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6169]
1. Debes recordar a que vista estaba intentando entrar y una vez termine el proceso de checking o login, me mandas a donde yo queria ir.

2. Revisa la logica del checking para que no tengas ninguna logica de agregar a una cohort o algo asi, ya que deberia funcionar gracias al punto 1

**Comment by tommygonzaleza** [comment]
- [ ] Debes enviarlo al checkout especificando el plan que esta en la variable de entorno, en el caso de produccion para 4geeks.com el plan suele ser 4geeks-standard. Asi debe verse: `https://4geeks.com/checkout?plan=4geeks-standard`
