### ISSUE TITLE
Layout de projectos de alumnos malo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6172]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43356716?key=e9c78749d5cac7846eed0a615b259c20&size=orig) 

 Este es el original:
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9397-577&mode=design&t=hSXKAJfO5H2rV8ky-0

---
**Source URL**:
[https://8000-4geeksacademy-websitev2-x15u2jvrtyu.ws-us105.gitpod.io/us/landing/full-stack-programs](https://8000-4geeksacademy-websitev2-x15u2jvrtyu.ws-us105.gitpod.io/us/landing/full-stack-programs)

**Comment by alesanchezr** [comment]
- [ ] EN movil, los puntios estan demasiado separados hacia abajo.
- [ ] Tambien se meten debajo de la iamgen y por eso no funcionar.

**Comment by tommygonzaleza** [comment]
- [ ] En movil, todas las imagenes deben partir desde el mismo punto arriba

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1807
