### ISSUE TITLE
Tener posibilidad de agregar mas contenido y video sobre la locacion

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6173]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43358508?key=053f9da201a1f46cafe7ab7e886f0f72&size=orig) 

 Estoy esperado que gustavo nos pase un draft de que tipo de contenido quisiera desplegar sobre la locacion, pareciera que una columna de texto a la izq y un video a la derecha.

---
**Source URL**:
[https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami](https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami)

**Comment by alesanchezr** [comment]
Aqui esta el video y texto que se quiere

![image (8)](https://github.com/breatheco-de/breatheco-de/assets/426452/032924f6-997f-4079-b988-4283afd95757)

**Comment by ali5uarez5** [comment]
Esto puede ser un two columns? https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9447%3A6643&mode=design&t=anFB1qGkwBj2r6SP-1

**Comment by G-code7** [comment]
Se ha agregado el componente entre esas dos secciones, pero no me encanta como queda allí, 
entiendo que un video por locación donde hable un poco de 4geeks podría ayudar a naturalizar la marca  y que pueda contribuir a  la conversión. 

solo creo que se podría añadir de otra forma.
