### ISSUE TITLE
Rediseño de pagina de campus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6177]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9504%3A12638&mode=design&t=cWXPCLadXTSjsteA-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9504%3A12638&mode=design&t=cWXPCLadXTSjsteA-1

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/6198
