### ISSUE TITLE
Articulos que no deberian estar en 4geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6192]
- [New York Coding Bootcamp](https://4geeks.com/lesson/new-york-coding-bootcamp) es de la academia latam y categoria blog-us.
- [Bootcamp Data Science Toronto](https://4geeks.com/lesson/bootcamp-data-science-toronto)

**Comment by tommygonzaleza** [comment]
Siguen apareciendo estos links en 4geeks.com

**Comment by ArielCalisaya** [comment]
Este cambio estaba en la rama `development`, ya fue movido a un PR directo a Main
