### ISSUE TITLE
Bugs on landing tech coalition design

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6195]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43432001?key=1865f61a1a0169ac52afc43665abfe28&size=orig) 

 Actualizar este componente que deberia usar two column right.

---
**Source URL**:
[https://landings.4geeksacademy.com/us/landing/miami-tech-talent-coalition](https://landings.4geeksacademy.com/us/landing/miami-tech-talent-coalition)

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/50710a0d-438a-4be3-97b6-9f424f583319)

**Comment by ali5uarez5** [comment]
Revisar el componente Why 4Geeks, hay una versión actualizada. Además, ajustar los márgenes.

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/bd41f392-0147-4b2b-9bb4-0ca51156395c)


Ajustar margen

**Comment by G-code7** [comment]
- [ ]  arreglar la distribución de /us/landing/miami-tech-talent-coalition

se puede mejorar la versión que actualmente tenemos.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1845

**Comment by G-code7** [comment]
actualizado
