### ISSUE TITLE
Rediseñar Landing de locations

### ISSUE THREAD

**Issue by ali5uarez5** [breatheco-de/breatheco-de#6198]
Cambiar landing de locations actual: https://4geeksacademy.com/us/coding-campus/coding-bootcamp-argentina-buenos-aires

Por la landing que  se comparte en este link: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9504%3A12638&mode=design&t=C4nFN0eg1u2CYnCu-1

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1877

**Comment by tommygonzaleza** [comment]
- [ ] Debes modificar el componente que utiliza el slider de react slick para que pueda ser utilizado tanto aqui como en la otra vista que se usa

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1886             ->  FUNCIONANDO
