### ISSUE TITLE
Modificar grid container with image

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6199]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43451299?key=742f5cdbb3977936d77664451faddff4&size=orig) 

- [ ] Modificar componente para que opcionalmente tenga layout horizontal de una sola fila. 

El diseño está aquí: 
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9504%3A12638&mode=design&t=C4nFN0eg1u2CYnCu-1

---
**Source URL**:
[https://4geeksacademy.com/us/coding-campus/coding-bootcamp-argentina-buenos-aires](https://4geeksacademy.com/us/coding-campus/coding-bootcamp-argentina-buenos-aires)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1904

**Comment by tommygonzaleza** [comment]
Aceptar PR
