### ISSUE TITLE
No se pueden entregar proyectos de una cohorte anterior

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6203]
### Bug description

![Screenshot 2023-10-10 at 13 19 45](https://github.com/breatheco-de/breatheco-de/assets/410890/cc67691a-90bb-4db7-bb12-1f1aa158595a)

### Steps to reproduce

He ido a las entregas de un estudiante, le he dado a "Deliver"

**Comment by alesanchezr** [comment]
Pero el metodo `deliver` del api no es para entregar un projecto, es para obtener el delivery URL, te refieres a que no te aparece la modal con el delivery URL?

Por otro lado no logro replicarlo. [He ido con tu token al Madrid PT 24 y me ha salido la modal de delivery.](https://www.awesomescreenshot.com/image/43474987?key=6d50f865cc669e7b977ce09fb7f96d58)

**Comment by marcogonzalo** [comment]
Pasado por mensajería un video mostrando el problema
