### ISSUE TITLE
Refrescamiento de landing de geekpal y geekforce

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6204]
- [Aqui encuentras el diseño de geekpal](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7489-12061&mode=design&t=cRnIN4ZUGxEeLJ3l-0)
- [Aqui encuentras el diseño de geekforce](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7497-13028&mode=design&t=irCMs2Cw27Y5TaL5-0)

![Screenshot 2023-10-10 at 9 43 25 AM](https://github.com/breatheco-de/breatheco-de/assets/426452/b3ba57b1-02db-47f5-9928-c9fe47d51851)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1816

**Comment by alesanchezr** [comment]
falta resolver conflictos

**Comment by tommygonzaleza** [comment]
- [ ] Todas las imagenes (Menos los logos de las empresas) estan de baja calidad

**Comment by tommygonzaleza** [comment]
- [ ] Todavia hay imagenes de baja calidad

**Comment by kelvinruizdevel** [comment]
Nuevo PR 

https://github.com/4GeeksAcademy/website-v2/pull/1851

**Comment by tommygonzaleza** [comment]
Esperando a que se acepte el PR
