### ISSUE TITLE
Error en breathecode activity: Unconverted Data Remains

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6205]
ValueError: unconverted data remains: T19:24:55.096000+00:00

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43483018?key=39d3926f5f0f85293a76d4bda8333e48&size=orig) 

---
**Source URL**:
[https://dashboard.heroku.com/apps/breathecode/logs](https://dashboard.heroku.com/apps/breathecode/logs)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1122

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1123

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1124

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1127
