### ISSUE TITLE
Nueva seccion de press

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6206]
https://4geeksacademy.com/us/press

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7347-11707&mode=design&t=cRnIN4ZUGxEeLJ3l-0

![News](https://github.com/breatheco-de/breatheco-de/assets/426452/f1e47e5c-9637-4028-9e77-60437b91cef5)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1830

**Comment by tommygonzaleza** [comment]
- [ ] Solucionar conflicto
- [ ] Agregar padding en los lados de las tarjetas de news en mobile

**Comment by tommygonzaleza** [comment]
Aceptar PR, esta bien lo que hizo
