### ISSUE TITLE
No se estan respetando los margenes en job-guarantee

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6209]
- [ ] Ni el header principal ni la seccion de `Why are we offering...` respetan los margenes.
- [ ] El boton de apply en `Why are we offering` no lleva a ningun lado.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43504926?key=ee0903b076772400f857524a1e4ebb8d&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/job-guarantee#top](https://4geeksacademy.com/us/job-guarantee#top)

**Comment by andresmedtr** [comment]
It's not solved yet

**Comment by Khrisefzm** [comment]
New PR: https://github.com/4GeeksAcademy/website-v2/pull/1944

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1944
