### ISSUE TITLE
Bug -  escuchalo de nuestros alumnos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6217]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43526269?key=9f12b835e36111f8d75557da096e2f6f&size=orig) 

 El componente sigue dando problemas, ya no se corta abajo pero la caja se deforma. 

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/aprende-a-programar-colombia](https://landings.4geeksacademy.com/es/landing/aprende-a-programar-colombia)

**Comment by ali5uarez5** [comment]
Este es el componente: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9612%3A11567&mode=design&t=9oIgTWZzEDG2hmHe-1

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1815
