### ISSUE TITLE
Descripcion y un Agregar CTA "Unete a la academia"

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6219]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43526738?key=70c7b94c93b15c51865f5179a55ad5cf&size=orig) 

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/aprende-a-programar-ve](https://landings.4geeksacademy.com/es/landing/aprende-a-programar-ve)

**Comment by G-code7** [comment]
Acá te dejo el link del PR
https://github.com/4GeeksAcademy/website-v2/pull/1795

**Comment by G-code7** [comment]
Agregar titulos relacionados a los videos contactar con la persona del video para saber donde está trabajando ahorita. 
revisar las otras paginas para ver si se pueden aplicar estos cambios. 

- [ ] listo

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1801
