### ISSUE TITLE
Actualizar componente

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6221]
Esto deberia ser un two_column_right sin shadow

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43526902?key=935cf847869a96c4fca4aff748975a14&size=orig) 

 La referencia es esta: 

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8134%3A3906&mode=design&t=OjIQlHThfPIvEWRP-1

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera](https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1836

**Comment by tommygonzaleza** [comment]
Esperando a que se acepte el PR
