### ISSUE TITLE
Este componente no está hecho en el diseño

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6222]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43526933?key=161e414d1941a194ec4dd0c58288bb52&size=orig) 

 Se puede hacer en un two columns y agregar CTA

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera](https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera)

**Comment by kelvinruizdevel** [comment]
CTA no se hara
