### ISSUE TITLE
Se esta mostrando para adquirir el curso de JS aunque ya lo adquirio

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6223]
Para validar quizas lo mejor es comparar el syllabus del marketing course (El card que se muestra abajo como oferta) con el syllabus de las cohorts a las que pertenece el estudiante (Las obtienes ya en un endpoint)

<img width="1103" alt="Screenshot 2023-10-12 at 2 30 23 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/40b0a425-89a1-446d-a98b-932728575a27">

**Comment by ArielCalisaya** [comment]
Ya ha sido arreglado, anteriormente
