### ISSUE TITLE
Desplegar titulo, descripcion e icono de service items en vista de checkin

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6225]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/878fb885-5317-4636-9302-c9b6fee3f8d0)

---
**Source URL**:
[https://4geeks.com/checkout?plan=4geeks-standard&plan_id=p-0-trial](https://4geeks.com/checkout?plan=4geeks-standard&plan_id=p-0-trial)

**Comment by ArielCalisaya** [comment]
Cambios actualmente aplicados

**Comment by tommygonzaleza** [comment]
- Falta mostrarse el icono (Lo obtienes del service) y el title (Lo obtienes del service item feature, que es donde estan las traducicones)

**Comment by tommygonzaleza** [comment]
Falta mostrarse el icono (Lo obtienes del service) y el title (Lo obtienes del service item feature, que es donde estan las traducciones)
![Screenshot 2024-01-23 at 2 26 12 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/3f4548a6-971e-45a0-ae11-68b7a06b0d81)

**Comment by tommygonzaleza** [comment]
- [ ] El icono debe tener un max-width:
![Screenshot 2024-01-25 at 4 39 48 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/85245e26-2e7d-468a-babe-306ecc3a27df)
- [ ] Sigue sin mostrarlo en development, no se si lo agregaste en otro PR
![Uploading Screenshot 2024-01-25 at 4.42.11 PM.png…]()

**Comment by tommygonzaleza** [comment]
Falta la descripcion
