### ISSUE TITLE
Separar logicas de redireccion vs onclick en el componente button

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6226]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43533142?key=0870e12a8e8e3d3272688a97ff733de2&size=orig) 

 - [ ] Los onclick se comporant como el tipico onclick en react.
- [ ] Si el boton tiene seteada la propiedad "to" entonces el onclick no se usa, sino que mas bien redirigimos al usuario al URL que salga alli. 
- [ ] Si el URL al que vamos a redirigir es un hash entonces el boton no va mostrar animacion de loading.
- [ ] Si el URL al que vamos a redirigi NO ES UN HASH entonces mostramos la animacion de loading. Esto se hace para calmar las anciedades del usuario si la redireccion toma mucho tiempo.

---
**Source URL**:
[https://breatheco-de.github.io/app/?path=/story/components-button--default&globals=locale:en](https://breatheco-de.github.io/app/?path=/story/components-button--default&globals=locale:en)

**Comment by tommygonzaleza** [comment]
Se esta haciendo demasiadas veces el request para chequear consumibles y planes. Vamos a ponerle para que espere un segundo luego de hacer cada request hasta que obtenga los consumibles
<img width="1470" alt="Screenshot 2023-11-07 at 4 10 34 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/b57a09d5-3b18-4429-bb32-c17d4523abdc">
