### ISSUE TITLE
Bug seccion starting soon

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6230]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43535781?key=397d90e394ba969f6df593cc77f37a74&size=orig) 

 Actualmente no se puede navegar por los items desde PC. Vamos a hacer q se muevan lentamente y que puedas hacer drag&drop para moverte a la derecha.

---
**Source URL**:
[https://4geeks.com/workshops](https://4geeks.com/workshops)

**Comment by tommygonzaleza** [comment]
No me funciona el grab to scroll

**Comment by tommygonzaleza** [comment]
Ya funciona pero se mueve muy rapido y la interaccion no es agradable, hazla un poco mas lenta
