### ISSUE TITLE
Correccion de bugs en el formulario de los landings

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6232]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43538345?key=054b6e0782e22e9f2a6fb1bb7929defb&size=orig) 

 En este landing de colombia hay 3 errors que empezaron a existir pero antes no era asi, debe habar algun problema pequeño que hace que no esten asignandose bien las propiedades del componente <LeadForm>

- [ ] No deberia mostrarse la privasidad
- [ ] En el caso de que se mostrara, deberia entonces ser obligatorio hacerle check.
- [ ] Si hay un solo programa en del dropdown para seleccionar programa, entonces no es necesario mostrarlo.

---
**Source URL**:
[https://4geeksacademy.com/es/landing/bootcamp-colombia](https://4geeksacademy.com/es/landing/bootcamp-colombia)

**Comment by tommygonzaleza** [comment]
No se logra ver bien el formulario en /es/landing/becas-ticjob-espana:
![Screenshot 2023-11-07 at 11 08 38 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/5be0502a-f7ba-43bf-8cdc-0b9dcd4cd18a)
