### ISSUE TITLE
Esta mostrando que no tiene acceso a esa cohort aunque si deberia

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6236]
Esta mostrando que no tiene acceso a esa cohort aunque tiene una subscripcion cuyo cohort set incluye esa cohort

<img width="1470" alt="Screenshot 2023-10-12 at 10 07 43 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/bdd2c2c1-928f-4c0a-ab18-af6b3fdfe5ed">

**Comment by ArielCalisaya** [comment]
Ya ha sido arreglado y esta aplicado en producción
