### ISSUE TITLE
Mejorar vista para unirse a una cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6239]
Actualmente la vista se ve como en al foto de abajo, deberiamos hacer mas visible el boton de unirse a la cohort, ahora puede pasar desapercibido

<img width="1470" alt="Screenshot 2023-10-12 at 11 27 23 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/cd2f1d30-bd0c-4c14-940c-5e61bee5d0e6">

**Comment by ali5uarez5** [comment]
Hacer un header que empuje el contenido hacia abajo, el texto deberia ser parecido a: 


Join 2323 people taking this course right now
You are reviewing this cohort dashboard on "preview mode", in order to start learning and interactive with the materials please join the cohort.

Usar el icono de cada curso.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11638%3A42467&mode=design&t=9QH9E5ubzyCGNhwV-1

**Comment by tommygonzaleza** [comment]
Vamos a hacer mas grande el cuadro azul, le hace falta tambien padding con respecto al contenido del cuadro

No se ve como en el diseño:

Asi se ve en tu PR:
<img width="1453" alt="Screenshot 2023-10-31 at 3 24 01 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/1fdc0bb7-ce75-44d3-a52e-4e2f835eaa32">

Asi deberia verse:
<img width="920" alt="Screenshot 2023-10-31 at 3 25 29 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/6b028653-8a13-4c53-b927-05f728b7372f">

**Comment by tommygonzaleza** [comment]
Mueve el widget con la informacion de la cohort para abajo. Debe verse asi:
<img width="920" alt="Screenshot 2023-10-31 at 4 27 56 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/08f1e903-97ac-4230-8027-fb203581dfc6">
