### ISSUE TITLE
El contenido de markdown debería estar un poco mas cerca de la caja interactiva

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6260]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43562652?key=f4198d285bc8c2ea3cf89aa77e86353c&size=orig) 

---
**Source URL**:
[https://4geeks.com/syllabus/fake-ml-cohort/practice/python-beginner-exercises](https://4geeks.com/syllabus/fake-ml-cohort/practice/python-beginner-exercises)

**Comment by ArielCalisaya** [comment]
Estos cambios ya han sido aplicados
