### ISSUE TITLE
Texto muy grande en los badges del website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6263]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43604757?key=7aa1c6114032631799717c031011912b&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack?utm_source=fb&utm_medium=ppc&utm_campaign=23857920622670770&utm_content=23857921152130770](https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack?utm_source=fb&utm_medium=ppc&utm_campaign=23857920622670770&utm_content=23857921152130770)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1819

**Comment by tommygonzaleza** [comment]
Esta bien, falta aceptar el PR
