### ISSUE TITLE
Mejor manejo de errores en marketing.tasks.persist_leads

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6266]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43627430?key=b8cfd03718869b56a9a30cc3ad71b02b&size=orig) 

---
**Source URL**:
[https://github.com/breatheco-de/apiv2/blob/main/breathecode/marketing/tasks.py#L38](https://github.com/breatheco-de/apiv2/blob/main/breathecode/marketing/tasks.py#L38)

**Comment by jefer94** [comment]
This function is unused, no have any reference in the rest of the code, it was delete, actually all developer are been using it throught of `persist_single_lead` as you can see here `breathecode/marketing/management/commands/retry_pending_leads.py`
https://github.com/breatheco-de/apiv2/pull/1132
