### ISSUE TITLE
GeoCoding API is giving 80% error rate

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6267]
We should start by logging these errors to see what is happening. Where should we log these errors? on the form_entry? maybe a new field FormEntry.geo_location_status_text

![Screenshot 2023-10-17 at 9 09 07 AM](https://github.com/breatheco-de/breatheco-de/assets/426452/ec72dbe2-6ee8-4a6b-acb2-e542709b03d8)

**Comment by jefer94** [comment]
If the issue is being caused by `save_get_geolocal` this issue should be caused by the input on the querystring
![image](https://github.com/breatheco-de/breatheco-de/assets/3018142/5d57159d-56a3-47dd-bf18-9ea1150ad643)
