### ISSUE TITLE
Permitir comprar mas consumibles en vista de acceso a mentorships

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6270]
Si no te quedan consumibles e intentas acceder a un workshop o mentoria, te aparecera una vista que te dice que no puedes acceder por no tener suficientes creditos (Consumibles), se debe agregar un boton sencillo que diga `Get more consumables` y te redireccione a renovar el plan o a adquirir consumibles de forma individual (de no poder renover el plan). O tambien se debe mostrar arriba a la izquierda un link de back to dashboard

## Caso 1: Renovar el plan

Si el usuario tiene un plan que incluye el mentorship service de la mentoria en el mentorship service set del plan, y ademas este plan tiene un plan offer disponible (En el que este plan es el original_plan), entonces, al apretar el boton, debes redireccionarlo a `https://4geeks.com/checkout?plan=<planoffer.suggested_plan>`. Tambien se debe agregar otro boton (Con estilo el estilo secundario) que diga `Go back to dashboard` y te redireccione al dashboard.

## Caso 2: Adquirir consumibles de forma individual

Si el usuario no tiene un plan que tenga un planoffer en el que este plan sea el original_plan y tenga un suggested_plan disponible, entonces quiere decir que el ya tiene el plan pago y que se consumio todos los consumibles de ese plan. En este caso lo vamos a redireccionar a la vista de checkout de consumibles, especificando el mentorship service set del que va a comprar mas consumibles. El mentorship service set lo obtienes de alguno de los planes que incluya el mentorship service de la mentoria en su mentorship service set. Lo debes redireccionar a: `https://4geeks.com/checkout?mentorship_service_set=geekpal-1-1-javascript`

---

Esto lo puedes hacer modificando en el decorador de has_permission, donde se esta renderizando este mensaje, para que en vez de renderizar solo el mensaje renderice un template de html que tu debes crear

![Screenshot 2023-10-17 at 9 51 35 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/efa9c6d5-d3db-4ffc-94c8-54fd53ffa94b)

**Comment by alesanchezr** [comment]
Que van a decir los botones? Especificalo en el issue.
Tambien creo que deberia una opcion de "back to dashboard" o algo asi que simplemente te regrese a tu dashboard, esa opcion con estilos de boton secundarios

**Comment by tommygonzaleza** [comment]
- [ ] Falta validacion para planfinancing, debes hacer lo mismo que con los consumibles

**Comment by jefer94** [comment]
Completa los tests relacionado a este PR https://github.com/breatheco-de/apiv2/pull/1232

**Comment by tommygonzaleza** [comment]
No me esta mostrando ninguna de las opciones para comprar
![Screenshot 2024-01-29 at 4 02 19 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/fb0b6316-874b-4f10-be4c-db0c6afd0a5e)

**Comment by tommygonzaleza** [comment]
- [ ] No esta funcionando para los eventos, en el caso de los eventos no se pasa el event_type a traves del querystring y menos como service_slug. Este es el link de la vista para unirte a los eventos: https://github.com/breatheco-de/apiv2/blob/ca206ab42b521ba8a39756d95ff16f539092fdd3/breathecode/events/views.py#L647
- [ ] Puedes acceder a los mentorship_service_sets de la persona directamente en el subscription o plan financing, sin necesidad de acceder al plan
- [ ] Debes asegurarte tambien que el no tenga ninguna subcripcion o planfinancing con el mismo plan recomendado en el planoffer, de haberlo adquirido, entonces tambien debes enviarlo a comprar mas consumibles de manera individual. Valida por el status, solo si no esta `ACTIVE`

**Comment by tommygonzaleza** [comment]
- [ ] Esta mostrando que no tiene consumibles cuando el usuario si tiene:
![Screenshot 2024-02-01 at 3 05 29 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/49c0e6ed-ba86-411a-a528-23ee76656f2a)
![Screenshot 2024-02-01 at 3 06 27 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/a5588963-bba8-4a8f-ac87-f3b3cb43bc3d)
- [ ] Por otro lado, lo esta mandando a comprar mas consumibles individuales en vez de hacer upgrade a su plan

**Comment by tommygonzaleza** [comment]
- [ ] No tomamos en cuenta el caso de que un usuario no saas intente acceder a una mentoria saas, en este caso deberiamos mostrar un mensaje que diga "You must get a plan in order to access this mentorship"
