### ISSUE TITLE
with4geeks component bug

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6280]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/4ef3f151-a586-40c4-bb9c-3920cd58b4d1)

las imagenes se superponen a los logos en la versión de desktop. 

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/61a7f43f-0776-4341-8f68-ed163582fd95)
y a partir de un width de 767px  se muestra de esta forma. 

### Steps to reproduce

En la vistas de Tlf se muestra de forma desproporcionada las imágenes de los videos.
también en la versión de pc las imágenes se superponen a los logos. 

### Expected behavior

creo que a partir de 767px podríamos hacerlo un slide. 
para que se muestre uno a la vez y vaya mostrando un testimonial para que esas versiones no se hagan tan larga la pag.

**Comment by kelvinruizdev** [comment]
Si bro, vi ese bug, ya lo solucione en un Pull Request

**Comment by kelvinruizdev** [comment]
Puedes echarle un vistazo en un PR que se llama corrección-image-video
