### ISSUE TITLE
Dropdown para filtrar upcoming dates no esta funcionando

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6283]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43635439?key=745d9a0369ccfad3e53458edfd6d937e&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer?lang=en](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer?lang=en)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1856

**Comment by tommygonzaleza** [comment]
Parece funcionar bien con los datos de prueba, Aceptar PR y probar en produccion
