### ISSUE TITLE
Revisar secciones del home de 4geeksacademy

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6289]
Debes revisar cada una de las secciones y asegurarte de que se vea ordenado en todos los tamaños. Para esto debes asegurarte que los componentes que lo requieran tengan un max-width de 1366px y que les hace falta como el que se ve ahora, esten centrados
![Screenshot 2023-10-17 at 4 30 17 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/2b9c332d-deb7-473d-a5db-a3582b8a4b88)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1817
