### ISSUE TITLE
El servicio de mkt courses esta dando 500

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6298]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/0b185792-adf8-48f5-99d5-d95fa4dd3823)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1136

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1142
