### ISSUE TITLE
3 articulos semanales a publicar y 3 requerimientos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6301]

**Comment by G-code7** [comment]
https://admin.4geeks.com/media/asset/full-stack-developer-interview-questions

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/blog/pull/71 
el articulo de este requerimiento esta en optimización.

**Comment by alesanchezr** [comment]
- Para interview questions puse comentarios en el admin.
- El de desarrollo de software es una mierda, borralo, es mejor pedirle otro aritculo al escritor y dar este como "aceptado" para que no se arreche.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/blog/pulls 
- tenemos dos propuestas de articulos ya evaluados por Anik y para el 3er articulo de esta semana se pretende optimizar uno que esta en borradores.
