### ISSUE TITLE
Mejoras responsive a componente de 4GeeksVSOthers

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6303]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43659533?key=b7d99e6eb57efb6ae3d7dcd573a5ccc9&size=orig)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1821

**Comment by tommygonzaleza** [comment]
- [ ] Poner el width del cuadro de adentro al 100%
- [ ] La flecha de la derecha debe apuntar hacia abajo cuando se abre
