### ISSUE TITLE
Corregir landings de españa

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6304]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43661201?key=0c4529d4ee883a626ff0e65629d5b82c&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/landings](https://4geeksacademy.com/landings)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1810
