### ISSUE TITLE
Cambiar la vista de "get help from rigo" que sale por defecto

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6306]
En lugar de esta: [Screenshot 2023-10-18 at 1 32 51 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/63391db4-8092-4bf8-ae4f-2bd6d556c594)
Deberia ser esta: [Screenshot 2023-10-18 at 1 32 36 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/d0ca4ee2-51e2-4ced-90b5-b82a197821c0)

**Comment by Charlytoc** [comment]
- [ ] If you already selected a purpose it must be pre-selected in the dropdown instead of opening the templates
