### ISSUE TITLE
Learnpack last changes

### ISSUE THREAD

**Issue by Charlytoc** [breatheco-de/breatheco-de#6308]
- [x] Socket.on("ask") (It is ) https://github.com/learnpack/coding-ide/blob/learnpack/src/js/home.js#L243
- [x] Socket.on("reload") (This makes a reload in the frontend) https://github.com/learnpack/coding-ide/blob/8aada24d442d6419565f9283ebde9300fd78e2de/src/js/home.js#L255
- [x] Socket.on("ope_window") to open a link instead of the anchor. You can select all the anchors and pass an event listener for each one. https://github.com/learnpack/coding-ide/blob/8aada24d442d6419565f9283ebde9300fd78e2de/src/js/home.js#L334. I need to check if the open_window function works for our use case
- [x] Feedback button styling: If fails, all the colors inside must be white: the svg, border and color. Also, it needs to have exactly the same height as the other buttons
- [x] Save in a hash string the last exercise visited to avoid returning at the beginning when refreshing
- [x] Mark exercises as completed to show the user him advances

**Comment by JParedesArtica** [comment]
Las tareas ya fueron realizadas
