### ISSUE TITLE
Pagina del Programa de datascience esta caida

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6309]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43664601?key=6bb911b8569eae7d9cb6ecf53c1d78c3&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/coding-bootcamps/datascience-machine-learning](https://4geeksacademy.com/us/coding-bootcamps/datascience-machine-learning)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1802
