### ISSUE TITLE
Recopilar media relevante para quienes quieran hablar de 4geeks

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6312]
La idea es crear un landing con descargables de imagenes para que si otras personas quieren hablar de 4geeks.com, puedan encontrar imagenes del equipo, logos, iconos, etc para agregarlos en su articulo.

Tu tarea es recopilar todas estas imagenes que te parezcan relevantes y agregarlas en este issue

**Comment by ali5uarez5** [comment]
[4Geeks_logos.zip](https://github.com/breatheco-de/breatheco-de/files/13054887/4Geeks_logos.zip)
Logos en svg

**Comment by ali5uarez5** [comment]
[Lato.zip](https://github.com/breatheco-de/breatheco-de/files/13056796/Lato.zip)
fonts

**Comment by ali5uarez5** [comment]
[BrandBook_compressed.pdf](https://github.com/breatheco-de/breatheco-de/files/13057068/BrandBook_compressed.pdf)
brandbook

**Comment by alesanchezr** [comment]
Vamos a crear un figma publico para la gente.

**Comment by ali5uarez5** [comment]
Comencé a trabajar en este file

https://www.figma.com/file/KKpSTS8RnHIk6VfcsddZzZ/4Geeks-Media-Kit?type=design&node-id=1%3A6787&mode=design&t=Bj3RvLDZV8pKrDu2-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/bCFnyXv8xazLofCUkXYeAb/BrandBook-2023?type=design&node-id=117%3A0&mode=design&t=n39Qew2PgkSBrxzF-1

**Comment by tommygonzaleza** [comment]
Te va a enviar al brandbook
