### ISSUE TITLE
Crear articulo/cluster de que-es-datas-cience

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6316]
- [ ] Este articulo es un cluster, tiene que tener 2500+ caracteres
- [ ] Mencionar a toda latam y tambien una sección sobre chile, otra sobre mexico, otra sobre colombia, otra sobre españa.

**Comment by G-code7** [comment]
Esperando El feedback de Anik con los requisitos que le envié

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/blog/pull/72
