### ISSUE TITLE
Dominio de los sitempas no hace match con el del whitelabel

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6331]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43716807?key=1c825f027fe4792ec1377e16e0ff213f&size=orig) 

 Deberias agarrar segun la variable de env?

**Comment by ArielCalisaya** [comment]
It depends on the environment variable `DOMAIN_NAME`

**Comment by tommygonzaleza** [comment]
@alesanchezr

**Comment by alesanchezr** [comment]
I closed it because that particular whitelabel deployment is not going to be used. But also, because its already handled by the `DOMAIN_NAME` env variable
