### ISSUE TITLE
Revision exahustiva de 4GeeksAcademy para bugs de UI/UX y mejoras

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6338]

**Comment by ali5uarez5** [comment]
Plan de mejoras para las landings: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9926%3A12324&mode=design&t=pnLIYKJaHDWmsIEz-1

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/b94ec83b-7287-4bbf-9240-eaeefcaafad7)
La tipografia del H1 debería ser "Archivo"
