### ISSUE TITLE
Cambios en el contenido de signup

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6339]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43720963?key=1bd62055d02130af7bafdc7c7951c3ea&size=orig) 

 - [ ] En lugar de mostrar el plan por defecto vamos a mostrar es la version "premium" de ese plan.
- [ ] El titulo y descripcion se va a quedar hard-coded.
- [ ] Los items seran los del plan premium, no el standard (el que sea recomendado)
- [ ] Poner icono y tooltip de mas informacion al lado de cada item.
---
**Source URL**:
[https://4geeks.com/checkout](https://4geeks.com/checkout)

**Comment by tommygonzaleza** [comment]
- [ ] La informacion que se muestra a la derecha debe ser la del plan que el usuario va a adquirir

**Comment by tommygonzaleza** [comment]
- [ ] Pon este link donde dice Read the science behind it: https://4geeksacademy.notion.site/4geeksacademy/Mastering-Technical-Knowledge-984d2df394c44aedb05987311ccfcf06
- [ ] Haz el link visible (Que tenga el underline fijo)
