### ISSUE TITLE
En el YML de los landings, permitir colocarle width y height al player del video

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6341]
Puedo poner solo height (y el width seria 100%) o ambos. No puedo poner solo with, daria error (validar).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43722067?key=f16b0278aec9c9c03864e3c9401e37d4&size=orig) 

 Fijate como el video se ve en modo "portrait" porque le reduje el width.

---
**Source URL**:
[https://website-v2-git-fork-g-code7-two-columns-landings-geeksacademy.vercel.app/es/landing/curso-de-programacion-mexico](https://website-v2-git-fork-g-code7-two-columns-landings-geeksacademy.vercel.app/es/landing/curso-de-programacion-mexico)

**Comment by tommygonzaleza** [comment]
Agregar ambas propiedades en los YMLs de todos los landings, luego en el [reactplayer](https://github.com/4GeeksAcademy/website-v2/blob/8d92fd017ddf3874e0f20d4a93988938d5aa0385/src/components/TwoColumn/index.js#L29), se debe usar el width o height que se esta definiendo en el YML y de no tener el YML, debe usar los que ya tiene por defecto

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1961

**Comment by tommygonzaleza** [comment]
- [ ] Quita los console.log() que no se estan utilizando.
- [ ] No deberias reemplazar las propiedades de height y width que creo que se usan en otro lugar

**Comment by tommygonzaleza** [comment]
- [ ] Se le ve un poco de borde blanco al video, hazla un poco mas pequeña hasta que no se vea
![Screenshot 2024-02-27 at 2 23 45 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/4b6b7e4a-777f-4232-8a17-00dca98ef665)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1977

**Comment by tommygonzaleza** [comment]
- [ ] El borde debe estar al rededor de toda la imagen

![Screenshot 2024-02-27 at 5 46 57 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/06aedf79-df06-492f-8475-1b62c59c152a)
