### ISSUE TITLE
Como deberia verse este diseño si el wideo es portrait?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6342]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43722067?key=f16b0278aec9c9c03864e3c9401e37d4&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-two-columns-landings-geeksacademy.vercel.app/es/landing/curso-de-programacion-mexico](https://website-v2-git-fork-g-code7-two-columns-landings-geeksacademy.vercel.app/es/landing/curso-de-programacion-mexico)

**Comment by ali5uarez5** [comment]
-El componente se hizo para que tuviera bullets como en el diseño
-Por qué está en azul el fondo?
-No está respetando los margenes. 

Si se respetan las proporciones la propuesta deberia ser así: 

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9447%3A6643&mode=design&t=pnLIYKJaHDWmsIEz-1
