### ISSUE TITLE
Mejoras en movile a componente de reviews en los landings

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6343]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43724053?key=b6a29cea02979d0ea4215207bdc6507c&size=orig)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1822

**Comment by tommygonzaleza** [comment]
- [ ] Agregarle el max-width al componente cuando esta en desktop
