### ISSUE TITLE
Mejoras en mobile a componente de quien contrata nuestros alumnos

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6344]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43724073?key=30ad209f248f272e195841a23b5747d0&size=orig)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1820
