### ISSUE TITLE
How it works? - coding bootcamp colombia

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6346]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43740031?key=c566f7f41b6ad6d5983b4cc2a77d12c2&size=orig) 

 Agregar CTA
El titulo está en ingles y la descripción en español.

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/conding-bootcamp-colombia](https://landings.4geeksacademy.com/es/landing/conding-bootcamp-colombia)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1873

**Comment by tommygonzaleza** [comment]
- [ ] Resolver conflictos del PR
