### ISSUE TITLE
Bugs Landing bootcamp-colomboa-jg

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6348]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43740052?key=b69a5c2221d8ed7ad900dea239c40da5&size=orig) 

 1- El componente Python y Javascritp debería ser un two columns de los nuevos, con CTA incluido
2- Hay que subir el cintilo de Job guarantee, ahí no tiene sentido, debería estar abajo del componente "domina python, js y react" , o se puede cambiar el cintillo por este componente: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7003%3A10046&mode=design&t=87IhvH0WJYmEEVcH-1
3- La sección escuchalo de nuestros alumnos sigue fallando.

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/bootcamp-colombia-jg](https://landings.4geeksacademy.com/es/landing/bootcamp-colombia-jg)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1823

**Comment by alesanchezr** [comment]
Two column de python no tiene mucha relevancia, ver #6399

**Comment by alesanchezr** [comment]
falta logos de credenciales

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1838
