### ISSUE TITLE
Bugs Landing: aprende-a-programar-ve#top

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6349]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43740097?key=f8f2b2dd01377e005eb62bf9b6febf42&size=orig) 

 La estructura debería ser: 
1-header
2-acerca del programa
3-lo que aprenderás
4- sección "todo lo hacemos con pasión..."
5- sección  "tenemos 3 años consecutivos..."
6- sección "qué hace academy tan exitoso"
7- premios
8-escúchalo de nuestros alumnos (3 columnas
9- quién contrata a nuestros alumnos
10-form

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/aprende-a-programar-ve](https://landings.4geeksacademy.com/es/landing/aprende-a-programar-ve)
 
---

Expected time: 0.5 - 1 hrs

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2015

**Comment by tommygonzaleza** [comment]
- [ ] Arregla los estilos de la seccion de "Llevamos 3 años consecutivos..." para que se vea como el diseño (Debe tomarte entre 15 a 30 minutos mas)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2015
<hrs>0.4<hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.4</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.4</hrs>
