### ISSUE TITLE
Bugs landing: alianza-tecnologia-financiera

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6351]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43740173?key=34e493178010138e4d64e2c32fa68abc&size=orig) 

 El componente: "diseñado para hacerte exitoso..." debería ser así https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8134%3A3906&mode=design&t=87IhvH0WJYmEEVcH-1

Actualizar el componente membresías por un two collumns de los nuevos, ya no usamos los logos de Geekpal t Geekforce ahí. 

---
**Source URL**:
[https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera](https://landings.4geeksacademy.com/es/landing/alianza-tecnologia-financiera)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1823
