### ISSUE TITLE
Falla en actualizacion de estados de proyectos entregados

### ISSUE THREAD

**Issue by lauramagallanes** [breatheco-de/breatheco-de#6354]

**Comment by lauramagallanes** [comment]
No se estan actualizando los estados de los proyectos entregados al ser calificados por los mentores. Al marcarlo como aprobado o rechazado, aparece el menaje de que fue correctamente calificado, pero no se actualiza el estado de la entrega.

**Comment by lauramagallanes** [comment]
Tampoco actualiza las entregas si el alumno quiere subir un repositorio diferente al de su entrega anterior

**Comment by ehiber** [comment]
Un alumno reportó lo mismo pero del lado del estudiante. 

Hola Ehiber, buenos días! Te escribo porque me está dando problemas la página de 4Geeks, no me deja marcar las tareas realizadas y no me actualiza el porcentaje del curso para ver el progreso del curso. He hablado con mis compañeros y están en la misma situación

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/6355

**Comment by tommygonzaleza** [comment]
Ya estamos solucionandolo
