### ISSUE TITLE
Aplicar ahora otras landings de miami el two_column_right

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6360]
- [ ] Landings de Miami con video Alissa
- [ ] Landings de Ecuador
- [ ] Landings de colombia
- [ ] Landings de argentina
- [ ] Venezuela
- [ ] Uruguay
- [ ] Mexico

Por favor evitar que los video tengan audio malo.

**Comment by G-code7** [comment]
Solicité los videos nuevamente en formato horizontal, me lo entregarán está semana para reemplazar los que están en formato reel

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1828

contando los two columns video, tambien arreglé cualquier cosa en las landings ya sea video o actualiza de otros componentes al nuevo two columns

**Comment by G-code7** [comment]
Ahora, voy a agregarle una seccion iconogram a las landings que se modificaron.
