### ISSUE TITLE
Error con la aprobacion de assignment

### ISSUE THREAD

**Issue by Jtoledo88** [breatheco-de/breatheco-de#6363]
### Bug description

Cuando la tarea es aprobada, la plataforma lo registra pero no lo muestra, adjunto imagen
![image](https://github.com/breatheco-de/breatheco-de/assets/32654829/b118ea3e-7c8e-469f-a1af-e7e15752750f)

### Steps to reproduce

ingresas a 4geeks.com o al admin, entras al curso a evaluar, en assignment aprueba un proyecto y este no cambia

**Comment by tommygonzaleza** [comment]
https://github.com/breatheco-de/apiv2/commit/2d72f4e43ff4cc0248cf81634cc4ef3f18141407
