### ISSUE TITLE
Actualizar redes sociales en la página   y cambiar el logo a X

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6364]
LANDING LATAM CAMBIAR RRSS: 
1- https://4geeksacademy.com/es/landing/bootcamp-colombia 
2-https://4geeksacademy.com/es/landing/bootcamp-colombia-jg 
3-https://4geeksacademy.com/es/landing/aprende-a-programar-ve 
5- https://4geeksacademy.com/es/landing/alianza-tecnologia-financiera
6-https://4geeksacademy.com/es/landing/academia-programacion 
7- https://4geeksacademy.com/es/landing/bootcamp-costa-rica 
8- https://4geeksacademy.com/es/landing/bootcamp-mexico 
9- https://4geeksacademy.com/es/landing/bootcamp-uruguay 
10- https://4geeksacademy.com/es/landing/bootcamp-ecuador-quito 
11- https://4geeksacademy.com/es/landing/alianza-hireline 

COLOCAR LAS REDES DE LATAM: 
* INSTAGRAM: [https://www.instagram.com/4geeksacademylatam/ ](https://www.instagram.com/4geeksacademylatam/)
* FACEBOOK: https://www.facebook.com/4geeksacademyve 
* X (TWITTER): https://twitter.com/4geeksacademyES 
* LINKEDIN: https://www.linkedin.com/company/79678753/admin/feed/posts/ 

LANDING ESPAÑA CAMBIAR RRSS: 
1- https://4geeksacademy.com/es/landing/becas-ticjob-espana 
2- https://4geeksacademy.com/es/landing/aprende-a-programar 
3- https://4geeksacademy.com/es/landing/curso-de-programacion 
4- https://4geeksacademy.com/es/landing/united-way-espana 
5- https://4geeksacademy.com/es/landing/becas-landing-jobs-spain 

COLOCAR LAS RRSS DE ESPAÑA: 
* INSTAGRAM: [https://www.instagram.com/4geeksacademyes/ ](https://www.instagram.com/4geeksacademyes/)
* FACEBOOK: [https://www.facebook.com/4GeeksAcademyES ](https://www.facebook.com/4GeeksAcademyES)
* LINKEDIN: [https://www.linkedin.com/school/4geeksacademyes/?viewAsMember=true ](https://www.linkedin.com/school/4geeksacademyes/?viewAsMember=true)

LANDING CHILE CAMBIAR RRSS
1- https://4geeksacademy.com/es/landing/clases-de-programacion-santiago-chile 
2- https://4geeksacademy.com/es/landing/aprende-a-programar-santiago 
3- https://4geeksacademy.com/es/landing/alianza-banco-ripley 
4- https://4geeksacademy.com/es/landing/bootcamp-de-programacion-santiago 
5- https://4geeksacademy.com/es/landing/curso-de-programacion-santiago 
6- https://4geeksacademy.com/es/landing/curso-node-js 

COLOCAR LAS RRSS DE CHILE: 
* INSTAGRAM: [https://www.instagram.com/4geeksacademycl/ ](https://www.instagram.com/4geeksacademycl/)
* FACEBOOK:[ https://www.facebook.com/4GeeksAcademyCL](https://www.facebook.com/4GeeksAcademyCL) 
* X (TWITTER): [https://twitter.com/4geeksacademycl ](https://twitter.com/4geeksacademycl)
*LINKEDIN: [https://www.linkedin.com/school/4geeks-academy-latam/posts/?feedView=all ](https://www.linkedin.com/school/4geeks-academy-latam/posts/?feedView=all)

LANDING USA CAMBIAR RRSS:
1- https://4geeksacademy.com/us/landing/clark-scholarship 
2- https://4geeksacademy.com/us/landing/full-stack-programs
3- https://4geeksacademy.com/us/landing/income-sharing-agreement 
4- https://4geeksacademy.com/us/landing/programming-bootcamp 
5- https://4geeksacademy.com/us/landing/scholarships-blacks-in-technology 
6- https://4geeksacademy.com/us/landing/no-excuses 
7- https://4geeksacademy.com/us/landing/miami-tech-talent-coalition 

COLOCAR LAS RRSS DE USA
* INSTAGRAM:[ https://www.facebook.com/4geeksacademy ](https://www.facebook.com/4geeksacademy)
* FACEBOOK: [https://www.instagram.com/4geeksacademy/ ](https://www.instagram.com/4geeksacademy/)
* X (TWITTER): [https://twitter.com/4GeeksAcademy ](https://twitter.com/4GeeksAcademy)
*LINKEDIN:[ https://www.linkedin.com/school/4geeksacademy/mycompany/verification/ ](https://www.linkedin.com/school/4geeksacademy/mycompany/verification/)

LANDING EUROPA-PORTUGAL-ALEMANIA -MANY LOCATIONS CAMBIAR RRSS: 
1- https://4geeksacademy.com/es/landing/academia-programacion 
2- https://4geeksacademy.com/es/landing/trust-the-geeks 
3- https://4geeksacademy.com/us/landing/scholarships-landing-jobs-brazil
4- https://4geeksacademy.com/us/landing/europe-learn-to-code 
5- https://4geeksacademy.com/us/landing/scholarships-landing-jobs-europe 
6- https://4geeksacademy.com/us/landing/europe-portugal-coding-course 
7- https://4geeksacademy.com/us/landing/example 
8- https://4geeksacademy.com/us/landing/europe-germany-coding-course 
9- https://4geeksacademy.com/es/landing/becas-landing-jobs-latam 
10- 

USAR LAS RRSS DE USA
* INSTAGRAM:[ https://www.facebook.com/4geeksacademy ](https://www.facebook.com/4geeksacademy)
* FACEBOOK: [https://www.instagram.com/4geeksacademy/ ](https://www.instagram.com/4geeksacademy/)
* X (TWITTER): [https://twitter.com/4GeeksAcademy ](https://twitter.com/4GeeksAcademy)
*LINKEDIN: https://www.linkedin.com/school/4geeksacademy/mycompany/verification/

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1862

**Comment by alesanchezr** [comment]
[Cambiar el enlace de redes sociales de Meetup a Eventbrite](https://github.com/breatheco-de/breatheco-de/issues/6667)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1862
.
