### ISSUE TITLE
Al terminar una sesión de mentoría, le doy a leave, y no muestra el formulario sino que me envía al login y luego ya me dice que la sesión ha acabado y no muestra el formulario

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6365]
### Bug description

me ha pasado ya dos veces esta semana que al terminar una sesión de mentoría, le doy a leave, y en lugar de llevarme al formulario de cierre, me envía al login y luego ya me dice que la sesión ha acabado. ¿Por qué podrá ser?
<img width="1323" alt="Screenshot 2023-10-24 at 13 30 19" src="https://github.com/breatheco-de/breatheco-de/assets/410890/8ed9d20f-e169-4832-8962-29b6e9224df1">

### Steps to reproduce

Tener una sesión, tal vez iniciada por el estudiante (no tengo clara esta parte), darle a leave (tal vez después del estudiante?).

**Comment by tommygonzaleza** [comment]
No logramos replicar el error, te ha vuelto ha suceder? @marcogonzalo
