### ISSUE TITLE
Error 503 al reportar attendance

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6372]
El error no da siempre, sin embargo, me dio las tres primeras veces que lo intente, y a la cuarta si logro ejecutarse el request con exito

<img width="610" alt="Screenshot 2023-10-25 at 1 10 09 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/edb7833c-38b3-419f-9248-ed9cbe481d64">

**Comment by jefer94** [comment]
This should be caused by the cache issue

**Comment by jefer94** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/3018142/545102e0-7c3e-4b3e-b13c-344ec694a74c)
