### ISSUE TITLE
La traducción de Keep your projects no se está mostrando

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6373]
### Bug description

Cuando entro a https://4geeks.com/es/docs/knowledge-base-4geeks/keep-your-projects, el contenido aparece en inglés.

Sin embargo, el documento de traducción existe: https://github.com/breatheco-de/knowledge-base/blob/main/content/keep-your-projects.es.md

### Steps to reproduce

Ira a https://4geeks.com/es/docs/knowledge-base-4geeks/keep-your-projects

**Comment by tommygonzaleza** [comment]
Hola! Ya tenemos este issue reportado en otro y ya esta semana vamos a mostrar las traducciones de este syllabus
