### ISSUE TITLE
ejemplo no se puede visualizar por fallo de fetch/API

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6374]
en esta lección al final del todo hay un ejemplo de lista de tareas en codesandbox que no funciona

https://4geeks.com/syllabus/full-stack-fake-5/read/react-hooks-explained

link al sandbox:

https://codesandbox.io/s/xenodochial-varahamihira-egh86?fontsize=14&file=/src/index.js

**Comment by arnaldoperez** [comment]
Actualizado el sandbox y los comentarios a la nueva version de la API de los todos
Se sugiere crear un seeder para que el usuario "demo" de la api todos, siempre tenga data para mostrar en el ejemplo

**Comment by arnaldoperez** [comment]
https://github.com/breatheco-de/content/pull/2264
