### ISSUE TITLE
Rediseño landing de locations

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6383]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43830828?key=3dca349c506f54230711dc4c89d6a7d5&size=orig) 

 Este rediseño ya estaba planteado, el link es este: 
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9504%3A12638&mode=design&t=pnLIYKJaHDWmsIEz-1

---
**Source URL**:
[https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami](https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami)

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/6198
