### ISSUE TITLE
Rediseño geekpal

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6384]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43830850?key=1f6bc69b7e7a838e495618bd8568d26f&size=orig) 

 Este rediseño ya estaba planteado el link es este: 
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7489%3A12061&mode=design&t=pnLIYKJaHDWmsIEz-1

---
**Source URL**:
[https://4geeksacademy.com/us/geekpal-support](https://4geeksacademy.com/us/geekpal-support)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1879

**Comment by tommygonzaleza** [comment]
- [ ] Falta aprobar el PR
