### ISSUE TITLE
Rediseño Geekforce

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6385]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43830882?key=5b87fae3e7f65908b1c39e7c636a0563&size=orig) 

 El link es este https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7497%3A13028&mode=design&t=pnLIYKJaHDWmsIEz-1

---
**Source URL**:
[https://4geeksacademy.com/us/geekforce-career-support](https://4geeksacademy.com/us/geekforce-career-support)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1876
