### ISSUE TITLE
Bugs job guarantee

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6386]
- [x] La tipografía del H1 debería ser "Archivo"
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/a177d450-08ac-4e04-b758-40714021468b)

- [x] Cambiar color de fondo por: #FAFAFA
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/a53278b7-491f-4485-bda3-0354a0a57ec2)

- [x] Debe haber mas espacio entre cada sección, en el diseño hay 100 px entre cada una, tomar eso como referencia.
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/d329cd29-7a7d-4537-adaf-e01ce6dff678)

---

Expected time: 1 - 2 hrs

**Comment by ali5uarez5** [comment]
![fixes](https://github.com/breatheco-de/breatheco-de/assets/105449728/ed1384e6-ec53-41ad-b032-1e945be56a66)
Centrar componente two colums de job guarantee

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/a177d450-08ac-4e04-b758-40714021468b)
La tipografía del H1 debería ser "Archivo"

**Comment by ali5uarez5** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/edfd4cef-dd43-405e-a346-ecaa84dba4eb)
Cambiar color de fondo por: #FAFAFA

**Comment by ali5uarez5** [comment]
Debe haber mas espacio entre cada sección, en el diseño hay 80 px entre cada una, tomar eso como referencia.
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/d329cd29-7a7d-4537-adaf-e01ce6dff678)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1986
Time: 1 hr

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
