### ISSUE TITLE
Refrescamiento Awards page

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6387]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43831156?key=a20c7c40a884568378a374fcc9cdbe56&size=orig) 

 Se podría rediseñar para que sea más parecida al rediseño de press articles?

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7347%3A11707&mode=design&t=pnLIYKJaHDWmsIEz-1

---
**Source URL**:
[https://4geeksacademy.com/us/awards](https://4geeksacademy.com/us/awards)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=10104%3A10390&mode=design&t=AM2qQ1pXKrJJTbCT-1

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1829

**Comment by tommygonzaleza** [comment]
- [ ] Cambiar imagenes que estan de muy baja calidad.

**Comment by tommygonzaleza** [comment]
El PR tiene conflictos

**Comment by tommygonzaleza** [comment]
- [ ] Cambiale el titulo a: < AWARD WINNING BOOTCAMP >
