### ISSUE TITLE
Redirects del website dejaron de funcionar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6391]
Mira esta pagina deberia redireccionar a notion:
https://4geeksacademy.com/talent

Mira aqui estan los redirects:
https://github.com/4GeeksAcademy/website-v2/blob/2a33174b030b90c94ecbfdb28832c25301db649d/src/data/additional-redirects.yml#L13

**Comment by tommygonzaleza** [comment]
Algunos URL de redirects como este, llegan a una pagina en blanco la primera vez, antes de refrescar: https://4geeksacademy.com/landing/becas-partner
