### ISSUE TITLE
Tedchnology landing

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6392]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6823-143975&mode=design&t=JFewIO8O0OuRLo1w-0

![technology landing](https://github.com/breatheco-de/breatheco-de/assets/426452/2f9b7091-7f39-4867-b42f-c317ea161edb)

**Comment by tommygonzaleza** [comment]
Assigned to Luis
