### ISSUE TITLE
Agregar opcion open_in_modal en YML de with 4Geeks

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6393]
- [x] Ahora cada testimonial de la lista de with_4geeks va a incluir una propiedad [open_in_modal](https://www.awesomescreenshot.com/web/image/thumbnail/43839477?key=570341a5f9dc92a94419aa1d27f00a96&size=orig) que va  permitir decidir se si abre una modal o no al momento de abrirlo.
- [x] El componente de reactplayer ya tiene una propiedad [WithModal](https://www.awesomescreenshot.com/image/43839505?key=7123a2ee266d57ddd0e3b8c2f0ce5e0f) para controlar eso, debemos asegurarnos que el componete iwth_4geeks haga uso de esa propiedad.
- [x] Si open_in_modal es falso entonces el video se despliega en el mismo lugar donde estaba la imagen previa con el boton de play, y con las mismas proporciones que tenia.
- [x] Por ultimo se debe poder [controlar el height ](https://www.awesomescreenshot.com/image/43839685?key=34ae4c5e18251ad5ccd806f03a5c753f) de los videos (cada uno) en el [YML del testimonio aqui](https://www.awesomescreenshot.com/image/43839723?key=0dfa6bc09e15a18e89067ef7772432b5).
- [ ]

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1849

**Comment by tommygonzaleza** [comment]
Esperando a que se acepte el PR

**Comment by tommygonzaleza** [comment]
- [ ] Al poner un video vertical, vimos que mientras agregabamos mas height, se agrega un espacio cada vez mas grande arriba y abajo
