### ISSUE TITLE
Aplicar refrescamiento de los landing de los cursos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6396]
Aqui esta el refrescamiento del rediseño: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9357%3A13716&mode=design&t=hvnS9fYXgC6qFjQz-1

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1836

**Comment by tommygonzaleza** [comment]
seo_title no puede estar comentado

**Comment by tommygonzaleza** [comment]
Esperando a que se acepte el PR
