### ISSUE TITLE
Aplicar rediseño de landing de financing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6397]
Aqui esta el diseño del landing: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7620%3A13570&mode=design&t=hvnS9fYXgC6qFjQz-1

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1854

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-11-21 at 4 33 09 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/9b99f945-add2-4ec9-9edf-3598e6d46c9b)
- [ ] Esta imagen se muestra rota
![Screenshot 2023-11-21 at 4 37 54 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/c90c36c6-02bb-45ea-bf28-67ea9bdd065a)

**Comment by tommygonzaleza** [comment]
- [ ] El titulo debe decir FINANCING en vez de FINANCIALS

**Comment by tommygonzaleza** [comment]
Solo falta aceptar el PR

**Comment by tommygonzaleza** [comment]
- [ ] Poner para que se carguen los precios por defecto, en vez de que diga que no estan disponibles

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1854

**Comment by tommygonzaleza** [comment]
- [ ] Quitar el dropdown de modalidad en el cuadro de la primera seccion. Siempre sera part time
- [ ] Al darle a search, debemos enviarlos al componente de abajo que muestra los precios del programa. Los dropdowns deben estar precargados
- [ ] Agregar el dropdown de programa en el componente de precios de abajo 
- [ ] El texto debe decir select the location and program...

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1854

**Comment by tommygonzaleza** [comment]
- <img width="1429" alt="Screenshot 2024-01-17 at 9 37 17 PM" src="https://github.com/4GeeksAcademy/website-v2/assets/56565994/8fa74f93-972a-4467-9443-49de301433f4">
- <img width="1429" alt="Screenshot 2024-01-17 at 9 41 00 PM" src="https://github.com/4GeeksAcademy/website-v2/assets/56565994/4c03180c-a89e-46af-b05b-ec13b9c92e1a">
- <img width="1429" alt="Screenshot 2024-01-17 at 9 47 13 PM" src="https://github.com/4GeeksAcademy/website-v2/assets/56565994/7ab65e30-ebd3-4f38-a5e2-76159a9903a4">
- <img width="1429" alt="Screenshot 2024-01-17 at 9 49 38 PM" src="https://github.com/4GeeksAcademy/website-v2/assets/56565994/d54f04c0-79a9-4ed6-9d23-224e519b44eb">
- <img width="1470" alt="Screenshot 2024-01-17 at 9 53 35 PM" src="https://github.com/4GeeksAcademy/website-v2/assets/56565994/28a661b4-07ba-4fb0-ae10-2f927d2a1faa">

**Comment by tommygonzaleza** [comment]
Los cambios se encuentran en esta branch: https://github.com/4GeeksAcademy/website-v2/tree/refresh-financing

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1916
