### ISSUE TITLE
Refrescar pagina de testimonials & press

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6398]
Son paginas diferentes pero similares en diseño

- [ ] https://4geeksacademy.com/us/press
- [ ] https://4geeksacademy.com/us/testimonials

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43840209?key=bbdb5e7e58df926bb919c667ae01c17e&size=orig)

**Comment by ali5uarez5** [comment]
Press articles: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7347%3A11704&mode=design&t=zcKQuX484mxkGbs3-1

**Comment by ali5uarez5** [comment]
testimonials: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=10101%3A5250&mode=design&t=zcKQuX484mxkGbs3-1
