### ISSUE TITLE
Cambios en componente de python

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6399]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43845429?key=42bf8585d49d38391a6ee1996ffe5838&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-testimonios-esp-geeksacademy.vercel.app/es/landing/bootcamp-colombia-jg](https://website-v2-git-fork-g-code7-testimonios-esp-geeksacademy.vercel.app/es/landing/bootcamp-colombia-jg)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1832


ya esta arreglado en este PR
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/ac6cb8f3-ea5d-4262-b50f-6e94d542e41d)
