### ISSUE TITLE
padding al componente two columns y un margen  para  Acerca del programa ambos en la version de tlf.

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6407]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/c170d8a0-642f-42a1-b5d4-637518096144)

aca muestro como se ven estos componentes en tlf, se podría mejorar eso. 
creo que con unos 15-20px de margin para la sección de domina python js y react
y unos 15-20px para la sección detro del two columns.

### Steps to reproduce

se ven a simple vista en la versión de tablet, a partir de 767px

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1836

**Comment by tommygonzaleza** [comment]
Esperando a que se acepte el PR
