### ISSUE TITLE
Refrescamiento de landing de testimonials

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6410]
Este es el link del figma: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=10101%3A5250&mode=design&t=zcKQuX484mxkGbs3-1

**Comment by tommygonzaleza** [comment]
Aqui estan los logos actualizados

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1863

**Comment by tommygonzaleza** [comment]
- [ ] Si tiene un source_url, entonces en vez de tener un source_text, el source_text no se debe agregar por cada alumno, sino es un valor general del componente que se va a usar en todos los cards que tengan source_url, el source_text, debe decir: `See review`
