### ISSUE TITLE
Correccion de templates de emails 

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6413]
Estos son los templates, primero tienes un pantallazo de como lo estoy recibiendo y luego como debería verse:
https://docs.google.com/document/d/1Ntcy3pqAX5YW6Hz2dj-DCMjCMRfK4FIFc6UL5yVoqEM/edit

Puedes probar con esas clases que son gratis:
`IBM Skills academy 0795`

**Comment by celes-sb** [comment]
hr: 1
(al momento)

**Comment by celes-sb** [comment]
**Screenshot**
**GenericStudentWelcomeEmail.vm**

![image](https://github.com/breatheco-de/breatheco-de/assets/121136209/ce228500-1576-4560-a23d-a67d5e77bb65)

**Comment by celes-sb** [comment]
**Screenshots**
**StudentEnrollmentConfirmation.vm & Receipt.vm**

![image](https://github.com/breatheco-de/breatheco-de/assets/121136209/c4bf8554-cda4-477e-9036-aa8b3e2411e9)

![image](https://github.com/breatheco-de/breatheco-de/assets/121136209/3d1901d8-4a4e-41c4-8682-50d06ddf3ab1)

**Comment by celes-sb** [comment]
**Screenshot**
**EmailCourseProfile.vm**

![image](https://github.com/breatheco-de/breatheco-de/assets/121136209/0a6c2ff9-5422-4880-a760-85458986ebfb)

**Comment by celes-sb** [comment]
**Screenshot**
**AbandonedCartReminder.vm**

![image](https://github.com/breatheco-de/breatheco-de/assets/121136209/f6a47503-b7ee-43ca-a31d-66959c2cf643)

**Comment by jdelabl1** [comment]
Hola Celeste, como conversamos aqui te dejo los [templates actualizados](https://docs.google.com/document/d/1Ntcy3pqAX5YW6Hz2dj-DCMjCMRfK4FIFc6UL5yVoqEM/edit?usp=sharing) en temas de texto y estructura.

Déjame saber si tienes alguón comentario.
Gracias de antemano.

**Comment by alesanchezr** [comment]
<hrs>10</hrs>

**Comment by alesanchezr** [comment]
<hrs>10</hrs>
