### ISSUE TITLE
Se esta cobrando doble consumo de aprovisionamiento a las academias al no tomar en cuenta los deleted GithubAcademyUserLog

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6418]
Si revisas el GithubAcademyUserLog para el usuario `anfetirano` vas a ver que [perteneció a dos academias por un breve momento en el tiempo, y luego fue eliminado de chile](https://www.awesomescreenshot.com/image/43938159?key=f4e254b4c61a8c18794fbb13eea2b812).

Sin enmbargo, los consumos de `anfetirano` [se le estan cobrando a chile en su factura.](https://www.awesomescreenshot.com/image/43938199?key=4bb46c787b2cb79e2cad26ec1f49e1c7).

Revisando el codigo creo que es porque la consulta no esta excluyendo a los usuarios que ya fueron eliminados de la academia, solo toma en cuenta que en algun momento fueron agregados.

Como excluir aquellos github_academy_user_logs que tambien tienen una fila con storage_action=DELETE y storage_status='SYNCHED' con una fecha mas reciente que la fila storage_action=ADD?

https://github.com/breatheco-de/apiv2/blob/9a3775e81f3d59f9fc68cbd29329ef08d66a8380/breathecode/provisioning/actions.py#L239

Esta consulta tiene un error
```py
    if github_academy_user_log is None:
        github_academy_user_log = GithubAcademyUserLog.objects.filter(
            Q(valid_until__isnull=True)
            | Q(valid_until__gte=context['limit'] - relativedelta(months=1, weeks=1)),
            created_at__lte=context['limit'],
            academy_user__username=field['Username'],
            storage_status='SYNCHED',
            storage_action='ADD').order_by('-created_at')
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1170

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1174

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/c5e9bd214b9878195e63d74bd5767467f841e351

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/d87373719d1c3fa71b79c2e24f42331d33f06674

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/e690fedeefa3187fec5d564580173bc03ac9385e

**Comment by jefer94** [comment]
`GithubAcademyUserLog` was generating with a wrong valid_until, it was fixed, but it requires you run the fixer to sanity the data

```bash
python manage.py fix_github_academy_user_logs
```
