### ISSUE TITLE
Cambiar diseño vista para unirse a una cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6426]
Debes mover el widget de la informacion de la cohort para abajo. Cambia la imagen de la señora por un video, y entre el video y la caja azul con el boton para unirse, deben ocupar el 100% del width del heading

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11638%3A42467&mode=design&t=9QH9E5ubzyCGNhwV-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11638%3A42467&mode=design&t=Nh2XaJwWc4ygy80u-1

**Comment by tommygonzaleza** [comment]
El link se expiro

**Comment by ali5uarez5** [comment]
Aqui estan las 2 propuestas:

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A47912&mode=design&t=Hpm7g8ZqIelkI2l4-1

**Comment by alesanchezr** [comment]
listo para programar.

**Comment by tommygonzaleza** [comment]
Asignado en este [issue](https://github.com/breatheco-de/breatheco-de/issues/6764)
