### ISSUE TITLE
Solucionar bugs de SEO en APP

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6427]
https://docs.google.com/document/d/1thfuEIEKVE1NO8Z9j_hziTCejaQDTNEmI8HABMqj5t8/edit#heading=h.md51pqw8bomx

**Comment by ArielCalisaya** [comment]
Documentos del [informe](https://docs.google.com/document/d/1thfuEIEKVE1NO8Z9j_hziTCejaQDTNEmI8HABMqj5t8) que no pude arreglar:

- [H1s duplicados](https://drive.google.com/file/d/1yysmb_qyBBWIWDmn5f8_XxsLCqprJyHn/view?usp=drive_link) se deben modificar los títulos de tecnología ya que a pesar de tener slug distinto (ej: `Conditions` y `conditions`) tienen el mismo titulo esto también ocurre en algunos markdown que se mencionan en el documento

- (sección 11) “Remove internal links to localhost” Menciona 4 links que apuntan a localhost, pero el articulo es una guía con relación a entornos locales:

1. https://4geeks.com/es/lesson/implementar-modelo-usando-flask-y-heroku
2. https://4geeks.com/es/lesson/implementar-modelo-usando-streamlit-y-heroku
3. https://4geeks.com/lesson/deploy-model-using-flask-and-heroku
4. https://4geeks.com/lesson/deploy-model-using-streamlit-and-heroku
