### ISSUE TITLE
Mover los componentes `Side` y el `TwoColumn` al archivo `TwoColumn.js`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6428]
Debes mover el codigo de los componentes `Side` y `TwoColumn` a un archivo `TwoColumn.js` y luego importar el componente desde el archivo `TwoColumn.js` tanto en landings, como en las vistas del website donde se utilicen

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1835

**Comment by tommygonzaleza** [comment]
Esta bien lo que hizo, falta aprobar el PR
