### ISSUE TITLE
Crear tickets para optimizar landings para dispositivos moviles with: 375+

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6432]
Tienes que crear los tickets y poner la lista en este issue, como comentario.

Enfocate en estos landings principalemnte:

- [ ] `/es/coding-bootcamps/desarrollador-full-stack`
- [ ] `/es/landing/clases-de-programacion-santiago-chile`
- [ ] `/us/index`
- [ ] `/es/landing/bootcamp-programacion`
- [ ] `/es/coding-bootcamps/curso-datascience-machine-learning`
- [ ] `/es/landing/aprende-a-programar-mexico`
- [ ] `/us/coding-bootcamps/datascience-machine-learning`
- [ ] `/es/landing/curso-de-programacion-mexico`

**Comment by G-code7** [comment]
- [x]  /es/coding-bootcamps/desarrollador-full-stack  #6464 
- [ ]  /es/landing/clases-de-programacion-santiago-chile 
- [ ]  /us/index
- [ ]  /es/landing/bootcamp-programacion
- [ ]  /es/coding-bootcamps/curso-datascience-machine-learning
- [ ]  /es/landing/aprende-a-programar-mexico
- [ ]  /us/coding-bootcamps/datascience-machine-learning
- [ ]  /es/landing/curso-de-programacion-mexico
