### ISSUE TITLE
Reducir la cantidad de texto en Python y Javascript

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6434]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43960785?key=4fc5c196d978cc568fafc738be4ebc78&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-two-columns-vid-363947-geeksacademy.vercel.app/es/landing/bootcamp-colombia-jg#top](https://website-v2-git-fork-g-code7-two-columns-vid-363947-geeksacademy.vercel.app/es/landing/bootcamp-colombia-jg#top)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1832
