### ISSUE TITLE
Crear version del logo de python sin fondo

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6436]
<img width="1256" alt="Screenshot 2023-11-01 at 11 53 56 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/fde9e1d6-3b06-4d91-947a-544a8ee6e24b">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=5164%3A17665&mode=design&t=mkN7r3DV7bcgNgIt-1
