### ISSUE TITLE
codesandbox no parece tener el comportamiento deseado

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6444]
https://4geeks.com/syllabus/full-stack-fake-5/read/context-api

al final de esta lección hay un [codesandbox](https://codesandbox.io/s/w75wq6v01k?from-embed) que renderiza una lista to-do con un botón de "+ add" que se supone que debería agregar una task nueva cada vez que se presiona pero no lo hace

**Comment by arnaldoperez** [comment]
Mudado a replit y arreglado, a la espera de aprobacion del PR

**Comment by arnaldoperez** [comment]
Hay un problema con la plataforma PlayCode, ya fue notificado a soporte y estamos a la espera de respuesta

![image](https://github.com/breatheco-de/breatheco-de/assets/19396163/5ae5ffe9-ef86-442e-b048-9f259dda6450)
