### ISSUE TITLE
Activar el HTML en las descripciones de los componentes de prismic

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6453]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/43989857?key=b6360ca9c6cac0176127d0760e95507a&size=orig) 

---
**Source URL**:
[https://4geeks.com/pricing](https://4geeks.com/pricing)

**Comment by tommygonzaleza** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/51c2d50c-6405-4f44-a612-1296a27a0d6b)
