### ISSUE TITLE
Video tag in HTML exercises is not working

### ISSUE THREAD

**Issue by Jtoledo88** [breatheco-de/breatheco-de#6456]
This video is not working, https://assets.breatheco.de/apis/video/why-pair-programming

![image (3)](https://github.com/breatheco-de/breatheco-de/assets/32654829/c89ff38d-4493-4a5d-b785-9534567e79ca)

**Comment by JParedesArtica** [comment]
El bug ya fue resuelto, el link del video fue actualizado a https://github.com/breatheco-de/assets-old/blob/bb5870b89e029884360641b544665bcb037ef437/apis/video/videos/4geeks-background.mp4?raw=true.
