### ISSUE TITLE
Create FastAPI + Vite/React boilerplate

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6459]
- [ ] Celery tasks
- [ ] Redis integrated with the celery
- [ ] The root path `/` will serve the react applications.
- [ ] The `/api` path will serve the Fast API.

## Chat APP

- [ ] Store the purpose template on the front end at the initiation of the chat.
- [ ] When the front end sends the first message, we add the message into the pre-stored prompt and build the definitive prompt.

### Django API (for postgress communication)
- [ ] Develop a GET /conversation/<id>/memory to pre-fetch. We will call this endpoint right after each answer has been given to the user. 

### Fast API
- [ ] Develop a Python function to getContext(purpose, [last_messages]). Building the context requires one or more questions because the context may vary depending on the question.

![Screenshot 2023-11-03 at 1 23 02 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/9fde62e3-efe9-4606-84b3-17fdb67eb69c)

**Comment by Charlytoc** [comment]
- [ ] https://github.com/4GeeksAcademy/react-flask-hello/blob/main/src/app.py
- [ ] You will serve the index.html or an static file. Check the implementation of the general path at the end of the file
