### ISSUE TITLE
Crear version del landing de eventos para eventos en persona

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6460]
- [ ] Se debe crear un landing para los eventos que no sean online.
- [ ] Al darle click al boton para unirse al evento debe mostrar una modal que diga: `This is an in-person event that will take place in Miami, USA at 3234 SW 144th ST. Do you still want to confirm your attendance?`, con dos opciones: `Yes, I will be there`. `No, I will not attend`

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11776%3A44251&mode=design&t=mkN7r3DV7bcgNgIt-1
