### ISSUE TITLE
El proyecto del perfil de Linkedin no se puede entregar porque pide un repo de Github

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6467]
### Bug description

![image (1)](https://github.com/breatheco-de/breatheco-de/assets/410890/f789309c-a1a3-4566-a649-cdbaff4973a1)

### Steps to reproduce

Ir al curso de Build your Tech Profile, intentar entregar el proyecto de Linkedin

### Expected behavior

Debería permitir una URL de linkedin y validarla

**Comment by alesanchezr** [comment]
listo
