### ISSUE TITLE
El webhook de eventbrite esta fallando 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6470]
El webhook de eventbrite esta fallando por lo que el evento se crea dos veces, dando error en el que tiene toda la informacion del evento

![Screenshot 2023-11-06 at 3 22 16 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/9ed46d1e-a50d-4763-b1e1-66235b4c3100)

**Comment by tommygonzaleza** [comment]
Sigue fallando a pesar de cambiar el timeout

**Comment by jefer94** [comment]
Y este endpoint no habia sido deshabilitado?

**Comment by tommygonzaleza** [comment]
Si tienes razon, ya no hace falta esto
