### ISSUE TITLE
El metodo para renovar consumibles desde el admin no esta funcionando

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6471]
El metodo renew consumables de una subscripcion no esta funcionando, si no tiene consumibles deberia generar los consumibles que incluye la subscripcion

**Comment by jefer94** [comment]
This should be caused by the cache issue

**Comment by jefer94** [comment]
Tomas removed a service, and then it removes the consumable, when he was calling renew_subscription_consumables it couldn't renew the consumables maybe because it removes the consumable or the service stock scheduler

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1185

**Comment by tommygonzaleza** [comment]
El codigo parece estar bien, tendria que probarlo para asegurarme que esta funcionando
