### ISSUE TITLE
Fix comments on the assets near to 0

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6476]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44085236?key=4938049ceceb6b28f479715848a4c370&size=orig) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset](https://admin.4geeks.com/media/asset)

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/00f6e8ed-73ce-420d-989d-474a2e3e5322)

ya se había arreglado ese issue.

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/890ffd7d-2ff1-4c1e-bd91-abf396311942)

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/f86712eb-ee57-4b13-9a26-b60e50aae3fe)

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/dc8f608d-766c-4b0c-878c-036e1fd8eaf1)

problema con este articulo 

- [ ]  resuelto

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/888a5bce-bc57-4db7-a35d-3d702813416d)
