### ISSUE TITLE
Session.locations no aparece en los landings

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6480]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44086480?key=58aa8eb0c7cfa9fe14e274a289f25b61&size=orig) 

 Estuve revisando y al parecer el objeto de session no include session.locations y eso nos esta trayendo varios problemas.

- [ ] No se esta mostrando el nro de telfono.
- [ ] El formulario esta cargando muchos campos que tal vez no deberia

Revisa este codigo a ver porque no se llena bien en el caso de los ladnings:
https://www.awesomescreenshot.com/image/44086541?key=14f2afe8afcd9a21be8f41ee90b34676

---
**Source URL**:
[https://website-v2-jyoekpn35-geeksacademy.vercel.app/es/landing/trust-the-geeks](https://website-v2-jyoekpn35-geeksacademy.vercel.app/es/landing/trust-the-geeks)

**Comment by tommygonzaleza** [comment]
El error esta en esta linea de codigo: https://github.com/4GeeksAcademy/website-v2/blob/b908cc4ae8d9ac500932ed1965efdb82b276a07f/src/templates/landing_a.js#L85 meta_info.utm_locations es un array

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1857

**Comment by tommygonzaleza** [comment]
Esta mostrando este error en el deployment
<img width="1349" alt="Screenshot 2023-11-28 at 2 32 55 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/62a1f77c-cc2a-4f21-9d55-56ce8b5d343f">

**Comment by tommygonzaleza** [comment]
<img width="1457" alt="Screenshot 2023-11-28 at 6 56 04 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/4778212d-3cf0-4e13-bbba-1e8b401f7b0d">
