### ISSUE TITLE
Add job guarentee section in landings de mexico

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6481]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/aedc359d-f6b7-42d6-a241-7237d201706f)

### Steps to reproduce

falta esta sección en estas landings

https://4geeksacademy.com/es/landing/aprende-a-programar-mexico
https://4geeksacademy.com/es/landing/bootcamp-mexico
https://4geeksacademy.com/es/landing/curso-de-programacion-mexico

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1852

**Comment by tommygonzaleza** [comment]
Falta un cambio que se pidio en el PR

**Comment by G-code7** [comment]
Cambio Listo!!!
