### ISSUE TITLE
Crear landing nuevo de pricing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6486]
[Aqui](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11711%3A35302&mode=design&t=Yavcl0rUrCR8VrMp-1) esta el diseño nuevo.

El contenido se va a agregar en el json del landing.

**Comment by tommygonzaleza** [comment]
Estamos analizando un diseño nuevo, espera por el diseño para hacer este issue

**Comment by gustavomm19** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=11877-49484&mode=design&t=uBVk1BPl36BL03Ie-0

**Comment by tommygonzaleza** [comment]
<img width="1455" alt="Screenshot 2023-11-21 at 9 30 15 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/c9b3cdfe-043c-4edd-9c86-23d0a33a96f6">
<img width="1455" alt="Screenshot 2023-11-21 at 9 31 09 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/45253b42-fa4d-409f-9df8-7d6d9ece5923">

**Comment by tommygonzaleza** [comment]
Poner `per month` en las tarjetas tanto en month como en yearly, ya que ahora se mostrara el precio del plan mensual aunque pague por año para que pueda comparar los precios mejor
