### ISSUE TITLE
Cancel subscription: undefined

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6494]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44096615?key=9750cac26124015e8be6c8971ca0217a&size=orig) 

---
**Source URL**:
[https://dev.4geeks.com/profile/subscriptions](https://dev.4geeks.com/profile/subscriptions)

**Comment by tommygonzaleza** [comment]
No me esta mostrando la subscripcion
<img width="1470" alt="Screenshot 2023-11-27 at 10 37 06 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/8515f4b4-e6b2-4287-92af-638a745b80c7">
