### ISSUE TITLE
Contactanos bug with columns 

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6497]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/382f5c11-624c-4ba4-81d1-db72271b60eb)
la pagina contactanos se ve rara. 
noté que la distibución con columns está mal. 
creo que queda mucho mejor si en vez de aplicar un valor `repeat (3, 0fr )`
utilizamos `grid-template-columns: 3fr 1fr 3fr; `

### Steps to reproduce

se ve a simple vista en la versión de desktop, **en movile me parece que está bien.** 

### Expected behavior

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/a5e78d04-1b5e-4d6a-a968-3f0cec130c98)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1859

**Comment by tommygonzaleza** [comment]
Solo falta aceptar PR
