### ISSUE TITLE
Update salaries to include latam, spain and other countries.

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6503]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44121440?key=75d02812f13b9641d1efa00116aab01a&size=orig) 

---
**Source URL**:
[https://github.com/breatheco-de/content/blob/master/src/content/lesson/intro-to-prework.md](https://github.com/breatheco-de/content/blob/master/src/content/lesson/intro-to-prework.md)

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1964
