### ISSUE TITLE
Los sitemaps se rompieron

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6505]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44147751?key=8cf2803721d09ff8c9ef25fc199c6391&size=orig) 

---
**Source URL**:
[https://app.ahrefs.com/site-audit/3643119/103/data-explorer?columns=pageRating%2Curl%2ChttpCode%2CcontentType%2Csitemap_error%2Corigin&filterId=f48bfa38e92879ef5231a3a15b2767f5&issueId=df634009-c696-4c27-9cb9-5bc37d58093f&sorting=-pageRating](https://app.ahrefs.com/site-audit/3643119/103/data-explorer?columns=pageRating%2Curl%2ChttpCode%2CcontentType%2Csitemap_error%2Corigin&filterId=f48bfa38e92879ef5231a3a15b2767f5&issueId=df634009-c696-4c27-9cb9-5bc37d58093f&sorting=-pageRating)

**Comment by tommygonzaleza** [comment]
Muestra este error en todas las paginas de los sitemaps
<img width="1403" alt="Screenshot 2023-11-14 at 4 26 44 PM" src="https://github.com/breatheco-de/breatheco-
de/assets/56565994/8b756232-cdd6-4ef0-ae3f-877b085caf47">
