### ISSUE TITLE
Replantear website de BocaCode.com utilizando los componentes de landings

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6508]
- [ ] El logo ahora sera "4Geeks Boca" y tendrá un cintillo que diga "BocaCode cohorts are now running through 4Geeks Academy".
- [ ] Quitar cualquier referencia a otras sedes.
- [ ] Quitar cualquier referencia a otros programs, el unico programa sera full-stack full-time
- [ ] Utilizar los colores de boca code.
- [ ] Intentar mantener las mismas seccione spero usando los componentes de 4GeeksAcademy

El navbar tendra las siguientes secciones:

- Programs (con un solo programa de full-stack full time).
- Financing
- Alumni
- For Companies
- Contact

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=10418%3A542&mode=design&t=wpryyrVZHdxMeyLw-1

**Comment by tommygonzaleza** [comment]
Ya no hace falta, se hizo con los componentes de bocacode en un repo nuevo
