### ISSUE TITLE
Algunos related articles estan repetidos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6510]
![Screenshot 2023-11-09 at 2 15 42 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/cf615b41-5729-405e-82f5-f5042bb97b41)

**Comment by ArielCalisaya** [comment]
Este issue parece ser un big con los filtros del endpoint y esta relacionado con [Asset repetido #6540](https://github.com/breatheco-de/breatheco-de/issues/6540)

[json relacionado](https://breathecode.herokuapp.com/v1/registry/asset?status=PUBLISHED&technologies=codespaces,gitpod)
