### ISSUE TITLE
Related content ahora sera "Read next" y tendra este diseño

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6511]
![Screenshot 2023-11-09 at 1 23 26 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/6c27f4ab-00f2-46f1-9908-9ccf7ffba7ed)

**Comment by tommygonzaleza** [comment]
Se ve repetido el asset en el que estoy.

Esto pasa cuando, estoy en un asset primero y luego me voy a otro desde los Read next, cuando estoy en el otro, el read next no cambia, por lo que muestra a los mismos
<img width="1470" alt="Screenshot 2023-11-27 at 10 34 04 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/e6429fa9-d20c-4039-8aca-eae3efd40e44">

**Comment by ArielCalisaya** [comment]
No logre encontrar ese bug en el ultimo deploy, ya existe un filtro para evitar esto

**Comment by tommygonzaleza** [comment]
Sigue sucediendo
<img width="1457" alt="Screenshot 2023-11-28 at 5 14 48 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/6303c3de-275f-43e0-9ada-82143916ba59">
