### ISSUE TITLE
Intercambiar cintillos en 20 million

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6521]
![Screenshot 2023-11-13 at 11 09 14 AM](https://github.com/breatheco-de/breatheco-de/assets/426452/d6d4a019-3d89-4f75-8a69-6473c7bf7d20)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1848

**Comment by tommygonzaleza** [comment]
Falta aceptar el PR
