### ISSUE TITLE
Buscar fotos reales y mejores de esta gente en 20million

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6522]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44216898?key=473ae5e08f1108b809cfce94f2302cc1&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/20-million](https://4geeksacademy.com/us/20-million)

**Comment by ali5uarez5** [comment]
No puedo usar las fotos del archivo, están bloqueadas.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7025%3A10646&mode=design&t=aIFyubYevfOl362g-1

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7025%3A10646&mode=design&t=OXeFL0ag1mv9m557-1

**Comment by G-code7** [comment]
tambien deje la imagen en el figma por si la quieren usar en otro lado. 

![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/758df324-3223-4b9a-b988-6aed6567e5dc)
