### ISSUE TITLE
Texto sin espaciado

### ISSUE THREAD

**Issue by vancieta** [breatheco-de/breatheco-de#6523]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/116301809/f3787a2f-b61f-4536-b743-4f3e51c75c27)

### Steps to reproduce

El texto con fondo negro se ve sin espaciado aunque en el Readme sale con espacio. Esto esta en la primera lección del prework en español

### Expected behavior

Que el texto se vea con el espaciado correcto

**Comment by Khrisefzm** [comment]
El bug fue corregido. Se colocó una tabla
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/ae6642e4-d803-498a-b6b8-979ea3eb3f2e)
