### ISSUE TITLE
Transferir repositorios de github de los usuarios eliminados hace mas de 60 dias

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6531]
Se deben borrar los repositorios de los usuarios que ya no estan en la academia, para esto debemos usar el API de GitHub. Especificamente estos requests:

- GET Repositories de la orgranizacion: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories
- DELETE Repository: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#delete-a-repository

La lista de repositorios que obtienes, tendra la propiedad `fork`, ademas de la informacion del repo como el nombre.

No debes borrar ninguno de los repositorios incluidos en la tabla `monitoring.repositorysubscription` (No importa que status tengan, todos los repos de esta tabla son protegidos).

Por otro lado, TAMPOCO SE DEBEN BORRAR ninguno de los repos que esten utilizados en algun asset, por lo que se debe revisar el `readme_url` de cada asset y el content de cada asset para chequear si contiene en el readme, un link a algun repo de github, de ser asi, se debe guardar ese repo para saber que no se va a borrar si se encuentra en el listado de los repos de las organizacion.

Para borrarlos, usamos el endpoint de GET repositories de GitHub con paginacion (Para no comprometer el rendimiento del sistema), y filtramos aquellos repositorios que sean `fork=True`, luego utilizamos el endpoint de DELETE, y borramos cada uno de estos repositorios de 100 en 100 (TOMANDO EN CUENTA LAS VALIDACIONES DESCRITAS ANTES).

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1404

**Comment by tommygonzaleza** [comment]
Now we should transfer the repository to the user's github account instead of deleting them

**Comment by tommygonzaleza** [comment]
You should transfer all the repositories of a user to their github account once the cohort user is marked as GRADUATED. You will know which repositories to transfer to him as those repositories are in the Task of that user in that cohort.

Besides those that are going to be deleted recurrently, we should transfer as well those repos that are not in the white list.

**Comment by tommygonzaleza** [comment]
- [ ] We should send them an email that the repository will be deleted in 60 days if they don't accept the transfer request sent. If you didn;t receive any transfer request, talk to the program manager to get help
