### ISSUE TITLE
h1 para geekforce

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6537]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44300504?key=5f0ee189d89a56b091ca73441c6f3eaa&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/geekforce-career-support](https://4geeksacademy.com/us/geekforce-career-support)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1853
