### ISSUE TITLE
Landings de workshops en español estan duplicados

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6541]
Otra cosa es que al parecer estas dos paginas web estan duplicadas:
https://4geeks.com/es/workshops/websockets-and-react-como-hacer-interfaces-de-usuario-en-tiempo-real
https://4geeks.com/workshops/websockets-and-react-como-hacer-interfaces-de-usuario-en-tiempo-real
Una tiene es y la otra no, no deberian estar duplicadas, deberia ser un redirect.

**Comment by tommygonzaleza** [comment]
Lo solucionaste quitando el landing del evento en español cuando el evento es en español, creo que la solucion seria mantener solo el que tiene /es, en vez de quitar ese y mantener la pagina en ingles

**Comment by tommygonzaleza** [comment]
La solucion esta generando un bug dando 404 con algunos landings de eventos
