### ISSUE TITLE
Estructura especifica para el landing de fullstack

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6551]
Aqui puedes [acceder al figma](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=9926-12324&mode=design&t=RlVT2xc36eUtnngz-0).

Vamos a cambiar el YML [de este landing](https://4geeksacademy.com/us/landing/full-stack-programs) de full-stack-programs para respectar esta estructura:

![Screenshot 2023-11-20 at 12 15 21 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/48b62026-8234-4167-b359-acbdd1e0e619)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1867

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1884
