### ISSUE TITLE
Agregar `intro_video_url` en los tutoriales interactivos y proyectos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6554]
Mostremos el video como en los workshops en donde esta la cuenta regresiva.
![Screenshot 2023-11-21 at 5 58 25 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/1c108400-e7dd-465e-8ce5-6ff3ca5c263e)

Debes usar la propiedad `intro_video_url` que tiene el asset para el video y `intro_image_url` para la foto que se usara de placeholder, si no lo incluye no muestras el video. Debes usar el componente `VideoPlayer`.

Esperando por el issue del componente: https://github.com/breatheco-de/breatheco-de/issues/6555

**Comment by tommygonzaleza** [comment]
Me equivoque al crearte el issue, no sabia que el backend regresaba la propiedad del video con un nombre diferente, en vez de `intro` es `intro_video_url`

**Comment by tommygonzaleza** [comment]
Usaste `solution_video_url` en vez de `intro_video_url`

**Comment by tommygonzaleza** [comment]
La imagen esta un poco cortada y el signo de play se ve
![Screenshot 2023-12-04 at 2 13 25 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/1c6fb7f1-79b6-48c0-8e33-b7b529ac992f)

**Comment by ArielCalisaya** [comment]
arreglado
