### ISSUE TITLE
Pagina del certificado, falta alineación en el botón de LinkedIn y un espacio en las horas

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6562]
![issue](https://github.com/breatheco-de/breatheco-de/assets/109150320/71a1c2a0-8fa9-4475-88ca-b758a339cad8)

poner "Instructor Principal" en ingles ya que el resto del certificado esta todo en ingles

los demás cambios que se ven en la captura.

**Comment by Khrisefzm** [comment]
Espacio en horas resuelto. Aún falta resolver la alineaciín de linkedIn

**Comment by andresmedtr** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/123752360/73345c95-70a7-40b2-82db-343ef9ee40ac)

It all looks fixed
