### ISSUE TITLE
Error en tipografía

### ISSUE THREAD

**Issue by Khrisefzm** [breatheco-de/breatheco-de#6566]
### Bug description

En la primera clase del pre-work hay una tabla con salios de programadores. Algunas celdas tienen la moneda, mientras que otras no.
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/c272a367-d3f3-42df-b1e6-c5fa3c7647d5)

### Steps to reproduce

Ir a la primera lección del pre-work

### Expected behavior

Que todas las celdas tengan moneda

**Comment by Lorenagubaira** [comment]
https://github.com/breatheco-de/content/pull/2013
