### ISSUE TITLE
El top ar no deberia tapar el navbar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6567]
![image](https://github.com/breatheco-de/breatheco-de/assets/426452/4a9ad3e5-5d79-4614-966f-a98e55d0507b)

**Comment by tommygonzaleza** [comment]
- [ ] No esta mostrando el navbar ahora
<img width="824" alt="Screenshot 2023-11-28 at 2 34 59 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/c3a56f56-8843-4704-a8f1-a67249b61694">

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1860

**Comment by tommygonzaleza** [comment]
Solo falta aceptar el PR
