### ISSUE TITLE
Revisar landing de un curso

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6568]

**Comment by tommygonzaleza** [comment]
- [ ] Cambia los placeholder por el texto que realmente crees que debe ir ahi para captar la atencion del usuario y mejorar su experiencia para que se inscriba

**Comment by ali5uarez5** [comment]
La propuesta que trabajé es la del medio. 

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=GldgNlAI98EOEkEP-1

**Comment by tommygonzaleza** [comment]
- [ ] Utilicemos el mismo componente ShowOnSignUp (para el widget del formulario) que se usa en los workshops (Incluir los colores).
- [ ] Agregar iconos a Dificultad, Lecturas, Ejercicios interactivos, proyectos y duración promedio del curso.
- [ ] Deberiamos tener un video, podemos agregarlo igual que en los proyectos.
- [ ] Agrega el logo de la tecnologia en el header
- [ ] A donde te llevaria "See full content".
- [ ] Agregar el placeholder del GIF de learnpack [aqui](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=59mjsA3d85KTo1EW-1). El GIF esta al final del home de https://www.learnpack.co/

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=sOURQcICNvhYQDyk-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=KQLMyo5I5AT1vLSh-1

**Comment by tommygonzaleza** [comment]
- [ ] En la seccion de Why learn with 4geeks? debemos hablar de AI, Live Workshops y Mentoring sessions.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=ipOSzEVimE8fNedj-1

**Comment by tommygonzaleza** [comment]
Se esta desarrollando aqui: https://github.com/breatheco-de/breatheco-de/issues/6947

**Comment by tommygonzaleza** [comment]
Se esta desarrollando aqui: https://github.com/breatheco-de/breatheco-de/issues/6947
