### ISSUE TITLE
Agregar traduccion de knowledge base

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6573]
En el admin en la academia de 4geeks.com, tienes asignadas las siguientes traducciones:

<img width="1457" alt="Screenshot 2023-11-28 at 2 58 58 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/5a9ff11e-7bdd-4d78-8180-ee05fbe229c4">

**Comment by Lorenagubaira** [comment]
- [ ]  https://github.com/breatheco-de/knowledge-base/pull/59
- [ ] https://github.com/breatheco-de/knowledge-base/pull/60
- [ ] https://github.com/breatheco-de/knowledge-base/pull/61

**Comment by tommygonzaleza** [comment]
Recuerda agregar la traduccion y marcar la tarea como entregada en el admin
