### ISSUE TITLE
Mejorar landing de un proyecto

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6578]
- [ ] Agregar video de como usar un template (Boilerplate) de un proyecto.
- [ ] Hacer mas llamativo el link de las instrucciones

Este es un ejemplo de un landing de un proyecto: https://4geeks.com/interactive-coding-tutorial/domain-generator

Quizas debamos crear algun componente o de alguna manera tenemos que mejorar la comunicacion porque aunque este escrito el link, la gente no lo usa. No es un tema del texto sino mas de lo visual

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=pFVBxCaPoPDf3M10-1

No me queda claro cual es el link de las instrucciones, pero agregué el video y cambié el componente que habla de los otros cursos.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12240%3A42384&mode=design&t=VzLAFbmHtXK1yDve-1

**Comment by tommygonzaleza** [comment]
- [ ] En la caja de la derecha cuando no tenga video debe verse como esta actualmente pero sin el icono amarillo

**Comment by ali5uarez5** [comment]
Todo lo referente a este issue lo estoy haciendo aqui: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=cKz4Y8Wcy4cFz446-1

**Comment by tommygonzaleza** [comment]
Estos issues se pueden trabajar en este mismo:
- https://github.com/breatheco-de/breatheco-de/issues/6655
- https://github.com/breatheco-de/breatheco-de/issues/6651

**Comment by tommygonzaleza** [comment]
### Metadata en mobile:

- [ ] Las tecnologias deben verse como en las lessons y no en el cuadro de metadata.
- [ ] Las translations no deben salir, ya que eso lo mostramos en el navbar

**Comment by alesanchezr** [comment]
Tambien faltan los videos genericos.

**Comment by tommygonzaleza** [comment]
- [ ] En la meta info del proyecto, debes agregar el titulo al lado de cada icono (El icono solo no explica lo suficiente)
- [ ] En la meta info del proyecto, quedan definidos los dos tipos de video como: `Instructions` y `Solution`, al mismo tiempo, debe explicar que es un video, entonces el icono debe incluir algo de video.

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/db27c64f-34e1-46ba-bab0-bd0d7550584e)

**Comment by tommygonzaleza** [comment]
- [ ] Falta agregar la version movil con formulario cuando hay video y cuando no hay video. (Que pasa cuando le das al boton de create account en el caso de cuando hay video?

El formulario deberia estar al final de las instrucciones del proyecto y en ambos casos (Con y sin video) debe haber un boton abajo de Create account, que al darle click te lleve al formulario al final de las instrucciones

**Comment by ali5uarez5** [comment]
Este es el comportamiento del cta: https://www.figma.com/proto/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?page-id=2563%3A3760&type=design&node-id=13254-36683&viewport=-26237%2C-10262%2C0.34&t=yXWplS52Jo5Cs2WF-1&scaling=scale-down&starting-point-node-id=13254%3A36683&show-proto-sidebar=1&mode=design

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=Pz3eKEKObAxJCZnS-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13399%3A43033&mode=design&t=GQn6nyFF8M7byKj3-1

**Comment by tommygonzaleza** [comment]
- [ ] Si no tiene video solution o video instructions, no se debe mostrar el campo, si si los tiene, debes mostrar un checkmark

**Comment by tommygonzaleza** [comment]
Se va a desarrollar en este issue: https://github.com/breatheco-de/breatheco-de/issues/6880
