### ISSUE TITLE
Cambiar componentes de MktRecommendedCourses

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6589]
Cambia el componente por este: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12241%3A44520&mode=design&t=Uq3zQ4dmGUyxnfo5-1

**Comment by ArielCalisaya** [comment]
link expirado

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12910%3A46331&mode=design&t=eDJkkFO1E03GZuwp-1

**Comment by tommygonzaleza** [comment]
- [ ] Hay mucho espacio entre ellos, reducelo para que se vea asi:
Antes:
![Screenshot 2024-02-06 at 2 53 48 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/84a1a829-b2ac-43f7-adee-87d7b16c6405)
Despues:
![Screenshot 2024-02-06 at 2 54 45 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/10902d99-424e-4a6d-9fcd-be83d9abcf9e)

Le puse el mismo padding tanto a los lados como arriba y abajo al padre. Le quite el justify center y le puse justify right. Le quite justify-content: space-between

**Comment by tommygonzaleza** [comment]
- [ ] No se esta mostrando ninguno de los CTA si el asset no tiene tecnologias
