### ISSUE TITLE
Probar bigquery trhotelling

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6597]
1. Asegurar que las variables de env este definidas
2. Si la ventana de tiempo es 1 minuto, esperar 5 minutos y deberian haber 5 ejecuciones en el log de actvidades.
3. Revisar que antes del minuto no haya ninguna actvidad en bigquery
4. Revisar que despues de un minuto ya si exitan actividade en bigquery.

**Comment by tommygonzaleza** [comment]
Tomas: 
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/e9cdf9b5-8c3b-4b85-9cb1-537d06f29f2e)

Jejerson: upload_activities se ejecuto solo una vez que es el que cuenta, el de clean_task tambien contaria pero como no tengo los segundos
Jeferson: `python manage.py upload_activities` no esta en el scheduler de produccion
