### ISSUE TITLE
Links de awards no llevan a nada

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6604]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44712007?key=cf23f5d05dfe98c6d60fa0529ec880d6&size=orig) 

 A donde los ibas a llevar? Si no tenemos link pues que no aparezca el boton.

---
**Source URL**:
[https://4geeksacademy.com/es/premios](https://4geeksacademy.com/es/premios)

**Comment by G-code7** [comment]
Solo me falta hacer los cambios en el awards  que está en ingles

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1932
