### ISSUE TITLE
Rediseño flujo de componente nuevo de mentorias

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6605]
El componente que se usa ahora para las mentorias no tiene el diseño del flujo completo.

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&mode=design&t=Esn0WE3u9VIP5hp1-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=WDeeTcK1gWeJ4AsP-1

**Comment by ArielCalisaya** [comment]
Al parecer los links expiraron, no logro encontrar el diseño

**Comment by tommygonzaleza** [comment]
Aqui esta el link actualizado del figma: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62637&mode=design&t=14GGKUrAzbFi0gll-1
