### ISSUE TITLE
No esta mostrando bien el icono de cuando esta loading

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6606]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/5c62d2fe-d7a3-4a9e-bede-e834b37aed6d)

**Comment by ArielCalisaya** [comment]
@tommygonzaleza 
Ya esta resuelto, aunque se debería mejorar el GIF ya que aparece por 1 segundo y desaparece por 3 segundos (aprox) dejando el fondo en blanco (un loader nunca debería desaparecer durante la animación)
Yo me puedo encargar de animar la desaparición al completarse la carga
