### ISSUE TITLE
Agregar campo nuevo en objeto de consumibles

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6613]
- [ ] En el servicio que te retorna los consumibles, se debe agregar una propiedad nueva para aquellos consumibles que no estan relacionados con mentorship_service_set, event_type_set, o cohort_set, como por ejemplo las interacciones con AI
- [ ] Agrgear un endpoint para consumir un consumible. Este endpoint debe recibir alguno de los valores que se entregan en el /me/consumable para identificar que consumible se va a consumir (Debes definirlo), y solo debe permitir consumir, solo debe restar el balance

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1221

**Comment by tommygonzaleza** [comment]
- [ ] Debemos agregar una tabla nueva llamada ServiceSet que tenga: slug, academy, meta_info (JSON), ManyToMany con service. Esta tabla debe usarse para que los Service Sets se incluyan en el serializador de balance de consumibles. Agregandolo asi:
```js
{
    merntoship_service_set:
    cohort_set:
    event_type_set: [
        { balance: 0, items: [] }
    ],
    learnpack_set: [
        { balance: 3, items: [{ slug: "compile" }] }
    ],
    rigobot_set: [
        { balance: 3, items: [{ slug: "id-interaction" }] }
    ],
}
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1262

**Comment by jefer94** [comment]
https://github.com/breatheco-de/breatheco-de/issues/6688
