### ISSUE TITLE
Agregar consumibles de learnpack

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6614]
- [x] Agregar `ai-interaction` a plan pago y gratuito
- [x] Agregar `learnpack-build` para utilizar la funcionalidad build de learnpack
- [x] Agregar `learnpack-test` para utilizar la funcionalidad de test de learnpack

**Comment by tommygonzaleza** [comment]
Falta determinar la cantidad de consumibles que tendran de cada uno para agregar los service items

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1221
