### ISSUE TITLE
BocaCode Website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6620]
https://bocacode.com/
https://bocacode.com/courses/career/software-engineering
https://bocacode.com/finance
https://bocacode.com/candidates
https://bocacode.com/alumni
https://bocacode.com/contact

**Comment by kelvinruizdevel** [comment]
https://github.com/kelvinruizdev/bocacode-website

**Comment by kelvinruizdevel** [comment]
https://bocacode-website-92aa-mmapc1umg-kelvinruizdev.vercel.app/

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/bocacode-website/pull/1
No encontré el curso de full stack developer como tal, solo he dejado el curso de Software Engineering Career Track que consideré el más parecido

**Comment by tommygonzaleza** [comment]
Fallo el deployment y no puedo verlo, este es el error que muestra:
![Screenshot 2024-02-27 at 2 46 38 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/56b7e543-50f4-425b-be32-76135fcbc6a4)

**Comment by tommygonzaleza** [comment]
- [ ] Falta agregar las vistas de cada alumno
- [ ] Los links de apply de la pagina de financing deben llevarte a /contact
- [ ] Baja el width de los videos de la pagina de alumni a como esta en la pagina
![Screenshot 2024-03-05 at 5 18 05 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/902b4e5c-04aa-4a77-ac88-01f483db4f0c)
- [ ] Debe mostrarse como seleccionada la opcion del navbar que este seleccionada, tal como funciona en la pagina original
- [ ] Asegurate que todos los links esten llevando a donde deberian llevar, hay varios de apply o de schedule a call que no te llevan a /contact

Expected time: 5 - 7 hrs

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/bocacode-website/pull/1

**Comment by Khrisefzm** [comment]
Solo falta colocar los datos de los alumnos
<hrs>8.41</hrs>

**Comment by tommygonzaleza** [comment]
Se pidieron algunos cambios en el PR

**Comment by tommygonzaleza** [comment]
Para las paginas de terms and conditions y privacy policy copiaras y pegaras esta informacion:
- Terms and conditions: https://github.com/breatheco-de/content/blob/master/src/content/misc/terms-and-conditions.md
- Privacy policy: https://github.com/breatheco-de/content/blob/master/src/content/misc/privacy-policy.md

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/bocacode-website/pull/1
Me tomó <hrs>4.23</hrs> más terminarlo

**Comment by tommygonzaleza** [comment]
- [ ] Que son estos que no tienen imagenes?
![Screenshot 2024-03-26 at 3 23 47 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/5e5b829c-0927-41a5-a883-76ddbbadc422)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/bocacode-website/pull/1

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>12.23</hrs>
