### ISSUE TITLE
Pantalla de login 

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6627]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44797312?key=a0de4af7c80eae9a942e369df2d1642e&size=orig) 

 Despues de hacer clic en "you can try a free plan" te muestra esta pagina. Hay que hacer enfasis en que la membresía sera gratuita, aquí hay un ejemplo de cambio de texto: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A14722&mode=design&t=bycxibcZ6ghbpj0E-1

---
**Source URL**:
[https://4geeks.com/checkout?plan=basic&plan_id=p-0-trial](https://4geeks.com/checkout?plan=basic&plan_id=p-0-trial)

**Comment by Khrisefzm** [comment]
La página sigue igual.
No se visualiza el ejemplo del cambio de texto que menciona el usuario en el link: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A14722&mode=design&t=bycxibcZ6ghbpj0E-1

**Comment by ali5uarez5** [comment]
este link deberia fucionar. 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62640&mode=design&t=vLrCwAiMlDAePRd5-1

**Comment by tommygonzaleza** [comment]
Agregar `AI Feedback and support`.
