### ISSUE TITLE
margin top for datascience machine learning

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6631]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/0d3cbf8c-1220-4218-bd23-e09cd5813161)
https://4geeksacademy.com/us/coding-bootcamps/datascience-machine-learning

### Steps to reproduce

it can be view at naked eye, is nedeed 70px of margin top.

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/cfbbdb94-da0f-407d-9c8a-127b239e9422)

also for a fullstack web page

**Comment by kelvinruizdevel** [comment]
![Screenshot 2023-12-12 141347](https://github.com/breatheco-de/breatheco-de/assets/138077477/fa300786-25b5-47d8-bec3-785b6b93724f)
![Screenshot 2023-12-12 141405](https://github.com/breatheco-de/breatheco-de/assets/138077477/f718c89e-7603-4168-9261-b421febccacf)

A mi no me genera ese error
