### ISSUE TITLE
Cambiar animacion de loading de rigo

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6635]
Actualmente se muestra por 1 segundo y se quita por 3 segundos, una animacion de loading no deberia quitarse o por lo menos no por tanto tiempo

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/dc1fc734-760a-4d1b-b4a9-9ccdd408f676)
