### ISSUE TITLE
Mejorar el componente ShowOnSignUp

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6643]
- [ ] Agregar color al formulario, tenemos que hacerlo mas llamativo.
- [ ] El boton no es obvio que es un boton, usemos otro color o algo para que se note que es un boton pero tambien que esta inhabilitado
![Screenshot 2023-12-14 at 12 48 27 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/76a77492-913c-42b7-abd4-23a2238e467a)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12659%3A34050&mode=design&t=VGlS92uQImfqI9yl-1

**Comment by tommygonzaleza** [comment]
[Aqui](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9400%3A43809&mode=design&t=IPe91VPDls1OUG6Y-1) se encuentran las distintas versiones del componente ShowOnSignUp, asegurate de que en todas las versiones se vea como en el diseño

**Comment by tommygonzaleza** [comment]
<img width="1281" alt="Screenshot 2024-02-08 at 2 57 09 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/c5c1f2ec-f7e2-4bb6-990f-ccb5d10f051d">

**Comment by alesanchezr** [comment]
- [ ] si tiene solution_video_url entonces muestras un boton para ver la solucion "Watch video solution explained"
- [ ] si tiene asset.gitpod = true entonces muestras tanto el boton de learnpack como el de clonar.
- [ ] si tiene solution URL muestras un boton para "Review solution"

**Comment by tommygonzaleza** [comment]
Sera que los cambios solo los pusiste en la vista de los ejercicios? Yo estoy probando con un proyecto y no me aparecen los cambios de los mensajes. Los mensajes deben variar tambien para los proyectos

**Comment by tommygonzaleza** [comment]
### Cuando es hecho en LearnPack (`asset.gitpod=true`):

![Screenshot 2024-02-20 at 1 58 08 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/2041ff9b-7292-47fb-a179-009aaddb1f40)

### Cuando no es hecho con LearnPack pero si tiene solution video y code solution:

![Screenshot 2024-02-20 at 2 11 30 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/47c62cb1-eafa-4793-b5cd-3fdfd61d5594)

### Cuando no es hecho con LearnPack y solo tiene solution video o code solution:

![Screenshot 2024-02-20 at 2 12 20 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/3558bfac-b2a7-4625-9a39-b442e9dd27b4)

**Comment by tommygonzaleza** [comment]
- [ ] No se debe mostrar al menos de que este loggeado (Es uno de los incentivos de registrarse)
![Screenshot 2024-02-22 at 3 49 10 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/ab970604-68a7-464a-b449-ad23a2212f8d). Hazlo como la propiedad de repository
