### ISSUE TITLE
Poner GIFs generico que se utilizara como placeholder en videos de proyectos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6651]
Haz 5 GIFs a partir de un video tuyo, debe ser muy atractivo, muy llamativo, para mostrar como placeholder en los proyectos

**Comment by tommygonzaleza** [comment]
Se esta haciendo en: https://github.com/breatheco-de/breatheco-de/issues/6578

**Comment by alesanchezr** [comment]
falta hace rel video
