### ISSUE TITLE
Modal para hacer login si quieren ver el video

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6652]
- [ ] Al darle click al video, debe mostrarse una modal que diga que debe hacer login para poder verlo.
- [ ] Debe dejar verlo si ya esta loggeado
- [ ] Quitemos el icono de chats que esta arriba, el titulo de goal y el mensaje.

Diseña esta modal

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=5kVx4jpjJj9QQTgJ-1

**Comment by tommygonzaleza** [comment]
- [ ] Deberiamos priorizar el registro antes que el login

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=663ro0w5dXw7rEwr-1

**Comment by tommygonzaleza** [comment]
<img width="811" alt="Screenshot 2024-01-08 at 12 02 20 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/046fa137-a971-45d6-9b3a-b4904e71a326">

**Comment by ali5uarez5** [comment]
Con el nuevo form ya no se si va a ser necesario utilizar esa modal ahí, pero ya el cambio está hecho: 

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=Hpm7g8ZqIelkI2l4-1

**Comment by alesanchezr** [comment]
esta listo porque en mobil te redirigimos al signup tradicional en lugar de mostrarte el signup alli mismo, no hay espacio.

**Comment by alesanchezr** [comment]
listo para que gustavo lo programe

**Comment by tommygonzaleza** [comment]
Se va a utilizar el ShowOnSignUp nada mas, de resto los cambios estan en este issue: https://github.com/breatheco-de/breatheco-de/issues/6578#issuecomment-1887621365
