### ISSUE TITLE
Agregar weekly coding challenge

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6653]
- [ ] Debe ser un componente usado en el dashboard y vista del proyecto, que al darle click te entregue un proyecto para practicar.
- [ ] Debes estar loggeado para poder acceder a el
- [ ] Debe tener este texto: `Every week, we pick a real-life project to build your portfolio and get ready for a job. All projects are built with chaGPT as co-pilot.`
- [ ] Debe mostrar informacion del progreso de las semanas en las que lo has completado

**Comment by tommygonzaleza** [comment]
Aqui esta el diseño del componente: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=hdzLckC3nQlZLFEO-1

**Comment by ali5uarez5** [comment]
en el dashboard: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62637&mode=design&t=cKz4Y8Wcy4cFz446-1

En el proyecto: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=cKz4Y8Wcy4cFz446-1

**Comment by ali5uarez5** [comment]
Tenemos que resolver como se va a ver la versión responsive, aquí hay 3 propuestas: 
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=cKz4Y8Wcy4cFz446-1

**Comment by tommygonzaleza** [comment]
Se esta agregando [aqui](https://github.com/breatheco-de/breatheco-de/issues/5848)
