### ISSUE TITLE
Agregar cajita de Supplementary Material en landing de proyectos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6655]
- [ ] Debe ser una cajita abajo de la de la informacion del proyecto

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10965%3A52036&mode=design&t=FClDzDajfpRhAelq-1

**Comment by tommygonzaleza** [comment]
- [ ] Rediseñala completa, puedes reutilizar el componente de feedback, usando los tabs de los descargables.
- [ ] Si es un ejercicio, no deberiamos sugerir proyectos

![Image](https://github.com/breatheco-de/breatheco-de/assets/56565994/8db5ba35-b185-4ccf-9534-c30200f1dde7)

**Comment by tommygonzaleza** [comment]
Se esta haciendo en: https://github.com/breatheco-de/breatheco-de/issues/6578

**Comment by tommygonzaleza** [comment]
Fue asignado para programarlo en este [issue](https://github.com/breatheco-de/breatheco-de/issues/6768)
