### ISSUE TITLE
Outcomes esta descuadrado

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6660]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44973511?key=a4a32cbfa2e27b139f2996cc144f1fda&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/outcomes](https://4geeksacademy.com/us/outcomes)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1890

**Comment by tommygonzaleza** [comment]
Falta aprobar el PR

**Comment by tommygonzaleza** [comment]
Tiene un bug en movil
<img width="941" alt="Screenshot 2024-01-16 at 5 14 08 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/827edb70-2ba9-4005-91d1-c7200ca2f32c">

**Comment by tommygonzaleza** [comment]
Sigue pasando el mismo bug

**Comment by kelvinruizdevel** [comment]
Vale
