### ISSUE TITLE
Boton de I Want To Contribute no esta funcionando

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6661]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/44973544?key=196f3758a4ef4a1476d7213e99db619f&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/20-million](https://4geeksacademy.com/us/20-million)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1889

**Comment by tommygonzaleza** [comment]
Falta aceptar el PR

**Comment by veljzs** [comment]
![Screenshot ](https://github.com/breatheco-de/breatheco-de/assets/128405596/b6d00eb7-1b05-49de-85e8-3751dcf92399)

**Comment by tommygonzaleza** [comment]
@veljzs esto ya se corrigio en otro PR
