### ISSUE TITLE
Landing que redirecciona a 3 landings más (Inicio formulario, Video, Agenda calendly)

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6670]
Necesitamos:

- [ ] Copy del primer landing ([ejemplo](https://info.lewagon.com/cl-ds-bootcamps-1))
- [ ] Video del segundo landing.
- [ ] Estructura de la tercera.

Necesitamos un ejemplo de el 2do y tercer landing.

**Comment by alesanchezr** [comment]
Esperando por thania para que pase el video del 2do landing y la estructura del tercero.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2106

**Comment by alesanchezr** [comment]
Hay que eliminar el landing y migrarlo a downloadable, y cuando llenes el form de manda a video ask.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2106

**Comment by G-code7** [comment]
falta crear un slug para un downloadable que esté relacionado a la programación 3.0
