### ISSUE TITLE
Cambiar todos los textos y mensaje del landing de applied AI en chile

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6671]
Marketing messages:

“Metele esteroides a tu trabajo”
“Se 10 veces mas productivo”
“Aprende a utilizar inteligencia artificial en tu dia a dia”
“Domina las herramientas de inteligencia artificial”
“Haz tu trabajo en la mitad del tiempo”
“Facilita tu trabajo con inteligencia artificial”
“Aprende a usar inteligencia artificial o quedate afuera”
“No te quedes atras, únete a la ola de AI”

Statistics

ChatGPT had 1 million users within the first five days of being available

64% of businesses expect AI to increase productivity
A significant 64% of businesses believe that artificial intelligence will help increase their overall productivity, as revealed in a Forbes Advisor survey. This demonstrates the growing confidence in AI’s potential to transform business operations.

**Comment by G-code7** [comment]
Hacer la pagina en ingles tambien

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1874
