### ISSUE TITLE
Escribir textos para nuevo componente de video de las paginas de las locaciones

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6672]
Algo de esto ya tienes hecho porque en los landings de colombia, argentina, etc. Ya tu tenias un two column right con su video y texto a la izquierda. Ahora hay que replicar eso en cada colacion.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1891

**Comment by G-code7** [comment]
Hacer los cambios con el nuevo video de Alissa, a parte algunos videos que me gustaría hacer para  locations para reemplazar aquellos casos en los que el testimonio no está del todo alineado con la locación. 

- [ ] grabar videos
- [ ] subir videos

**Comment by alesanchezr** [comment]
ya el video se subio a youtube, falta actualizarlo en la pagina

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1979
