### ISSUE TITLE
FAQ's de las locaciones

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6673]
Apuntar a 10 preguntas frecuentes, la mayoria se repiten en cada locaicon pero algunas son muy propias:

- Necesito una laptop?
- Necesito conocimiento previo? Mencionar aqui tambien que NO necesitas ser bueno o saber matematica.
- Planes de finaciamiento?
- Becas?

Para inspierarte en preguntas:

- Escribir por char a los crontry managers para preguntar las preguntas mas locales que siempre hacen los leads.
- Revisar FAQ de la competencia.

**Comment by alesanchezr** [comment]
- [ ] Construir un google sheet con las siguientes preguntas:

```
HOW DO I PAY FOR MY TUITION?
DOES 4GEEKS OFFER CAREER SUPPORT IN <SPAIN>?
EXTENDED PAYMENT PLAN? HOW DOES IT WORK? AND WHAT DOES IT MEAN?
CAN I PAY AFTER I GET A JOB?
```

Every country manager has to answer for this questions using geolocalized answers, for example, in pain the 4 answers will only speak about payment methods available in pain or Europe but in Miami the payment method will be different.

**Comment by G-code7** [comment]
Ya tengo el documento [acá](https://docs.google.com/spreadsheets/d/1u_8Y4gCYgQgmFBRkzwDNTFru7s96i5uhS_HzoJVvfdE/edit#gid=394208727), 
Esta semana lo actualizo

**Comment by alesanchezr** [comment]
Cambios:
https://www.awesomescreenshot.com/video/26786378

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2052/files

**Comment by alesanchezr** [comment]
- [ ] Separar la pregunta del FAQ sobre el horario para que sea por locacion, debes mencionar las ciudades y lugares donde estamos presentes en esa locacion y sus horarios.
- [ ] Tropicalizar la pregunta de como pagar para ponerla sobre la locacion en particular, hablar de los partners locales que usamos en esa locacion y en general de las formas de pago, los precios no los menciones para que vayan a la vista de financials.
- [ ] La pregunta de "do I need to have my own laptop" [tiene un link malo](https://tinyurl.com/28nmk8qt).
