### ISSUE TITLE
Definir como se ve los resultados (La terminal) en el componente `CodeViewer`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6674]
Cuando le dan a run, se debe mostrar el resultado del codigo en un cuadro que debe verse como una terminal.

![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/257a6464-d024-4b53-bd1f-55a62fc998fc)

**Comment by ali5uarez5** [comment]
Lo estoy trabajando aquí: 

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=6jKkm7XkklIgjUSC-1

**Comment by tommygonzaleza** [comment]
- [ ] El preview no es markdown, debe verse como en el formato de la terminal

**Comment by tommygonzaleza** [comment]
Es como la respuesta del codigo
![Screenshot 2023-12-21 at 12 25 18 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/0a0a62ca-6f88-4d14-9219-e4a3a8dfb3af)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=663ro0w5dXw7rEwr-1

**Comment by tommygonzaleza** [comment]
Cuando el tab de codigo que se esta visualizando es HTML o CSS, se debe ocultar el boton de run

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10944%3A27689&mode=design&t=Hpm7g8ZqIelkI2l4-1
