### ISSUE TITLE
Genera 3 ejercicios sobre clases en python

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6678]
Utiliza ChatGPT para que te ayude en la creacion de varios ejercicios sobre clases en python que iran al final de los ejercicios de master-python. Estos ejercicios deben dejar claro, que es una clase, cuando utilizar una clase, metodos y atributos de una clase, herencia, polimorfismo, Magic Methods (Special Methods), Class Methods and Static Methods

**Comment by josemoracard** [comment]
https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/61
https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/62
https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/63

3 exercises created
