### ISSUE TITLE
Agregar componente para mostrar workshops en lessons

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6680]

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12910%3A46331&mode=design&t=g4IOP566o0lOdz51-1

**Comment by alesanchezr** [comment]
listo pa programar


![Image](https://github.com/breatheco-de/breatheco-de/assets/426452/e23536b8-e477-4ffd-b434-49e46bc2fe2b)

**Comment by tommygonzaleza** [comment]
Se mando a programar en este [issue](https://github.com/breatheco-de/breatheco-de/issues/6765)
