### ISSUE TITLE
"How to start a coding project" no carga bien en Edge

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6684]
### Bug description

Cuando abres https://4geeks.com/lesson/how-to-start-a-project se ve todo el contenido pero luego es reemplazado por la plantilla de carga de contenido. Esto ha pasado con Edge.
<img width="824" alt="Screenshot 2023-12-26 at 14 28 48" src="https://github.com/breatheco-de/breatheco-de/assets/410890/434a054d-4785-489b-a3cb-ea20e3e7dd7a">

### Steps to reproduce

Entrar en https://4geeks.com/lesson/how-to-start-a-project con Edge

**Comment by jasbears** [comment]
the screenshot link is broken so I can't quite tell the issue.  But I did open the link in 3 different browsers (Chrome, Edge, and OperaGX) they all look relatively the same. If you can, c

![chrome](https://github.com/breatheco-de/breatheco-de/assets/79122202/07d6a536-b113-4342-b8b9-13a2db10565b)

![edge](https://github.com/breatheco-de/breatheco-de/assets/79122202/3843145a-f5f0-49cf-a327-2df513e47f33)

![ogx](https://github.com/breatheco-de/breatheco-de/assets/79122202/7d6a142a-a39d-41b6-8987-1f53c7453fc5)

an you please re-upload the screenshot so I can fully confirm it?

**Comment by tommygonzaleza** [comment]
No se pudo replicar, el link que utilizaste estaba roto, quizas es por eso, estaba intentando acceder a la lesson en ingles pero con la pagina en español
