### ISSUE TITLE
Revision de logica de consumibles para code_reviews

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6688]
stoy viendo lo de los app_service y eso se creo para los consumibles de los code reviews
[se creo un app service](https://github.com/breatheco-de/apiv2/blob/main/breathecode/assignments/permissions/consumers.py#L7) llamado `code_revision`
pero creo que eso es mejor que lo tengan los profesores
da igual cuales o cuantas 3rd party apps se usen, los consumibles siempre deberian caer sobre los usuarios
ademas que quien debería consumir no es el que revisa, sino al que le revisan su codigo (el watcher)

**Comment by jefer94** [comment]
En teoría si lo usara el profesor sería uso interno, un profesor necesita poder hacer uso de Rigobot de manera gratuita, creo que se podría dejar un endpoint para el estudiante y si se desea dejar de usar se elimina en el frontend, aparte de eso se puede usar la idea nueva de las auditorias para analizar si alguien este usando el endpoint sin permiso para tener siempre cuadrado el tema financiero

**Comment by jefer94** [comment]
Por otra parte, si creas un endpoint que retorne un dict y este depende de las variables de entorno, podrías implementar un feature flag sencillo

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1262

**Comment by jefer94** [comment]
¿Debería tener consumer el endpoint del estudiante o solo tener `consumer=true`?, es lo último a ajustar
