### ISSUE TITLE
Mapeo de usuarios entre BC y Rigobot

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6690]
Tenemos este problema: 
https://github.com/breatheco-de/breatheco-de/issues/6689

Lo mejor es que brisco tenga una tabla con los ids de rigobot de ada uno de susu usuarios, el id se busca y agrega en esta tabla en el momento enque el usuario "autoriza" a rigobot.
https://github.com/breatheco-de/rigobot/blob/711fc8f954846c756597bb8a1893532adc729b1f/breathecode/authenticate/urls.py#L28

Esto ya es estandar en oauth, siempre la aplicacion que consume el 3rd party API debe tener los id de los usuarios que representan a sus usuarios en esa 3rd part api.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1265

**Comment by jefer94** [comment]
Rigobot no es un third party service, es un first party service
