### ISSUE TITLE
Mejorar usabilidad cuando no haz abierto ningun modulo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6694]
Si una persona no ha activado ni un módulo, es un error decir que tiene el 100% del programa. Lo mismo cuando un módulo se ha iniciado y terminado y el resto están sin iniciar.
No le deja clara la ruta de estudio a la persona, porque es relativa a lo que haya avanzado y no a lo que debe avanzar.
![image-2](https://github.com/breatheco-de/breatheco-de/assets/426452/cd2a1b71-21dc-41fa-8bcc-37440f960c02)
![image-1](https://github.com/breatheco-de/breatheco-de/assets/426452/fa62e91a-82ce-4c8c-bfa1-14294e2a3606)

**Comment by ali5uarez5** [comment]
a mi me sale 0% cuando no he iniciado ningun modulo


![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/fcd5036a-47b8-4b87-b37b-e556a3a7cbe9)

**Comment by tommygonzaleza** [comment]
@ArielCalisaya Lo que esta pasando es que se esta tomando el progreso de la cohorte respecto a los modulos que tienes abiertos, sin embargo se tiene que tomar el progreso con respecto a todos los modulos de la cohort, por lo que no deberia decir 100% al completar el primer modulo y antes de abrir el segundo

**Comment by tommygonzaleza** [comment]
- [ ] Esta ocurriendo este error al entrar al dashboard de la cohort
<img width="1448" alt="Screenshot 2024-01-16 at 11 25 18 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/bb72a878-59b5-48cd-b906-6e0ab39f8d3a">

**Comment by tommygonzaleza** [comment]
La barra de progreso esta mostrando progreso aunque muestre 0%, y dice undefined en la cuenta de las tareas abajo

<img width="941" alt="Screenshot 2024-01-16 at 4 35 29 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/a9254dc3-16a0-42b8-bd46-1af5c904d998">
