### ISSUE TITLE
redondear bordes inferiores del rectangulo del video

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6695]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45174713?key=f6b3624855482c64b7773ab8d7ce3d75&size=orig) 

---
**Source URL**:
[https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2](https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2)

**Comment by AngelesRocks** [comment]
It's confirmed
