### ISSUE TITLE
Cuando tienes un lang por defecto y accedes a una lesson de otro lang, falla

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6696]
https://github.com/breatheco-de/breatheco-de/assets/109150320/17592cff-e950-4315-b1de-8d2cb219ff65

**Comment by tommygonzaleza** [comment]
No parece estar pasando desde dev, igual vamos a probar de nuevo cuando se pase a produccion

**Comment by josemoracard** [comment]
video sobre como reproducir el error:

tiene que ver con el idioma en el que pones tu cuenta y luego abrir una lección del idioma contrario

https://github.com/breatheco-de/breatheco-de/assets/109150320/951426ee-7808-44cf-88e4-b1e3d6ccd5ad

**Comment by tommygonzaleza** [comment]
El bug esta relacionado con el idioma del estudiante. Basicamente esta abriendo directamente el link del lesson en español cuando en su perfil esta guardado el idioma de ingles, si esto pasa, se debe redirigir al contenido en ingles

**Comment by ArielCalisaya** [comment]
El bug es provocado por un redirect que no se planteó bien.

[AuthContext.jsx#L198](https://github.com/breatheco-de/app/blob/main/src/common/context/AuthContext.jsx#L198)
