### ISSUE TITLE
Refreshment of Rigobot User Agreement view

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6702]
- [ ] La vista puede o no tener los inputs para hacer login.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45261553?key=abfa62677a38787f2087cff54bc3dfb1&size=orig) 

Ejemplos de otras vistas similares:
![oauth](https://github.com/breatheco-de/breatheco-de/assets/426452/14a4dd65-68c4-47ab-99d0-7db36b4eb14d)

![oauth2](https://github.com/breatheco-de/breatheco-de/assets/426452/0994352d-3179-4b26-8d5b-d765d815a0d6)

---
**Source URL**:
[https://rigobot.herokuapp.com/invite/?referer=4geeks](https://rigobot.herokuapp.com/invite/?referer=4geeks)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12992%3A58371&mode=design&t=Hpm7g8ZqIelkI2l4-1

**Comment by tommygonzaleza** [comment]
- [ ] Cambiar para que no sea una modal
- [ ] Agregar los inputs de login

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12992%3A58371&mode=design&t=3pXHaeHPNgKFfYbV-1

**Comment by alesanchezr** [comment]
tanto los inputs como el texto explicativo deben estar en la misma vista, no son pasos separados.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12992%3A58371&mode=design&t=AeG7i8OE4vgeWNum-1

**Comment by tommygonzaleza** [comment]
Aqui esta el diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12992%3A58371&mode=design&t=RF4wFZH0MdIrMEQ9-1

Si el usuario le da a Register here, debes redireccionarlo a `https://4geeks.com/pricing`
