### ISSUE TITLE
Porque la dificultad de los proyectos dice uknown?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6705]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45263097?key=b4d2a987891ee604ef9b777019f98472&size=orig) 

 Corregir a la dificultad correspondiente

---
**Source URL**:
[https://4geeks.com/interactive-coding-tutorial/interacting-with-api-python-project-tutorial](https://4geeks.com/interactive-coding-tutorial/interacting-with-api-python-project-tutorial)

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-01-09 at 2 56 42 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/abfeb637-1084-49da-bec9-ccf7ec927e62)

**Comment by ArielCalisaya** [comment]
Ya esta actualizado
<img width="1171" alt="Captura de pantalla 2024-01-09 a la(s) 17 14 27" src="https://github.com/breatheco-de/breatheco-de/assets/51676628/aad875e1-ae1d-4022-80d3-0c93ba6246c1">
