### ISSUE TITLE
Agregar logo en version movil

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6710]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45268391?key=d98e65a62f6d45ed091cec7e934bc5ba&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/index](https://4geeksacademy.com/us/index)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1895

**Comment by tommygonzaleza** [comment]
Aceptar PR
