### ISSUE TITLE
Bordes top y bottom en imágenes a veces no salen

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6714]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45289309?key=efe7ac652f4641029c1f18eea4c63441&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-development-geeksacademy.vercel.app/es/inicio](https://website-v2-git-fork-g-code7-development-geeksacademy.vercel.app/es/inicio)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1901

**Comment by tommygonzaleza** [comment]
Aceptar PR
