### ISSUE TITLE
URGENT! No puedo tener mentorías por la plataforma de 4geeks

### ISSUE THREAD

**Issue by vancieta** [breatheco-de/breatheco-de#6716]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/116301809/2253f107-3396-44d8-a28e-2024d3021c8d)

Al intentar entrar a una mentoría me sale que el mentor no está listo, pero el mentor soy yo

### Steps to reproduce

Darle click a mi link de mentorías, me pasa tanto para el campus de usa como para el de LATAM

![image](https://github.com/breatheco-de/breatheco-de/assets/116301809/9b9358fa-733b-461c-a76e-ce6c119dcbc8)

### Expected behavior

Abrir la reunión de mentorías con el estudiante

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/breatheco-de/breatheco-de/issues/6727)
