### ISSUE TITLE
Traducir

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6721]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45295109?key=001369c5526bf6cacb09042de2d87ce0&size=orig) 

---
**Source URL**:
[https://website-v2-5yxg8liha-geeksacademy.vercel.app/us/geeks-vs-others](https://website-v2-5yxg8liha-geeksacademy.vercel.app/us/geeks-vs-others)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1902
