### ISSUE TITLE
bajar font-size a 16px y letter-spacing 0.06em

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6722]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45295140?key=c1036a3b6c1c78e969ad4c6384ae4b48&size=orig) 

---
**Source URL**:
[https://website-v2-5yxg8liha-geeksacademy.vercel.app/es/inicio](https://website-v2-5yxg8liha-geeksacademy.vercel.app/es/inicio)

**Comment by kelvinruizdevel** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1899

**Comment by tommygonzaleza** [comment]
Aceptar PR
