### ISSUE TITLE
El contenido de la página está en español pero el titulo y la info del form están en inglés

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6723]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45303541?key=716fab76cd3d1db541a3a4f65cebb936&size=orig) 

---
**Source URL**:
[https://4geeks.com/workshops/crea-un-contador-simple-con-react-115a1311-44a8-4daf-9009-3eacea787977](https://4geeks.com/workshops/crea-un-contador-simple-con-react-115a1311-44a8-4daf-9009-3eacea787977)

**Comment by tommygonzaleza** [comment]
Ya el problema no esta pasando
