### ISSUE TITLE
Hay que agregar espacio entre el texto descriptivo y el bloque de info sobre el host

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6725]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45303733?key=e00182145f0c8fdc0864079c3d5a71ba&size=orig) 

 El espacio debería ser igual al que tiene la card del host con el form. En el diseño son 32 px.

---
**Source URL**:
[https://4geeks.com/workshops/crea-un-contador-simple-con-react-115a1311-44a8-4daf-9009-3eacea787977](https://4geeks.com/workshops/crea-un-contador-simple-con-react-115a1311-44a8-4daf-9009-3eacea787977)

**Comment by JorgeCoto98** [comment]
El espacio entre el host y la descripción fue corregido
