### ISSUE TITLE
No esta dejando entrar a los estudiantes a las mentorias

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6727]
Esta dando este error aunque el mentor ya este adentro:
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/688ca9ae-6f50-4eea-a06a-a0016d47608f)

Hay mentores que le esta funcionando a veces y a veces no le funciona. Este es uno de los usuarios a los que les esta pasando: 4542

**Comment by arnaldoperez** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/19396163/0fb8ace6-bf64-4c96-9ce2-ea0415cd863e)
Muestra este error al iniciar sesion y despues de seleccionar un estudiante. La consola no muestra ningun error

**Comment by arnaldoperez** [comment]
Dando click atras y volviendo a seleccionar el estudiante hace que permita entrar

**Comment by jefer94** [comment]
Sospechamos que el error es causado por una ralentización en las respuestas del servicio de Calendly, este parche solucionara el problema
https://github.com/breatheco-de/apiv2/pull/1236
