### ISSUE TITLE
El curso le muestra al estudiante el tutorial de profesor

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6731]
### Bug description

<img width="559" alt="Screenshot 2024-01-11 at 16 25 56" src="https://github.com/breatheco-de/breatheco-de/assets/410890/242022c1-21bf-40f5-99a7-89fcd0ea03bd">

### Steps to reproduce

Asignar una cohorte a un perfil como estudiante e ingresar al listado de contenidos de un curso

**Comment by tommygonzaleza** [comment]
A que estudiante le ocurrio?

**Comment by tommygonzaleza** [comment]
Esa persona tiene ProfileAcademy de teacher
