### ISSUE TITLE
Rediseñar modal cuando intentan abrir un assignment

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6734]
En la vista para unirse a una cohort si intentan abrir un assignment, como esta bloqueado, se muestra la siguiente modal:
![Screenshot 2024-01-11 at 1 57 47 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/400bda39-58ce-43a2-a767-c6f3e58c4519)

Debemos agregar en esta modal:

- [ ] El titulo del asset que quiere abrir
- [ ] Un parrafo que explica el asset
- [ ] Y luego un parrafo como el que esta en la modal, que invite a usar el call to action de unirse a la cohort

**Comment by alesanchezr** [comment]
falta el icono del tipo de contenido.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62640&mode=design&t=AeG7i8OE4vgeWNum-1




![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/cac8af1e-e9cf-458d-8886-897dee9446b3)

**Comment by tommygonzaleza** [comment]
@gustavomm19 aqui una explicacion mejor de cada parte del contenido:

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62640&mode=design&t=15zNNc5vWdPGvpjO-1

- El titulo azul incluye un icono y dice el tipo de asset, obtienes ambos del asset que se quiso abrir, recuerda que tenemos un icono para cada tipo de asset, puedes verlos aqui: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12643%3A40546&mode=design&t=4qpDhaXZKB1u2uBO-1
- Luego tienes el titulo del asset
- Luego el description del asset

**Comment by tommygonzaleza** [comment]
- [ ] No esta mostrando el description de los assets:
<img width="1344" alt="Screenshot 2024-01-26 at 3 24 59 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/930b9f68-ab97-4b3a-b920-582313823fe5">

**Comment by tommygonzaleza** [comment]
No tenemos acceso a la descripcion en el syllabus
