### ISSUE TITLE
No carga la lesson en español - Syllabus DS

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/breatheco-de#6743]
### Bug description

En el syllabus de Data Science y Machine Learning, la lesson **Graficar Funciones con Python** solo está en Inglés, en español carga la info en inglés, a pesar de que la lesson si existe en español 

### Steps to reproduce

![image](https://github.com/breatheco-de/breatheco-de/assets/48845580/c40f73f0-bc7a-4fc5-bd7a-dba5d81e009d)

Esto es lo que carga: 
![image](https://github.com/breatheco-de/breatheco-de/assets/48845580/e4ed4fcb-4f96-4f06-b1bd-c1b0a765950d)

### Expected behavior

Debe cargar esta lesson: https://github.com/4GeeksAcademy/calculus-and-algebra-with-python/blob/main/plotting-functions-with-python.es.ipynb

**Comment by jatv93** [comment]
La lesson **Mean and Standard Deviation** tiene el mismo problema:

![image](https://github.com/breatheco-de/breatheco-de/assets/48845580/a5a329cf-7977-4d85-b7bc-527903ebd0df)

La lesson en español ya existe: https://github.com/4GeeksAcademy/calculus-and-algebra-with-python/blob/main/mean-std-with-python.es.ipynb

**Comment by tommygonzaleza** [comment]
Resuelto!
