### ISSUE TITLE
DS - No abre el link correcto en Collab

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/breatheco-de#6747]
### Bug description

https://github.com/breatheco-de/breatheco-de/assets/48845580/4c6424d0-4a5b-443e-8664-f08897de58d7

### Steps to reproduce

En el syllabus de DS, si entras desde el Dashboard a algunas lesson, NO puedes abrirlas en Collab, y si entras por el menú de la izquierda, una vez ya abriste la primera lesson si puedes ingresar y es porque el slug de la URL cambia según desde donde ingreses, y eso no debe ocurrir.

### Expected behavior

Validar todos los slug de los redireccionamientos para que estén correctos y mande al sitio correcto

**Comment by jatv93** [comment]
Esta lesson tampoco abre en collab, pero ni en inglés ni es español, el respositorio si existe y tiene la extensión correcta:

https://4geeks.com/syllabus/python-ia/read/mean-and-std-with-python

Repo Inglés: https://github.com/4GeeksAcademy/calculus-and-algebra-with-python/blob/main/mean-std-with-python.ipynb
Repo Español: https://github.com/4GeeksAcademy/calculus-and-algebra-with-python/blob/main/mean-std-with-python.es.ipynb

**Comment by tommygonzaleza** [comment]
Esta ya se esta resolviendo en otro issue: https://github.com/breatheco-de/breatheco-de/issues/6730
