### ISSUE TITLE
No se esta agregando info de email quality desde workshops o ejercicios

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6754]
Si alguien se registra desde un workshop o desde un interactive tutorial, no se esta registrando la informacion de email quality ni email status. Si lo haces desde /checkout, si esta funcionando

**Comment by tommygonzaleza** [comment]
Sigue sin guardarse la info de email quality

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1355
