### ISSUE TITLE
Crear articulo acerca de useReduce para una lesson

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6757]

**Comment by arnaldoperez** [comment]
Articulo para revision y aprobacion https://github.com/breatheco-de/content/pull/2066

**Comment by arnaldoperez** [comment]
https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f?pvs=4
