### ISSUE TITLE
Agregar un ejercicio sobre magic methods

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6758]
- [ ] Agregar una breve explicacion de que son
- [ ] Agregar un parrafo donde nombres los mas conocidos
- [ ] Explicar la funcionalidad del metodo `__init__()` y `__str__()`.
- [ ] Las instrucciones deben pedir crear una clase que tenga estos metodos y luego llamarlos para validarlo
- [ ] El test debe validar la clase y cada uno de los metodos

**Comment by josemoracard** [comment]
ejercicio:

https://github.com/4GeeksAcademy/master-python-programming-exercises/pull/67
