### ISSUE TITLE
No puedo asignarle una cohorte a un estudiante

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#6766]
### Bug description

En el admin, cuando entro a un estudiante, le doy al botón de "add cohort" y no hace nada

### Steps to reproduce

Entrar en un estudiante, ir al listado de las cohortes donde está asignado y darle al botón de Add cohort

**Comment by tommygonzaleza** [comment]
Tienes que seleccionar la cohort para poder agregarlo
