### ISSUE TITLE
Agregar tabla `authenticate.CredentialsRigobot`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6770]
En esta tabla debemos guardar:
- rigobot_id: int
- token (optional, token to access the rigobot api on behaf of this user)
- token_expires_at (optional)
- user: Relationship with user.
- created_at
- updated_at

**Comment by jefer94** [comment]
Esto está en contra de como está documentado que funciona la conexión entre los servicios, en función de los servicios first parties

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1265
