### ISSUE TITLE
Rediseñar modal para ver tus code reviews

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6771]
Un estudiante deberia poder ver los code reviews que ha recibido en una de sus tareas. Actualmente [esta es la modal](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13172%3A36037&mode=design&t=gQo90OigKl497LHB-1) que diseñamos antes, esta es la que se usa para la vista de los profesores cuando van a escoger un archivo para hacer un code review de ese archivo, sin embargo, no nos sirve para el estudiante, ya que no se debe mostrar archivos sino code reviews.

De cada code review de la lista de code reviews de esta tarea, se debe mostrar:

- Nombre del archivo al que se le hizo el review
- Preview del comment (Opcional: Agrega una propuesta que no cambie mucho el componente)
- Recibes el lenguaje del archivo, entonces lo puedes usar para mostrar el icono de la tecnologia en el icono del archivo
- Opcion para hacer rating bueno o malo. Al darle a cualquiera de las opciones tiene que abrir una modal con un textfield y dos botones, uno que diga submit (Inhabilitado hasta que el comentario tenga al menos 30 caracteres, agrega ambas versiones habilitado e inhabilitado), y otro que diga skip 
- Debe tener un boton para poder ver el code review (No debe estar marcado como que ya lo vio, ese indiferente, el boton debe quedar siempre como para ver el code review)

**Comment by tommygonzaleza** [comment]
- [ ] El preview del comentario debe ser scrollable si es muy largo el mensaje.
- [ ] El preview del comentario debe poder mostrar un markdown que tenga, titulos, ejemplos de codigo, etc.
- [ ] Cuando le da a feedback, debe haber boton de Go back y el otro de Send. Abajo de ellos mas pequeño y como link, debe estar un link de skip.
- [ ] Cuando le da a feedback, donde te permite agregar el comentario, debe mostrar cual feedback esta dando (Bueno o malo) opacando el no seleccionado.
- [ ] Quitar la modal que teniamos antes en el flujo (Reacomoda el flujo para que muestre todo lo actualizado)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=Pz3eKEKObAxJCZnS-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar el diseño en mobile, no debe permitir ver la ultima modal donde se muestra el codigo del archivo y el comentario. Solo debe llegar hasta donde escoge los code reviews y ve un preview del comment

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=GQn6nyFF8M7byKj3-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar un icono de un archivo generico, que se utilice cuando no se encuentra la tecnologia del archivo.
- [ ] Cambiar el color del icono que muestra cuando aun no has hecho feedback de rojo a amarillo
- [ ] Mostrar el comentario del feedback que dio el alumno en mobile una vez que fue enviado

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=bXMKUOW0BtLvGjhV-1

**Comment by tommygonzaleza** [comment]
- [ ] El color de cuando no se ha dado feedback todavia deberia ser amarillo en vez de azul o rojo
