### ISSUE TITLE
Se esta tapando el titulo de outcomes en movil

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6773]
Occurre en: https://4geeksacademy.com/us/outcomes en movil.

## Solucion

- [ ] Actualmente se puso el valor fijo en la variable donde se define el valor de si se muestra el CustomBar o no como true, debes obtenerlo de la informacion del location. [Este es el codigo](https://github.com/4GeeksAcademy/website-v2/blob/8d92fd017ddf3874e0f20d4a93988938d5aa0385/src/components/NavbarDesktop/index.js#L204)
- [ ] Cambia el div que abarca al CustomBar y al Navbar para que tenga position sticky, esto empujara el resto del contenido para abajo, de modo que no hara falta agregarle margin ni mucho padding (Un poco si, lo que tiene en los lados tambien) para que se pueda ver bien el contenido

> Recuerda que es solo en movil

![Screenshot 2024-01-19 at 1 20 45 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/7b0db424-41f0-4c93-a521-a937d6af9566)

**Comment by andresmedtr** [comment]
Confirmed

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1924

**Comment by Khrisefzm** [comment]
New PR: https://github.com/4GeeksAcademy/website-v2/pull/1942

**Comment by tommygonzaleza** [comment]
- [ ] Se ve todavia un poco del borde azul cuando lo pruebo con el iphone 14 pro max.
![Screenshot 2024-02-20 at 2 35 05 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/3f3b09e6-ee62-49de-940f-e623e697ff3a)
