### ISSUE TITLE
Permitir pasar parametros a Code Blocks en Markdown Parser

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6775]
La idea es permitir pasar parametros como [este](https://docusaurus.io/docs/markdown-features/code-blocks#code-title), en nuestros code blocks de nuestro markdown parser.

Agregar los siguientes parametros:

- `runable`, debe ser false por defecto. Si es true entonces el siguiente codigo se muestra con el componente CodeViewer, de ser false, entonces se debe mostrar como se muestra actualmente, el codigo normal y ya como en GitHub tambien.

> Sin este issue no se puede pasar a produccion el CodeViewer

**Comment by gustavomm19** [comment]
Parece que el Markdown Parser no admite este tipo de sintaxis. En su lugar, sugiero usar como etiqueta ` <codeviewer>` para hacer wrapp a los snipets de codigo que utilicen el CodeViewer
