### ISSUE TITLE
4Geeks's logo is cropped

### ISSUE THREAD

**Issue by andresmedtr** [breatheco-de/breatheco-de#6779]
### Bug description

When entering the main page, the logo is cropped

![image](https://github.com/breatheco-de/breatheco-de/assets/123752360/273af8f1-a50f-40d1-8bb9-ef8d4929ac2c)

source url: https://4geeksacademy.com/us/index

### Steps to reproduce

Enter the URL in your browser
Check the Logo

### Expected behavior

It should look like this

https://coursereport-s3-production.global.ssl.fastly.net/uploads/school/logo/260/original/Logo-B_4Geeks_Nuevo.png

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1925

I change the logo for the new one in the Desktop navbar.

![Image](https://github.com/breatheco-de/breatheco-de/assets/129009072/b886eb82-37a7-4599-8bb1-e7f8e9f073c4)

And in the mobile navbar:

![Image](https://github.com/breatheco-de/breatheco-de/assets/129009072/2721b0ab-d507-4644-8542-2c987dcd6ed8)

**Comment by tommygonzaleza** [comment]
- [ ] Cambia el branch al que haces el PR para que sea a `development` en vez de `master`

**Comment by Khrisefzm** [comment]
New PR: https://github.com/4GeeksAcademy/website-v2/pull/1943

**Comment by tommygonzaleza** [comment]
Todo bien, esperando a que se acepte el PR
