### ISSUE TITLE
No esta funcionando el sign up en dev con el host de produccion

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6783]
Por alguna razon, solo con el servidor de produccion en dev.4ggeks.com, no avanza cuando llenas el formulario de registro en vista de checkout

https://github.com/breatheco-de/breatheco-de/assets/56565994/4c02b013-db13-4dd1-b9d6-d8b3f6379e47

> Frena pasar dev a produccion

**Comment by ArielCalisaya** [comment]
Corregido en este commit [fix bug in signup and modify icon size](https://github.com/breatheco-de/app/pull/1297/commits/0d1d1096fcc8c2fe6ae4dbb0b63ed9a429b6561a)

**Comment by tommygonzaleza** [comment]
Sigue ocurriendo
