### ISSUE TITLE
Mejorar metadatos de un curso

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6784]
Debemos poner los metadatos que vendan mas, lo que es mas atractivo para un usuario nuevo

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=ZAu767Crv8r3lHDr-1
