### ISSUE TITLE
Solucionar API para generacion de thumnails

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6786]
Esta tarera que genera thumnails esta fallando.
https://github.com/breatheco-de/apiv2/blob/90f2502f8847dbadfb6549ac794a063c515fa02c/breathecode/registry/tasks.py#L128

Vamos a reemplazar el cloud function por el API de screenshot machine.
https://www.screenshotmachine.com/website-screenshot-api.php#api_doc

Agregar un action para que tome el screenshot con screenshot machine y utilizarlo en este [receiver](https://github.com/breatheco-de/apiv2/blob/053e1507c504ee3c094137a1290687eed4c63116/breathecode/registry/receivers.py#L38)

**Comment by tommygonzaleza** [comment]
- [ ] Chequea el review que te dejo Jeferson en el PR

**Comment by tommygonzaleza** [comment]
- [ ] Crear un script que busque todos los assets que no tengan preview o cuyo preview contenga el nombre del archivo de la variable de entorno `DEFAULT_ASSET_PREVIEW_URL`, y generarle el thumbnail nuevo.
