### ISSUE TITLE
Cambiar estructura de vista de assets para que sean iguales

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6804]
Las vistas de los assets deben tener la misma estructura, es decir, arriba debe estar el header donde se muestran los pills de las tecnologias, el titulo del articulo, etc. Al lado izquierdo debe estar el contenido que debe ser siempre del mismo tamaño y al lado derecho deben estar widgets, showonsignup, cta, etc, que deben ser tambien siempre del mismo tamaño. 

Teniendo asi los assets siempre con la misma estructura

**Comment by ali5uarez5** [comment]
De un lado estan los componentes y del otro están los templates

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13399%3A43033&mode=design&t=Pz3eKEKObAxJCZnS-1

**Comment by tommygonzaleza** [comment]
No se va a implementar
