### ISSUE TITLE
Registrar a los usuarios de 4geeks en rigobot al crear el usuario

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6812]
Queremos que la sincronizacion con rigobot sea automatica. Para esto, debemos utilizar el servicio `GET /v1/auth/me/token?breathecode_token=` de rigobot para que rigobot lo agregue en su base de datos. [Aqui esta la documentacion del endpoint](https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#0060b86e-4d57-4f6d-ad26-89527c3357b7)

Esto se debe hacer en el [callback de github cuando el usuario se sincroniza su cuenta con github](https://github.com/breatheco-de/apiv2/blob/28bd3c7d318eef84fab5f0676b928dce658c4670/breathecode/authenticate/urls.py#L87C11-L87C27), desepues de que las credenciales ya existen, podemos ejecutar el endpoint de rigobot para que se sincronice con rigobot.

**Comment by tomasgonzaleza** [comment]
Debes usar este endpoint:
![image](https://github.com/breatheco-de/breatheco-de/assets/71781086/90591ffc-88ae-40f8-b814-4bca779b5217)
