### ISSUE TITLE
Unificar documentacion de projecto final para 4Geeks

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6815]
Vamos a tener un modulo de projecto final

### Desarrollar y/o actualizar las siguientes lecturas

- [ ] [Porque construir un projecto final](https://4geeks.com/docs/knowledge-base-4geeks/why-build-a-final-project).
- [ ] [Como elegir el projecto final](https://4geeks.com/docs/knowledge-base-4geeks/pick-your-capstone-project#general-requirements-for-capstone-projects).
- [ ] Guia de proyecto final (general, luego linkea a fullstack o datascience o cibersecurity).
- [ ] Guia de projecto final para profesores.

Solo las cosas que no tienen en comun:

- [ ] Guia de project final para alumnos (fullstack)

- [ ] Guia de proyecto final para alumnos (datascience)
- [ ] Guia de proyecto final para alumnos (ciberseguridad)

### Estas son otras fuentes de contenido importantes:

Vercel "interactivo"
https://fullstack-final-project.vercel.app/

[Guía para profesores](https://4geeksacademy.notion.site/Gu-a-para-mentores-sobre-el-proyecto-final-c7071a03134d4bcab1dda66079a78e8e).

[Guia para estudiantes](https://4geeksacademy.notion.site/Gu-a-sobre-el-proyecto-final-para-estudiantes-f5fe79165dc5408fa83e7a2704e5d7be).

[Guía sobre el proyecto final para estudiantes | Notion](https://4geeksacademy.notion.site/Gu-a-sobre-el-proyecto-final-para-estudiantes-f5fe79165dc5408fa83e7a2704e5d7be).

**Comment by arnaldoperez** [comment]
Recursos

- https://4geeksacademy.notion.site/Gu-a-para-mentores-sobre-el-proyecto-final-c7071a03134d4bcab1dda66079a78e8e
- https://4geeksacademy.notion.site/Gu-a-sobre-el-proyecto-final-para-estudiantes-f5fe79165dc5408fa83e7a2704e5d7be
- https://fullstack-final-project.vercel.app/
- https://4geeks.com/interactive-coding-tutorial/full-stack-project-stories-and-wireframes
- https://4geeks.com/docs/knowledge-base-4geeks/pick-your-capstone-project#specific-requirements-by-program
- https://4geeks.com/docs/knowledge-base-4geeks/why-build-a-final-project

**Comment by alesanchezr** [comment]
enfocarse solo en esto esta asemana.

**Comment by alesanchezr** [comment]
Módulo 30 - Historias de usuario
📗 [¿Por qué construir un proyecto final?](https://4geeks.com/es/lesson/porque-construir-un-proyecto-final)
📗 [Creando Historias de usuarios](https://4geeks.com/lesson/user-stories-examples)
📗 [Introducción al desarrollo profesional y ágil](https://4geeks.com/lesson/agile-development)
 📗 [¿Cómo debe ser un proyecto Full-Stack para tu portafolio?]
 📗 [¿Cómo debe ser un proyecto de DataScience y Machine Learning para tu portafolio?]
 🧪 Historias de usuario (Product Backlog) y alcance del proyecto final
Módulo 31 - Diseño y Wireframes
 📗 Introducción al diseño UI/UX
 🧪 Wireframes del proyecto final
Módulo 32: Arranque del proyecto final
 📗 Repositorio de apis externas para realizar proyectos
 📗 Librerías populares
 📗 Modelado de base de datos
 🧪Modelado de datos de un Zoológico https://app.quickdatabasediagrams.com/#/
 🧪Modelado de datos del proyecto
