### ISSUE TITLE
Esta dando error 500 en vista de checking

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6820]
El problema parece estar relacionado con el lock. Abajo pongo imagenes de lo que salio:

Me paso con mi usuario (5301), al intentar comprar el plan pago. Luego intente sin tener un usuario y me funciono bien el endpoint.

![Screenshot 2024-01-29 at 8 02 27 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/79c4e92b-5b2b-4f9f-884a-8fda50feb7cf)
![Screenshot 2024-01-29 at 8 02 19 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/25ab1b31-050c-4e48-9d70-90fcbffb3c70)

**Comment by jefer94** [comment]
La solución pasa por crear un `lock` por usuario en vez de hacer el chequeo dentro del `get_or_create`, esto se está causando por mandar 2 requests para hacer la misma acción, los endpoints afectados podrían ser, el bag, el checking y todos los pay (plan y consumible), el comportamiento debe ser, la primera acción se hará, la segunda se rechazará y se le hará saber al frontend su error

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1354

**Comment by jefer94** [comment]
El lock cuando se liberaba, aun no habia liberado la transaccion, por lo tanto, cuando llegaba la segunda solicitud del frontend erronea, cuando se liberaba el primer lock aun no habia sido commiteado, por lo tanto se crean 2, y si despues intentas acceder a el, el get consigue 2 objetos
