### ISSUE TITLE
Crear una landing para cada keyword (empezar con la primera para probar)

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6822]
Basado en [este archivo excel](https://docs.google.com/spreadsheets/d/1FNy0W4NMcwxYsoxlLCuTkq0dpOE0W3GrvmVzTYdQk7Q/edit#gid=0). 

Vamos a crear [un landing page para cada keyword](https://www.awesomescreenshot.com/image/45677037?key=44e773a22e26e830782382a610cdc3ea), tenemos que cada uno pensando en ese keyword, el H1, un par de. h2 y algunos parrafos deben mencionar la keyword o algo parecido.

Empecemos con una sola y me la pasas para ver como queda.

Landing 1:
"front end developer bootcamp"

Landing 2:
[coding bootcamp]
"programming bootcamp"

Landing 3:
"coding bootcamp without degree"
"coding bootcamp no experience"
"coding bootcamp with job placement"

Landing 4:
- [x] "full stack developer bootcamp"

Landing 5:
"programming bootcamp near me"

Landing 6:
- [x] "web developer bootcamp"

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1954/files?diff=unified&w=0

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1962

**Comment by alesanchezr** [comment]
faltan bastantes keywords

**Comment by G-code7** [comment]
- https://github.com/4GeeksAcademy/website-v2/pull/1983 <--- este fue una actualización de mi branch master, lo paso porque acá ahay unos cambios en awards  y programming-bootcamp-near-me **created**

- https://github.com/4GeeksAcademy/website-v2/pull/1985 <--- actualización de: 
-   front end developer bootcamp
-   fullstack developer bootcamp
-   full stack conding bootcamp
-   no experience coding bootcamp
-   web development bopotcamp
