### ISSUE TITLE
Vista de detalles de evento

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6827]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/24539603?key=a4480891fa6473858ff678b80c3b960e&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/24539603?key=a4480891fa6473858ff678b80c3b960e

**Comment by tommygonzaleza** [comment]
- [ ] Deberia mostrar `No name` en vez de `
![Screenshot 2024-02-20 at 12 20 46 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/a949d7ac-4a01-4e09-83ff-183472523d7a)
undefined undefined`
