### ISSUE TITLE
Review pricing componente to check why its not showing the different programs on finantials

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6836]
![All the ways you can pay (or not) at 4Geeks Academy · 4Geeks Academy](https://github.com/breatheco-de/breatheco-de/assets/426452/472201f1-8e5d-4e2d-9ffd-523da46f2df4)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1966

**Comment by tommygonzaleza** [comment]
- [ ] Agregar la tipografia usada en el resto de la pagina cuando se escoge un programa que no esta disponible en un location.
- [ ] Quitarle el border-radius a los dropdown de location y program
![Screenshot 2024-02-20 at 5 12 39 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/8346d175-4b70-42ec-901f-539c8b697431)

**Comment by tommygonzaleza** [comment]
Todo bien, solo falta aceptar el PR
