### ISSUE TITLE
Location page on the website must have partners section with only partners from that campus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6837]
[Similar to this section](https://www.awesomescreenshot.com/image/45754556?key=d535406a8cf7c5fd37b6131149b77ef6) but with miami-first partners.

**Comment by tommygonzaleza** [comment]
Debemos agregar en el yml del location el listado de partners que se va a mostrar, que debe ser un carousel, y luego utilizarlo en el landing de cada location
