### ISSUE TITLE
Cambiar los headers de todas las paginas del website

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6839]
Cambiar los headers para que esten acordes al diseño nuevo que se ha ido incorporando en el home, financials, etc.

**Comment by ali5uarez5** [comment]
Home: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=8258%3A6529&mode=design&t=1WZdM8kNY0oZJtdi-1

**Comment by ali5uarez5** [comment]
20 Millions: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7025%3A10646&mode=design&t=1WZdM8kNY0oZJtdi-1

**Comment by alesanchezr** [comment]
Comentarios sobre header del home: https://www.awesomescreenshot.com/image/45962179?key=8d8853a59b855626149e1707cb30a675

**Comment by ali5uarez5** [comment]
20 millions: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7025%3A10646&mode=design&t=FZwt0SpSbYLfv2Hh-1
