### ISSUE TITLE
Agregar sensacion de descuento en el pricing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6846]
En el pricing de 4geeks academy, se debe agregar una sensacion de que se esta ofreciendo un super descuento. 

Estos seran los precios nuevos de cada uno de los programas:

- Full-Stack Part-time- $14,500
- Full-Stack Full-time $18,500
- Data Science and Machine Learning Part-time - $15,500

Pero en todos lados que eso salga, tiene que estar, SIEMPRE, un logo que dice o algo que diga: 40% OFF

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=11567%3A18380&mode=design&t=m9xqSmCGQomXscUM-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar un sello o algo que haga entender que estamos ofreciendo descuentos en este momento

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=11567%3A18380&mode=design&t=gfGBnLjUxHsjRu96-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar un sello como el de job guarantee pero de descuento que se pueda poner a la izquierda para representar que estamos en un descuento limitado
- [ ] En la pagina tiene que haber la sensacion de hay un descuento por tiempo limitado y que tienen que aprovecharlo porque se puede acabar

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7137
