### ISSUE TITLE
Cambiar imagen en diseño de Home

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6853]
Esta una imagen de 4geeks academy que es muy oscura, no va con los colores ni el mood de la pagina. Esta es la imagen que se debe cambiar: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8210%3A39885&mode=design&t=9C9Lv0Y4WCPhZ8zk-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8210%3A39885&mode=design&t=2LjRaIDSPHHkU5Ol-1
