### ISSUE TITLE
Listado de mentorias no corresponde con el syllabus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6854]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45846226?key=c20cafca25655aeddc5db89e06d58d9c&size=orig) 

 Los servicios y mentores de las mentorias que estan listados en el dashboard de la cohort deberiar pertenecer al mismo syllabus que el syllabus de la cohort en el dashboard.
 
1. Cuando hagas el request al backend asegurate de los mentores filtrando por syllabus y servicio asociado, si alguno de los servicios no retorna ningun mentor, entonces no lo muestras.
~2. Luego revisa que servicios tienen asociados los mentores que te quedan filtrados.~ 
~3. Luego remueve todos los servicios que no tengan a esos mentores.~

---
**Source URL**:
[https://4geeks.com/cohort/machine-learning-prework/prework-machine-learning-python-2w/v3](https://4geeks.com/cohort/machine-learning-prework/prework-machine-learning-python-2w/v3)

**Comment by tommygonzaleza** [comment]
Intente con el prework de miami usando el host de produccion y no funciono, no esta mostrando ningun servicio de mentoria
