### ISSUE TITLE
Rediseñar call to action en mobile

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6855]
El call to action debe mostrarse en movil tambien, actualmente tenemos esto pero es terrible:

![Screenshot 2024-02-06 at 5 05 58 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/b1f3067b-b2ec-4f77-a9f5-a712eebb15b5)

**Comment by ali5uarez5** [comment]
podemos usar este formato https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=10534%3A25195&mode=design&t=2LjRaIDSPHHkU5Ol-1

o colocar el componente dentro del body

**Comment by tommygonzaleza** [comment]
Cambia tambien el componente para unirse al evento en movil para que se vea como este y reutilizas el componente en ambos lugares

**Comment by tommygonzaleza** [comment]
- [ ] Tiene que estar con sticky y acompañarlo siempre
