### ISSUE TITLE
Hay una imagen rota en el asset intro-to-pandas

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6856]
![Screenshot 2024-02-06 at 5 40 57 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/d9fc6344-aa8f-4a98-b148-867e03dcbaa9)

**Comment by Lorenagubaira** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/102861577/0f8c414d-491c-4ced-ac3e-b93f0f808992)

**Comment by Lorenagubaira** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/102861577/c3c24cdd-0f67-4831-8c9d-fb9c29c3fe98)

`

**Comment by Lorenagubaira** [comment]
`ya se ve en ambos idiomas
