### ISSUE TITLE
Cambiar los links de los botones en los landings para que apunten a #learnform_header y #learform_bottom en lugar de #top y #bottom

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6859]
- [ ] Revisar todos los botones, no solo el TopBar sino TODOS los botones en los landings. Puedes hacer una busqueda massiva de #top y otra de #bottom para reemplazar.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45871427?key=05e940c5a8a03183ed04300d017e76c9&size=orig) 

 Esto hay que hacerl porque en mobile #top y #bottom no funcionan igual, los formularios quedan afuera del viewport.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1959/files
