### ISSUE TITLE
Falta logo de 4geeks en navbar en mobile

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6861]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45871922?key=a980a7e3da7565200833e8c37b63eec9&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-alesanchezr-master-geeksacademy.vercel.app/es/landing/clases-de-programacion-santiago-chile](https://website-v2-git-fork-alesanchezr-master-geeksacademy.vercel.app/es/landing/clases-de-programacion-santiago-chile)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1972
