### ISSUE TITLE
Page title is out of the layout

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6862]
Make sure its contained

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45872342?key=bfb33aebf4b1fec10dd0840424a99dc4&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero](https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1951

**Comment by tommygonzaleza** [comment]
No lo resuelvas con porcentajes y agregandoles unos paddings desde donde llamas al componente. El componente header debe tener un max-width del que no debe pasarse ademas, este debe tener un padding por defecto, asi como funciona bootstrap con la clase container que le aplica cierto padding

**Comment by tommygonzaleza** [comment]
- [ ] Mira el padding que tiene el componente a los lados, debe llegar al final siempre en ambos lados
![Screenshot 2024-02-27 at 2 44 45 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/bf208bed-5aa5-4a9b-99ee-8afb37f9866f)

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1951
