### ISSUE TITLE
Crear un endpoint para consumir un consumible

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6866]
Este es el URL para este servicio: `PUT /me/service/<service_slug>/consume/<hash>`

Debe generarse una sesion de consumo cuando se manda este PUT, si el evento del consumible falla, se utiliza la siguiente URL

Este es el URL para cancelar la sesion de consumo en caso de falle la accion en el front end y no se le quiera cobrar: Este es el URL para este servicio: `PUT /me/service/<service_slug>/consume/<hash>/canceled`

> Learnpack debe generar un hash a partir del codigo que se hara build o test y pasarlo por la URL

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1352
