### ISSUE TITLE
Crear comando para sincronizar usuarios con Rigobot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6868]
Este comando es para sincronizar con Rigobot a los usuarios que ya esten sincronizados con GitHub. Para esto debes crear un comando que ejecute el request `GET /v1/auth/me/token?breathecode_token=` para cada uno de los usuarios que si esten sincronizados con GitHub.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1265
