### ISSUE TITLE
Agregar link al podcast en el navbar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6873]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45901899?key=1b045c1834d2b4e7db04a3388a53661b&size=orig) 

 - [ ] Pedirle a Ali el icono del podcast con el microfono.

---
**Source URL**:
[https://4geeks.com/podcast](https://4geeks.com/podcast)

**Comment by ArielCalisaya** [comment]
@tommygonzaleza  Este issue ya ha sido resuelto
