### ISSUE TITLE
En el reporte del estudiante, no refleja las mentorías que ha pedido, siempre es 0. 

### ISSUE THREAD

**Issue by ehiber** [breatheco-de/breatheco-de#6875]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/56272634/f3f8625d-fd68-4b58-851a-85196f73c618)

### Steps to reproduce

Ver cualquier reporte de los alumnos

### Expected behavior

Reflejar la cantidad de mentorias que ha tenido el estudiante de manera satisfactoria

**Comment by tommygonzaleza** [comment]
- [ ] Utiliza la actividad `mentorship_session_checkin`
