### ISSUE TITLE
Cuando un cohort dashboard de una cohort con status=FINAL_PROJECT, el profesor, el TA y el staff debe ver la lista de final projects

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6878]
Ahora mismo la ventana que aparece cuando haces click en ese widget es para que el alumno suba su projecto.

Si eres staff de la academia la ventana y el mensaje deberian ser diferentes: 

**Titulo de la caja**: `Review final projects`
**Mensaje**:  `We are almost there! Make sure students submit their projects ASAP. Click on the following button to review them.`
**Mensaje del boton**: `List Projects`

Si le das al boton de `List Projects` te aparece una modal con todos los projectos, cada projecto tiene un titulo, descripcion, link a github y aparecen los avatares de los miembros del equipo. El link a github le puedes dar click para que te lleve a github.

Adicionalmente los projectos pueden tener un live link, que tambien le peudes dar click para abrir el projecto en vivo.

La caja tambien tiene un warning que dice cuanta gente falta por subir su projecto y sus avatares. `The following students are still pending to upload their final project information`

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45918225?key=e0618a629414a9c0adf87baa35b3a901&size=orig) 

---
**Source URL**:
[https://4geeks.com/cohort/full-stack-fake-6/full-stack-pt-18w/v2](https://4geeks.com/cohort/full-stack-fake-6/full-stack-pt-18w/v2)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13951%3A69785&mode=design&t=YY6jJKkPVd7mv80O-1

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/49b6b9b0-294c-4e3a-be79-c88891dfaf35)

**Comment by alesanchezr** [comment]
La cajita que le avisa al profesor para revisar los proyectos esta bien.

En lugar de abrir los proyectos en una modal. vamos a llevar al profesor a la vista de assiggnments pero en pestaña nueva: students view, project view y la nueva es "final projects".

En el componente de DottedTimeline poner un icono si entrego o no el projecto final.

En el student cohort report agregar al principio de las actividades una caja sobre si entrego o no el proyecto final.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=14027%3A74408&mode=design&t=Q8jye4y8vF4lhoC7-1

**Comment by tommygonzaleza** [comment]
- [ ] Solo mostrar maximo dos lineas de la descripcion del proyecto, de ser mas largo se deben mostrar tres puntos suspensivos y decir See more.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=14027%3A74408&mode=design&t=nA4dJRKXY3KrAtzj-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregale la foto del proyecto en caso de que tenga foto en la lista de final projects.
- [ ] Agrega un warning que indique cuantos estudiantes faltan por final project. Debe decir: `The following students are still pending to upload their final project information`. Lo ponemos arriba de la lista, parecido a como se muestra en el componente de feedback. Al darle click se debe mostrar en una modal (Seria una lista de alumnos que faltan por entregar el final project).

**Comment by tommygonzaleza** [comment]
- [ ] Debemos permitirle al profesor modificar el revision status del final project desde esta lista, por lo que se deben mostrar estos dos estados Project Status (Pending o Done), este se muestra como un tag del status y ya, no se modifica. Y Revision Status (Se muestran las opciones en la imagen), se debe permitir cambiar desde esta vista, deberiamos tener un boton de add review, que al darle se abra una modal y le permita aprobarlo o rechazarlo, ademas de agregarle un comentario (Igual a la que se usa para los demas proyectos actualmente).

Esta es la imagen con los estados del Revision Status.
![Screenshot 2024-02-27 at 1 54 20 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/7b6a235f-5220-485a-a1cc-44f6c66bbd96)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13951%3A69785&mode=design&t=vLsESmg086rtjF7H-1

**Comment by tommygonzaleza** [comment]
Se desarrollara [aqui](https://github.com/breatheco-de/breatheco-de/issues/7307)
