### ISSUE TITLE
Keep showing up final project modal until student submits the project

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6879]
Right now if the student decides to close the final project modal we are saving on the local storage a boolean to avoid showing it in the future. This needs to change, its not ideal.

## Close the modal only until window refresh

 - [ ] If the student decides to close the final project modal, we will close it without saving anything on the local storage, don't use local storage anymore.
 - [ ] When the website refresh, lets check if the final project was submitted, if it WAS NOT submitted, we make the modal show up.

**Comment by tommygonzaleza** [comment]
- [ ] Quitaste la modal de FinalProject
