### ISSUE TITLE
Boton de download no sirve en explorer de django

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6884]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45954703?key=3d39186d6806680c990f856b6f1195ce&size=orig) 

---
**Source URL**:
[https://breathecode.herokuapp.com/explorer/56/](https://breathecode.herokuapp.com/explorer/56/)

**Comment by jefer94** [comment]
https://github.com/chrisclark/django-sql-explorer/issues/588
