### ISSUE TITLE
Subir testimoniales a la seccion de testimoniales del website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6896]
- [Veronica Larrondo](https://www.youtube.com/watch?v=hpvI_iBaX28).
- [Gabriela Rodriguez](https://www.youtube.com/watch?v=l0OgTgDIMnM).
- [Kevin Soria](https://www.youtube.com/watch?v=JcZpQkKwP4E).
- [Mattia Tozzi](https://www.youtube.com/watch?v=B01-eTfgqqc).
- [Josh Lewis](https://www.youtube.com/watch?v=ZlyVlif9jts).
- [Ernesto](https://www.youtube.com/watch?v=s5buJw_i2Hc).
- [Javier Murillo](https://www.youtube.com/watch?v=c14ZDHXN6_w)
- [João Xavier](https://www.youtube.com/watch?v=MBXqEnhodx0)
- [Hernan Garcia](https://www.youtube.com/watch?v=ln3bQsV1BaQ)

## Alumnos de boca code

Para estos alumnos de boca code, puedes buscar sus descripciones y bio aqui:
https://bocacode.com/alumni

Aqui estan los videos:
- [Vitoria](https://www.youtube.com/watch?v=IcFxpxvJfC8).
- [Dariel](https://www.youtube.com/watch?v=rvQl5zFUVPQ)
- [Manny's](https://www.youtube.com/watch?v=fiECVWMZ85U).
- [Diana Tineo](https://www.youtube.com/watch?v=nDubSBOJlMA).

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2038

**Comment by alesanchezr** [comment]
Esto sigue igual, todos los tesimoniales deberian tener el texto.
