### ISSUE TITLE
Implementar padina de podcast sin iframe dentro de next.js

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6897]
Ahora mismo metimos un iframe dentro del react, pero los links a spotify no estan funcionando, tenemos que quitar el iframe y desarrollar el landing nosotros para poder tener el control.

Modifica el HTML de esta [pagina de podcast](https://github.com/breatheco-de/app/blob/main/src/pages/podcast.jsx) para que en lugar de ser un iframe sea con react.

Puedes usar este iframe para listar los episodios en la pestaña de "episodes":

```html
<div id='buzzsprout-large-player'></div><script type='text/javascript' charset='utf-8' src='https://www.buzzsprout.com/2309390.js?container_id=buzzsprout-large-player&player=large'></script>
```

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45981909?key=545f067b755c2d4fed3668b81ff7e00d&size=orig) 

---
**Source URL**:
[https://4geeks.com/podcast](https://4geeks.com/podcast)

**Comment by tommygonzaleza** [comment]
Aqui esta el diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=14047%3A61363&mode=design&t=gOgL2L4T7UqIgrOQ-1

**Comment by tommygonzaleza** [comment]
- [ ] Link de Spotify esta roto, este es el nuevo: https://open.spotify.com/show/4jOf9ngqajCcVgOEXmtiNW?si=817061bc53cc4ace
- [ ] Agregar el resto de logos de los lugares donde se puede escuchar el podcast.
- [ ] El max-width de los componentes debe ser de 1280px

**Comment by tommygonzaleza** [comment]
- [ ] Puedes sacar los iconos aqui: https://podcast.4geeks.com/
