### ISSUE TITLE
Introducir el "path" para el CodeViewer

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6899]
Hay un nuevo prompt template que vamos a utilizar para el CodeViewer: `code-compiler-with-context` que tiene el ID: `32`

Si encontramos varios ejemplos de código dentro del mismo archivo de markdown y ademas esos archivos tienen un `path`, entonces esos archivos se van a considerar parte del mismo proyecto y Rigobot los incluira todos dentro del contexto a la hora de simular el compilador. Por ejemplo:

Consideremos un markdown que tiene estos dos ejemplos de codigo en lugares diferentes:

Primero tenemos este ejemplo de codigo en python con parametros ` runable=true path=./main.py`

```py runable=true path=./main.py
import csv, json, yaml

def load_csv():
	filePointer = open("bitcoin_prices.csv", "r") 
	csv_f = csv.reader(filePointer)
	prices = []
	for row in csv_f:
		prices.append({
			"ticker": row[0],
			"date": row[1],
			"price": row[2]
		})
	print(prices)
```

Luego varios parrafos mas abajo tenemos este `path=./bitcoin_prices.csv` pero que no tiene `runable` porque no es necesario ejecutarlo directamente:

```csv path=./bitcoin_prices.csv
Currency,Date,Closing Price (USD)
BTC,2019-10-29,9455.7246926058
BTC,2019-10-30,9225.9954793378
BTC,2019-10-31,9131.4106303055
BTC,2019-11-01,9197.6323446207
BTC,2019-11-02,9290.8966023936
```

Cuando el CodeViewer vaya a recibir el codigo que va a ejecutar, tambien recibira otros codigos que no va a ejecutar pero que si sera parte de su contexto que le va a pasar a rigobot.

Rigobot va a recibir algo como esto:

Main file:
```txt
File path: ./main.py
File content:
import csv, json, yaml

def load_csv():
	filePointer = open("bitcoin_prices.csv", "r") 
	csv_f = csv.reader(filePointer)
	prices = []
	for row in csv_f:
		prices.append({
			"ticker": row[0],
			"date": row[1],
			"price": row[2]
		})
	print(prices)
```

Secondary files:
```txt
File: ./bitcoin_prices.csv
File content:
Currency,Date,Closing Price (USD)
BTC,2019-10-29,9455.7246926058
BTC,2019-10-30,9225.9954793378
BTC,2019-10-31,9131.4106303055
BTC,2019-11-01,9197.6323446207
BTC,2019-11-02,9290.8966023936
```

La LLM que usa rigobot va a simular que esos archivos estan en el mismo directorio pero con nombres diferentes y los incluira dentro del contexto ejecutable.

# Nota importante:

Da igual si los codigos estan uno detras del otro o no, pueden pertenecer a cualquier parte del archivo, todos los que tengan un `path` seran parte del mismo contexto.

**Comment by gustavomm19** [comment]
https://chat.openai.com/share/5d837b0a-17ef-4ae4-b4c6-062e7e8490d0
