### ISSUE TITLE
No estamos usando el componente de workshops

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6900]
La forma como se deberian visualizar los workshops [es así](https://www.awesomescreenshot.com/image/45989679?key=62579392245cc37b518566f6628396d3).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/45989671?key=426dd898b9e38112ce0d09fcf3099e00&size=orig) 

---
**Source URL**:
[https://4geeks.com/lesson/what-is-object-oriented-programming-concepts](https://4geeks.com/lesson/what-is-object-oriented-programming-concepts)

**Comment by tommygonzaleza** [comment]
Pon para que todas las cards de workshops tengan 300px de width 

![Screenshot 2024-02-16 at 5 49 18 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/21fa0c44-9d3b-4e03-9fd7-fd9452e02269)
