### ISSUE TITLE
Todos los botones deben ser cuadrados

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6908]
No deben tener border-radius o este debe ser 0.

- [ ] Cambiar el componente del boton para que no tenga borde y asegurarte de que se utilice en todos los landings, navbar, etc.

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1965

**Comment by tommygonzaleza** [comment]
Todo bien. Esperando a que se acepte el PR.
