### ISSUE TITLE
Crear diseño del landing del podcast

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6909]
Este es el landing que tenemos actualmente: https://4geeks.com/podcast.

Se debe rediseñar mostrando todo lo que se muestra actualmente en el landing pero con los estilos de 4geeks, reutilizando los componentes que se puedan reutilizar.

Debes cambiar la barra de progreso del podcast cuando se escucha ahi mismo en el landing por la que se utiliza regularmente en 4geeks.com para mostrar el progreso de la cohort

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=14047%3A61363&mode=design&t=nA4dJRKXY3KrAtzj-1

**Comment by tommygonzaleza** [comment]
- [ ] Poner la seccion de los hosts abajo de los episodios

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=14047%3A61363&mode=design&t=gOgL2L4T7UqIgrOQ-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar imagenes de hosts.
- [ ] Agregar todos los iconos en donde se puede escuchar

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/6897)
