### ISSUE TITLE
Si una persona no esta al dia con los pagos `finantial_status=LATE` le debe salir un letrero avisandole y no permitirle entrar a la cohort.

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6915]
- [ ] This modal window will show on the main dashboard.
- [ ] The cohort card should also show, but the `Continue course` button will say `Action Required` and will be red. If the button is pressed, it will show the modal window again.
- [ ] We have to ensure that if the student types the cohort dashboard URL manual y redirects to the main dashboard without allowing the student to see the cohort dashboard.
- [ ] In the main dashboard we have to ensure the student does not see any mentors from that cohort/syllabus.

Modal window title: `Action Required: Late Payments`
Description: `Your account has outstanding payments for cohort <cohort name> . Please contact <Academy name> coordinator to restore full access to all features. Thank you for your prompt attention.`

**Comment by tommygonzaleza** [comment]
- [ ] Dice undefined en el nombre de la cohort y de la academia
- [ ] Muestra abajo en el boton "Action requiredContinue course"
- [ ] Me permite acceder al dashboard de la cohort
<img width="1464" alt="Screenshot 2024-02-26 at 10 29 42 AM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/fbc833f1-eed6-4e2c-ab94-7c8b45465799">

**Comment by ArielCalisaya** [comment]
Ya corregí los el bug

**Comment by tommygonzaleza** [comment]
- [ ] Cuando el usuario tiene educational_status=SUSPENDED o finantial_status=LATE, deberia sacarlo del dashboard de la cohort si entro a traves del link, no deberia tener acceso de ninguna manera y al estar adentro deberia sacarse al dashboard principal.

**Comment by ArielCalisaya** [comment]
Acabo de añadir eso cambios

**Comment by tommygonzaleza** [comment]
- [ ] El boton debe ocupar el mismo width que los otro botones
![Screenshot 2024-02-27 at 4 33 39 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/0d3d7cea-6a43-48ff-80a3-be6b9ba6f1dd)
