### ISSUE TITLE
Cambia el logo de rigobot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6918]
El diseño debe parecerse mas a un robot

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2657%3A4234&mode=design&t=gOgL2L4T7UqIgrOQ-1

**Comment by tommygonzaleza** [comment]
- [ ] Utilizar la primera version y asemejarlo mas a rigo, debe tener dimensiones mas cuadradas
