### ISSUE TITLE
Crear endpoint para sincronizar con rigobot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6929]
En breathecode seria: `POST /v1/auth/service/<service_slug>/sync` que funcionaria como un proxy que haria el request a este endpoint de rigobot: `POST /v1/auth/app/user` en el cual se envie el name, lastname, github_credentials, email.

El request debe validar que el usuario tenga github_credentials en breathecode, sino debe dar un validation exception

En el lado de rigobot, debes usar el decorador scope, para validar el token de breathecode, y con eso registrar un breathecode credentials nuevo.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1305
