### ISSUE TITLE
En carrusel de los alumnos contratados debe hablar mas de ese cambio de carrera

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6930]
En carrusel de los alumnos contratados debe hablar mas de ese cambio de carrera, mira lo que dice, algunos dice liderazgo en programacion, debe decir algo relacionado a que fueron contratados, a lo que hacen ahora, quizas lo que hacian antes y lo que hacen ahora.

Hay que buscar entre los testimoniales de los alumnos para poder corregir esto

![Screenshot 2024-02-21 at 8 32 14 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/25e27ed7-ff5f-4f92-b850-533c2321a663)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2038
