### ISSUE TITLE
El condiciones aplican debe verse como un link

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6931]
Esto es en el header del home de 4geeks academy

![Screenshot 2024-02-21 at 8 34 51 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/7b87f697-2867-442e-9a8b-1239a07317ab)

---

Expected time: 0.5 - 1 hrs

**Comment by AltaciosTheDev** [comment]
Tanto en ingles como en español estan en negrita y con hover effect donde mouse cursor cambia a pointer.
