### ISSUE TITLE
Revision de codigo de colores para los proyectos nadamas

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6946]
- **un circulo sin relleno** `Not opened yet`
- **gris**: `Pending student delivery`
- **amarillo**: `Student has delivered and needs review`
- **rojo** `Rejected`
- **verde** `Approved`
- 
<img width="800" alt="Screenshot 2024-02-19 at 15 11 08" src="https://github.com/breatheco-de/breatheco-de/assets/426452/b8b481ed-5638-4014-906e-1d35b0f62fd0">

**Comment by ArielCalisaya** [comment]
@alesanchezr  Las caracteristicas planteadas en este issue ya se encuentra hecho en la rama `development`
solo modifiqué el color para los lesson que no han sido leidos (antes rojo, ahora gris)

**Comment by tommygonzaleza** [comment]
Se rompio el dashboard principal, mira este video:


https://github.com/breatheco-de/breatheco-de/assets/56565994/23a7d5f3-f1fb-4fcb-8ff1-c84e9da224b7
