### ISSUE TITLE
Mejoras al dashboard de actividades del alumno

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6954]
- [ ] Sortear las actividades de la mas reciente a la mas lejana
- [ ] Agregar el nombre del asset relacionado (de existir).
- [ ] Si ahces click en la actividad te lleva al asset relacionado.
       - Si e sun lesson/projecto/ejercicio te lleva a la vista publica.
       - Un evento te lleva al landing publico del evento.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/46256285?key=3102c390be2717481f5b803eddd3b247&size=orig) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-58/student/6699?academy=4](https://4geeks.com/cohort/miami-58/student/6699?academy=4)

**Comment by tommygonzaleza** [comment]
- [ ] Te puse un comentario en el codigo del app, de resto esta funcionando todo bien
