### ISSUE TITLE
Mentorship widget not working consistently to book mentorhips

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6968]
Mentoring widget is still not working correctly on the home page
Just onboarded a full stack student. and saw DS mentors on the homepage, but not inside the prework. 
Check with Brandon Panavelil token.

**Comment by tommygonzaleza** [comment]
- [ ] No esta filtrando por syllabus, se esta trayendo todos los mentorship services de la academia y luego se trae todos los mentores de cada mentorship services.
- [ ] En un request si se esta filtrando por syllabus (`GET /v1/mentorship/academy/mentor?status=ACTIVE&syllabus=coding-introduction&academy=4`), este es el que debes tomar en cuenta, este se debe hacer por el syllabus de cada cohort

**Comment by tommygonzaleza** [comment]
Mira este usuario solo tiene la cohort de miami prework y le esta mostrando las mentorias de data science
![Screenshot 2024-03-05 at 2 06 02 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/b014ea34-a4ea-4e4d-b591-31f9040d6c3a)

**Comment by tommygonzaleza** [comment]
- [ ] Estas buscando los syllabus de esa academia, y en verdad los syllabus se comparten entre las academias, por ejemplo, todas las academias usan el syllabus de full stack que es de miami
