### ISSUE TITLE
DS - modulo #26 correspondiente a ML WEB APP,  repositorio de la actividad de este modulo, la pagina no aparece.

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/breatheco-de#6977]

**Comment by pbullor** [comment]
@tomasg2704 
Levantado por Leonardo Palacios Teacher de DS y validado por Belen Fernandez Piñeyro
Busqué en el github de 4Geeks y con esa descripción me aparece solo este repo que fue actualizado por última vez por Ale Sánchez.


![Image](https://github.com/breatheco-de/breatheco-de/assets/70356168/74b332fb-c1bf-4518-b31d-4754b1830155)


La verdad no sé quién se encarga de mantener al día estas cosas, yo no tengo acceso, solo estoy encargada del canal de Slack.

**Comment by tommygonzaleza** [comment]
El repositorio estaba privado
