### ISSUE TITLE
typo en página de 4geeks programas

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6980]
https://4geeksacademy.com/us/programs

![image](https://github.com/breatheco-de/breatheco-de/assets/109150320/e4cf8bce-def8-4b7c-8d66-69bdf16d4c69)

debería decir:

Pick one of 4Geeks' Bootcamps

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1994
