### ISSUE TITLE
no se actualizan los colores entre light mode y dark mode

### ISSUE THREAD

**Issue by josemoracard** [breatheco-de/breatheco-de#6981]
cuando cambias a light mode estando ya en dark mode y viceversa no se actualizan bien los colores de las letras y el fondo.

![image](https://github.com/breatheco-de/breatheco-de/assets/109150320/66e3dbc4-1bcf-44ba-89e1-2e5485a11d9b)

**Comment by tommygonzaleza** [comment]
Lo tengo que probar en produccion, esperare a que se hagan los cambios del otro issue que se resolvio en el PR para aceptarlo
