### ISSUE TITLE
No se esta mostrando el consent correcto en vista de Apply

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6986]
En la vista de apply el usuario debe escoger el location al que quiere aplicar, debe tomarse ese location que escoge el estudiante para ponerle los checkbox de los consents de ese location en el formulario

- [ ] Corregir el apply para que muestre el consent de la locacion a la que aplica.

---

Expected time: 2 - 3 hrs.

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2007
<1.25 hrs>

**Comment by Khrisefzm** [comment]
<1.25hrs>

**Comment by Khrisefzm** [comment]
<1 hrs/>

**Comment by tommygonzaleza** [comment]
<hrs>1.25</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.25</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.25</hrs>
