### ISSUE TITLE
No mostrar para hacer code review si no esta sincronizado con RigoBot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#6991]
Si no esta sincronizado todo el cuadro azul que habla de cuantos code reviews tiene y que dice para hacer un code review no debe mostrarse
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/4856c862-1862-4e56-89ae-b86bf4a44b5a)

Por lo que no deberia llegar a verse asi, que es lo que pasa cuando le das a Start code review (Ya que se quitaria el start code review)
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/fa906d76-bc75-47a5-90d2-48f350e9a34c)

**Comment by tommygonzaleza** [comment]
Sigue mostrandolo:
![Screenshot 2024-02-29 at 6 50 29 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/a72f6834-e56b-406c-aca1-e13f1f96092d)

**Comment by tommygonzaleza** [comment]
Se debe mostrar es esta modal, pero sin el cuadro azul de code reviews:
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/1cec3418-f952-4c9d-8896-aa468ba9996a)

**Comment by ArielCalisaya** [comment]
@tommygonzaleza Ya esta resuelto

**Comment by tommygonzaleza** [comment]
Cuando si esta sincronizado el request que se trae el task esta retornando Not Found, quizas le estas pasando mal el task. Se muestra asi (Este es un proyecto que incluso ya tiene varios code reviews):
![Screenshot 2024-03-01 at 7 38 06 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/17654715-9072-4a61-a581-2ea1f0b2f107)

**Comment by tommygonzaleza** [comment]
Se esta mostrnado asi cuando esta accepted
![Screenshot 2024-03-04 at 4 42 23 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/426f1822-4331-4917-991e-ea34506e3673)

**Comment by tommygonzaleza** [comment]
Si le doy a Start code review lo muestra asi:
![Screenshot 2024-03-04 at 8 58 59 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/4eae9843-aa53-4af4-a324-e00c8d50d17a)
