### ISSUE TITLE
Agregar animacion de loading mientras se cargan los consumibles en vista de workshops

### ISSUE THREAD

**Issue by Leonel2612** [breatheco-de/breatheco-de#6992]
### Bug description

Esto sucede al principio.
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/70397b09-10cc-4675-ae12-7a8c5c8c63d5)

Luego, me sale el mensaje de que no tengo consumibles a pesar de estar registrado y aun tener consumibles.
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/03ec426f-3d50-44cc-9430-fee62c88d955)

Esta es la vista final indicando que los elementos de la pagina se han cargado completamente. 
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/64266bc3-ca9f-4488-afea-ec5225d14dba)

### Steps to reproduce

Se puede ver el Bug al refrescar la página web con f5.

### Expected behavior

No debería salirme el form estando logueado con una cuenta y no debería salirme que necesito conseguir nuevos consumibles mientras se carga completamente la página. Debería mostrarse que se están cargando los elementos a través de algun estilo que indique al usuario que se están cargando dichos elementos.

**Comment by tommygonzaleza** [comment]
- [ ] Esta mostrando el icono de que esta cargando por un tiempo, luego vuelve a pasar lo que pasaba antes, me muestra get consumables y hasta que luego me muestra que puedo unirme
