### ISSUE TITLE
Permitir poner el video del home segun location

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7012]
- [ ] Agregar en el YML de los location la siguiente propiedad adentro de `meta_info`:

```yml
home_video: ""
```

- [ ] De no tener `home_video` en el YML del location, se van a mostrar los valores del index.yml.
- [ ] Agregar a todos los locations en español de latam y de USA este video: `"https://ask.4geeks.com/f67qc0ewu"`
- [ ] Agregar a todo latam y usa en ingles este video: `https://www.videoask.com/fyq2h2hvx`
- [ ] España y europa deben quedarse sin video por ahora, leugo se especificará.

---

Expected time: 1 - 2 hrs.

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2010
Tiempo: <hrs>1.9</hrs>

**Comment by tommygonzaleza** [comment]
- [ ] Agregar el escenario de los videos del index.yml, que es uno de los que esta ahora. La validacion debe chequear por tres posibles escenarios, si tiene home_video, entonces se muestra, sino revisa si tiene video (En el index.yml), y de tener se muestra, sino, se muestra la imagen (Del index.yml). Los ultimos dos escenarios ya existen, solo falta la validacion entre home_video y video

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2023

**Comment by tommygonzaleza** [comment]
No esta el escenario de la imagen que es cuando no hay video en ninguno de los YMLs

**Comment by Khrisefzm** [comment]
Esta contemplado de la siguiente forma:
![image](https://github.com/breatheco-de/breatheco-de/assets/129009072/751fecad-ce8b-4778-958e-64f32622e9c0)

Contempla únicamente la imagen del index

**Comment by tommygonzaleza** [comment]
<hrs>1.9</hrs>
