### ISSUE TITLE
Cambiar icono de componente de IconogramSection GeekForce

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7018]
Los iconos no estan similares a los del resto de la pagina

---

Expected time: 0.5 - 1 hrs

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7831%3A13248&mode=design&t=m9xqSmCGQomXscUM-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar los cambios en el componente [IconoGram](https://github.com/Khrisefzm/website-v2/blob/ed2143112a4513a4ebcb1d88bd639f28fcc2c301/src/components/Iconogram/index.js), recuerda que tiene que mantenerse compatible con todo lo que permitia el iconogram, es decir, solo vas a cambiar el diseño.
- [ ] Usa el componente iconogram nuevo, pasandole los iconos de GeekForce en el landing de GeekForce.

**Comment by tommygonzaleza** [comment]
<hrs>1.33</hrs>
