### ISSUE TITLE
Rediseño de vista de financing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7019]
- [ ] El componente que se muestra de ultimo que habla de job guarantee, solo debe mostrarse si la academia tiene job guarantee

Expected time: 4 - 8 hrs

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7620%3A13570&mode=design&t=qhjDRa3eA6JP2R9E-1

**Comment by tommygonzaleza** [comment]
- [ ] Esta parte se ve diferente en el diseño, los iconos son distintos y no tienen el mismo color
![Screenshot 2024-04-30 at 11 05 32 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/b3372d56-4192-4493-a9ba-f5f0105796d0)

- [ ] No tiene flecha para echar para atras
![Screenshot 2024-04-30 at 11 06 50 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/fd59855f-e8ca-4152-a7da-54faf0d9dfc8)

- [ ] Falta la seccion de Job Guarantee
![Screenshot 2024-04-30 at 11 08 05 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/5a394a92-e4d6-421a-b981-2febd1be7a66)

**Comment by tommygonzaleza** [comment]
- [ ] En el footer la parte gris debe ocupar todo el width de la pantalla, con el texto centrado. Y lo de we accept bitcoin y ethereum debe estar por encima de la parte gris centrado
