### ISSUE TITLE
Cambiar icono de ver comentario en un todo

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7027]

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8718%3A42109&mode=design&t=hFuFRANpEokmOoB3-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7048)
