### ISSUE TITLE
Agregar soluciones a asset de tipo PROJECT

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7032]
Revisar todos los projectos de datascience y fullstack y agregar el "solution" al learn.json para los casos en que este disponible. 

Para saber si hay una solucion:

1. Los proyectos de datascience tienen solutions.ipynb o solutions.es.ipynb para español.
2. Los proyectos de full-stack a veces tienen un branch "solution". Por [ejemplo esta](https://github.com/breatheco-de/exercise-html5-form/tree/solution).

![Annotate-Image](https://github.com/breatheco-de/breatheco-de/assets/426452/36df4e3a-8b9f-44dd-85c1-55323c80d7de)

**Comment by josemoracard** [comment]
revisados todos los proyectos.

estas son las PRs que salieron:

https://github.com/breatheco-de/exercise-instagram-post/pull/57
https://github.com/breatheco-de/exercise-random-card/pull/25
https://github.com/breatheco-de/exercise-starwars-data-modeling/pull/50
https://github.com/4GeeksAcademy/web-scraping-project-tutorial/pull/13
https://github.com/4GeeksAcademy/data-preprocessing-project-tutorial/pull/8
https://github.com/4GeeksAcademy/logistic-regression-project-tutorial/pull/5
https://github.com/4GeeksAcademy/linear-regression-project-tutorial/pull/5
https://github.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/pull/4
https://github.com/4GeeksAcademy/decision-tree-project-tutorial/pull/6
https://github.com/4GeeksAcademy/random-forest-project-tutorial/pull/7
https://github.com/4GeeksAcademy/boosting-algorithms-project-tutorial/pull/6
https://github.com/4GeeksAcademy/naive-bayes-project-tutorial/pull/5
https://github.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/pull/5
https://github.com/4GeeksAcademy/k-means-project-tutorial/pull/6
https://github.com/4GeeksAcademy/alternative-time-series-project/pull/5
https://github.com/4GeeksAcademy/time-series-project-tutorial/pull/5
https://github.com/4GeeksAcademy/image-classifier-project-tutorial/pull/7
https://github.com/4GeeksAcademy/NLP-project-tutorial/pull/5
