### ISSUE TITLE
Crear nuevo flujo de Getting Started

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7045]
Volveremos a mostrar la vista de pricing, solo que ahora en esta vista escoges tambien el programa (FS o DS), tal como se hace en 4Geeks Acadey, en financing.

Mostraremos las tres opciones como se hace ahora en pricing, y la gratis debe ser en vez de un plan gratuito, una prueba de la experiencia 4geeks, sin decirle, le permitiremos reailzar proyectos, ejercicios y todo del full stack pero luego de un numero determinado de lessons, practicas, proyectos, abiertos, le quitaremos el acceso a los demas.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=RTvuCsPAnILCCki9-1

**Comment by tommygonzaleza** [comment]
- [ ] Ya no es un modelo de subscripcion, sino que o paga de una vez o tiene opciones de financiamiento

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=aOGvQPUqlfOcTbX2-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7157
