### ISSUE TITLE
Cambiar iconos para seccion de why learn with 4Geeks en landing de cursos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7046]
Antes teniamos un texto diferente, ahora se habla mas de learn live + learn by doing + learn in community

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=uPR6u7vb9ERBl8Ks-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12782%3A51392&mode=design&t=coMzYBobipG4Q77o-1
