### ISSUE TITLE
Incorrect Task Completion Status for Prework Course Graduation

### ISSUE THREAD

**Issue by lbdelilla** [breatheco-de/breatheco-de#7047]
### Bug description

When attempting to graduate certain students from the prework course who have completed and submitted all required assignments, the system incorrectly indicates that they still have pending tasks. Upon further investigation, it was found that some of the listed pending tasks actually belong to the bootcamp course, leading to confusion and inaccurate completion status.

![image (1)](https://github.com/breatheco-de/breatheco-de/assets/112482614/982e37df-50c2-49e6-a71b-b2bc90c333bd)
![image](https://github.com/breatheco-de/breatheco-de/assets/112482614/e00ccf86-fa71-49b3-b9dc-70030d9962ba)

### Steps to reproduce

- Check de "projects view" of the "Madrid Prework" course. 
- Filter the student "Ana María Romero Gonzalez" 
- See the project with pending status 

### Expected behavior

We should only see the 3 projects that belong to the prework course. 

1.  Postcard 
2.  IG Feed 
3. Excuse Generator

### Anything else?

The same issue is happening for another DS student.

**Comment by tommygonzaleza** [comment]
@gustavomm19  El error podria ser o del front que esta pidiendo tasks no relacionados a esa cohort o de backend, que esta creando por alguna razon, algunos tasks que no pertenecen a este syllabus.
