### ISSUE TITLE
Se debe agregar el id de la cohort al que se quiere unir desde el landing del bootcamp

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7050]
Actualmente te esta uniendo a la primera cohort de las que recibe en el plan, pero que pasa si el usuario estaba en el landing de un curso con una cohort diferente? En ese caso lo une a la cohort equivocada.

Debemos pasar por querystring el id de la cohort a la que se le va a unir para utilizar ese id en el metodo de join que se usa en checkout, y de no recibir ningun id de cohort por query string, no se debe agregar en ninguna cohort.

**Comment by tommygonzaleza** [comment]
- [ ] Probe con el bootcamp de full stack y no se paso la cohort por querystring

**Comment by ArielCalisaya** [comment]
> * [ ]  Probe con el bootcamp de full stack y no se paso la cohort por querystring

Acabo de probarlo en el ultimo preview y si esta usando el querystring

![Image](https://github.com/breatheco-de/breatheco-de/assets/51676628/c5c3e228-4bdc-4496-8e50-c75f73a6538f)

**Comment by tommygonzaleza** [comment]
- [ ] Si el plan es gratis no se esta agregando el cohort id en los querystrings
