### ISSUE TITLE
Error 404 al crear Usuario en ingles

### ISSUE THREAD

**Issue by BrayanSO** [breatheco-de/breatheco-de#7051]
### Bug description

Me redirecciona a una pagina con error 404

### Steps to reproduce

Entramos a la pagina de 4geeks y creamos un usuario , cerramos la ventana de verificar correo y damos en el botton de start learning . algunas veces da este error  "  There was an error trying to find the role "undefined"
Cannot read properties of undefined (reading 'data')" otras nos lleva a la pagina de error 404 

### Anything else?

![image](https://github.com/breatheco-de/breatheco-de/assets/102002240/27fb3d74-bc97-41f0-aa56-161b46eef375)
![Captura de pantalla 1](https://github.com/breatheco-de/breatheco-de/assets/102002240/3267cd5a-15ba-49e2-882f-7857e1854972)

**Comment by tommygonzaleza** [comment]
@ArielCalisaya El problema es que todavia no ha cargado la informacion del cohort user. Debes esperar un poco para mandarlo al landing de la cohort
