### ISSUE TITLE
Bug en `choose-program` 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7052]
![Screenshot 2024-03-14 at 12 09 05 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/b71515e5-e923-429d-ac56-5a9e35d605a2)

**Comment by ArielCalisaya** [comment]
@tommygonzaleza no logré replicar este bug, puede que esté relacionado a [otro PR](https://github.com/breatheco-de/app/pull/1396), intenta probarlo con la rama development
