### ISSUE TITLE
Cambios en vista de checkout

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7054]
El flujo de checkout actual es bastante extraño, el usuario no sabe que esta adquiriendo en todo momento.

Es importante que en todo momento del flujo (Desde que agrega sus datos hasta que paga), se debe mostrar el precio del plan que quiere adquirir, el nombre, etc. Debe ser como un resumen de lo que va a comprar.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=RTvuCsPAnILCCki9-1

**Comment by tommygonzaleza** [comment]
- [ ] Tenemos que poder mostrar el plan de financiamento (En el total debemos mostrar "Total now" y abajo debe haber una opcion desplegable que te describa el plan de financiamiento, debe decirte cuando es el proximo pago y cuanto se cobrara los proximos meses, ademas de tener un link a un doc que hable sobre como funciona el financiamiento con 4Geeks).
- [ ] Tienes que resaltar el paso en el que estas. Cuando falla el pago todavia no puedes marcar como completado ese paso
- [ ] Falta el escenario de cuando el plan es gratuito. Debe ser un solo paso, llenas tu informacion y el CTA del boton debe cambiar, a la derecha debe mostrarte la informacion del plan y resaltar que es gratuito.
- [ ] Que pasa cuando adquieres un plan sin una cohort? Debes mostrar quizas el nombre del plan en vez del curso.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=aOGvQPUqlfOcTbX2-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar checkmarks en los bullets de lo que obtienes del plan

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=3I4nSRU0AcvIF8AV-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7140
