### ISSUE TITLE
Agregar Coupons en Payment

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7055]
Queremos agregar los coupons por multiples razones, como poder crear descuentos, pero mas importante para poder determinar a quien atribuirle las ventas que se realizan de forma desatendida. Cada vendedor tendra un coupon propio, cuyo slug se podra pasar por querystring para prellenar el input de cupon en checkout.

Se debe validar que el cupon exista para dicho plan, para poder asi bajarle el precio (Debe haber un servicio especifico para validar el cupon).

- [ ] Se debe incluir una relacion con el cupon en PlanFinancing, Subscription, Invoice, Bag.
- [ ] Agregar `Payment.coupon`, el cual debe tener las propiedades:
     - `discount_ratio`: (help_text="i.e.: if you want to apply 10% of discount, the value would be 0.1")
     - `allowed_plans`: ManyToMany con plan. (Son los planes en los que se permitira aplicar este coupon).
     - `salesman`: TextField (Aqui pondremos el nombre del vendedor al que se le atribuiran las ventas de ese cupon)
     - `slug`.
- [ ] En el servicio de pay de tener un cupon se debe validar que el cupon es permitido para ese plan, de ser asi se aplica el descuento, sino se hace un PaymentException. (El front end no debe enviar el cupon de ser invalido, si el backend lo recibe, no debe procesar el pago para evitar problemas con el usuario de cobrarle mas de lo que dice el front)

**Comment by tommygonzaleza** [comment]
- [ ] Falta agregar un endpoint que permita chequear si uno o mas coupones que se le envien son validos, para poder mostrar asi en el front si ese coupon se podra utilizar o no

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1337/files

**Comment by jefer94** [comment]
Prefieres que devuelva los cupones que aceptaria checking o todos?
