### ISSUE TITLE
Permitir agregar cupones en checkout

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7056]
Debes modificar el diseño para que de aplicar el cupon se muestre como mas llamativo y resalte que esta saliendo mas barato

**Comment by tommygonzaleza** [comment]
- [ ] No debe mostrar cuanto descuento se le aplicara si todavia no ha introducido el cupon
- [ ] Al agregar un cupon, debe mostrarse como un tag o un pill con el nombre del cupon en mayuscula y a la derecha del tag una X para quitarlo y asi poder agregar otro cupon. Es decir, si agregas un cupon, no deberia verse como input.
- [ ] Cuando vayas a agregar el cupon, debe mostrarse un boton para confirmar que lo vas a agregar y luego, de ser valido se muestra como en el punto anterior pero de ser invalido, debe mostrarse como con una X roja que demuestre que es invalido pero igual le permita modificarlo o agregar otro cupon.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=UK99UrswjysVpEqs-1
