### ISSUE TITLE
Revisar step en tutorial de css

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7057]
1. Exercise Name: 00.1-Inline-Styles

2. Repository URL: https://github.com/4GeeksAcademy/css-tutorial-exercises-course

- [ ] Las instrucciones no estan iguales en ingles y español, ademas de tener errores en el texto.
- [ ] El numero del ejercicio debe ser 01-inline-styles, por lo que se debe cambiar el nombre de todos los demas ejercicios que le siguen
- [ ] Hay que agregarle solution.hide.html y tests

**Comment by josemoracard** [comment]
https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/138
