### ISSUE TITLE
Agregarle animación cuando cambio a un plan de pago

### ISSUE THREAD

**Issue by Leonel2612** [breatheco-de/breatheco-de#7058]
### Bug description

Cuando hago el cambio del plan gratis al plan de pago no me cambia la animación indicándome  que ya tengo un plan de pago.
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/511e151a-9666-4254-8e4a-c0fbacda467b)

### Steps to reproduce

Sucede cuando ingreso primero al plan gratis y después quiero cambiar al plan de pago. Al realizar el pago, me sigue saliendo que puedo mejorar mi plan a pesar de ya haber comprado un plan.  

### Expected behavior

Deberia mostrarme esta animación indicandome de que tengo un plan de pago
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/a7158eff-87cc-4016-86d7-51e792ab6fbb)

**Comment by tommygonzaleza** [comment]
Se quito ese boton mientras se decide que hacer
