### ISSUE TITLE
Falta video para la pag de datascience

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#7063]
https://4geeksacademy.com/es/coding-bootcamps/curso-datascience-machine-learning?lang=es
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/5f3127d9-814b-4269-8d4c-2fb2e2c82a8f)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2122

**Comment by alesanchezr** [comment]
falta el de ingles

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2190
