### ISSUE TITLE
Cada tecnologia del syllabus debe mostrarse en un pill diferente

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7066]
![Screenshot 2024-03-18 at 9 17 26 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/55965f47-d26c-4451-aeef-4627582ee67e)

**Comment by AltaciosTheDev** [comment]
Confirmed.

Still 1 pill for all technologies.
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/85428c96-bf06-4f1b-a3e4-87d575c19f2d)
