### ISSUE TITLE
Event landing page waiting for something when user with no workshops tries to register

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7069]
### Bug description

When a user with no workshop consumables tries to register for an event on the event landing page, the registration panel gives the message: "You have run out of workshops, but don't worry, you can get more in a few clicks." However, the button to purchase more workshops/access to workshop never loads as shown in the image below.

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/5edb1c0f-228b-4b52-a888-bf27cb9df9f5)

### Steps to reproduce

Created new user with free account on dev site
On backend: modified the created user's consumables (service-item = join-workshops) to 0.
On frontend: navigated to event landing page and then clicked on an available event (First fake date test event).
When event page loaded, the registration panel does not load button to get access to new events

### Expected behavior

The registration panel should show a button allowing users to purchase access to event.

**Comment by tommygonzaleza** [comment]
Todavia se queda cargando aunque no tenga consumibles

**Comment by christadkelly** [comment]
The "Get more workshops" button appears when the screen is less than 768 px.

https://github.com/breatheco-de/breatheco-de/assets/46685557/8a05fc34-4e61-4328-b4fb-601fcda1df3e

**Comment by ArielCalisaya** [comment]
Resuelto!
