### ISSUE TITLE
Algunas sesiones de mentoría se muestran con Invalid Date, pero se han realizado y tienen comentarios registrados

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#7075]
### Bug description

Se decía que al tener "Invalid Date" era porque no se había tenido la sesión. Sin embargo, hay sesiones que tiene un comentario registrado por parte del mentor, lo que indica que sí se ha realizado la sesión, pero no se ha registrado adecuadamente.

### Steps to reproduce

Buscar en la BD sesiones con Invalid date pero con comentarios.

### Expected behavior

Debería haberse registrado la fecha del evento.

https://admin.4geeks.com/mentors/sessions

**Comment by tommygonzaleza** [comment]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/36d9d2d6-e662-47f8-8220-75523558addd)

**Comment by alesanchezr** [comment]
Esto pasa porque no no vino el alumno o el profesor, no hay datos.
