### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by Leonel2612** [breatheco-de/breatheco-de#7076]
### Bug description

Al querer entrar a uno de estos proyectos recibo el error 404
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/03918143-5e1c-4253-a712-64454204e1bb)

Este es el error 404, la URL también pasa a ser undefined
![image](https://github.com/breatheco-de/breatheco-de/assets/77934438/1de99676-9903-4bc0-bff5-e79926539577)

### Steps to reproduce

Se puede observar entrando al landing page para la inscripción del bootcamp Full Stack y al querer entrar a uno de los proyectos que se pueden realizar, dentro del mismo sale el error 404 con una URL undefined.

### Expected behavior

No debería salirme el error 404. 
Debería poder ver los detalles del proyecto que me interesó revisar.

**Comment by tommygonzaleza** [comment]
@ArielCalisaya Parece que el link que se genera [aqui](https://github.com/breatheco-de/app/blob/d53b3dac1a0c88c329fad39523883ce46f604e42/src/pages/bootcamp/%5Bcourse_slug%5D.jsx#L610) no esta funcionando bien
