### ISSUE TITLE
Agregar telemetry a los demás compilers

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7083]
La telemetria la vamos a implementar en la carpeta plugin que esta compartida con todos los plugins, ahora mismo puedes ver que el execute retorna el stdout solamente, y eso hay que cambiarlo.

https://github.com/learnpack/learnpack-cli/blob/2b9c0cc0e500c92ce67a2254eeb310ec20bfb70d/plugin/plugin.js#L57

En lugar de eso, hay que modificar todos los plugins para que en lugar de retornar cleanStdout retornen el objeto results completo.

https://github.com/learnpack/learnpack-python/blob/08c0e18e9df180bd2b1bb82f4ab1586553246758/src/compile.js#L22

- [ ] No olvides modificar el results.stdout para aplicarle el cleanStdout.
- [ ] recuerda devolver results en lugar de el stadout.
- [ ] recuerda modificar la carpeta de `plugin` para esperar el results completo.

**Comment by Charlytoc** [comment]
- [ ] https://github.com/learnpack/learnpack-python/pull/24 needs to be accepted, re-published
- [ ] https://github.com/learnpack/learnpack-node/pull/3 needs to be accepted, re-published and tested in some exercises
WARNING: I'm having an error that says: Could not find error report.
- [ ] https://github.com/learnpack/learnpack-html/pull/1 needs to be accepted, re-published and tested in some exercises
