### ISSUE TITLE
Poner el numero de todos los estudiantes del syllabus en vez de cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7097]
En el landing de bootcamps, en vez de mostrar los inscritos en esa cohort, traete todos los cohort user de tipo student de  todas las cohorts que tengan ese syllabus, seria usando este request: `GET /v1/admissions/public/cohort/user?syllabus=<course_syllabus_slug>`

**Comment by tommygonzaleza** [comment]
- [ ] No esta mostrando ningun estudiante en el de full stack a pesar de que hay muchos estudiantes con ese syllabus

**Comment by tommygonzaleza** [comment]
En este request: `https://breathecode-test.herokuapp.com/v1/admissions/public/cohort/user?syllabus=full-stack-pt-18w&roles=STUDENT` estoy recibiendo mas de 8 students pero en la pagina me muestra solo 8

**Comment by tommygonzaleza** [comment]
- [ ] Debe mostrar solo los instructores de esa cohort, no de todas las cohorts del syllabus como funciona con los estudiantes

**Comment by tommygonzaleza** [comment]
- [ ] Aqui `https://breathecode-test.herokuapp.com/v1/admissions/public/cohort/user?syllabus=full-stack-pt-18w&roles=STUDENT` estas recibiendo mas de 8 estudiantes, sin embargo solo muestra 8 en el landing

**Comment by ArielCalisaya** [comment]
Arreglado!
