### ISSUE TITLE
Marketing Consent checkbox is not being sent on the subscribe method

### ISSUE THREAD

**Issue by andresmedtr** [breatheco-de/breatheco-de#7100]
### Bug description

When registering into the[]( https://dev.4geeks.com/checkout?plan=basic)

- it creates an invite in the backend

- in the frontend it doesn't let you register unless you click the marketing consent box

- when the user is created, [](https://breathecode-test.herokuapp.com/admin/authenticate/userinvite) look for the user and the 
Has marketing consent checkbox is not checked
![Screenshot 2024-03-25 165533](https://github.com/breatheco-de/breatheco-de/assets/123752360/129a1f4b-3c14-4b9d-9a2a-183bf585a647)
![Screenshot 2024-03-25 170345](https://github.com/breatheco-de/breatheco-de/assets/123752360/b4e82756-c748-48ad-bc63-fb303fbf25bf)

### Steps to reproduce

- Create an account on 4geeks
- Check on the backend to confirm that the user was created.
- Go into the user's info and check if the Has marketing consent was default as true or not(it should default as true)

**Comment by gustavomm19** [comment]
Solved here https://github.com/breatheco-de/breatheco-de/issues/7887
