### ISSUE TITLE
Agregarle texto al testimonial de jonathan ferragut

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7104]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42512-372df0c5f0b9f929cb0957a2499a6ba3) 

---
**Source URL**:
[https://website-v2-mn229ay4f-geeksacademy.vercel.app/us/testimonials?lang=en](https://website-v2-mn229ay4f-geeksacademy.vercel.app/us/testimonials?lang=en)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x855</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/a0e558f9-ac19-4e8c-90ee-46d97e9a3ff1)

jonthan y en general casi todos tienen un texto pero, no se muestra en en contenedor si hay un video.
