### ISSUE TITLE
Centrar video en mobile

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7107]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42519-4a897978ed0ebc661f899636b47b95fd) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-text-component-video-geeksacademy.vercel.app/us/index](https://website-v2-git-fork-g-code7-text-component-video-geeksacademy.vercel.app/us/index)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x855</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2042
