### ISSUE TITLE
Si le doy a la opcion de financing options deberia hacer scroll hacia abajo y ubicarme de una vez en la opcion de "finance"

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7108]
Una posible implementacion es escuchar los cambios en el hashstring desde el componente de precios abajo... si vez que en el hashstring dice "#finance" entonces vas a la pestaña de finance, si vez que url cambia a `#one-payment` entoncses marcas la primera tab.
![4Geeks (4)](https://github.com/breatheco-de/breatheco-de/assets/426452/66203be1-af29-4574-8392-bb451f7fd193)

**Comment by tommygonzaleza** [comment]
- [ ] El boton de enroll for $500 esta bien que te envie directo a checkout
- [ ] El boton de see financing options, debe enviarte hacia abajo al componente de pricing pero con la parte de financing seleccionada
