### ISSUE TITLE
Esta foto hace que el texto quede muy pequeño, buscar una foto con menos height

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7109]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42523-d3490311b39a724686c97466df08599b) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-fullstack-geeksacademy.vercel.app/us/landing/full-stack-programs](https://website-v2-git-fork-g-code7-fullstack-geeksacademy.vercel.app/us/landing/full-stack-programs)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x879</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
- [x ] Landing partner Banco de chile
- [ ]

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2024
