### ISSUE TITLE
En el landing de geekforce se esta tapando un titulo en mobile

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7110]
El layout esta bastante raro en mobile, la caja de interview simulation no se extiende lo suficiente y tapa el siguiente titulo
![Screenshot 2024-03-26 at 4 24 49 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/024fca37-5299-42cf-8c6b-a0d3506e4b73)

---

Expected time: 0.25 - 0.75 hrs

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2041
<hrs>0.5<hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.5</hrs>
