### ISSUE TITLE
Eliminar botones de gitpod y codespaces en "clone a project" en el landing de interactive tutorial

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7113]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42549-ba4fd5dc85d35447fd527fe48bd67b00) 

---
**Source URL**:
[https://4geeks.com/interactive-exercise/python-http-requests-api-tutorial-exercises](https://4geeks.com/interactive-exercise/python-http-requests-api-tutorial-exercises)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x855</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Elimina los botones de abajo tambien
