### ISSUE TITLE
New instructions for interactive tutorials on localhost

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7114]
Actualizar las instrucciones para "run locally" un interactive tutorial.
Ahora tenemos que leer el asset.config via API y revisar la propiedad editor.agent.

## Ejemplo de instrucciones

This exercise can be downloaded and run locally if you have node.js installed on your [Mac](https://4geeks.com/how-to/install-node-nvm-mac-osx) or [PC](https://4geeks.com/how-to/nvm-install-windows). Start by installing learnpack and clone this project into your computer by typing the following command on your terminal:

```
$ npm i @learnpack/learnpack -g
$ git clone https://github.com/4GeeksAcademy/python-http-requests-api-tutorial-exercises
```

Note: This will create a new folder "python-http-requests-api-tutorial-exercises" in your computer with the project code inside.

------ if the config.editor.agent == 'vscode':
When using VSCode please [install the VSCode LearnPack plugin](https://marketplace.visualstudio.com/items?itemName=learn-pack.learnpack-vscode) and then open this folder in VSCode and type `$ learnpack start` on your vscode terminal.
------ if the config.editor.agent == 'os':
Using the terminal get inside your recently created folder and start learnpack:

```
$ cd python-http-requests-api-tutorial-exercises
$ learnpack start
```

Read the README.md file and follow the rest of the instructions.

**Comment by ArielCalisaya** [comment]
Listo

![image](https://github.com/breatheco-de/breatheco-de/assets/51676628/767157e4-d10c-4381-9ea7-8c525aedddf8)

**Comment by tommygonzaleza** [comment]
El texto de las instrucciones se cambio, revisalo y cambialo en el PR tambien
