### ISSUE TITLE
Funcion de backend que remueve el primer h1 no esta funcionando

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7122]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42579-14e4246b617a89aa32e211ffefa18ff2) 

 El objetivo es que si lo primero que se encuentra en un archivo markdown es un h1 entonces que se borre ese h1 del readme pero si mantenga en el readme_raw

A veces no funciona y creo que puede ser por saltos de linea vacios, caracteres blancos o tal vez el frontmatter viene primero que el h1 y eso hace que no se borre el h1

El frontmatter debe ignorarse antes de pasar por la funcion que remueve el h1

Agregar pruebas unitarias de esta funcion, validando con diferentes combinaciones en un markdown

---
**Source URL**:
[https://github.com/breatheco-de/apiv2/edit/main/breathecode/registry/actions.py](https://github.com/breatheco-de/apiv2/edit/main/breathecode/registry/actions.py)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1.25</td></tr></table>

**Comment by gustavomm19** [comment]
prepararing-for-software-developer-interview

**Comment by tommygonzaleza** [comment]
- [ ] Agrega 4 pruebas mas, una en la que se incluya frontmatter y luego mas adelante tenga `---` que tambien se usa en md para poner una linea (Pruebalo si quieres ver como funciona). Y otra prueba en la que chequees un md que no tenga frontmatter pero tenga `---` mas abajo. Ambas chequealas con y sin h1 (Por eso serian 4 pruebas).
