### ISSUE TITLE
Extra line with checkmark on bootcamp complete purchase page

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7123]
### Bug description

There is an extra, empty line on the complete purchase page. See circled part on image below.

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/dd13cd5a-a6ba-40d3-9356-4c560268ad6d)

### Steps to reproduce

Create new free user.
Navigate to bootcamp landing page.
Join cohort and begin checkout process.
Choose any payment option.
Error is on complete purchase page.

**Comment by tommygonzaleza** [comment]
It only happens on the development server because of an error in the configuration
