### ISSUE TITLE
Error en la platilla del proyecto de la Postcard 

### ISSUE THREAD

**Issue by lbdelilla** [breatheco-de/breatheco-de#7124]
### Bug description

Ya al menos 3 alumnos en los últimos días han reportado tener errores en el learnpack de la plantilla de la postal al compilar o testear el código. 
Se les cierra el learnpack con el cartel de "oops.." y le salta un error en la terminal que dice 
" Cannot read properties of undefined reading registerStepEvent" 
![image (4)](https://github.com/breatheco-de/breatheco-de/assets/112482614/0980ea96-5a5b-4b4c-9b5e-269751cc5ba7)
![IMG_20240401_132356](https://github.com/breatheco-de/breatheco-de/assets/112482614/25c90a9d-4b05-466d-ae71-d0862ff54e94)

### Steps to reproduce

Dentro del repositorio de la postal intentar seguir los pasos para hacer el proyecto. 

### Anything else?

Esto no está permitiendo a los estudiantes completar el proyecto con normalidad.

**Comment by tommygonzaleza** [comment]
Ya no esta ocurriendo el error

**Comment by Charlytoc** [comment]
Muchas gracias por reportar, solucionado
