### ISSUE TITLE
El mensaje de suscripción en los ejercicios interactivos en español presenta un error.

### ISSUE THREAD

**Issue by veljzs** [breatheco-de/breatheco-de#7127]
### Bug description

Cuando accedes a un tutorial interactivo de forma anónima (sin iniciar sesión), se muestra un mensaje que te invita a suscribirte.
![Screenshot 2024-04-01 154731](https://github.com/breatheco-de/breatheco-de/assets/128405596/55e06d7c-0cb8-4ab4-a450-11acc0e33dbf)

Sin embargo, al cambiar al idioma español, el mensaje que aparece no es la traducción correcta.
![Screenshot 2024-04-01 154932](https://github.com/breatheco-de/breatheco-de/assets/128405596/cc11919d-0bb5-4ce3-a547-2dde5c9fe64f)

### Steps to reproduce

1. No tener una sesión iniciada.
2. Ingresar a cualquier tutorial interactivo en https://4geeks.com/es/interactive-exercises y cambiar el idioma al español.

**Comment by ArielCalisaya** [comment]
ya estaba resuelto
