### ISSUE TITLE
Bug al ingresar a cursos

### ISSUE THREAD

**Issue by BrayanSO** [breatheco-de/breatheco-de#7131]
### Bug description

Se ve información errónea la primera vez que se carga.

### Steps to reproduce

Al crear una cuenta nueva, los 3 cursos disponibles tienen el mensaje de "Join Cohort" y al ingresar al de Python el único gratis, me salta un mensaje que ya tengo el plan, y me lleva a página de suscripciones, pero nunca le di clic en suscribirme a ese plan, antes y al tratar de ir nuevamente al plan por el dashboar el mensaje del plan es Enroll now , en lugar de Join the cohort como deberia ser y me redirecciona otra vez a suscripciones.

### Anything else?

https://github.com/breatheco-de/breatheco-de/assets/102002240/7c822ebe-ab55-4ed8-8a84-96b8b493e06a

**Comment by tommygonzaleza** [comment]
- [ ] Sigue ocurriendo el error

**Comment by ArielCalisaya** [comment]
Ahora si esta funcionando en la rama `development`

**Comment by tommygonzaleza** [comment]
Ahora ocurre otro bug por refrescarse al llegar al landing

https://github.com/breatheco-de/breatheco-de/assets/56565994/2fa0f2c5-b438-491d-94cf-1cefbd37ca4d
