### ISSUE TITLE
Problema con carga de workshops "no free for bootcamps".

### ISSUE THREAD

**Issue by veljzs** [breatheco-de/breatheco-de#7133]
### Bug description

Cuando intento acceder a un workshop "No gratuito para bootcamps" con un usuario registrado en un bootcamp, el componente que debería mostrar el botón para unirse a este workshop no se carga correctamente.
![Screenshot 2024-04-02 120252](https://github.com/breatheco-de/breatheco-de/assets/128405596/df67e5a2-f052-4152-bac2-def5d7e13bed)

### Steps to reproduce

Ingresar a un workshop "No free for bootcamps" con un usuario que este registrado en un bootcamp.

**Comment by tommygonzaleza** [comment]
- [ ] Sigue sin funcionar, prueba entrar con un usuario de bootcamps que no tenga ninguna subscripcion

**Comment by ArielCalisaya** [comment]
Acabo de probarlo con un usuario nuevo, esta funcionando, el componente realiza una validación de 10 intentos (1 cada seg) hasta que finaliza

https://github.com/breatheco-de/breatheco-de/assets/51676628/d873ee65-a630-40b5-87a3-363080a7f5fa

**Comment by tommygonzaleza** [comment]
- [ ] Ya no esta mostrando el icono de que esta cargando sino que muestra que no tiene consumibles y se refresca el componente
