### ISSUE TITLE
SEO Optimization para knowledge base

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7136]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42595-3b11e848a0daf2fa5d9056fa36b642b9) 

 - [x] El titulo de la pestaña deberia ser el del articulo
- [x] La descripcion es la descripcion del articulo
- [x] La fecha es la del articulo
- [x] Hace falta la data estructurada
- [x] Replicar lo que se habia logrado de SEO con las lessons
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by ArielCalisaya** [comment]
- [ ] Añadir structured data
