### ISSUE TITLE
Give priority to workshops from the language that I'm reading

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7138]
- [ ]  If there are no upcoming workshops on that language its better to hide the component.
- [ ] Update the workshop card to add a tag to specify the language of the workshop with the flag icon.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42597-d58da832b6f60152c24e7132c568725d) 

---
**Source URL**:
[https://4geeks.com/interactive-exercise/forms-exercises](https://4geeks.com/interactive-exercise/forms-exercises)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13399%3A43033&mode=design&t=7K18vJ9xYla853Qb-1

**Comment by tommygonzaleza** [comment]
- [ ] Agrega el de español para que Ariel sepa que color usar de fondo tambien

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13399%3A43033&mode=design&t=6st5ueLwvLR5ygtM-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7283)
