### ISSUE TITLE
Rediseño flujo de checkout

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7140]
Hemos cambiado el diseño del flujo de checkout para poder mostrarles en todo momento lo que estan adquiriendo y el preecio de una manera mas clara, ademas de poder incluir cupones en las compras.

Aqui esta el diseño del flujo: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2563%3A3760&mode=design&t=3I4nSRU0AcvIF8AV-1

- [ ] En el caso de que el pago falle, al darle al boton de try again debe enviarlo a poner los datos de la tarjeta
- [ ] Permitir pasar un cupon por querystring y de recibirlo lo muestras en el input del coupon
- [ ] Utiliza este endpoint para validar si el coupon es valido o no: `GET /v1/payments/coupon?coupons=andres-20&plan=basic`, de recibir un array vacio, significa que el coupon no es valido, sino, vas a recibir un objeto como este:
```json
[
    {
        "slug": "andres-20",
        "discount_type": "PERCENT_OFF",
        "discount_value": 0.2,
        "referral_type": "NO_REFERRAL",
        "referral_value": 0.0,
        "auto": false,
        "offered_at": "2024-04-23T20:25:00.743322Z",
        "expires_at": "2025-04-23T20:24:36Z"
    }
]
```

- [ ] Existen cuatro tipos de coupons: `NO_DISCOUNT` (No aplicas ningun tipo de descuento), `PERCENT_OFF` (El descuento lo recibaras como un numero entre 0 y 1, siendo los decimales el porcentaje de descuento que se aplica, al multiplicarlo por 100 obtienes el porcentaje, y al multiplicarlo por el valor del plan, obtienes el valor a descontar del precio final), `FIXED_PRICE` (Vas a descontar exactamente el valor que recibas en `discount_value`, por ejemplo, si es 20 el valor, descuentas $20), `HAGGLING` (Es un porcentaje y funciona igual que el PERCENT_OFF).
- [ ] En el endpoint de `/v1/payments/pay`, debes agregar en el payload la propiedad `coupons` cuyo valor debe ser un array de strings. De no tener ningun coupon valido, NO AGREGUES LA PROPIEDAD `courpons` EN EL PAYLOAD.

**Comment by tommygonzaleza** [comment]
- [ ] Agregale un width de 500px al cuadro de la derecha en la etapa de contact information, se ve muy pequeño.
- [ ] Si es free en vez de decir `payment successful`, digamos `The plan is ready!`
![Screenshot 2024-05-06 at 11 52 51 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/12901017-6ee1-4a75-ad35-13648a951dde)
- [ ] Es `Payment successful` no ~Payment successfull~

**Comment by tommygonzaleza** [comment]
- [ ] Comparar paso a paso con el flujo del diseño, hay algunos textos diferentes, se estan mostrando pasos diferentes en el checkout, no se esta mostrando el precio cuando el plan es pago, etc.
- [ ] Yo te habia pedido que si no se especifica cohort, que lo unieramos a la primera cohort que incluye el plan pero eso es un error, debemos quitarlo de nuevo y solo unirlo a una cohort si se especifica por querystring

**Comment by tommygonzaleza** [comment]
- [ ] El max width de todas las secciones de la pagina debe ser de 1280px, no 1160px
![Screenshot 2024-05-09 at 11 27 22 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/cad7acf0-3bbc-453e-87c9-293d44460514)

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-05-13 at 1 16 01 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/53f6f925-8c15-425a-a85d-3744f1171502)

**Comment by tommygonzaleza** [comment]
Esta mostrando el plan basic cuando configuro el planoffer
![Screenshot 2024-05-13 at 1 18 55 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/8cddd503-03f9-
47cf-9ef5-a83db7cb0369)

**Comment by ArielCalisaya** [comment]
Listo!

**Comment by tommygonzaleza** [comment]
- [ ] Se esta quedando cargando para siempre con el plan `with-feedback`: https://app-4j3l7ahil-geeksacademy.vercel.app/checkout?plan=with-feedback&plan_id=p-19.99&price=19.99&period=MONTH&cohort=541

**Comment by tommygonzaleza** [comment]
- [ ] Debes incluir la cohort en el querystring cuando lo mandas a checkout
- [ ] Agrega esto abajo del formulario de la tarjeta de credito:
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/fc818deb-f658-4a02-9679-2dca777cc6e0)

**Comment by ArielCalisaya** [comment]
listo!

**Comment by tommygonzaleza** [comment]
No esta funcionando con el plan `with-feedback`

**Comment by ArielCalisaya** [comment]
Corregido!
