### ISSUE TITLE
Agregar descripciones y linkedin a los testimoniales

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7141]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42606-c18d58e5afc4306a17e25185ae8b7efb) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/testimonios?lang=es](https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/testimonios?lang=es)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2038
