### ISSUE TITLE
Crear programar de ciberseguridad en el website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7142]
- [ ] Incluir a chema alonso tanto en profesores ocmo en su propio cintillo.
- [ ] Incluir a daniela maissi
- [ ] Agregar logos y badges de ciberseguridad de todas las certificaciones y de las organizaciones dentras de los contenidos.
- [ ] Optimizar en español para `Curso Ciberseguridad` y en ingles para `Cybersecurity Bootcamp`.

**Comment by alesanchezr** [comment]
Has estos cambios:
https://www.awesomescreenshot.com/video/26398349?key=ebbd649c5d34b5a7a0cd4d7d6aaac840

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2027

**Comment by alesanchezr** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/426452/ab1c9261-144b-4b7d-bec9-5dfe64e00cbb)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2027
