### ISSUE TITLE
Usar flex-start para corregir el margen superior en esta imagen

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7143]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42607-94571878f0cedffaad77f5fbe972d1fb) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/us/landing/programming-bootcamp](https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/us/landing/programming-bootcamp)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2024
