### ISSUE TITLE
Simplificar testimonio de Joshua

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7144]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42608-dc26c22aac326320426f53294930af77) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/landing/santiago-front-end-developer](https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/landing/santiago-front-end-developer)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2024

**Comment by alesanchezr** [comment]
Esta equivocado el layout del componente en el landing, dice: programming-bootcamp y deberia ser two_colum...

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2036
