### ISSUE TITLE
Textos de proyectos en ingles

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7145]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42609-9a1a32315706a388cec70b94f309c378) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/landing/santiago-front-end-developer](https://website-v2-git-fork-g-code7-landings-update-geeksacademy.vercel.app/es/landing/santiago-front-end-developer)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/c2667be2-b471-4273-8689-23af4c9f5c9f)

**Comment by tommygonzaleza** [comment]
@gustavomm19 Agregalo en el yml
