### ISSUE TITLE
No esta validando bien si esta conectado a rigobot o no

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7166]
![Screenshot 2024-04-05 at 2 46 19 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/7aacb2ca-2bcd-4e60-8cba-31d809379c80)

**Comment by ArielCalisaya** [comment]
Este error solo ocurrió en development, ya se corrigió

**Comment by ArielCalisaya** [comment]
Ya lo corregí
