### ISSUE TITLE
Mensaje cuando el alumno no a atentido a ningun workshop

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7167]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42640-6f068cbb51fff2c3ca65182566b84e78) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-58/student/5429?academy=4](https://4geeks.com/cohort/miami-58/student/5429?academy=4)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] Debes quitarle el background rosado y ponerle al font el color gris

**Comment by ArielCalisaya** [comment]
Ya lo corregí

**Comment by ArielCalisaya** [comment]
corregido!

**Comment by tommygonzaleza** [comment]
No me aparece ni en dev ni en main, y tampoco veo un PR tuyo

**Comment by ArielCalisaya** [comment]
[Este cambio](https://github.com/breatheco-de/app/pull/1430/files#diff-73e12165b82dfb00670b5162564426af6c77133428d973175132a6f8ca9cb969R48-R52) ya esta en producción

**Comment by tommygonzaleza** [comment]
Por alguna razon hay algunos estudiantes en los que no aparece el mensaje y otro en los que si
![Screenshot 2024-04-16 at 9 22 21 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/eb6d725c-0864-4e0a-b79b-f8d8522e6230)
