### ISSUE TITLE
Broken badges

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7178]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42687-1866efebc05ef79b9d2c99baba1bc3a3) 

 The yellow background should be 100% width.
The last badge is cut in half

---
**Source URL**:
[https://website-v2-fdp1z36ik-geeksacademy.vercel.app/us/the-academy](https://website-v2-fdp1z36ik-geeksacademy.vercel.app/us/the-academy)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1817x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/2039
<hrs>0.5</hrs>
