### ISSUE TITLE
Cambios de la sección overlaped

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7179]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42688-6ce705da3fe2567175bff713aead9edd) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-course-geeksacademy.vercel.app/es/coding-bootcamps/curso-ciberseguridad](https://website-v2-git-fork-g-code7-course-geeksacademy.vercel.app/es/coding-bootcamps/curso-ciberseguridad)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1915x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>0.75</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2027
