### ISSUE TITLE
Grafico para representar el provisioning bridge

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7182]
Cumpliendo con la imagen de 4Geeks debemos hacer un gráfico que explique el [Provisioning Bridge de 4geeks](4geeks.com/provisioning).

The diagram begins with the representation of a learner's entry point, symbolized by an icon of a person next to a computer, where they are about to click on a project link. This action is visually represented by a cursor clicking on a link icon, emphasizing the simplicity of starting the process.

From this initial action, the diagram branches into two pathways, indicating a decision point for the learner. Each path leads to a different coding environment: one for VSCode Gitpod and another for VSCode Codespaces. These options are represented by labeled icons, making it clear that the learner has the flexibility to choose their preferred environment.

After the selection is made, the diagram converges onto a singular process: the automatic provisioning of a new virtual computer. This step is illustrated by an icon of a cloud with a computer screen, highlighting the cloud-based nature of the technology and its capability to instantly set up a ready-to-use coding environment. The diagram specifies that this virtual computer is preloaded with all the necessary technologies for the selected project, ensuring a smooth and efficient setup process.

Next, the diagram expands to showcase the compatibility of the system with various hosting platforms, represented by icons for Vercel, Heroku, and Render.com. This section demonstrates the flexibility of the Provisioning Bridge in deploying projects to different platforms, facilitating a broader range of final product hosting options.

The final section of the diagram emphasizes the availability of comprehensive documentation. It is depicted by an icon of a document, suggesting that detailed guides and instructions are readily accessible to help learners navigate the process of creating and publishing their code.

Throughout the diagram, the use of icons and labels plays a crucial role in conveying information clearly and efficiently. The visual flow from one step to the next is designed to be intuitive, ensuring that the viewer can easily follow the progression from initial link click to project deployment. The diagram as a whole encapsulates the seamless, user-friendly experience provided by the Provisioning Bridge, highlighting its value in simplifying the coding learning process.

- [Imagen generada por chatgpt](https://files.oaiusercontent.com/file-HNi9MocZeJ9ripgAxCDe2gv5?se=2024-04-09T19%3A35%3A59Z&sp=r&sv=2021-08-06&sr=b&rscc=max-age%3D31536000%2C%20immutable&rscd=attachment%3B%20filename%3D70958cc4-2d2b-4e01-a027-38b55ed1cd0c.webp&sig=4ssH3ccvD/%2BHUxhyA3B9fk3SJch6hO6kTfF0pjG1Z%2BU%3D)
- [Una de hubspot](https://f.hubspotusercontent20.net/hubfs/5670923/Picture3.png)
- [Otra de allxon](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.allxon.com%2Fprovisioning&psig=AOvVaw27VuLEUhAmIN4QzrtWk9Zu&ust=1712777268779000&source=images&cd=vfe&opi=89978449&ved=2ahUKEwjn6t_W7rWFAxXRmoQIHTYrDLMQjRx6BAgAEBY)

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42695-a5f4518b0fa0c963deb820c44dded23b) 

---
**Source URL**:
[https://dev.4geeks.com/provisioning](https://dev.4geeks.com/provisioning)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 122.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1915x892</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] Ponlo en 2D, similar al de webpack

**Comment by ali5uarez5** [comment]
Icono: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2574%3A3609&mode=design&t=eC6fgmJfpysszFey-1

**Comment by ali5uarez5** [comment]
Usar a la derecha el logo de visual code studio

**Comment by tommygonzaleza** [comment]
- [ ] Falta agregar los iconos de las tecnologias (Se pusieron en figma al lado de la lista de los iconos de todas las tecnologias)
- [ ] Falta agregar el icono de visual studio code a la derecha

**Comment by tommygonzaleza** [comment]
- [ ] Cambia los iconos agregando estos:
     - python
     - javascript
     - node
     - php
     - java

**Comment by ali5uarez5** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/7792206b-6b66-4de5-97bd-cd6c3a069d38)



![Image](https://github.com/breatheco-de/breatheco-de/assets/105449728/d0675e76-344c-46e3-8345-db99f5c46d11)
