### ISSUE TITLE
Crear otra version del endpoint para obtener un asset

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7183]
- [ ] Agregar carpeta un v2 en registry similar a como se hace en el modulo de activity, lo que nos permitira tener diferentes versiones de un mismo endpoint.
- [ ] Debemos agregar la version 2 del endpoint: `GET https://breathecode.herokuapp.com/v1/registry/asset/<asset_slug>`
- [ ] Esta v2 debe consumir usando el decorador `@has_permission('<consumable>')`.
- [ ] Se debe agregar una funcion de consumo para que sea utilizada en el decorador y cuya finalidad es solo consumir si la cohort es available_as_saas.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1337

**Comment by tommygonzaleza** [comment]
Se pidieron unos cambios respecto a unas validaciones relacionadas al academy en el consumer
