### ISSUE TITLE
Video del landing principal de chile (version español) debe tener un video en español

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7185]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42702-46d969265743db0bb3e9c6180bf161e3) 

 Revisar todas las demas landings pricipales de locaciones.

---
**Source URL**:
[https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-santiago?lang=es](https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-santiago?lang=es)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1073x965</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>0.9</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2057
