### ISSUE TITLE
Error 500 cuando se intenta consultar los codereivisions en el dashboard

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7197]
- [Error desde el network tab](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42712-78b43cd657aeb7d41617a3236e16e2e4) 
- [Informacion en la terminal de heroku](https://github.com/breatheco-de/breatheco-de/assets/426452/bd3a81ed-349f-4350-9364-3800688876bd)
- Para replicar el request, entrar al dashboard de 4geeks.com [con el usuario bobby dylan](https://4geeks.com/?token=80c94899d5415b2da6ee8ea02196a08a8c58e606).

 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x965</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by tommygonzaleza** [comment]
Ya no esta ocurriendo el error
