### ISSUE TITLE
Request para obtener credenciales de rigobot parece estar haciendose al host incorrecto

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7198]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42713-a89390a23a18eb702844728294f74094) 
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x965</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by ArielCalisaya** [comment]
ya esta solucionado
