### ISSUE TITLE
Build button doesn't update /dist folder

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7202]
**Describe the bug**
The build button doesn't update the folder for the preview. If you move to the next exercise and then go back, it does update the preview

**In what exercise**
[This exercise](https://github.com/arnaldoperez/javascript-events-tutorial-exercises) step 7

**Comment by Charlytoc** [comment]
Ejercicio de eventos y DOM actualizados, ahora usando versión @learnpack/dom@1.1.6 del compilador para dom
