### ISSUE TITLE
Problemas al iniciar logeado un evento en vivo .

### ISSUE THREAD

**Issue by JorgeCoto98** [breatheco-de/breatheco-de#7203]
### Bug description

Al haber iniciado sesión creando una nueva cuenta me dirigí al dashboard y trate de entrar en un evento en vivo emitido en el momento, da el mensaje que necesito acceder a un plan para este evento por lo que accedo y me envia al formulario para crear otra cuenta nuevamente. 
![Captura de pantalla (153)](https://github.com/breatheco-de/breatheco-de/assets/120097112/41bfbd38-4d68-4dfa-b062-537b2e6e879a)
![Captura de pantalla (151)](https://github.com/breatheco-de/breatheco-de/assets/120097112/ba2c26bd-e72f-48d2-9553-f6dbfffe1795)
![Captura de pantalla (152)](https://github.com/breatheco-de/breatheco-de/assets/120097112/1cfbfff7-3f12-4025-8793-8519fd6ef70f)

### Steps to reproduce

1. Crear cuenta.
2. Acceder al dashboard.
3. Entrar en un evento en vivo emitido en el momento.

**Comment by tommygonzaleza** [comment]
Era un problema de la configuracion del plan en el servidor de pruebas
