### ISSUE TITLE
Rediseño de tutoriales interactivos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7208]
Debemos mencionar por que es tan bueno hacer un tutorial con 4geeks, mencionando la ayuda de LearnPack y todos los beneficios que trae, como:

 - Obten feedback instantaneo con Test automatizados
 - AI integrado para ayudarte con tus dudas
 - Nada de instalacion, vas directo a programar

Debe ser como un banner al inicio del readme de cada tutorial

Aqui se habla de LearnPack para que tomes algunos datos: https://4geeks.com/learnpack

**Comment by tommygonzaleza** [comment]
Esta esperando por estos dos issues:
- https://github.com/breatheco-de/breatheco-de/issues/7300
- https://github.com/breatheco-de/breatheco-de/issues/7182

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=13399%3A43033&mode=design&t=EVqJnkawFKKzgsYD-1

**Comment by alesanchezr** [comment]
Esperando tener los iconos listos.

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=13399-43033&t=egjqBcFpM7LvvWMw-1
