### ISSUE TITLE
Agregar todos los alumni de bocacode en nuestro repo

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7209]
Nosotros pasamos el codigo de la pagina de bocacode a un repo nuestro. Nos falta ahora llenar los datos de los alumnos que aparecen en la pagina original de bocacode.

La data sale de estos JSON: https://github.com/4GeeksAcademy/bocacode-website/tree/master/app/data, es muy similar a los YML de 4geeksacademy.

- [ ] Falta llenar la informacion de cada alumno que se muestra aqui: https://bocacode.com/alumni, podras ver que en el nuestro ya hay algunos agregados pero faltan muchos
- [ ] Debes asegurarte que la data se este mostrando tambien en la vista de cada alumni, por ejemplo esta es la del primero: https://bocacode.com/alumni/software-engineer/joelle-johnson

Esta es nuestra pagina: https://boca.4geeksacademy.com/alumni
Esta es la de bocacode: https://bocacode.com/

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/bocacode-website/pull/9
