### ISSUE TITLE
Corregir nuevos descuentos

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7218]
Se va a agregar para que parezca que estamos en descuento, esto ya se esta pasando a development, la idea es que antes de pasarlo a produccion, lo puedas poner bien en todas las academias y programas.

La idea es que se muestre como si estuviera en descuento el plan de cuando pagan decontado, mostrando el precio original tachado, con un 40% off. El precio no va a cambiar, solo que ahora se va a mostrar como si el precio original fuera mas caro para que parezca que esta en descuento.

**Comment by G-code7** [comment]
Noté que habían algunos textos en ingles, cuando se supone deberían estar en español, así que también  lo arreglé acá.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2065

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2079

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2091
