### ISSUE TITLE
Error al intentar usar la simulación de pagos con Stripe

### ISSUE THREAD

**Issue by veljzs** [breatheco-de/breatheco-de#7228]
### Bug description

Se produce un error al intentar utilizar la simulación de pagos con Stripe. Cuando intento realizar el pago con una tarjeta de Stripe, no se carga y me aparece un error 500 porque el chosen_period no puede ser "ONE_TIME".

![Screenshot 2024-04-18 090346](https://github.com/breatheco-de/breatheco-de/assets/128405596/c8ef865c-09d2-47ce-a6e8-4cf7a3b36fde)

### Steps to reproduce

Intentar comprar un plan utilizando una tarjeta de simulación de pagos de Stripe en https://dev.4geeks.com/

**Comment by tommygonzaleza** [comment]
Ya fue resuelto
