### ISSUE TITLE
Agregar LearnPack a ejercicios de Numpy 100

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7245]
Existen unos ejercicios de numpy que son muy famosos y que se usan en una universidad, queremos pasar estos ejercicios a LearnPack para mejorarles la experiencia.

Repo: https://github.com/rougier/numpy-100

**Comment by alesanchezr** [comment]
Esto mejor lo hacemos con uno de MDC, esperemos a tener el GO del profesor.
