### ISSUE TITLE
Crear landing para escoger carrera

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7246]
Debemos tener un landing de todos los cursos, este landing tiene que enfocar la comunicacion en que escojan su camino de carrera, mostrando asi (Quizas con las tarjetas que ya existen de los cursos, pero si hace falta otra, se crea) todos los cursos disponibles.

Puedes ponerlo en el landing de pricing, reemplzando las tarjetas de los precios por esto

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=L0GdbVJQAluCXofW-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar en el card de cada carrera, unos bullets de informacion de esa carrera, por ejemplo:
     - Average salary
     - Job Positions
     - Career Growth
- [ ] Quitar lo de starts in
- [ ] Prueba poner precio: from $64.99 p/mo

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=fbvFSRrKYr88YLts-1

**Comment by tommygonzaleza** [comment]
Esta casi listo solo falta:
- [ ] Agregar mas gente en el landing, solo hay una seccion con personas

**Comment by tommygonzaleza** [comment]
Se va a desarrollar en este [issue](https://github.com/breatheco-de/breatheco-de/issues/7305)
