### ISSUE TITLE
Crear landing para escoger plan

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7247]
Tenemos que tener otro landing de pricing, muy similar al que ya tenemos (Podemos reutilizar el diseño de las tarjetas de precios), en el que mostramos la opcion gratuita (Es una prueba de los que incluye el plan), una subscripcion paga de 20$ al mes que te da acceso ilimitado al LearnPack AI & Rigobot, y el plan de immersive bootcamp que es otra manera de adquirir lo que incluye esta subscripcion anterior y mucho mas

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=bY16AvzI12Mbx50Y-1

**Comment by tommygonzaleza** [comment]
- [ ] Documentarlo para que Ariel tenga claro todos los detalles

**Comment by tommygonzaleza** [comment]
- [ ] Agregar mas a Rigobot en el landing. Puede ser con el componente de los landing de los bootcamps

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7306)
