### ISSUE TITLE
Calculation error on checkout for 3 months payment option

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7256]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/a99bb2db-4483-4170-9115-4b685d107ec2)

Issue is circled in red

### Steps to reproduce

Begin checking out process for a self-paced bootcamp. Select the 3 months payment option.

**Comment by tommygonzaleza** [comment]
- [ ] Sigue ocurriendo:
![Screenshot 2024-05-09 at 4 13 54 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/00abfc59-d79a-4713-a7c1-8ef817b523fd)
