### ISSUE TITLE
Misleading "Subscribe to workshops" button and bad graph axis

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7259]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/a5170bff-c02c-4d8b-8072-01819555412a)

- [ ] #7311

Clicking the "Subscribe to workshops" button should not direct you to the pricing page especially if you are already a member and logged in. Perhaps this button should put you on an email list with information about upcoming workshops.

### Steps to reproduce

Navigate to the events landing page (4geeks.com/workshops).
Scroll down until you see the above graphic and button.

**Comment by tommygonzaleza** [comment]
We are going to redirect them to the workshops' landing, and created another issue to fix the graph
