### ISSUE TITLE
Reorder material at the bottom of exercises

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7262]
### Bug description

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/1514807b-1e0f-472e-97c7-312042f581d3)

Suggested reorganization on left, current organization on right.
If an article has a "Read Next" section, move that directly under the article. Then have the CTA for the self-paced bootcamps. Have the upcoming workshops as the last item before the footer.

### Steps to reproduce

Navigate to an exercise in the learning library. (https://4geeks.com/interactive-exercise)

This example was from Pandas for Machine Learning

**Comment by AltaciosTheDev** [comment]
Confirmed.

Organization is still like the one on the right side of the picture above. Suggestion hasn't been implemented.
