### ISSUE TITLE
Se estan marcando como GRADUATED sin terminar ni un proyecto

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7270]
Todos estos estudiantes fueron marcados como GRADUATED por alguna razon, a pesar de no haber entregado todas sus tareas. De hecho algunos de ellos se acaban de unir a la cohort
![Screenshot 2024-04-25 at 10 04 46 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/176245d1-2911-4107-a4b1-1ccd5ea25b7c)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1355
