### ISSUE TITLE
Crear guidelines de como deben hacerse los code reviews por los profesores detalladamente.

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7274]
- [ ] Debemos incluir primero el paso a paso para poder hacer un code review.
- [ ] Luego explicar que significa cada cosa de la modal de code reviews. (Cuales son commitfiles, el feedback del estudiante, cuales son los code reviews, etc).
- [ ] Tener unos guidelines de que deben tomar en cuenta a la hora de revisar un codigo en cada lenguaje: python, javascript, html, css, etc.
- [ ] Agregar cualquier recomendacion que ayude a obtener mejores code reviews en caso de que se decida entrenar a rigobot en un futuro

**Comment by Charlytoc** [comment]
# Guidelines al momento de hacer Code Reviews

Los **Code Reviews** son una de las características más interesantes de 4Geeks.com. Le dan al mentor una herramienta rápida para poder revisar código, y al estudiante, una fuente adicional de **feedback** para mejorar como desarrollador. Un Code Review, como su nombre lo indica, no es más que un comentario con respecto a una porción de código. En este artículo analizaremos las características deseables que debe tener un Code Review para ser efectivo para el estudiante.

Empecemos por lo primero:

# ¿Cómo hacer un Code Review desde la plataforma de 4Geeks.com?
### Paso 1: Selecciona un programa.
Si eres un mentor, tienes un dashboard donde puedes ver los distintos programas o cohorts en los que estás. El primer paso para hacer un Code Review es entrar en alguno de estos programas.

![example programs](https://github.com/breatheco-de/breatheco-de/assets/107764250/ed6cfb70-bd4a-4571-b632-7d1d82bd76a4)

### Paso 2: Ve al apartado de **Assignments**
Necesitas hacerle Code Reviews a alguna entrega de un estudiante, así que dirígete a ese apartado.
![assignments](https://github.com/breatheco-de/breatheco-de/assets/107764250/8e818c70-d71f-4e1b-ba1c-b20359468234)

### Paso 3: Selecciona la vista de proyectos

![Select projects view](https://github.com/breatheco-de/breatheco-de/assets/107764250/a5604dd2-4d69-4d44-b80f-76eda5c61020)

### Paso 4: Selecciona un proyecto
Los proyectos disponibles para Code Review son los entregados, estos aparecerán con un botón azul y el texto "Review" dentro del mismo. Presiona ese botón.

![review button](https://github.com/breatheco-de/breatheco-de/assets/107764250/2da5d7e5-6953-48ec-95a3-bb18da4ad4f0)

### Paso 5: Empieza a hacer Code Reviews
Si el proyecto no tiene al menos 3 Code Reviews, no puede ser marcado como **Aprobado** o **Rechazado**. Presiona el botón "Start code review" para empezar a hacer Code Reviews.

![Start code review](https://github.com/breatheco-de/breatheco-de/assets/107764250/08e37594-b12f-4e3d-a56c-1b3383fdc187)

### Paso 6: Selecciona el Commitfile que quieres revisar
Un commitfile es un archivo modificado por un estudiante en un commit en particular. Por defecto, Rigobot analiza los tres últimos commits de un repositorio, y según el **Committer** de interés, extrae los archivos necesarios en cada commit. Los commitfiles son una de las partes fundamentales del Code Review, es bueno saber el uso de ese archivo en el proyecto que estés revisando para que la review tenga más sentido. Selecciona un Commitfile con el botón: **Start Review**
![commitfiles view](https://github.com/breatheco-de/breatheco-de/assets/107764250/e82e7315-2673-4a68-ae85-5eafd909945e)

### Paso 7: Selecciona una porción de código del Commitfile
Cuando selecciones un Commitfile se mostrará una modal con el código de ese archivo en particular, puedes seleccionar las líneas que quieras comentar, luego presiona el botón azul para iniciar el Code Review.

> Sugerencia: Revisa primero todo el código, así puedes saber exactamente dónde el código tiene fallas o mejoras posibles antes de ir y seleccionar cualquier parte que te parezca mejorable, los archivos suelen tener un sentido y este sentido es importante para dar reviews de calidad.

![Select code from commitfile](https://github.com/breatheco-de/breatheco-de/assets/107764250/6e8f7dd7-08de-4d26-b39d-2b3b492a7f1f)

![Selected code](https://github.com/breatheco-de/breatheco-de/assets/107764250/f2565833-b79a-4a2e-ae32-8f29d1c2b326)

### Paso 8: Escribe el comentario.
Comentar el Code Review es quizás la parte más importante. Más adelante vas a encontrar una guía de puntos a tener en cuenta para escribir un Code Review de calidad. Luego de escribir un comentario de calidad, presiona el botón de **Submit** y habrás hecho tu primer Code Review.

![Write a comment](https://github.com/breatheco-de/breatheco-de/assets/107764250/53c88ae8-2a22-496b-a13e-65f3bdb2102a)
