### ISSUE TITLE
Actualizar active users and el componente de about your cohort

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7276]
- [ ] We have to update the serializer of this endpoint that fetches active users to include user.last_login and that way we use the front end to count the number of users with user.last_login < one week ago

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42865-ce8a88588d9862aff9df55b838a1b40c) 

---
**Source URL**:
[https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2](https://4geeks.com/cohort/start-coding-using-javascript-1/start-coding-using-javascript/v2)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1708x873</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] Si no hay ningun "active geek" (Last login < 1 week), entonces deberiamos mostrar solo "Alumni Geeks", teniendo un tab unico
- [ ] Abajo debe mostrar el perfil de las personas, si no tiene foto de perfil, usa los iconos de los muñequitos, tal como se hace en los workshops, replica lo que hacemos ahi para generar los iconos de forma aleatoria
