### ISSUE TITLE
Correcciones al syllabus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7282]
- [x] Agregarle projectType: "tutorial" a todos los proyectos que deben tener la cajita azul para abrir con learnpack.
- [x] Cambiarle el asset.type a "PROJECT" a todos los laboratorios que tienen entregable.
- [x] Cambiarle el asset.type a "EXERCISE" a todos los laboratorios que no tienen entregable.

Todas las instrucciones de projectos deben tener:
```
Introduction
🌱 How to start this project.
🚛 How to deliver this project
📝 Instructions
```

### Semana 1

- [x] El proyecto de `understanding network internals` necesita traducciones en el learn.json
- [x] Borrar los quizzes que estan dentro de las lecturas y migrarlos a los quizzes o dejarlos como "open questions". Revisar cada una de las lecturas.
- [x] Actualizar las instrucciones de los readme para dejar mas claro: Como empezar el proyecto, 
- [x] Actualizar la seccion de contributors de los readme's de los proyectos para que tambien este el link de cybersecurity bootcamp al final.

### Semana 2

- [x] proyecto iptables-blocking-practice le falta completar bien el learn.json
- [x] falta projecto de instalation-virtualbox-guest-additions (va a ser un fork del de windows)
- [x] projecto presentacion-distros falta repo completo.
- [x] [Update script cron task debian](https://github.com/4GeeksAcademy/update-script-cron-task-debian) completar traducciones en el readme.

Semana 3
- [x] Falta la semana 3, no esta cargada completa.

Semana 4
- [ ] Falta la semana 4, no esta cargada completa.

**Comment by arnaldoperez** [comment]
Para los "laboratorios" de Daniela que resultaron ser muy basicos, se adapto la idea a 💪 **Desafío/Challenge:** actividades opcionales no evaluada que el estudiante puede realizar para reforzar los conocimientos
