### ISSUE TITLE
No permite abrir un ejercicio con LearnPack

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7284]
No permite abrir un ejercicio con LearnPack aunque en el backend si esta marcado como `gitpod=True`

<img width="1426" alt="Screenshot 2024-04-29 at 5 12 50 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/d5c22d5a-aa40-4c0e-b518-40f8db6b9409">

**Comment by ArielCalisaya** [comment]
Ya estaba corregido
