### ISSUE TITLE
Language issues with articles

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7287]
### Bug description

Issue is possibly with tagging/labeling articles

Articles in Spanish are appearing in lessons when the user's language is set to English.

### Steps to reproduce

Go to 4geeks.com/lessons
Have user language set to English.

Articles with issues:

Title and article in English, Description in Spanish
- Introduction to VirtualBox (tagged: Cybersecurity)
- Legal and regulatory compliance  (tagged: Ciberseguridad)
- IP address management (tagged: Direccion-IP)

Title in English, Article and description in Spanish
- Connecting a Database to our REST API (tagged: Rest, TypeOrm, APIs)

**Comment by tommygonzaleza** [comment]
Solved
