### ISSUE TITLE
Node API Tutorial doesn't have LearnPack connected

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7288]
### Bug description

The Node API Tutorial currently looks like this:
![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/d821a1b9-46ca-46fe-91d3-58b45a314fa1)

when the right-hand box should have an "Open with LearnPack" option like this:
![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/174c76f7-60c0-48de-859b-adcb82d0fc75)

### Steps to reproduce

https://4geeks.com/interactive-exercise/node-api-tutorial

**Comment by tommygonzaleza** [comment]
We fixed it
