### ISSUE TITLE
Crear consumibles por cada service item asociado a un service set

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7293]
En un service set se agregan varios services asociados, por otro lado, tenemos los plan service items, por cada service item que este en el service set, se debe crear un consumible de forma individual, permitiendo asi, tener cantidad de consumibles diferentes por cada service del service set.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1374
