### ISSUE TITLE
Rediseño del componente de `CardAsset`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7299]
Agregar variante al componente que incluya estas propiedades:

- [ ] Cuantas personas han hecho este proyecto.
- [ ] Icono de las tecnologias del proyecto. (Las tecnologias deben verse con iconos en los landing pero en los demas lugares como lecturas, etc, )
- [ ] Duration.
- [ ] Dificultad

> Ubicar y definir el componente de la card usada para los workshops

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2574%3A3609&mode=design&t=eC6fgmJfpysszFey-1

**Comment by ali5uarez5** [comment]
workshops: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=15414%3A57537&mode=design&t=eC6fgmJfpysszFey-1
