### ISSUE TITLE
Crear icono del provisioning bridge

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7300]
Debes partir de la explicacion del provisioning bridge dada en este [issue](https://github.com/breatheco-de/breatheco-de/issues/7182)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=13399-43033&t=eAp6LbApLXAvta2d-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7438
