### ISSUE TITLE
porque se ve asi la tarjeta de projects?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7301]
Vamos a esperar a aque ali termine la #7299 para mejorar como se ve el projecto en esta vista.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42904-c28ad3e9f7f0deb1c8a7312086d93728) 

---
**Source URL**:
[https://4geeks.com/es/workshops/aprende-a-crear-aplicaciones-con-multiples-vistas-usando-react](https://4geeks.com/es/workshops/aprende-a-crear-aplicaciones-con-multiples-vistas-usando-react)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x869</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Se rediseño y se esta trabajando en otro issue
