### ISSUE TITLE
Informacion incorrecta en preview de Applied Ai

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7304]
En el preview de la página web del programa de Applied AI USA sale es información de data science

![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/c4e8cc65-a8fb-49f1-ac0c-3abbdbde685b)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2075
