### ISSUE TITLE
Cambios al landing de pricing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7306]
Este es el diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=12466%3A62638&mode=design&t=3zO3EQb6lneDl6Av-1

Puntos a tomar en cuenta:

- [ ] Debes identificar si el plan es free o free trial para mostrar el mensaje correcto, esto ya lo estas haciendo en checkout.
- [ ] Cuando el plan sea con financing options, es decir, no es una subscripcion y se paga por mes hasta completar el pago, entonces debes mostrar el mensaje: `You are buying <plan_slug_unslugified>` (El slug del plan convertido en titulo). En el figma veras como se ven ambos diseños.
- [ ] Mira como se ve el dropdown de los financing options

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-05-07 at 5 32 30 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/197e02bb-c003-4a4a-b9e5-7b1ce5416d21)

**Comment by tommygonzaleza** [comment]
- [ ] Permitir recibir plan por querystring para aquellos planes que no pertenezcan a un curso

**Comment by ArielCalisaya** [comment]
Listo!

**Comment by tommygonzaleza** [comment]
No debe mostrarme el boton de financing options si es solo esa opcion de pago
![Screenshot 2024-05-15 at 5 18 40 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/056e7f62-8171-4f56-ac2b-4922e7968c07)

**Comment by ArielCalisaya** [comment]
Listo!
