### ISSUE TITLE
Centrado y espacio de titulos en la vista de celular y tablet

### ISSUE THREAD

**Issue by JorgeCoto98** [breatheco-de/breatheco-de#7308]
### Bug description

![WhatsApp Image 2024-04-25 at 2 55 11 PM (3)](https://github.com/breatheco-de/breatheco-de/assets/120097112/8469dc5d-27b6-44a8-b7b1-c04cbbe23965)
Hay títulos y botones que no están centrados en la vista de dispositivos móviles y el espaciado lateral izquierdo es muy reducido, por lo que aparece muy pegado al lado izquierdo de la pantalla.

### Steps to reproduce

En el inicio de 4geeks, en la sección de "Learn to code using AI"

**Comment by tommygonzaleza** [comment]
Se agrego en este issue: https://github.com/breatheco-de/breatheco-de/issues/7312
