### ISSUE TITLE
language bug  in  chile form

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#7313]
este formulario de chile le hace falta un parámetro para recibir la traducción en español. 
nota: en el yml ya está traducido en ingles y español. 
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/8be284e9-23a1-4fda-883c-0a9d7cab577b)

![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/5e71b3a9-2825-474d-91b5-0fd42e083b17)

**Comment by tommygonzaleza** [comment]
- [ ] Sigue sin tener traduccion en los consent
