### ISSUE TITLE
No esta cargando la cohort apenas te registras

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7316]
Luego de registrarte en el curso y pagar, te envia al dashboard de la cohort 

<img width="1447" alt="Screenshot 2024-05-03 at 1 14 13 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/3b3cc9e0-6f65-42b6-b003-8723443bb097">

**Comment by tommygonzaleza** [comment]
- [ ] Esta mostrando un mensaje como que no se han guardado los cambios del form, quizas deberiamos limpiar el form antes de enviarlo al landing del curso
![Screenshot 2024-06-04 at 11 42 06 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/8c03db08-73a6-49ae-bca8-a68efca2fe3e)

**Comment by ArielCalisaya** [comment]
Esa alerta la añadí para evitar que se cambie de pestaña o cierres de ventana accidentales, y se centre en presionar el botón

**Comment by tommygonzaleza** [comment]
Se debe resolver al terminar este issue: https://github.com/breatheco-de/breatheco-de/issues/7450
