### ISSUE TITLE
No utilizar headings en el sidebar

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7321]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-42952-710e40ad1cb0dcec80f90e0514d97e40) 

 Revisar todos los compoenntes

- [ ] Weekly coding challenge
- [ ] Podcast
- [ ] [Publicidades de cursos](https://tinyurl.com/2yb8xbsd)

---
**Source URL**:
[https://4geeks.com/how-to/clone-array-javascript](https://4geeks.com/how-to/clone-array-javascript)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1708x873</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Hazlo un span con estilos de heading
