### ISSUE TITLE
Reorder checkout screen

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7327]
### Bug description

Reorder the options when checking out for a self paced bootcamp

- 1 payment
- 3 payments
- 5 payments

![image](https://github.com/breatheco-de/breatheco-de/assets/46685557/b6133f73-ce97-4f52-bcb7-6a28e119b0b1)
Switch these options

### Steps to reproduce

Select a self-paced bootcamp
Begin the checkout process

**Comment by tommygonzaleza** [comment]
We removed that list from the checkout
