### ISSUE TITLE
Deberias obtener el planoffer del free trial para poder mostrar el precio del plan original

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7332]
![Screenshot 2024-05-07 at 5 24 39 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/bf4fe299-180e-4322-bb6e-a7b101d17164)

**Comment by tommygonzaleza** [comment]
No me explique bien en el primer comentario, debe tener tanto la opcion de free trial como los precios del suggested_plan

**Comment by ArielCalisaya** [comment]
Se están mostrando ambos 

![Image](https://github.com/breatheco-de/breatheco-de/assets/51676628/35f8ba04-10ff-4486-a096-17741053e733)
