### ISSUE TITLE
El quote de abajo deberia tener un formato similar al de arriba 

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7337]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-43027-dba81d4e786607abfc5ce5f0bea89a29) 

---
**Source URL**:
[https://4geeks.com/syllabus/full-stack-fake-6/read/what-is-debugging-code](https://4geeks.com/syllabus/full-stack-fake-6/read/what-is-debugging-code)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x893</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by AltaciosTheDev** [comment]
Confirmado. 

Posicionamiento de texto ha cambiado y estan identicos.
Imagenes de quote son distintas y solo quote de abajo tiene linea cruzando a lo largo de la pagina.
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/1b5fb02c-21ce-4f53-869b-5cedd5ddb87a)

**Comment by tommygonzaleza** [comment]
Se desarrollo de esa manera para tener diferentes diseños en cada quote
