### ISSUE TITLE
Agregar escenario de `CardAsset` para workshops

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7339]
Debe tener:

- Tecnologias del proyecto, si no esta, debe mostrar el event type
- Small description
- Starting soon o live now
- Duracion
- Idioma
- Host del workshop (si lo tiene)
- Botton de join workshop o register

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=15433%3A70165&mode=design&t=5Zf0xeCpO92hDOAC-1
