### ISSUE TITLE
Agregar escenario de `CardAsset` para lessons 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7340]
Debe tener:

- Tecnologias del lesson
- Si tiene video 
- Small description
- Duración del leason tipo "5 min read"
- Hacer un ejemplo de una lesson sin tecnologias a ver ocmo queda
- No hace falta tag de tipo de asset.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=15433%3A70165&mode=design&t=5Zf0xeCpO92hDOAC-1
