### ISSUE TITLE
Agregar escenario de `CardAsset` para Projects y Exercise

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7341]
Debe tener:

- Tecnologias
- Dificultad
- Si tiene video solucion
- Si tiene codigo de solucion
- Small description
- Duracion del projecto en horas
- Si es interactivo y con learnpack
- Si tiene video introducción
- Cuanta gente ha hecho este project
- Cuantos steps tiene

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=15433%3A70165&mode=design&t=5Zf0xeCpO92hDOAC-1
