### ISSUE TITLE
Plan not generated for users signing up via exercises

### ISSUE THREAD

**Issue by christadkelly** [breatheco-de/breatheco-de#7346]
### Bug description

When signing up/ creating an account to get access to an interactive tutorial, no subscription or plan is generated on the backend.

Only tested on Dev.

### Steps to reproduce

https://dev.4geeks.com/interactive-exercise/pandas-exercises-tutorial

https://github.com/breatheco-de/breatheco-de/assets/46685557/a43b8f93-6dbc-4090-986b-7c9cd5ee67fe

**Comment by tommygonzaleza** [comment]
We couldn't replicate the bug, please try replicating it again and if you do, show me the headers of the request
