### ISSUE TITLE
En lugar de apply more deberian decir read more y no tiene porque ser azules

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7348]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-43077-a2c6ae952b26b99e9ba180f1cd3da384) 

---
**Source URL**:
[https://website-v2-hneygj88d-geeksacademy.vercel.app/us/index?lang=en](https://website-v2-hneygj88d-geeksacademy.vercel.app/us/index?lang=en)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 123.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1746x869</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2096
