### ISSUE TITLE
Agregar experiencia guiada 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7360]
- [ ] Agregar en la experiencia Rigobot
- [ ] Mejorar el sidebar de la izquierda, debe entenderse que se puede usar para navegar entre los modulos. Quizas es solo mostrar los assets del modulo en el que esta y mostrar los otros modulos para que pueda navegar a ellos pero no directamente a alguno de los assets del otro modulo.

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=8dCXpCx3IVLAFX3r-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar el icono de click and learn en el boton de open in the cloud.
- [ ] Agregar tambien los iconos de las tecnologias

**Comment by tommygonzaleza** [comment]
## Vista para los proyectos:

Se tienen diferentes versiones para los proyectos:

### Cuando no has empezado el proyecto (`delivery_status=PENDING` y `revision_status=PENDING`):

- [ ] Debe tener titulo, descripcion, y video.
- [ ] Luego el README

### Cuando ya lo entrego pero no lo han revisado (`delivery_status=DONE` y `revision_status=PENDING`):

- [ ] Debe tener el titulo, descripcion.
- [ ] Acceso a las instrucciones y video solucion con botones.
- [ ] Mostrar un link al entregable que agrego. (O a los archivos agregados)
- [ ] Mostrar un mensaje de que el profesor lo revisara pronto y que va a recibir un email cuando sea revisado.

### Cuando ya lo entrego y fue rechazado/aprobado con Code reviews (`delivery_status=DONE` y `revision_status=REJECTED`):

- [ ] Titulo y descripcion
- [ ] Acceso a las instrucciones y video solucion con botones.
- [ ] Mostrar un link al entregable que agrego. (O a los archivos agregados)
- [ ] Mensaje del profesor con el feedback.
- [ ] Mostrar listado de code reviews.

### Cuando ya lo entrego y fue rechazado/aprobado sin Code reviews (`delivery_status=DONE` y `revision_status=REJECTED`):

- [ ] Titulo y descripcion
- [ ] Acceso a las instrucciones y video solucion con botones.
- [ ] Mostrar un link al entregable que agrego. (O a los archivos agregados)
- [ ] Mensaje del profesor con el feedback.

**Comment by tommygonzaleza** [comment]
- [ ] Cambiar el color de la primera version de un proyecto.
- [ ] Agregar boton de back to top cuando haces scroll y solo se ve el readme

**Comment by tommygonzaleza** [comment]
- [ ] Se debe cambiar las instrucciones del profesor por los code reviews, para que los code reviews sean mas relevantes

**Comment by tommygonzaleza** [comment]
- [ ] Falta la experiencia de los quizzes

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7648)

**Comment by tommygonzaleza** [comment]
- [ ] We are missing the menu's design

**Comment by tommygonzaleza** [comment]
- [ ] Agregar todos los diferentes status de un proyecto.
- [ ] Poner las versiones de los botones de entregar un proyecto.
- [ ] Poner las versiones del progreso de los subtasks marcados en la barra donde va el titulo.

**Comment by ali5uarez5** [comment]
Componentes documentados: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

Readings: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

Projects: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar intro video en lecturas en el task bar y que cuando se abra la lectura aparezca abierta por defecto como un popup encima del task bar

**Comment by ali5uarez5** [comment]
Video component: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=sI55kaB46faESjot-1

**Comment by ali5uarez5** [comment]
Updates in navigation: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=783-98026&t=sI55kaB46faESjot-1

**Comment by tommygonzaleza** [comment]
- [ ] Create a modal that will be used when you are going to the next module but you still have subtasks unmarked

**Comment by alesanchezr** [comment]
La modal tiene que tener cuantas tareas tienes pendientes de este asset.

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2256-102586&t=umpfEs3m6ztcjBQM-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7928
