### ISSUE TITLE
Cambios al home de 4geeksacademy.com

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7370]
- [ ] Rehacer esta seccion de Finance Your Future:
![Screenshot 2024-05-15 at 10 49 13 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/eede5997-9bca-4a56-b4e9-fd727b21048a)

- [ ] Agregar seccion donde se hable de scholarships y finance
- [ ] Quitar seccion de plans and payment
- [ ] Agregar cintillo de credibilidad que incluia lo de switchup, coursereport. Ese cintillo se sacó del home pero debería estarm, quizás mejorado, pero no quitado

**Comment by alesanchezr** [comment]
Lo cerre porque ya pudimos resolver con gustavo.

**Comment by ali5uarez5** [comment]
65% of our students join through Payment Plan
15% through ISA or Deferred Payment
20% through Universities and partnerships
90% of our student get a partial or total scholarship at the moment of securing their enrollment

**Comment by tommygonzaleza** [comment]
https://recharts.org/en-US/examples/TwoLevelPieChart

**Comment by tommygonzaleza** [comment]
- [ ] Hay que ver como solucionamos el borde ligero, puede ser dejarlo sin borde o ir probando otras opciones.
- [ ] Agregar bullets en el TwoColumn de Why 4Geeks

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=11784%3A8766&t=wQxoMURFlLZveWWL-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar el componente de video en seccion donde esta la china

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7435
