### ISSUE TITLE
El instructor principal debe ir primero que los asistentes

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7373]
![Screenshot 2024-05-15 at 12 36 05 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/39bf284b-5a29-415a-b377-98fd55dceef3)

**Comment by AltaciosTheDev** [comment]
Confirmed.

Currently Principal instructor is not showing. 
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/136d32b2-84cb-4820-8916-f647f28cd503)

**Comment by JennGuz** [comment]
https://github.com/breatheco-de/app/pull/1593
