### ISSUE TITLE
Cambiar texto de why 4geeks

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7378]
La seccion de [why 4geeks](https://www.awesomescreenshot.com/image/48194689?key=957ae64bac16a9202fccc8cb1d4dfe45) 
 en el home debe tener este [texto y bullets y boton](https://www.awesomescreenshot.com/image/48194667?key=9e22b53164241b384c0f88455570fd5a).

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2093
