### ISSUE TITLE
Cobrar rigobot a traves de Provisioning

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7381]
Hacer un upload para rigobot en provisioning, y que a partir de el se registren todas las actividades hechas por los estudiantes en rigobot, y a partir de ahi se agregue en el `ProviosioningBill` de la academia, para esto RigoBot debe ser un `ProvisioningVendor` mas.

- [ ] Agregar `FirstPartyCredentials` en el admin de linked_services.
- [ ] Utiliza este CSV para el consumo de los estudiantes, ahi podras ver la estructura: [consumption_period.csv](https://github.com/breatheco-de/breatheco-de/files/15327434/consumption_period.csv)
- [ ] Necesitamos replicar el codigo usado [aqui](https://github.com/breatheco-de/apiv2/blob/d81e0cb685ab64d9c2bfd77c84df94c0a7c494ba/breathecode/provisioning/actions.py#L245) (Podrias abstraerlo incluso la parte de determinar si es de una academia o no), pero ahora para cobrarles el uso de rigobot
- [ ] En el csv vas a poder ver el `user_id` del usuario en rigobot, debes buscar a ese usuario en `FirstPartyCredentials`, tambien te aparecera el `total_spent` que es el consumo en dolares.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1368

**Comment by tommygonzaleza** [comment]
Esta dando un error al intentar subir el archivo que se agrego en el comentario anterior
<img width="1355" alt="Screenshot 2024-07-02 at 4 11 24 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/cabb178d-a3b5-426e-b0ba-eab13941b317">

**Comment by jefer94** [comment]
No lo puedo replicar con ese archivo, porque le falta campos

**Comment by tommygonzaleza** [comment]
- [ ] No esta mostrando lo erroes
- [ ] El logo de 4geeks esta roto
