### ISSUE TITLE
Rediseño de landing de downloadables

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7383]

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=4143%3A2616&t=MdDEAR2By3QTuIsW-1

**Comment by tommygonzaleza** [comment]
- [ ] Poner la imagen que muestra parte de la guia en ingles. Puedes sacarlo de aqui: https://4geeksacademy.com/downloadables
- [ ] Genera esa imagen para cada downloadble

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=12317-11424&t=NkdYtuH0C0QIXAgG-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7437
