### ISSUE TITLE
Mejoras al landing de un tutorial interactivo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7385]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48222151?key=f9aad7e6bf433b0524d137eb1d0fc740&size=orig) 

---
**Source URL**:
[https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15506-61137&t=EWO8ihs6fyq8315o-0](https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15506-61137&t=EWO8ihs6fyq8315o-0)

**Comment by tommygonzaleza** [comment]
![Uploading Screenshot 2024-05-28 at 9.34.24 AM.png…]()

**Comment by ArielCalisaya** [comment]
Corregido!

**Comment by tommygonzaleza** [comment]
- [ ] Reemplazar icono de learnpack y click and code. Como se describe en este issue: https://github.com/breatheco-de/breatheco-de/issues/7438

**Comment by tommygonzaleza** [comment]
- [ ] Falta mostrar la informacion de si tiene video tutorial o no y si tiene video solucion o no. 
- [ ] Debes quiter el link del repositorio

**Comment by tommygonzaleza** [comment]
- [ ] El icono de cuando tiene video tutorial y solucion, debe ser un checkmark sin link cuando no esta logeado.
- [ ] Cuando esta logeado si debe verse como lo agregaste ahora

**Comment by ArielCalisaya** [comment]
Listo!
