### ISSUE TITLE
Footer de los landings dice 2019 pero se puede hacer que siempre diga el año actual con JS

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7394]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48289717?key=21dd378b864c20bad0c8a4cbef921d3d&size=orig) 

---
**Source URL**:
[https://website-v2-erl2qlpcc-geeksacademy.vercel.app/es/landing/bootcamp-de-programacion-santiago](https://website-v2-erl2qlpcc-geeksacademy.vercel.app/es/landing/bootcamp-de-programacion-santiago)

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/3d579ae7-71f7-4276-bb0a-a901646d4769)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2092
