### ISSUE TITLE
Logos de herramientas AI

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7402]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48347494?key=f1d30fb7e5291380faee1fdd9025b4a5&size=orig) 

 lo mismo de siempre, en este curso pongamos los logos aqui, y usa un two column para no perder esos logos

---
**Source URL**:
[https://4geeksacademy.com/us/coding-bootcamps/applied-ai-course](https://4geeksacademy.com/us/coding-bootcamps/applied-ai-course)

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/71dcec72-a20a-44a7-b33c-338e201aa09d)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2124
