### ISSUE TITLE
Creacion de learnpack para prompt engineering

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7407]
- [ ] Construir curso de learnpack interativo sobre prompt engineering.
- [ ] Realizar artículos sobre el cluster de prompt engineering para apuntarlos al curso.

Las siguientes lecturas son necesarias (adicionalmente a las que salen en 4Geeks.com)

- [x] Prompt engineering for beginners (lo suficiente para ser "decente" sin tener que leer todas las guias que hay por alli). 
- [x] Prompt engineering for developers. No tiene volumen en google pero hay que tenerlo para el curso.
- [ ] Prompt engineering for marketing. No tiene volumen en google pero hay que tenerlo para el curso.

**Comment by Charlytoc** [comment]
- [ ] Usar compilador de Python para curso de AI
- [ ] Usar GROQ API_KEY
