### ISSUE TITLE
Cambiar header de ejercicios

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7409]
- [ ] Debe hablar como secta de nuestros productos (LearnPack, Click and code y rigobot)
- [ ] Debemos agregar estos textos en la pagina:
    - What are you learning today?
    - Each of these tutorials and exercises is interactive, auto-graded, with video solutions.
    - After you open the exercise, our internal AI mentor will read your code along the way and be ready to help you.
- [ ] El search bar d
- [ ] El boton de filter en vez de Filter debe decir Exercise Finder

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15500-87071&t=egjqBcFpM7LvvWMw-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar iconos de LearnPack, click and code, y rigobot abajo del parrafo

**Comment by tommygonzaleza** [comment]
Se va a desarrollar en este [issue](https://github.com/breatheco-de/breatheco-de/issues/7461)
