### ISSUE TITLE
Agregar nuevo diseño del componente `CardAsset`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7411]
Aqui estan las versiones del componente: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15500%3A87071&t=xXu1EMCcX1ZcNGx4-1

**Comment by alesanchezr** [comment]
Corregir altura de las cajas y tamaño de los titulos
https://www.awesomescreenshot.com/image/48885088?key=16a38a8ada4065557ec8d6595843ec00

**Comment by tommygonzaleza** [comment]
- [ ] Los cards estan demasiado grandes y esta desproporcionados con respecto a lo demas de la pagina. Debemos quitar el espacio entre cada fila para que sea un poco mas pequeño, al igual que el width tambien debe ser menor, y todos los cards deben tener el mismo width
![Screenshot 2024-06-24 at 11 50 13 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/c16bed90-4faa-4eb5-b821-37374ed85ff1)

**Comment by ArielCalisaya** [comment]
Corregido!

**Comment by tommygonzaleza** [comment]
Fallo el deployment

**Comment by tommygonzaleza** [comment]
Debemos quitar el espacio que hay entre cada fila para que no quede tan grande en las dimensiones verticales.

**Comment by ArielCalisaya** [comment]
Ya reduci los espacios, los cambios estan en el mismo PR

**Comment by tommygonzaleza** [comment]
- [ ] No es clicable ni tiene boton para ir al landing desde el landing /workshops
![Screenshot 2024-06-26 at 1 47 51 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/c13555c5-fe1d-4712-974c-dddbdcb3d16d)

- [ ] Desde las lessons se sigue viendo el card de los workshops con los espacios grandes de antes
![Screenshot 2024-06-26 at 1 49 09 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/0c925db1-9549-40d7-b014-16635b355a4c)

**Comment by ArielCalisaya** [comment]
ya esta corregido!

**Comment by tommygonzaleza** [comment]
Siguen teniendo un height diferente, vamos a ponerle un min height para que todos sean iguales y la descripcion la cortamos a partir de las 4 lineas y ponemos ... Para que no pueda ser ni mas grande ni mas pequeño que el height puesto

![Screenshot 2024-06-27 at 2 59 01 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/f1b9db23-6072-47c9-8957-ba54aa8efc16)

**Comment by ArielCalisaya** [comment]
Listo,
