### ISSUE TITLE
Cambiar widget de Slack por comunidad de Whatsapp

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7413]
Cuando un estudiante le de click al boton para unirse a slack, deberia abrir hacer un llamado al API de slack para invitarlo.

Aqui esta un chat con ChatGPT donde se describe como hacerlo: https://chatgpt.com/share/a2e6cc01-7216-402f-b53b-fccb2ff948db

El codigo aparece en python, pero se entiende el llamado que debe hacerse, igual puedes usar la documentacion del api de slack

Recuerda utilizar el link del slack de 4geeks.com cuando no sea un usuario de un bootcamp de la academia y usar el de 4geeksacademy para usuarios invitados a una academia diferente a la de id 47 (4geeks.com)

**Comment by gustavomm19** [comment]
GET /academy/slack/team?academy=<slugs comma separated>

**Comment by gustavomm19** [comment]
El metodo de la API que permite invitar usuarios a un workspace es [admin.users.invite](https://api.slack.com/methods/admin.users.invite) pero requieres permisos que son pagos. Sin esos permisos, no se puede invitar a un usuario a un workspace de forma automatizada

**Comment by tommygonzaleza** [comment]
- [ ] Quitar el widget que dice para unirse a slack, pon uno para unirse a la comunidad de whatsapp. Ya tienes los links para unirlos segun el idioma. Aqui tienes los links para unirse: https://github.com/breatheco-de/breatheco-de/issues/7583
- [ ] El diseño debe ser el mismo widget pero con el logo de whatsapp
