### ISSUE TITLE
Landing de Front + FS para campaña de Google

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#7418]
@G-code7 A la landing de front que ya se tiene agregarle el curso de FS, ya que para que en ADS no se solapen ambos cursos se van a promocionar juntos y que las personas escojan.

Esta es la landing de Front a modificar https://4geeksacademy.com/es/landing/front-end-chile.

@jatv93

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2105
