### ISSUE TITLE
Hacer mas visibiles las instrucciones del profesor

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7424]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48456170?key=3401e239af96bfd0fc60b106dcbbbd15&size=orig) 

 - [ ] Mover las instrucciones al sidebar de la izquierda
- [ ] El item de instrucciones ponerlo mas llamativo y que diga "Open Teacher Instructions"
- [ ] Considerar usar un background amarillo para resaltarlas
- [ ] La modal de instrucciones deberia abrir siempre automatica.

---
**Source URL**:
[https://4geeks.com/syllabus/Machine-learning-2/read/python-for-datascience](https://4geeks.com/syllabus/Machine-learning-2/read/python-for-datascience)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15665-80821&t=eAp6LbApLXAvta2d-1
