### ISSUE TITLE
Lesson about JWT & Express and add link from the start.4geeksacademy.com

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7425]
- [x] Create lesson about jwt and express, use as many content as you can [from this lesson about JWT+Flask ](https://4geeks.com/lesson/what-is-JWT-and-how-to-implement-with-Flask).
- [x] Update the [code examples to these ones](https://github.com/4GeeksAcademy/Templates-Boilerplates/blob/c27077fd8831aebdd5d00f9f346a9599a769e41e/docs/express-jwt-authentication.md).
- [x] Publish and translate the lesson.
- [x] Update the [documentation links](https://4geeks.com/docs/start/express-typescript-api-template#authentication-with-jwt) to point to your new article.
- [x] Tell jonathan toledo about this update so he can update the course syllabus with that.

**Comment by arnaldoperez** [comment]
https://breathecode.herokuapp.com/v1/registry/asset/preview/jwt-authentication-for-apis
