### ISSUE TITLE
Rediseño de https://s.4geeks.com/start

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7427]
Esta landing:
https://s.4geeks.com/start?repo=asdasd

Es la landing apge que van a ver los alumnos cuando quieran abrir un projecto usando nuestro On Click Coding technology (provisioning briedge).

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=eAp6LbApLXAvta2d-1

**Comment by alesanchezr** [comment]
Falta la opcion para descargar localmente en tu maquina

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15662-69454&t=PMfhn01whdblrWMP-1

**Comment by tommygonzaleza** [comment]
- [ ] Los iconos no estan del mismo tamaño
- [ ] Disminuir el espacio entre los iconos y el texto en los botones

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15662-69454&t=FACoAByw8qpHgaLK-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7475)
