### ISSUE TITLE
Si no esta sincronizado con rigobot no debes pedir los code reviews

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7428]
No puede recibir code reviews si no esta conectado con rigobot, por lo que no deberias ni siquiera pedirlo, acutalmente da un error cada vez que tratas de leer el feedback de tu profesor si no estas conectado con rigobot

**Comment by ArielCalisaya** [comment]
Corregido!

**Comment by tommygonzaleza** [comment]
- [ ] Ahora la modal para ver el review del profesor en tu assignment se queda cargando infinitamente cuando no esta sincronizado con rigobot
