### ISSUE TITLE
Vamos a crear un projecto para `SQL Alchemy Operations`

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7431]
El modulo 26 se llama ahora database ORM and operations

Titulo: Building Starwars database with SQL Alchemy

- Este projecto va a ir en el modulo 26 para que practiquen usar SQL alchemy y hacer operaciones bases de datos.
- El projecto tendra un `pipenv run test` para validar que el alumno haya impelmentado todas las funciones y operaciones para manipualr las entidades.
- Maquina postgres 
- Vamos a dejarle los modelos creados pero solo con el AI para que ellos rellenen el modelo, asi podemos declarar el admin.py para agregar las entidades al admin.
- Tiene que haber un admin como el de fastapi para que los alumnos puedan ver sus tablas llenas.

**Comment by arnaldoperez** [comment]
-[] Agregar "Feeling confident y colocar ahi el uso de limit o offset"
-[] Simplificar la solution
-[] Realizar pruebas con conexion a SQLite
