### ISSUE TITLE
Articulo: Cuanto gana un Data Scientist en Chile

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#7433]
Redactar un artículo para el web site, ya que es una de las preguntas frecuentes que recibimos, funciona para mandarle el link a los lead, generamos tráfico en nuestro website y adicional contestamos sus dudas. Ya que se vieron resultados positivos con el de "cuanto gana un programador en chile"

@G-code7 

@jatv93

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/blog/pull/134
