### ISSUE TITLE
Rediseño del home

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7435]
Se cambiaron algunos componentes y se cambio el orden de ellos. Detalla tambien cada componente porque algunos se les cambio el borde, background, etc.

Aqui esta el figma: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=11784%3A8766&t=wQxoMURFlLZveWWL-1

**Comment by tommygonzaleza** [comment]
- [ ] No debe tener margin cada card sino busca ponerle un gap entre cada uno y listo, para que los cards lleguen al final del max-width
<img width="957" alt="Screenshot 2024-06-07 at 2 28 40 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/ca2ac7ca-2d5d-4cd3-a0d4-73b79e8d5e40">

**Comment by alesanchezr** [comment]
Estanda
