### ISSUE TITLE
Articulo: Ventajas competitivas en el mercado que te da conocer herramientas de inteligencia artificial

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#7436]
Artículo para promover el curso de inteligencia artificial para profesionales, donde se especifique las diversas herramientas y se haga énfasis en que en el curso abran herramientas personalizadas según la profesión y colocar un estimado del % el cual puede incrementar la remuneración salarial, la optimización del tiempo, entre otros beneficios que tendrían las personas a nivel profesional al tomar el curso. Todo orientado a chile por fa.

@G-code7 
@jatv93

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/blog/pull/133/files
