### ISSUE TITLE
Cambiar icono de LearnPack en todos los lugares donde se usan

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7438]
Se debe cambiar en los tutoriales interactivos (Tanto internamente como externamente). Aprovecha de cambiar tambien el icono de click and code (Antes llamado provisioning bridge)

Aqui esta el figma: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=13399-43033&t=OtnShP68sNlQgqKP-1

**Comment by ArielCalisaya** [comment]
A pesar de que me lleva a una sección de diseños, no logro encontrar ningún icono ni con la palabra clave "learnpack"

![2024-05-31 at 16 19 02@2x](https://github.com/breatheco-de/breatheco-de/assets/51676628/ca616917-b98a-4321-bfe3-55eabeac772d)

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-06-04 at 1 54 47 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/06b7fc9e-2a98-460d-967a-440c701d4253)

**Comment by ArielCalisaya** [comment]
corregido!
