### ISSUE TITLE
Error en landing /bootcamp-applied-ia-for-professionals-santiago

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7439]
La imagen deberia tener borde negro con shodow y esta mal espaciada, muy arriba.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48517221?key=02c64384677d3ca2161a2942b8b0adee&size=orig) 

---
**Source URL**:
[https://website-v2-q63ps24t1-geeksacademy.vercel.app/es/landing/bootcamp-applied-ia-for-professionals-santiago](https://website-v2-q63ps24t1-geeksacademy.vercel.app/es/landing/bootcamp-applied-ia-for-professionals-santiago)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2114
