### ISSUE TITLE
Dado que solo tenemos linkedin en los success cases, no se peude hacer mejor usao del espacio?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7441]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48518953?key=9cc61ec18fbc5cf9eb52151ccda3536c&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/index](https://4geeksacademy.com/us/index)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=11527-7719&t=mzFTi7AZ7nmRpR7F-1
