### ISSUE TITLE
Picar la lesson de jwt en tres

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7445]
- Una version en general que en la tabla de contenidos
- Una lesson para jwt flask
- Una lesson para jwt en python

**Comment by arnaldoperez** [comment]
La lesson [token auth API](https://4geeks.com/es/lesson/token-based-api-authentication-es) debe tener un apartado de JWT

Las lessons de Flask y Express deben tener una intruducción con referencia al articulo token auth API y enfocarse mas en la implementacion
