### ISSUE TITLE
Add warning if lesson has superseder

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7449]
La respuesta del API ahora viene con una propiedad `superseded_by` que si esta != null entonces contiene una lesson que representa la nueva version de la lesson actual.

```
    "superseded_by": {
        "id": 554,
        "slug": "bootstrap-tutorial-learn-bootstrap-5-in-10-minutes",
        "title": "Bootstrap Tutorial: Learn Bootstrap 5 in 10 minutes"
    },
```

Intentar usar el componente [AlertMessage](https://breatheco-de.github.io/app/?path=/story/components-alertmessage--default&globals=locale:en).

En el markdown de las lessons no estaticas (solamente estando logeado), cuando haya un superseder, vamos a agregar un warning dentro del texto que diga `This lesson belongs to the legacy archive, we recommend reading a more updated version: <superseded lesson title>`

**Comment by tommygonzaleza** [comment]
Esta mostrando la alerta siempre aunque no tenga superseder

**Comment by ArielCalisaya** [comment]
corregido!

**Comment by alesanchezr** [comment]
Poner la alerta mas abajo y con bordes curvos, ponerla dentro del contenido al principio.
