### ISSUE TITLE
Esta fallando el receivers del hook de `new_subscription_created`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7451]
Le agregamos un try except para evitar que rompiera el proceso de crear la subscripcion. Pero debe resolverse ya que no se esta enviando el hook ahora

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1396

**Comment by jefer94** [comment]
Vamos a usar este PR para determinar todos los hooks que están fallando

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1403
