### ISSUE TITLE
Preguntas a definir sobre los cupones

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7452]
- Si yo aplico un cupon, cuando se me renueve el plan se mantiene el cupon? Idealmente ambas opciones deberian poderse, dependieno del cupon, pero si no es asi entonces que por lo menos se aplique siempre de ahora en adelante.
- Si un plan tiene un cupon auto-aplicado, y yo traigo mi propio cupon, el mio sobreescribe el auto-aplicado, solo se peude un cupon a la vez.

**Comment by jefer94** [comment]
1. No fue hecho por diseño para poder aplicar en cada cargo, necesitaría una propiedad nueva para ser tomado en cuenta en todos los tasks relacionados a `make_charges`

2. 1. Los cupones automáticos que se usan para las ofertas especiales, se suelen considerar responsabilidad del equipo de marketing, por lo que, se debería ver en un dashboard los cupones que aplica a un plan y su precio, los cupones que el usuario trae están fijados en máximo uno, por lo cual, podría tener N descuentos de marketing + 1

2. 2. Tener varios cupones permanentes podría no ser conveniente, ahora, según a la experiencia de usuario actual, si yo veo un descuento y decidiera introducir un cupón, sería raro perder el descuento previamente ofrecido, por lo que, de desearse prevenir esto, el front-end debería ocultar el input de cupones y el back-end no aceptar recibir cupones del usuario, si hay algún cupón global permanente

Todo lo demás queda sujeto a consideraciones
