### ISSUE TITLE
Landing de Hire alumni

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7453]
Estos son los campos que se deben mostrar:

- [ ] Por que contratar al alumno
- [ ] Background 
- [ ] Github o LinkedIn
- [ ] Skills
- [ ] Especialidad (Full Stack, Data science o Ciber security)

**Comment by tommygonzaleza** [comment]
- [ ] Quitar el pais en la modal del perfil del estudiante
- [ ] En who is hiring our talent cambiar el grid de las cards para que sean del mismo tamaño

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=12330-7782&t=SrhaUWy1OBaVbUfa-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar aqui: https://github.com/breatheco-de/breatheco-de/issues/7477
