### ISSUE TITLE
Mostrar coupon autoaplicado en pricing y landing del bootcamp

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7454]
- [ ] Se debe mostrar a la derecha del precio un precio (Que es el original antes de aplicar el coupon) tachado y mas pequeño
- [ ] Se debe mostrar como una etiqueta o algo que muestre el coupon aplicado, debe ser llamativo
- [ ] Agrega una cuenta regresiva para mostrar cuanto falta para que se expire el coupon. Si falta menos de un dia, se debe mostrar los segundos, sino no. Agrega ambas versiones al diseño

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12466-62638&t=FACoAByw8qpHgaLK-1

**Comment by tommygonzaleza** [comment]
- [ ] En el landing del bootcamp falta agregar la etiqueta de descuento en el componente de precios. Recuerda mostrarlo con urgencia de que puede acabarse y tienen que aprovecharlo

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-51392&t=y9SHKTeTnNO73UZN-1

**Comment by tommygonzaleza** [comment]
- [ ] Se debe mostrar para todas las opciones de pago, el coupon es para el curso en todos sus planes de pago

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-51392&t=OkPJqyPEAR2wI7mz-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7455)
