### ISSUE TITLE
It is letting me register for an event not free for bootcamp user

### ISSUE THREAD

**Issue by Chapderlane** [breatheco-de/breatheco-de#7467]
### Bug description

It allowed me to register for an event that wasn't free for everyone and is not free for a bootcamp user.

This is the user. https://breathecode-test.herokuapp.com/admin/auth/user/8242/change/?_changelist_filters=q%3Dchap

This is the event. https://breathecode-test.herokuapp.com/admin/events/event/821/change/

![june14event](https://github.com/breatheco-de/breatheco-de/assets/154477996/65edbb06-f500-40e5-932d-20c72111962b)

### Steps to reproduce

I created a user that I signed up for a free trial on the full stck bootcamp. I edited the event and made it not free for everyone and also not free for bootcamp users. I was able to go to the event from the live event page and join the event.

### Expected behavior

It should check if the user has consumables, if the user doesn't have valid consumables to access that event, then it should ask him to buy more or renew plan

**Comment by tommygonzaleza** [comment]
You have enough consumables to access that workshops, that's why it allowed you
