### ISSUE TITLE
It is letting me register for a free for bootcamps event as a user that isn't in a bootcamp

### ISSUE THREAD

**Issue by Chapderlane** [breatheco-de/breatheco-de#7468]
### Bug description

I was able to register for an event that was free for bootcamp users but not free for all with a non bootcamp user.

This is the user. https://breathecode-test.herokuapp.com/admin/auth/user/8243/change/?_changelist_filters=q%3Dchap

This is the event. https://breathecode-test.herokuapp.com/admin/events/event/820/change/

![june15event](https://github.com/breatheco-de/breatheco-de/assets/154477996/7b4e2c72-eb3d-4065-9cfd-c3b02b2cc09c)

### Steps to reproduce

I created a free user. Then I went to the live events and selected the June 15 event which is free for bootcamps but not all users. I was able to register for the event.

### Expected behavior

It should check if the user has consumables, if the user doesn't have valid consumables to access that event, then it should ask him to buy more or renew plan

**Comment by tommygonzaleza** [comment]
That user has consumables, that's why it allowed him to join the workshop
