### ISSUE TITLE
It isn't allowing the user to get more consumables for mentorships

### ISSUE THREAD

**Issue by WinstonLesuT** [breatheco-de/breatheco-de#7473]
### Bug description

A user without consumables is not permitted to join mentorships. And attempts to acquire more consumables result in redirection to a page that is not loading.
This is my subscription: https://breathecode-test.herokuapp.com/admin/payments/subscription/1211/change/

https://github.com/breatheco-de/breatheco-de/assets/138252771/5f540409-38f0-4c54-b156-084f9e8be901

### Steps to reproduce

- Create a new user with an active subscription.
- Go to schedule a mentorship session without consumables.
- Click on get more mentorships.
- Click on purchase one or more sessions.
- Click on the button **Take me there**

### Expected behavior

It should expect a new page that allow the user to get more information about the consumables and how to refill it.

**Comment by AltaciosTheDev** [comment]
@tommygonzaleza Is this related to the same issue that was resolved today?

**Comment by AltaciosTheDev** [comment]
Confirmed.

Instead of taking to page to get more consumables, it redirects prod environment and to create an account and buy a plan with feedback.

**Comment by tommygonzaleza** [comment]
<img width="1085" alt="Screenshot 2024-07-11 at 5 12 25 PM" src="https://github.com/breatheco-de/breatheco-de/assets/56565994/6a9f58de-f9f0-4bc0-8018-e89ae83eff1a">
