### ISSUE TITLE
Queremos mostrar cuando ya tienes una mentoria en vivo.

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7478]
Nosotros podemos saber cuando una mentoria esta en curso, podemos saber el tipo de mentoria, el mentor, la hora de inicio y la hora en la que se deberia culminar.

**Comment by tommygonzaleza** [comment]
- [ ] Agrega la version en el diseño nuevo del dashboard.
- [ ] Debe tener un boton para unirse
- [ ] Debe estar con la animacion de que esta en vivo

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=16033-162407&t=y9SHKTeTnNO73UZN-1
