### ISSUE TITLE
Error al comenzar práctica de API "Learn hot to build HTTP request with python"

### ISSUE THREAD

**Issue by lbdelilla** [breatheco-de/breatheco-de#7481]
### Bug description

En la practica del Módulo de API request "Learn hot to build HTTP request with python" al darle "Start Excercise" abre una nueva pestaña con "Server Error 500" Tanto en la versión en inglés como la de castellano. 
![image (10)](https://github.com/breatheco-de/breatheco-de/assets/112482614/1e1568b7-c95c-438d-a21f-5a31ca76f90f)

### Steps to reproduce

1. Entra en el dashboard a una cohorte de DS 
2. Ir al módulo de API requests 
3. Abrir práctica  "Learn hot to build HTTP request with python"
4. Darle al botón "start new excercise"

**Comment by AltaciosTheDev** [comment]
Al no tener acceso a una cohort procedi con ingresar desde 4geeks.com y buscando la practica como ejercicio.
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/1e447934-8455-4433-bf8f-e08a70649b53)

Open with learnpack
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/6dfd7044-43da-4901-8e1e-f6932b5b3783)

Github Codespaces 
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/d60239f3-236c-4bf8-9a9e-bdd664d8bf7a)

Codespace abre con exito 
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/18b8dd52-f2de-4110-badf-c92c85eb3ae6)

Desconozco si posiblemente dentro de una cohort genera un error que no se genera al abrirlo como ejercicio dentro de la learning library.

**Comment by tommygonzaleza** [comment]
Ya ha sido arreglado
