### ISSUE TITLE
Si se encuentran provisioning consumptioun errors o warnings esos errores deben aparecer en el status messge del provisioning bill tambien para recordarle a uino que hay que ir a ver que paso

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7483]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48755403?key=066707876254e73ad80c603162aa2cb6&size=orig) 

---
**Source URL**:
[https://breathecode.herokuapp.com/admin/provisioning/provisioninguserconsumption/?status__exact=ERROR](https://breathecode.herokuapp.com/admin/provisioning/provisioninguserconsumption/?status__exact=ERROR)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1392

**Comment by jefer94** [comment]
https://github.com/breatheco-de/breatheco-de/issues/7484
