### ISSUE TITLE
Cambios al FAQ

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7485]
- [ ] Agregar `location: ["all"]` donde haga falta.
- [ ] Pica respuesta de `How do I pay for my tuition?` para cada pais.
- [ ] ¿Por qué nuestros campus?
El panorama laboral y tecnológico es diferente por país, las empresas que contratan son muy diferentes y las practicas de contratación también lo son. 4Geeks tiene un equipo local en cada una de sus sedes físicas para desarrollar alianzas con los actores locales. Te aconsejamos estudiar en la sede el país donde quieres desarrollarte como profesional y conseguir trabajo.

- [ ] Separar las preguntas de europa de las de españa: España tiene acuerdos locales de pago con empresas especificas

Las siguientes preguntas deben tener muchas referencias locales: Nombre del pais, ciudades, empresas, etc. Tambien apuntar a articulos del blog que elaboren mas en la respuesta.

- [ ] ¿Cuales son las empresas que mas contratan en <Pais>?
- [ ] ¿Cómo esta el mercado el mercado laboral en <Pais>?
- [ ] ¿Que hace a <Pais> un lugar atractivo para trabajar?
- [ ] ¿Cuanto gana un desarrollador en <Pais>?

**Comment by G-code7** [comment]
- [ ]  Agregar location: ["all"] donde haga falta.

- [ ]  Pica respuesta de How do I pay for my tuition? para cada pais.

- [ ]  ¿Por qué nuestros campus?
- [ ] El panorama laboral y tecnológico es diferente por país, las empresas que contratan son muy diferentes y las practicas de contratación también lo son. 4Geeks tiene un equipo local en cada una de sus sedes físicas para desarrollar alianzas con los actores locales. Te aconsejamos estudiar en la sede el país donde quieres desarrollarte como profesional y conseguir trabajo.

- [ ]  Separar las preguntas de europa de las de españa: España tiene acuerdos locales de pago con empresas especificas

- [ ] Las siguientes preguntas deben tener muchas referencias locales: Nombre del pais, ciudades, empresas, etc. Tambien apuntar a articulos del blog que elaboren mas en la respuesta.

- [ ]  ¿Cuales son las empresas que mas contratan en ?
- [ ]  ¿Cómo esta el mercado el mercado laboral en ?
- [ ]  ¿Que hace a un lugar atractivo para trabajar?
- [ ]  ¿Cuanto gana un desarrollador en ?

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2120/files

**Comment by alesanchezr** [comment]
Todos los links agregados estan malos porque:

- No usan las palabras clave, usas palabras como "click aqui" que no sirven, tienes que usar las palabras clave que queremos posicionar en el articulo al que estas apuntando.
- Son incoherentes: Si la pregunta es sobre "que diferencia las sedes de 4geeks" no puedes poner un link acosejando a la gente a leer sobre convertirse en programador.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2120
