### ISSUE TITLE
Revisar website de 4geeks bugs

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7490]

**Comment by ali5uarez5** [comment]
El icono de job guarantee está tapando el H1
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/4a8693a0-8054-42fe-97f5-899294e4da4c)
----

El color de bg debe ser F4F9FF
----
Hay que volver a revisar los textos, hay tamaños diferentes y algunos titulos en negro y otros en 3A3A3A. 
Los titulos deberian estar en: 2E2E38
El body en: 3A3A3A
----
Espacio entre las secciones: debe ser igual entre todas, tomar como referencia le diseño: 80 px
Cada sección tiene un padding top y bottom de 40 px. 
Espacio interno de las secciones: debe ser igual en todas las secciones, como referencia en el diseño: todos los cards tienen un margin top y bottom de 32 px.

![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/53c3192a-ea57-45ed-a31e-48c6e4ffa5fd)
----

Ocultar border

![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/a1a643d3-0ebe-4d02-9bbc-ae08a2777bd6)
----

Espacio entre las cards: todas las cards están separadas 24 px arriba abajo y entre ellas

![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/e0747133-f3c8-4aac-bf1e-fecfe105ac4a)
----

Se debe usar el mismo elemento que en el diseño, aqui el arrow no es igual, el punto que hace referencia al lugar en el que estás debe ser azul: 0084FF
Cuando estás en la primera página el arrow para ir a la izquierda está inhabilitado. 
El arrow no es redondeado. 
![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/9a0df8a2-b449-4f7f-8179-e84fbab9b27a)

![image](https://github.com/breatheco-de/breatheco-de/assets/105449728/9285454b-4e63-446a-acc9-6eb2f844a8e1)

----
