### ISSUE TITLE
Se estan generando previews con el texto negro que no se lee

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7491]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48800280?key=c68706ae4eaa3680880964cb3dffcdd6&size=orig) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset/intro-a-seguridad-de-linux](https://admin.4geeks.com/media/asset/intro-a-seguridad-de-linux)

**Comment by tommygonzaleza** [comment]
Eso no soluciona el problema, hay que saber que fondo utilizar con el font negro y cual usar con el font blanco
