### ISSUE TITLE
Iconos y background para comunidad de 4Geeks de whatsapp

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7492]
La comunidad es para los workshops de 4Geeks, esta es la descripcion:
```
Join this exclusive WhatsApp group to receive real-time updates, workshop announcements, and resources directly related to our [Full-Stack/Data Science/Cybersecurity] workshops. This is your space to connect with fellow learners, ask questions, share insights, and enhance your learning experience with 4Geeks.
```

Necesitamos iconos y background [como este](https://wallpapercave.com/wp/wp4892377.jpg):

- [ ] un icono para toda la comunidad
- [ ] un icono y un background para el grupo de workshops de full-stack
- [ ] un icono y un background para el grupo de workshops de datascience
- [ ] un icono y un background para el grupo de workshops de ciberseguridad
- [ ] un icono y un background para el grupo de workshops de anuncios
- [ ] un icono y un background para el grupo de workshops de preguntas y respuestas

![IMG_6722](https://github.com/breatheco-de/breatheco-de/assets/426452/313a5697-f6eb-45b9-a95f-ea5c0ff5ab91)
![IMG_6721](https://github.com/breatheco-de/breatheco-de/assets/426452/c1518a1c-d81b-463c-932e-f4cefd51ed41)

**Comment by ali5uarez5** [comment]
[logos grupos.zip](https://github.com/user-attachments/files/16132612/logos.grupos.zip)
