### ISSUE TITLE
Supplementary materials should be in the same language as the asset

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7493]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48803702?key=31942328c718f3e96e342abb0d473979&size=orig) 

 In this case the asset is in English (us) and the supplementary materials are in spanish.

---
**Source URL**:
[https://4geeks.com/interactive-coding-tutorial/build-your-resume-html-css](https://4geeks.com/interactive-coding-tutorial/build-your-resume-html-css)

**Comment by ArielCalisaya** [comment]
El endpoint no esta entregando `related_assets` por el idioma del asset correspondiente

![bug-related_assets](https://github.com/breatheco-de/breatheco-de/assets/51676628/68a0fb69-3de4-42b5-8ed7-15e90cf560ad)
