### ISSUE TITLE
Bullets estan demasiazdo grandes porque se uso el cam[p de titulo en lugar de el parrafo

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7500]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48884103?key=bb4119b3e03ab6876b3cea2f2a753e82&size=orig) 

---
**Source URL**:
[https://website-v2-hoab0leza-geeksacademy.vercel.app/es/landing/bootcamp-applied-ia-for-professionals-santiago](https://website-v2-hoab0leza-geeksacademy.vercel.app/es/landing/bootcamp-applied-ia-for-professionals-santiago)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2121

**Comment by G-code7** [comment]
![Image](https://github.com/breatheco-de/breatheco-de/assets/95352419/7efb4857-8b11-441f-b234-23ded4da088f)

**Comment by alesanchezr** [comment]
Lo hiciste modificando el html

**Comment by G-code7** [comment]
![Image](https://github.com/user-attachments/assets/568d50bd-6d6b-4794-b01e-cc8c37bafe46)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2129
