### ISSUE TITLE
No se esta enviando el feedback del alumno sobre los core reviews, el network esta vacio

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7502]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/48884988?key=ac558d80f938149d52212d501b07efa0&size=orig) 

---
**Source URL**:
[https://4geeks.com/choose-program](https://4geeks.com/choose-program)

**Comment by gustavomm19** [comment]
![image](https://github.com/user-attachments/assets/75606278-fb04-4e55-ad9d-57d0cabde695)
Después de revisar, parece que si se esta enviando el feedback del alumno
