### ISSUE TITLE
Plantear una interfaz/diseño para el prompt builder

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7508]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/28858025?key=a24b54881445039712e116992da84bb4&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/28858025?key=a24b54881445039712e116992da84bb4 

 https://chat.4geeks.com/prompt-builder

**Comment by tommygonzaleza** [comment]
- [ ] Inspirate de la pagina de grammarly

**Comment by tommygonzaleza** [comment]
- [ ] Agregar el icono de copy en el prompt recomendado
- [ ] Agregar boton de revisar el prompt en la primera pantalla

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15964-90875&t=iFsaUFHw4fpb9D2m-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7577)
