### ISSUE TITLE
Error en Prework practica Learn CSS Interactive

### ISSUE THREAD

**Issue by deimianvasquez** [breatheco-de/breatheco-de#7509]
### Bug description

Al entrar en el Prework en la practica de css el learnpack no se abre automáticamente. Si lo corremos manualmente al pasar a la siguiente lección no abre la pestaña para realizar el código. 

### Steps to reproduce

1.- Iniciar sesión en 4geeks.com
2.- Abrir la corte del prework
3.- Entrar a la lección de módulo uno de css (Learn CSS) 
4.- Crear un espacio nuevo en codespace para la practica 
5.- Correr learnpack en la terminal
6.- Intentar hacer las practicas y se ve el inconveniente 

### Expected behavior

Se debe poder ejecutar los test, ver la pantalla donde se escribe el código y al darle a la flecha de siguiente ejercicio de actualice a la izquierda el html del code nuevo 

### Anything else?

[Screencast from 21-06-24 14:47:34.webm](https://github.com/breatheco-de/breatheco-de/assets/45182016/1d4f1562-2f4e-438b-982d-ca4b47d73c42)

**Comment by Charlytoc** [comment]
Arreglado, se actualizó el archivo .devcontainer.json
https://github.com/4GeeksAcademy/css-tutorial-exercises-course/commit/fa97e6a0f70f7451a25411217c066dac4a00344c
https://github.com/4GeeksAcademy/css-tutorial-exercises-course/commit/ca7282383b17831c3cfce943548087cb3cc2bfe7
