### ISSUE TITLE
Upcoming + current workshops not being shown on user's dashboard

### ISSUE THREAD

**Issue by KonnorThatcher** [breatheco-de/breatheco-de#7516]
### Bug description

The workshop widget on the user's dashboard doesn't display any of the live or upcoming workshops, regardless of what events the user has or doesn't have access to. The user would have to go to the [workshops page](https://dev.4geeks.com/workshops) in order to see the events.

Here's a screenshot of the available events on the workshops page:
![Opera Snapshot_2024-06-24_135358_dev 4geeks com](https://github.com/breatheco-de/breatheco-de/assets/131403452/8e60de22-97de-4584-98aa-e70517c3ba77)

Here's what the user's dashboard looks like:
![Opera Snapshot_2024-06-24_135042_dev 4geeks com](https://github.com/breatheco-de/breatheco-de/assets/131403452/c85af6a7-857c-4358-976b-7f494cff0105)

### Steps to reproduce

- Created a user with any plan
- Went to https://breathecode-test.herokuapp.com/admin/events/event/ and changed the 'Starting at' and 'Ending at' dates and times of some of the events in order to have current/upcoming workshops

### Expected behavior

The user should see any of the live or upcoming workshops that they have access to on their dashboard, as shown here:
![Opera Snapshot_2024-06-24_142149_4geeks com](https://github.com/breatheco-de/breatheco-de/assets/131403452/9ac6a4ec-277e-4d6f-80c7-d53c5a8da6b5)

**Comment by jefer94** [comment]
Actually, this is a frontend issue because they forgot to use the pagination, I could add a new querystring param to reduce the response size

**Comment by jefer94** [comment]
Added support to `?upcoming=true` https://github.com/breatheco-de/apiv2/pull/1421
