### ISSUE TITLE
Landing Asíncrono chile

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#7517]
Una landing para vender el curso de Full Stack de forma Asincrona, donde toda la información con referente al curso como tal se encuentra en el siguiente doc.[https://docs.google.com/document/d/1bSJW1QTF8rvYGGI4pavgf4f9BOaGeKvmoJm4Pq8ADhY/edit?usp=sharing](url)

El componente de duración se modificaría dejando.

@jatv93

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2127
