### ISSUE TITLE
teacher assistant grading 

### ISSUE THREAD

**Issue by Suri1336** [breatheco-de/breatheco-de#7519]
### Bug description

when you click on the command line project to grade it stops showing the links to all of submitted  projects 

https://github.com/breatheco-de/breatheco-de/assets/146222294/93c1b09f-c25c-4446-8132-328a4f900fea

### Steps to reproduce

open the command line challenge project

### Expected behavior

all project links should still appear

**Comment by tommygonzaleza** [comment]
- [ ] Se esta mostrando el link del proyecto entregado aunque no tenga. Por ejemplo, el command line no tiene entregable pero se muestra el link, y lo que hace es refrescar la vista. No deberia mostrarse si no tiene
