### ISSUE TITLE
BUg al intentar entrar en una mentoria

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7525]
![Screenshot 2024-06-26 at 10 34 28 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/6e6406cf-5ee4-4f7c-95b1-ec6c51145db7)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1412

**Comment by jefer94** [comment]
This issue is related to google meet sessions

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1413

**Comment by jefer94** [comment]
We'll wait for the new scopes approbation in the OAuth App, right now we must revert to daily in all mentorship services using the action `use_daily`
https://github.com/breatheco-de/apiv2/pull/1414
