### ISSUE TITLE
No se estan generando los consumibles para service items sin tipo de servicio

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7527]
Por otro lado, se estan generando los consumibles dos veces

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1420

**Comment by tommygonzaleza** [comment]
- [ ] No esta mostrando lo erroes
- [ ] El logo de 4geeks esta roto

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1426

**Comment by tommygonzaleza** [comment]
- [ ] Si no hay hash, cobralo porque no puedes validar que sea repetido

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1430
