### ISSUE TITLE
Los recommended courses no toman el 100% del espacio

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7532]
- [ ] Esto pasa en lessons, how tos y ejercicios

![Screenshot 2024-06-27 at 3 05 30 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/dd483e07-bb38-48d8-8e1f-c8778655ae27)

- [ ] Ademas el width de los botones deben tomar el 100%:

![Screenshot 2024-06-28 at 9 51 02 AM](https://github.com/breatheco-de/breatheco-de/assets/56565994/99acfd0d-9dab-48a4-a34b-e189494bec65)

**Comment by Cristian2499** [comment]
working good 

![image](https://github.com/user-attachments/assets/191404ef-bdc0-4c53-8ba0-279c3968bef3)
