### ISSUE TITLE
Ambos botones deben estar uppercase para abrir learnpack

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7537]
![Screenshot 2024-06-27 at 3 34 52 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/822d5bc0-4bfd-4689-8e01-a692abe8b250)

**Comment by MadamSagas** [comment]
The buttons that open Learnpack are not in uppercase
Here's a screen record video of the bug 
![Image](https://github.com/user-attachments/assets/5825dc5e-0545-439e-afed-9295fa22e61e)

**Comment by tommygonzaleza** [comment]
https://github.com/breatheco-de/app/pull/1588

**Comment by MadamSagas** [comment]
The buttons that open Learnpack are not in uppercase
Ambos botones deben estar uppercase para abrir learnpack

**Comment by tommygonzaleza** [comment]
- [ ] You should include your changes for each issue in a different PR (Pull Request)

**Comment by JennGuz** [comment]
https://github.com/breatheco-de/app/pull/1588/commits/ee67a6ba361d5ca3b369a477a9a0407b1dc6c8fd
Already merged in this commit

**Comment by MadamSagas** [comment]
Ambos botones están en uppercase para abrir learnpack
both button that open Learnpack are in uppercase
