### ISSUE TITLE
Error al intentar entregar proyecto de network troubleshooting package tracer

### ISSUE THREAD

**Issue by deimianvasquez** [breatheco-de/breatheco-de#7542]
### Bug description

En la sección del para entregar el proyecto llamado "Solucionando problemas de red en Packet Tracer" se pide entregar un archivo pk, sin embargo sale la opción de entregar un link

### Steps to reproduce

1.- Entrar en el la corte de Cyber Security
2.- Entrar en el módulo network conectivity
3.- ir a la entrega del proyecto
4.- entregar el archivo .pk

### Expected behavior

![imagen](https://github.com/breatheco-de/breatheco-de/assets/45182016/e0321380-862e-43dd-9517-7ed154286cf2)

**Comment by tommygonzaleza** [comment]
Ya esta resuelto
