### ISSUE TITLE
Error al instalar LearnPack en windows local

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7547]
![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/a7c20724-6e3b-400f-b95b-126dde9fbcff)

![image](https://github.com/breatheco-de/breatheco-de/assets/56565994/66f4d486-9f73-48c9-8de8-a830ec549fde)

**Comment by Charlytoc** [comment]
Esas instrucciones están mal, por eso no encuentra el repo, se está instalando la versión incorrecta de LearnPack.

Lo correcto es:
```bash
npm i -g @learnpack/learnpack
```
y 
```bash
learnpack plugins:install @learnpack/html
```
