### ISSUE TITLE
It's not redirecting to where I was when logging in through the navbar

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7550]
```
## Tests:

- [ ] When located in a workshop's landing and logging in through the navbar, it should redirect you to the workshops landing after login.
- [ ] When located in an exercise's landing and logging in through the navbar, it should redirect you to the exercise after login.
- [ ] When located in a project's landing and logging in through the navbar, it should redirect you to the project after login.
```

**Comment by veljzs** [comment]
## Tests:

- [x] When located in a workshop's landing and logging in through the navbar, it should redirect you to the workshops landing after login.
- [x] When located in an exercise's landing and logging in through the navbar, it should redirect you to the exercise after login.
- [x] When located in a project's landing and logging in through the navbar, it should redirect you to the project after login.

**Comment by KonnorThatcher** [comment]
## Tests:

- [ ] When located in a workshop's landing and logging in through the navbar, it should redirect you to the workshops landing after login.
- [ ] When located in an exercise's landing and logging in through the navbar, it should redirect you to the exercise after login.
- [ ] When located in a project's landing and logging in through the navbar, it should redirect you to the project after login.

On the mobile site with phone dimensions, where the login button is located inside a collapsible menu, logging in does not redirect the user back to where they were.


https://github.com/user-attachments/assets/bf08e86f-e97b-48f9-a64e-7823095e0bf8
