### ISSUE TITLE
Validar ejercicio de IPTAbles

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7553]
Sigue los pasos y completa el ejercicio a ver si esta bueno

https://github.com/4GeeksAcademy/iptables-blocking-practice/tree/master

**Comment by rosinni** [comment]
Despues de corregir el archivo cron de la maquina virtual debian para que haga el git pull y se baje la ultima version del repositorio de los scripts, podemos decir que **funciona** tal cual como lo plantea el paso a paso. Dejo link del archivo .ova con las correciones hechas para que lo suban a la nube de 4geeks. Link: [maquina debian corregida](https://mega.nz/file/77Q2CTaA#yx_uGqYvXkYe768NjqMlK-7PiFeCrRyOpOE8qtsq_WA)
