### ISSUE TITLE
Agregar seccion de unete a la comunidad de whatsapp

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7556]
Queremos agregar un widget nuevo que sea para agregarse a la comunidad.

- [ ] Este widget deberia tener la opcion de entrar a la comunidad en slack y whatsapp (Incluye logos)
- [ ] Debe tener una breve descripcion en la que le decimos los beneficios de estar en la comunidad como promociones especiales, enterarse de primeros sobre nuevos features y productos, etc.
- [ ] La idea es agregar este widget abajo del ShowOnSignUp en el landing de workshops, ejercicio interactivos, dashboard, etc.

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-51392&t=T2ziLxK2dlbFOk02-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar en el landing del workshop

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7240-34693&t=OkPJqyPEAR2wI7mz-1

**Comment by tommygonzaleza** [comment]
- [ ] Debemos agregarlo adentro del showonsignup, abajo del boton de unirse al workshop.

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6565-25094&t=YBoSkTQomgKMvgvD-1

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7583)
