### ISSUE TITLE
The user can't schedule mentorships even the user has consumables.

### ISSUE THREAD

**Issue by WinstonLesuT** [breatheco-de/breatheco-de#7557]
### Bug description

The subscription of the user: https://breathecode-test.herokuapp.com/admin/payments/subscription/1296/change/
These are the consumables the user has:  https://breathecode-test.herokuapp.com/admin/payments/consumable/4714/change/

The user has 3 consumables for mentorships, but the user can't schedule one.

https://github.com/breatheco-de/breatheco-de/assets/138252771/9a84199e-0641-409f-934e-b837e11c4d9e

### Steps to reproduce

- Get started with a new user
- Get the Basic Free plan

**Comment by tommygonzaleza** [comment]
The problem is that the mentoring session included for your cohort is not part of the plan
