### ISSUE TITLE
Can only choose $500 x 1-month payment plan when upgrading from the free trial

### ISSUE THREAD

**Issue by KonnorThatcher** [breatheco-de/breatheco-de#7559]
### Bug description

When the user has a free trial and tries to upgrade to a paid plan, the user is immediately sent to the checkout screen where they are locked in to the 1 month payment of $500, unable to choose from some of the other payment plans like $180 x 3-months or the $110 x 5-months.

![Opera Snapshot_2024-07-01_172733_dev 4geeks com](https://github.com/breatheco-de/breatheco-de/assets/131403452/4e75c13c-d094-476e-8cb9-89403c75923c)

### Steps to reproduce

I created a user with the free trial plan and then tried to upgrade to a paid plan.

### Expected behavior

The user should be able to choose from any of the available payment plans when upgrading from a free trial.

**Comment by AltaciosTheDev** [comment]
Confirmed.

**Comment by tommygonzaleza** [comment]
@ali5uarez5 Let's add an option from checkout to change the If financed or not

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=14751-53746&t=sI55kaB46faESjot-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7852
