### ISSUE TITLE
No available workshop showing even though I have enough consumables

### ISSUE THREAD

**Issue by AltaciosTheDev** [breatheco-de/breatheco-de#7561]
### Bug description

I created a new user through the $500 plan and even though i should have unlimited workshop consumables and i modified an events end date, the screen is still not showing any live events for me to register.

![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/3ee23d39-3f1d-43b5-b2da-5a80b96e7f48)

![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/a4d8dbcd-b98c-48c5-a30f-1145f061b3e2)
![image](https://github.com/breatheco-de/breatheco-de/assets/133562096/5aeb6c94-4f1c-4780-9130-4244e2bfa356)

### Steps to reproduce

1) go to https://dev.4geeks.com/pricing?course=full-stack-development
2)choose the "get plan" option for $500 
3)create user and input card information 
4)modify an event to end a day after the creation of the account 

### Expected behavior

Live event should appear in home dashboard yet not a single one is appearing.

**Comment by tommygonzaleza** [comment]
Mismo issue que este: https://github.com/breatheco-de/breatheco-de/issues/7516
