### ISSUE TITLE
No se esta mostrando la seccion de read next

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7565]
![Screenshot 2024-07-02 at 12 21 59 PM](https://github.com/breatheco-de/breatheco-de/assets/56565994/3a49bc66-3dc3-42c4-b3e8-f5da1fba258f)

**Comment by gustavomm19** [comment]
Parece que ya se esta mostrando
![image](https://github.com/user-attachments/assets/55501f26-aaf7-4cdf-aa18-34017f61371e)
