### ISSUE TITLE
Me aparecen más mentorías que las que debo tener

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/breatheco-de#7572]
### Bug description

Me aparecen más mentorías que las que debo tener

![image](https://github.com/breatheco-de/breatheco-de/assets/48845580/eb15d01c-1885-4dcb-9611-e93c0488bde5)

Solo debe aparecer las mentorías de los cursos en los que estoy inscrita 

### Steps to reproduce

Panel de mentoría previo a escoger un curso en específico

**Comment by AltaciosTheDev** [comment]
Podrias compartir en que curso te inscribiste para repetir la situacion

**Comment by jatv93** [comment]
En los de Chile nada más

**Comment by tommygonzaleza** [comment]
Es porque la cuenta se inicio con la academia de 4geeks.com, por lo que te aparecen las mentorias de 4geeks.com
