### ISSUE TITLE
Las cohorts `available_as_saas` no deben incluir Teacher ni TA en los NPS

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7574]
- [ ] Agregar una validacion en [esta linea](https://github.com/breatheco-de/apiv2/blob/3624a974145bf490a6ed08dbe245a9c9eb09c498/breathecode/feedback/tasks.py#L114), para evitar enviar preguntas sobre Teachers o TAs en cohorts available_as_saas=true
- [ ] Agregar una pregunta sobre la plataforma y contenido (Debe ser con un boolean en el modelo de Answer). La pregunta debe decir (Lo traduces segun lang): `How has been your experience with the Platform and content?`
- [ ] Agrega las preguntas en: https://github.com/breatheco-de/apiv2/blob/main/breathecode/feedback/utils.py#L1
- [ ] #7630

---

## Tests:

No tests to perform by the QA team

**Comment by jefer94** [comment]
¿Por qué el booleano?, es decir, el booleano marca un tipo de pregunta, y si quisieras reconocer n tipos de preguntas, necesitarías n booleanos, hay mejores opciones como un slug libre o un campo que sea un enum de texto, pareciera que lo están usando para distinguir la pregunta en `build_question`, pero esa solución no escala
