### ISSUE TITLE
Rediseño del prompt builder

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7577]
Aqui esta el diseño nuevo: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15964-90875&t=iFsaUFHw4fpb9D2m-1

**Comment by Charlytoc** [comment]
Tomar la versión en azul dentro del Figma
- [ ] Cambiar el Layout
- [ ] Publicar y probar
