### ISSUE TITLE
Agregar endpoint para generar subscriptions

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7578]
- [ ] Debes agregar el endpoint `POST /v1/payments/academy/plan/<plan_slug>/subscription`
- [ ] Este endpoint debe ser muy similar al de pay, considera abstraer la funcionalidad para determinar que tipo de plan es.
- [ ] Agregar un nuevo permission para agregar usuarios a un plan.
- [ ] Agregar un endpoint nuevo de subscribe que sea con academy y valide por el permiso creado en el paso anterior. Este endpoint debe recibir el plan de manera opcional, y validar si la cohort a la que se quiere agregar el estudiante es available as saas, ajuro debes recibir un plan, ajuro la cohort debe ser una de las que tienes acceso por el plan (Cohort set, cohort set cohorts).
- [ ] Debes crear un signal cuando se acepta un invite, para que desde un receiver en payments, uses el task de generar subscription/planfinancing.

**Comment by tommygonzaleza** [comment]
- [ ] We shouldn't generate the subscriptions from this method; we should only create the plan financings with only one installment.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1431

**Comment by tommygonzaleza** [comment]
- [ ] No esta generando consumibles pero si el plan financing, invoice, etc
