### ISSUE TITLE
Agregar a Rigobot como mentor AI y aclarar todos los beneficios

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7596]
https://4geeks.com/rigobot

- [ ] Acomodar ambos landings, tanot rigobot como GeekPal para incluir sobre rigobot.

## Highlight the importance of getting answers when you are stuck

Students make dozens of errors every day when learning tech skills, that is why mentorship and support is so important. Its the bettest deterrent for learning coding-related skills.

Rigobot fixes that.

The average mentor response time for getting a mentorship in the industry is one week.
The average in 4Geeks is one day.
The average with rigobot to get an answer is 10 seconds.

## rigobot image

Maybe a piece of code with a mistake and a bubble with rigo poping up suggesting an answer?

## Rigobot animation:

Storyboard Outline Without Narration:

	1.	Introduction:
	•	Scene 1: Show Alex (the student) sitting at a desk, coding on their laptop.
	•	On-Screen Text: “Meet Alex, a dedicated student learning to code.”
	2.	Encountering a Problem:
	•	Scene 2: Alex types some code, runs it, and an error message appears on the screen.
	•	On-Screen Text: “Oops! An error in the code.”
	3.	Seeking Help from Rigobot:
	•	Scene 3: Alex looks confused, then types a question into a chat window labeled “Ask Rigobot”.
	•	On-Screen Text: “No worries, Rigobot is here to help!”
	4.	Rigobot’s Response:
	•	Scene 4: Rigobot analyzes the code and responds with a suggestion or solution, highlighting the error and explaining the fix.
	•	Animation: Show a friendly Rigobot avatar appearing on the screen, pointing to the error, and providing a solution.
	•	On-Screen Text: “Rigobot understands your code and provides instant help.”
	5.	Immediate Assistance:
	•	Scene 5: Alex implements Rigobot’s suggestion and reruns the code. This time, it works perfectly.
	•	Animation: Show the code running successfully, with a green checkmark or similar indicator.
	•	On-Screen Text: “Problem solved, thanks to Rigobot!”
	6.	Context-Aware Learning:
	•	Scene 6: Highlight Rigobot’s capability to remember the student and their coding history.
	•	Animation: Show a brief flashback of previous interactions between Alex and Rigobot.
	•	On-Screen Text: “Rigobot remembers your past interactions and code context.”
	7.	Conclusion:
	•	Scene 7: Alex smiles, feeling confident and supported.
	•	On-Screen Text: “With Rigobot, you’re never alone in your coding journey.”

Visual and Technical Details:

	1.	Visual Style:
	•	Clean, modern graphics with a friendly and approachable design.
	•	Rigobot should have a distinct, friendly avatar that conveys trust and efficiency.
	•	Highlight key coding elements and error messages clearly for easy understanding.
	2.	Animation Tools:
	•	Use animation software like Adobe After Effects, Blender, or a simpler tool like Powtoon or Animaker for quick and professional animations.
	•	Ensure smooth transitions and clear highlighting of important elements like the error, Rigobot’s suggestions, and the final successful run.
	3.	Sound Effects:
	•	Add sound effects for typing, error alerts, Rigobot’s appearance, and successful code execution to enhance the viewer’s experience.
	•	Use subtle background music to maintain engagement and set a positive tone.
	4.	Text and Timing:
	•	Ensure on-screen text is concise and appears at the right moments to guide the viewer.
	•	Timing should allow viewers to read and understand the text without feeling rushed.

Script Example Without Narration:

Scene 1:

	•	[Alex coding on laptop]
	•	On-Screen Text: “Meet Alex, a dedicated student learning to code.”

Scene 2:

	•	[Error message appears]
	•	On-Screen Text: “Oops! An error in the code.”

Scene 3:

	•	[Alex types question into “Ask Rigobot” chat]
	•	On-Screen Text: “No worries, Rigobot is here to help!”

Scene 4:

	•	[Rigobot avatar appears, analyzes code, points to error]
	•	On-Screen Text: “Rigobot understands your code and provides instant help.”

Scene 5:

	•	[Alex implements suggestion, code runs successfully]
	•	On-Screen Text: “Problem solved, thanks to Rigobot!”

Scene 6:

	•	[Flashback of previous interactions]
	•	On-Screen Text: “Rigobot remembers your past interactions and code context.”

Scene 7:

	•	[Alex smiles, feeling confident]
	•	On-Screen Text: “With Rigobot, you’re never alone in your coding journey.”

By following this approach, you can create a visually engaging and informative animation that effectively demonstrates Rigobot’s capabilities without the need for narration.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49376022?key=702aca0615a2f8baf205336897be3ace&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/geekpal-support](https://4geeksacademy.com/us/geekpal-support)

**Comment by ali5uarez5** [comment]
Landing de Rigobot: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=16287-24&t=uHrYyHg3ol7OHIDk-1

**Comment by ali5uarez5** [comment]
GeekPal: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=7489-12060&t=QrxMprXnkwnPKiDi-1
