### ISSUE TITLE
Pequeño cambio en modal de login de learnpack para aumentar usabilidad

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7597]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49394414?key=1c1671e9e3513fef1e5bdd378d20bf1e&size=orig) 

---
**Source URL**:
[https://cautious-space-sniffle-465wrg46xfqv47.github.dev/](https://cautious-space-sniffle-465wrg46xfqv47.github.dev/)

**Comment by Charlytoc** [comment]
- [ ] Rename to "skip"
