### ISSUE TITLE
Revisar el prompt builder y dar feedback a charly

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7600]
https://chat.4geeks.com/prompt-builder

**Comment by ali5uarez5** [comment]
no debería ocupar toda la pantalla? 

![Image](https://github.com/user-attachments/assets/ce1786e2-9842-43d6-ab70-06583279ca15)

**Comment by ali5uarez5** [comment]
Casi todos los recursos estan mal exportados, avisame si necesitas ayuda con eso, o si te los paso por aqui @Charlytoc 


![Image](https://github.com/user-attachments/assets/b42da23f-77f9-4915-9b51-e7a0958cdfef)



![Image](https://github.com/user-attachments/assets/af344815-dd2c-4749-8540-3244e83c212a)

**Comment by ali5uarez5** [comment]
Suggestions deberia estar mas a la derecha, el espacio prominente debería ser el que usas para escribir. 
Deberia ser un 70-30 ratio, 70% la entrada de texto, 30% las sugerencias.

![Image](https://github.com/user-attachments/assets/7a3c9528-ab32-471a-9d91-80e6e310470b)

Las líneas deberían llegar a los extremos de la pantalla, el color es #DADADA

Falta el powered by 4Geeks.

**Prompt engineering**  y los demás urls como **Learn more about writing detailed instructions** deberían estar en azul.
Hay que quitarles el efecto que hace que vaya creciendo con el hover. Si queremos agregarle una interacción podemos hacer que se subraye.

Cuando el botón está activo las letras y la flecha deberian ser blancas

![Image](https://github.com/user-attachments/assets/e9242eb6-d648-4d3e-a90a-f684f7098d1a)

Este botón también debería estar en azul

**Comment by ali5uarez5** [comment]
En mobile: 

La versión mobile se ve mejor que la version desktop, pero en general tiene los mismos errores en cuanto a los colores. 

- Hay que hacer el botón más grande. 
- Show suggestions tiene que ocupar mas espacios, cuando está cerrado casi no se ve.
