### ISSUE TITLE
El boton de code reviews aparece deshabilitado

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7607]
Cuando pone el cursor sobre el boton aparece deshabilitado

![image](https://github.com/user-attachments/assets/19f8d07b-cdf2-4c25-af43-0c0b7c6ac68d)

**Comment by gustavomm19** [comment]
Melissa Navarro spain-fs-pt-64

**Comment by tommygonzaleza** [comment]
Esto ocurre porque llega el content vacio en el commit file, otra cosa curiosa que vimos es el url del archivo, que se guardo con un archivo temporal en vez de una url a github como todos los demas.

Este es uno de los commitfiles: https://rigobot.herokuapp.com/admin/finetuning/commitfile/56517/change/?_changelist_filters=q%3DFSPT64-melisa-randomcardgenerator
