### ISSUE TITLE
Bug al subir un archivo en intro-packer-tracer

### ISSUE THREAD

**Issue by ehiber** [breatheco-de/breatheco-de#7620]
### Bug description

- Un alumno reporta 

> no me deja volver a subir este file desde ayer, tenia uno subido pero no era completo asi que lo acabe y al intentar volver a subirlo no lo accepta. Me podrias echar una mano porfa

> no hay manera, ni volviendo a hacer el login, cambiando el nombre o volviendo a hacer un nuevo saving dentro de packet tracer.
> Llevo desde ayer luchando la verdad y acabo de volver a interlo varias veces y de disntictas maneras y no me funciona.

- Tras sugerirle borrar el archivo, comenta:

> esta eliminado desde ayer y no me sale mas, subo el otro y aparece me permite hacer upload pero me saca el mensage de la foto.

![image](https://github.com/user-attachments/assets/50c0c5a0-d889-4723-bf16-dc964da30aca)

### Steps to reproduce

Subir un archivo y luego intentar cambiarlo por otro

### Expected behavior

Permita resubir un archivo

**Comment by tommygonzaleza** [comment]
![image](https://github.com/user-attachments/assets/54dc7dc4-b919-419c-b25f-cf414b1989ce)

![image](https://github.com/user-attachments/assets/885c3b33-5e5d-4e39-89ba-3ded58873f59)

**Comment by tommygonzaleza** [comment]
No logramos replicar el error, quizas es la validacion del tipo de archivo en el API @jefer94

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1431
