### ISSUE TITLE
Ordernar logos de credenciales por importancia

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7626]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49582400?key=23d6bec03f57ce34468b7399a2f3e2ff&size=orig) 

---
**Source URL**:
[https://website-v2-git-fork-g-code7-two-columns-bullets-geeksacademy.vercel.app/us/index](https://website-v2-git-fork-g-code7-two-columns-bullets-geeksacademy.vercel.app/us/index)

**Comment by G-code7** [comment]
![Image](https://github.com/user-attachments/assets/585b258b-d01e-44f5-9594-4b4c6899ca75)
