### ISSUE TITLE
La asistencia se resetea mientras estas seleccionando los estudiantes

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7639]
Mientras vas seleccionando los estudiantes que asistieron, a veces luego de un tiempo se deseleccionan todos los que se habian seleccionado

---

## Tests:

- [ ] When taking attendance of a class (It should be a cohort that has ending_date), after about 30 seconds, the list of students that the teacher selected disappears, if fixed, it shouldn't happen

**Comment by tommygonzaleza** [comment]
- [ ] Reduce the array of events to an array that only includes the `date.now() - event.starting_date` of an event, then you should loop this array and create a set timeout for each of these dates and change the status to live.

**Comment by MadamSagas** [comment]
When taking attendance of a class, the list of students that the teacher selected disappears after a few seconds 

here's a screen record video of the bug 
https://github.com/user-attachments/assets/17165257-0f6a-493a-9716-7ba47f56ea11

**Comment by lumi-tip** [comment]
Could you please tell me which user you used for the tests? Maybe that way I can reproduce the error with that user. I just ran a test with another user, and the attendance did not reset.
