### ISSUE TITLE
Agregar experiencia guiada

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7648]
### Lessons

Para las lessons no hay muchos cambios, inicialmente el menu de la izquierda y el de abajo que cambiara segun el tipo de asset.

Figma: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=GX5zXS3CZJnMYoox-1

<img width="802" alt="Screenshot 2024-07-26 at 4 00 41 PM" src="https://github.com/user-attachments/assets/0fd66d50-b6c9-4953-9630-5642e85a40f9">

### Exercises:

Debes tomar en cuenta la informacion de telemetria como haces en el dashboard del ejercicio

Figma: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=16013-97111&t=GvDIfIO6oGqUL18D-1

<img width="802" alt="Screenshot 2024-07-26 at 8 47 54 PM" src="https://github.com/user-attachments/assets/9108b99e-3917-40b8-a5d8-620f61b23403">

**Comment by gustavomm19** [comment]
Telemetry example here /cohort/mdc-21/student/6892/assignment/240986?academy=3

**Comment by gustavomm19** [comment]
Cambiar url estatica de rigobot en connect to rigobot, usar la variable de entorno

**Comment by tommygonzaleza** [comment]
- [ ] El boton para abrir o cerrar el menu por ahora debe ser como el de antes.
- [ ] Los botones de previous y next deben estar abajo con los iconos de rigobot, etc.
- [ ] No debe haber un scroll de la pagina sino solo de la parte de la lectura por lo que todo debe mostrarse "above the fold".
- [ ] No esta funcionando para entregar un proyecto.
- [ ] Quitale los controles a los video de youtube `?controls=0`

**Comment by tommygonzaleza** [comment]
- [ ] Hay un salto extraño al hacer la transicion del cuadro donde aparece el video y titulo de un proyecto a cuando haces scroll y se muestra las instrucciones.
- [ ] Hay un hueco pequeño en el border superior izquierdo de la barra del titulo de un proyecto cuando estas viendo las instrucciones de un proyecto, en el cual se ve el texto de arriba mientras haces scroll

**Comment by tommygonzaleza** [comment]
- [ ] Add animation to all the assets in the menu when hovered.
- [ ] The name of the module and the arrow should all be clickable, not only the arrow
![Screenshot 2024-09-16 at 3 12 55 PM](https://github.com/user-attachments/assets/30b0960b-8307-4158-8604-b88bf8d892fb)

**Comment by tommygonzaleza** [comment]
- [ ] The icon to watch video tutorial should be down in the actions menu (Where rigobot, deliver assignment, etc are), same is happening with the key concepts icon:
![Screenshot 2024-09-17 at 10 16 43 AM](https://github.com/user-attachments/assets/9a01d6c9-f5b3-4972-bd7f-bfceb6b2eb55)

**Comment by tommygonzaleza** [comment]
- [ ] We should always show the options to open a new codespace or continue a previous one, even if they don't or do have telemetry.
- [ ] If the project has delivery format===no_delivery:
![Screenshot 2024-09-19 at 11 38 08 AM](https://github.com/user-attachments/assets/d54ad7f0-d8d1-41d6-b4c8-a8e5c74ac657)
- [ ] If the project has interactive===true, then it's a project but it opens on LearnPack, in this case we should show the learnpack section we were showing before while we get a new design
- [ ] If the exercise/project has gitpod=false, then we should only show one button that says `Start Exercise` and it should open the modal for cloning locally

**Comment by tommygonzaleza** [comment]
- [ ] Try this layout (And the buttons should be aligned to the left):
![Screenshot 2024-09-20 at 3 29 38 PM](https://github.com/user-attachments/assets/8f601d39-975b-4891-8e36-7c999e91d3c4)

**Comment by tommygonzaleza** [comment]
- [ ] Add new small version of powered by LearnPack, used to open projects that are interactive like the postcard

**Comment by tommygonzaleza** [comment]
- [ ] Agregar estatus de la entrega del proyecto.
- [ ] Agregar version de los subtasks en un proyecto cuando haces scroll
- [ ] Agregar version de proyectos que se abren en learnpack (Ahora es con un boton mas pequeño)

Componentes documentados: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

Readings: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

Projects: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=CeeWJ6JDAhIngZAG-1

**Comment by tommygonzaleza** [comment]
- [ ] Here are some changes you should do on interactive assets
![Screenshot 2024-10-01 at 11 39 38 AM](https://github.com/user-attachments/assets/e2f37cdf-e0f6-49cd-a246-9050fa3d43d6)

**Comment by tommygonzaleza** [comment]
- [ ] You shouldn't show back to top if you are already in the top
<img width="1146" alt="Screenshot 2024-10-07 at 2 51 47 PM" src="https://github.com/user-attachments/assets/8b43c9a8-83cb-44cb-90da-6438c18ee80d">

**Comment by tommygonzaleza** [comment]
- [ ] It's showing an error on this project, I guess it's related to project subtasks
<img width="1466" alt="Screenshot 2024-10-11 at 9 52 06 AM" src="https://github.com/user-attachments/assets/6fa31168-51dc-4d1d-be6a-13c219e833ac">
