### ISSUE TITLE
Add new fields to register payments in the invoice

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7654]
- [ ] Add relation to payment_methods in the invoice. Include a help_text="Payment method used to pay this invoice"
- [ ] Add field provided_payment_details. help_text="These details are provided by the user as proof of payment."
- [ ] Add field confirmation_image_url. Add a help_text="The URL to the image that confirms their payment transaction."
- [ ] You will receive the `payment_method` in the `POST /v1/payments/pay` endpoint.

**Comment by tommygonzaleza** [comment]
- [ ] Remove functionality to charge subscriptions with external_payments with more than one installment (We can't have subscriptions paid externally with more than one payment).
- [ ] Generate the invoice with. the subscription, and in the same endpoint you will receive the ProofOfPayment information.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1431
