### ISSUE TITLE
With paid plan, can't join workshops/schedule mentorships if 0 consumables from Basic plan

### ISSUE THREAD

**Issue by KonnorThatcher** [breatheco-de/breatheco-de#7659]
### Bug description

With a user created from a basic plan that I then upgraded to a paid plan, I am unable to join a workshop or schedule a mentorship if the amount of the workshop/mentorship consumable generated from the basic plan is set to 0, even if I have available consumables that were generated from the paid plan.

![Screenshot 2024-07-31 174231](https://github.com/user-attachments/assets/1dac49ac-2440-4a2e-9c6d-a7e26a26cc8e)

In the example above, I set the amount of [this workshop consumable](https://breathecode-test.herokuapp.com/admin/payments/consumable/5320) that was generated from the basic plan to 0, and [the other workshop consumable](https://breathecode-test.herokuapp.com/admin/payments/consumable/5327) from the paid plan to -1 (infinite). Even though I have an infinite amount of workshop tokens available thanks to the paid plan consumable, I get told that I've run out of workshops.

If instead I set the amount of the paid plan consumables for workshops/mentorships to 0 and the basic plan consumables to any number, this doesn't happen; it will still let me click the button to join the meeting or schedule a mentorship. This also doesn't seem to be an issue with paid plan consumables themselves, as this isn't an issue at all if I have a user that only has the paid plan.

### Steps to reproduce

- Create a user with a basic plan, then upgrade to a paid plan.
- For Workshops:
  - Set the amount for the workshop consumable generated from the basic plan to 0
  - Try to join any active event
- For Mentorships:
  - Set the amount for the mentorship consumable generated from the basic plan to 0
  - Try to schedule a mentoring session

### Expected behavior

I should still be able to click the button to join an event or schedule a mentoring session if I still have consumables available, even if I have none from the basic plan.

**Comment by tommygonzaleza** [comment]
We should filter the mentorship services that the users have access to in the mentorship widget, by the consumables of mentorship services that they have access to.

**Comment by tommygonzaleza** [comment]
I added a review

**Comment by tommygonzaleza** [comment]
- [ ] Refactor code to get consumables on both views/components

**Comment by tommygonzaleza** [comment]
I added a code review

**Comment by WinstonLesuT** [comment]
## Tests:

- [ ]  We should filter the mentorship services that the users have access to in the mentorship widget, by the consumables of mentorship services that they have access to.

- [x] We should always include the mentorship services with balance 0, as we use it to allow them to buy more

- [x] We should check the event types associated to the event type set of the consumables of the user, if the consumables of the user don't include the event type of the event, then we should tell them: "This is a private event, you don't have access to this event".

**Note:** tested with this [User](https://breathecode-test.herokuapp.com/admin/payments/subscription/1579/change/) and this [consumables](https://breathecode-test.herokuapp.com/admin/payments/consumable/6114/change/) for the workshops. The subscription doesn't include the type of event _esGeekforce Gratis_ so an event with that type was created [event](https://breathecode-test.herokuapp.com/admin/events/event/857/change/) with that type was created; during the free trial or as long as the user doesn't belong to a bootcamp we get this message "This is a private event; you don't have access to this event". 
Once the user belongs to a bootcamp, they give access to join. (Event is free for bootcamps)

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-09-24 at 10 48 38 AM](https://github.com/user-attachments/assets/ec037e23-d257-459b-9b50-e14275d01d0d)

**Comment by lumi-tip** [comment]
This change was already included in:
https://github.com/breatheco-de/app/pull/1607#pullrequestreview-2325554659
