### ISSUE TITLE
Crear landings para campañas basda en locaciones

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7664]
- [x] Tres locaciones, tres landings: Austin, Tampa y Miami

Esos son los keywords:
- [x] Learn to code in Tampa
- [ ] Coding courses Tampa

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2139

**Comment by G-code7** [comment]
- [ ] Crear curso de introducción a la programación 
- [ ] Errores ortográficos
- [ ] Eliminar landing carne Joven y crear un redirect
