### ISSUE TITLE
Design component `TwoColumnLocation`

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7665]
The component should have an image for each location on the right side, and on the left side it should have a title and a description 

It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7663

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=12874-19209&t=VUGEWmy8klrJtM6n-1
