### ISSUE TITLE
Add a flag to turn off or on activity's module from an env variable

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7669]
By default, it should be enabled, and with the env variable we should be able to add false (Make sure it check for string instead of only truthy value) to disable it

---

## Tests:

No tests are required for this issue as you don't have access to heroku

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1439

**Comment by jefer94** [comment]
Use `ENABLE_ACTIVITY` environment.
