### ISSUE TITLE
The profile image looks cropped from the profile view

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7670]
![image](https://github.com/user-attachments/assets/4e22e080-76e0-4844-a45f-34ec7b9d1802)

---

Tests:

Upload a profile image with a user or use a user that has a profile image (you can find it in the Profile table)

- [ ] Check that the image is not being cropped in the profile view

**Comment by JennGuz** [comment]
Imposible replicar, aparece bien


![Image](https://github.com/user-attachments/assets/7de53bc0-6386-4b51-b8cb-9cd0c4b3ef29)

**Comment by MadamSagas** [comment]
Can you please tell me where can I find the PR
