### ISSUE TITLE
We should remove the footer if the user is logged in

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7672]
Remove the footer if the user is logged in.

---

```md
## Tests:

- [ ] Log in with any user and validate that the footer is not there from any public view like: `/workshops` or `/pricing`
```

**Comment by tommygonzaleza** [comment]
- [ ] Add padding to the bottom of the layout, this is happening in other pages as well, so try to make sure you are doing it from the layout
![Screenshot 2024-08-26 at 12 47 18 PM](https://github.com/user-attachments/assets/6517e2a0-faf2-4a61-a223-7c29344fea32)

**Comment by tommygonzaleza** [comment]
Do it in a new PR

**Comment by tommygonzaleza** [comment]
- [ ] Remove this from the footer and create a new component with it, you should add it in the layout below the footer, [here](https://github.com/breatheco-de/app/blob/f6574979640789f64634fa91809450ea316db9d2/src/pages/_app.jsx#L93)
![Uploading Screenshot 2024-08-27 at 2.16.09 PM.png…]()

- [ ] Change the year to the current year programmatically

**Comment by tommygonzaleza** [comment]
## Tests:

- [ ] Log in with any user and validate that the footer is not there from any public view like: `/workshops` or `/pricing`

**Comment by WinstonLesuT** [comment]
## Tested

- [x] Log in with any user and validate that the footer is not there from any public view like: `/workshops` or `/pricing`

**Comment by tommygonzaleza** [comment]
We shouldn't add the margin on all the pages, for example, the guided experience view (Where you read you lessons inside a cohort) shouldn't have any margin at the bottom or any footer at all

**Comment by KonnorThatcher** [comment]
## Tests:

- [x] Log in with any user and validate that the footer is not there from any public view like: `/workshops` or `/pricing`

**Comment by WinstonLesuT** [comment]
## Tests:

- [x] Log in with any user and validate that the footer is not there from any public view like: `/workshops` or `/pricing`
