### ISSUE TITLE
New Feature suggestion: Scroll back to top button

### ISSUE THREAD

**Issue by WinstonLesuT** [breatheco-de/breatheco-de#7676]
**Is your feature request related to a problem? Please describe.**
When you're part of a cohort and you start to progress, completing modules, etc. You scroll down a lot, and you lost the navbar that allows you to navigate between all the features that 4geeks offers.

So, it's a little annoying to scroll to top manually to see the navbar again.
The suggestion is to put a button that allow the user scroll back to top easily and faster.

**Image of reference**
![Screenshot 2024-08-07 115317](https://github.com/user-attachments/assets/bb31d29b-9b71-4816-a7a5-087694372e8b)

---

## Tests

Log in with any user that has access to a cohort or create a new user, then get in the cohort, enter a lesson and scroll to the bottom or middle of the lesson.

- [ ] There should be a button that takes you to the top.
- [ ] When you click the button it should take you to the top

**Comment by tommygonzaleza** [comment]
@ali5uarez5 add this feature in the guided experience we are currently designing

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=16078-82761&t=TE8T4dvVq25BDLJe-1
