### ISSUE TITLE
Explotar el OWASP top 10 completo bWapp

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7678]
Cumplir todos los pasos del pending muy detalladamente para una de las 10 y dejar que los alumnos hagan el resto.
Hay que ser incisivos en cumplir los pasos del pentesting que se vieron en la semana anterior de introduccion.

**Comment by rosinni** [comment]
Link del repositorio: https://github.com/breatheco-de/owasp-top-10-on-bwapp
