### ISSUE TITLE
Add `week_unit` to the choose_program YML

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7681]
After the week property, add a property named `week_unit`, which in Spanish the value should be `sm` and in English it should be `wk`.

Here is an example of where you should change it: https://github.com/4GeeksAcademy/website-v2/blob/e71a1060dc6998d9372df74874dee713766ffb12/src/data/course/full-stack.us.yaml#L147

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2151
