### ISSUE TITLE
It's not allowing to deliver projects from the guided experience

### ISSUE THREAD

**Issue by vancieta** [breatheco-de/breatheco-de#7682]
### Bug description

![image](https://github.com/user-attachments/assets/dc5edf83-03ab-46e7-909e-7581da48cc45)
![image](https://github.com/user-attachments/assets/9e036930-2e03-4cbb-9438-d0aa1d0c7af2)

Delivering projects from the cohort's dashboard is working but once you try to deliver a project from the guided experience inside the project, it only allows you to mark it as done.

### Steps to reproduce

Get into any project in 4geeks.com from the cohort "Building your tech profile"

### Expected behavior

It should allow to deliver the projects instead of considering it a lesson

---

## Tests:

Create a user as a student with access to that cohort, and try to deliver the assignment

- [ ] It should allow you to deliver it from the cohort's dashboard.
- [ ] It should allow you to deliver it from the guided experience inside the project instructions

**Comment by tommygonzaleza** [comment]
We weren't able to replicate it

**Comment by gustavomm19** [comment]
Solved here: https://github.com/breatheco-de/breatheco-de/issues/7713
