### ISSUE TITLE
Agregar social graph para cunado la gente compatrta el promt builder en redes

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7683]
https://www.opengraph.xyz/url/https%3A%2F%2Fai.4geeks.com%2Fprompt-builder

- [ ] Una buena imagen
- [ ] Favicon
- [ ] Una buena descripcion
- [ ] type

Si comparten ai.4geeks.com/prompt-builder es diferente que si comparten ai.4geeks.com solo.

Sugernecia de implementacion:

Usa react helmet

**Comment by Charlytoc** [comment]
HAcer un logo para el favicon con Midjourney
