### ISSUE TITLE
Landings de FS a tu propio ritmo

### ISSUE THREAD

**Issue by ThaniaCorro** [breatheco-de/breatheco-de#7684]
Crear una landing page con objetivo comercial, la cual se usara en google ADS para las provincias que dejamos de tocar en ADS porque el poder adquisitivo era menor y siempre quedaban en lost for money.

Se requiere tanto de Google como de Meta.

@jatv93

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2141
