### ISSUE TITLE
It shouldn't repeat mentorship services

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7695]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49938084?key=5d9d22c80a5e321458cfa6d62f0e0fad&size=orig) 

---
**Source URL**:
[https://4geeks.com/choose-program](https://4geeks.com/choose-program)

**Comment by MadamSagas** [comment]
Where can i find the PR?
