### ISSUE TITLE
Esta roto el boton para aceptar invitaciones en el dashboard

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7696]
https://insights.hotjar.com/r?site=5084735&recording=59261912808

Al parecer segun hotjar le da este error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cohort');

![Screenshot 2024-08-08 at 3 07 09 PM](https://github.com/user-attachments/assets/26641c52-95c4-4a62-9276-798246df1e4e)

**Comment by tommygonzaleza** [comment]
Reported [here](https://github.com/breatheco-de/breatheco-de/issues/7697)
