### ISSUE TITLE
This user has an invite but it's not allowing to accept it

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7697]
Here is a video that shows the error he's getting: https://insights.hotjar.com/r?recording=59261912808&startTime=540000&token=e15ecc350f4d3b584be65d4b63ea11f5&h=07010d01025600

It should allow him to accept the invite to that cohort.

---

Tests:

Invite a user that already exists to another cohort (IMPORTANT: The user should have a previous invite accepted from a different cohort).

- [ ] Validate that it allows to accept the invite, and then the cohort should be shown below with the rest of the cohorts.

**Comment by alesanchezr** [comment]
- no refrescar la pantalla
- terminer el #7888

**Comment by tommygonzaleza** [comment]
It allowed me to accept it but nothing happened, the user was not added to the cohort

**Comment by tommygonzaleza** [comment]
- [ ] We should create the cohort user when we are creating the profileacademy, specifically it should happen [here](https://github.com/breatheco-de/apiv2/blob/02e904b051f4699798c479ab42a6fcea6f663354/breathecode/authenticate/serializers.py#L976) before the validation that check the user is not in validated_data. Add the code to create the cohort user
