### ISSUE TITLE
Los credenciales del home no cambian de idioma, deberian salir en español

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7698]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49938467?key=9d9a5600b84b0fb1894766f5f463d2f9&size=orig) 

---
**Source URL**:
[https://4geeks.com/es](https://4geeks.com/es)

**Comment by KonnorThatcher** [comment]
Tested
