### ISSUE TITLE
Bug on layout when selecting mentorship service

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7702]
There we should have two divs, one for the mentorship service name and another for the arrow, that way they never overlay each other, and the name if it's too long, then it should jump to a new line.

<img width="623" alt="Screenshot 2024-08-08 at 3 57 30 PM" src="https://github.com/user-attachments/assets/bd9aa487-2bcb-43b3-b3e8-15ffbd81b238">

---

Tests:

Access to a mentor profile link (you can find it in the list of mentorship profiles) that has more than one mentorship service, access as that mentor (You can change the password in the user admissions), then change the name of one of the mentorship services and make it much longer

- [ ] The arrow and the name of the mentorship service should be separated.
- [ ] If the mentorship service title is too long, then it should jump to a new line

**Comment by JennGuz** [comment]
https://github.com/breatheco-de/apiv2/pull/1460
