### ISSUE TITLE
Error 404/500 cuando trata de ir al articulo anterior en el knowledge base

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7703]
En general creo que todo el [knowledge-base-4geeks](https://4geeks.com/es/docs/knowledge-base-4geeks) esta fallando en español, muevete entre las lessons dandole a siguiente y anterior.

 Si te fijas, esta intentando ir a un URL incorrecto, esta intentando ir a [why build a final project](https://4geeks.com/es/docs/knowledge-base-4geeks/why-build-a-final-project) y en verdad deberia ir a [eventos en vivo, workshipos y clases en 4geeks.com](https://4geeks.com/es/docs/knowledge-base-4geeks/eventos-en-vivo-workshops-y-clases).
 
 Si te cambias al idioma ingles todo funciona perfectamente.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49939871?key=16957dbe5d555c1a9d56ded76323f9b5&size=orig) 

---

```
 ## Tests

Go to the knowledge-base (`${BASE_URL}/docs/knowledge-base-4geeks/getting-started-with-4geeks`), the base_url should be the 4geeks.com URL of the instance you are working at (dev.4geeks.com or the preview URL). 

- [ ] Try to navigate to the previous and next articles with the bottom buttons.
- [ ] Try to navigate with the table of content
```

**Comment by veljzs** [comment]
## Tests

Go to the knowledge-base (`${BASE_URL}/docs/knowledge-base-4geeks/getting-started-with-4geeks`), the base_url should be the 4geeks.com URL of the instance you are working at (dev.4geeks.com or the preview URL). 

- [x] Try to navigate to the previous and next articles with the bottom buttons.
- [x] Try to navigate with the table of content
