### ISSUE TITLE
Updates on the modal that shows to run a project/exercise locally

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7714]
- We will no longer use the markdown component for these instructions, we will have a new component just for this.
- The component will have a series of collapse steps that students will expand if needed with details on each step.
- The last 2 steps are related to the editor.agent and only one of them will show (depending on the agent).
- Only the steps titles will show, the details will be collapse and the student will have to expand if needed.
- There should be 4 steps max.
- There will be a video that the student can watch if needed.
- Only if the `cohort.is_available_as_saas = true` there will be a button to request help with a mentorship.
- Each step will have a link to learn more about the step.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49995343?key=c6b4361bf95288d1a0187276732198b3&size=orig) 

---
**Source URL**:
[https://4geeks.com/syllabus/cybersecurity-fake/project/deploying-wordpress-site-debian](https://4geeks.com/syllabus/cybersecurity-fake/project/deploying-wordpress-site-debian)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=422-96634&t=WKTL9Epiqmozto9z-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2574-3609&t=BKDu7B49ELO3Fh87-1

**Comment by tommygonzaleza** [comment]
- [ ] Debes agregar como botones uno al lado del otro con el icono de cada sistema operativo, mientras los demas pasos deben estar ocultos

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7759
