### ISSUE TITLE
It's not finding the user commitfiles

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7716]
Here is the repository: https://github.com/julfom/calculus-and-algebra-problems-with-python_if

Here is the error received: `The github_username julfom was not found inside the Committer. Make sure to add a repository and include julfom in the watchers key`

**Comment by Charlytoc** [comment]
https://api.github.com/repos/julfom/calculus-and-algebra-problems-with-python_if/commits/c90c08c
