### ISSUE TITLE
De la lista de landings revisar que componentes no estan en el landing de tampa para que los diseñes

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7720]

**Comment by ali5uarez5** [comment]
Headers: 
![image](https://github.com/user-attachments/assets/703eda11-4319-41f6-96ee-83ad4b5df84b)


Este es el diseño: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=8090-3077&t=BlR1LxkwDYl5SHYt-1
-------------------------------------------------

Componente de job guarantee: 
![image](https://github.com/user-attachments/assets/71987da1-59de-47e0-a710-9af077785e29)
 
El diseño es este:
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=7831-13248&t=BlR1LxkwDYl5SHYt-1

----------------------------------------------

Objetivos de nuestra academia: 
![image](https://github.com/user-attachments/assets/08c5668f-fec7-424d-a128-11e381206de3)


Hay que diseñar este componente

-----------------------------------------------------

Quien contrata a nustros alumnos?
![image](https://github.com/user-attachments/assets/af0d6075-5506-4004-b259-2dd1e11167ea)


Este es el diseño: 
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=11569-19528&t=BlR1LxkwDYl5SHYt-1

--------------------------------------------------------

Componente de video:
![image](https://github.com/user-attachments/assets/0000cc55-d5c7-4c25-af62-e0b0d841d572)


Este es el diseño: 
https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1
---------------------------------------------------------------
About the program: 
![image](https://github.com/user-attachments/assets/945a67a0-90f8-4b4b-a478-99bd3918d7b8)

Este es el diseño: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=8090-3363&t=BlR1LxkwDYl5SHYt-1

-----------------------------------------------------------------------
Tenemos 3 años...
![image](https://github.com/user-attachments/assets/57c3669e-782a-420f-b6bb-c8c661e53eee)

Hay que diseñar este componente

------------------------------------------------------------------------
Python y javascript:
![image](https://github.com/user-attachments/assets/8cefa17f-329a-4d0f-a364-79b9b27baa87)

usar un two columns: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1

-------------------------------------------------------------------------

Componente proyecto final:
![image](https://github.com/user-attachments/assets/c728f880-c1d1-4262-9f3f-a133dc7f2b57)

Hay que rediseñar este componente

---------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/05d03568-21fb-4865-ae22-23a6bbadf69b)

Hay que rediseñar este componente.

-----------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/315733ec-a32a-49f7-908d-cde967810354)

Usar un two columns: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1
---------------------------------------------------------------------------------

Income sharing agreement: 
![image](https://github.com/user-attachments/assets/76e31f80-9c87-44b2-af26-77a7bd1eac34)

Hay que rediseñar este componente.

-----------------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/351c41eb-b140-48f6-b782-c7cde0f40a2f)


Hay que rediseñar este componente.

--------------------------------------------------------------------------------------
How it works: 
![image](https://github.com/user-attachments/assets/5a79b231-17a2-4692-8e50-a93c10918e21)

El componente esta aqui: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=7831-13248&t=BlR1LxkwDYl5SHYt-1

----------------------------------------------------------------------------------------------
Blacks in technology foundation:
![image](https://github.com/user-attachments/assets/4a2b635f-6b41-45c4-a90c-fba01a9527c4)

Usar un two columns: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1

--------------------------------------------------------------------------------------------------

Why coding? 
![image](https://github.com/user-attachments/assets/ae9d9254-d61f-49c3-88aa-8dea7be3ae2b)

Usar un two columns: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1

-------------------------------------------------------------------------------------------------------
Why our coding clases stands out?

![image](https://github.com/user-attachments/assets/56cfc244-0c50-4589-af08-430c15ab58cf)

Este seria el componente de rigobot?

---------------------------------------------------------------------------------------------------------

The 3 Steps of our Coding Classes

![image](https://github.com/user-attachments/assets/18e9e48f-344f-4b7d-97a7-d3b0d7d58c67)


Hay que rediseñar este componente

------------------------------------------------------------------------------------------------------------

Become a fullstack developer with coding classes:
![image](https://github.com/user-attachments/assets/0f5e5752-f1a4-4e21-8bcb-f0dc960bbb3a)

Usar un two columns: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6835-7497&t=BlR1LxkwDYl5SHYt-1

------------------------------------------------------------------------------------------------------------
Elegibility program: 
![image](https://github.com/user-attachments/assets/2e043f8b-dc5f-4388-b81c-8a349940b02d)

Hay que rediseñar este componente

------------------------------------------------------------------------------------------------------------

Why 4Geeks academy?
![image](https://github.com/user-attachments/assets/b8aec084-c74e-4e94-9894-6fd485281231)


Hay que rediseñar este componente

------------------------------------------------------------------------------------------------------------

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7746)
