### ISSUE TITLE
Redesign badges component

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7721]
Here is the figma link: https://www.figma.com/design/0kfc9La5QthLyu927siuCw/Website-Project?node-id=12931-9600&t=pxs2YyptsdZ9SbdX-1

This is how it is at this moment, it should be changed to the one of the figma, it should have by default but should be able to be modified from the YML:

- They should have a white background (Each card)
- The fontsize of the "4.6 on reviews" text should be smaller
- The stars should be smaller

<img width="1107" alt="Screenshot 2024-08-15 at 1 43 15 PM" src="https://github.com/user-attachments/assets/5101796a-506f-4d6c-b34a-fec9c73e8510">

> https://4geeksacademy.com/es/landing/aprende-a-programar-colombia

**Comment by gustavomm19** [comment]
https://4geeksacademy.com/es/landing/aprende-a-programar-colombia

**Comment by tommygonzaleza** [comment]
- [ ] The padding should be the same on top and bottom.
- [ ] The "En reseñas" text should be all lowercase in both Spanish and English
