### ISSUE TITLE
Video testimonial esta malo, sale el de otra persona

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7724]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/50063601?key=a7b7f5361f0355288b4562688ac800bd&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/es/testimonios?lang=es](https://4geeksacademy.com/es/testimonios?lang=es)

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2188
