### ISSUE TITLE
Add page to schedule mentorship

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7728]
This page will have the same flow as the widget but in an empty page. This will be used as link to send the students to schedule mentorship sessions.

Add it in the URL: `/mentorship/schedule`

It should allow to include querystring to specify the mentorship service or the mentor, both optional, like this:

`/mentorship/schedule?service=<mentorship_service_slug>&mentor=<mentor_slug>`.

Both are optional. If you receive only the mentorship service slug, then you should show the mentors available for that service. If you only receive the mentor, then you should show the services that you can use to have a mentorship with this mentor.

This is the figma: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=16227-72775&t=feCMA0HGrgY6XfxC-1

![Screenshot 2024-08-27 at 3 12 36 PM](https://github.com/user-attachments/assets/93e02044-5fbc-42ae-bdb4-c61aee604996)

---

## Tests:

- [ ] Go to the page `/mentorship/schedule` without a user, it should send you to the login page
- [ ] Go to the page logged in, with a BootCamp user (A user with a cohort user of a availabla_as_saas=false cohort), it should let you schedule a mentorship of one of the mentorship services that you have access to
- [ ] Go to the page logged in, with a saas user (A user from only an academy available as saas), and try to schedule a mentorship. If you have consumables it should let you schedule the mentorship.
- [ ] Go to the page logged in, with a saas user (A user from only an academy available as saas), and try to schedule a mentorship. If you don't have consumables it should tell you that you don't have consumables and show you the modal to buy more consumables or upgrade plan.

**Comment by tommygonzaleza** [comment]
- [ ] Debias reutilizar el componente de las mentorias que se usa en el widget
![Screenshot 2024-09-17 at 10 06 49 AM](https://github.com/user-attachments/assets/5c972b4f-6001-461a-aa72-76ec24493654)

**Comment by tommygonzaleza** [comment]
- [ ] Use this endpoint to get the mentorship services of the mentorship service set: mentorshipserviceset/<int:mentorship_service_set_id>

**Comment by KonnorThatcher** [comment]
For a user with a basic plan, the mentorship page doesn't list any available mentors like it does in the mentorship widget on the user's dashboard.

https://www.loom.com/share/158f6a60064644bc9b4601fed9a16587?sid=33cb4fe1-590c-49f2-8628-6f5dacd12e7e

Here's the user's [subscription](https://breathecode-test.herokuapp.com/admin/payments/subscription/1568/change/) and the [mentorship consumable](https://breathecode-test.herokuapp.com/admin/payments/consumable/6057/change/) this was tested with.

**Comment by WinstonLesuT** [comment]
## For user that got the basic plan but previously had the free trial, it's not possible to schedule mentorships using the page /mentorship/schedule. But the user can schedule a mentorship from the widget.

I create a new user and test with no consumables. It told me that I should upgrade the plan, I did it. I notice a new consumable was generated, and I can schedule mentorships from the widget but not from the page. 

Steps to reproduce:

- Register a new [user](https://breathecode-test.herokuapp.com/admin/payments/subscription/1596/change/) and get the free trial.
- Set the [Consumables](https://breathecode-test.herokuapp.com/admin/payments/consumable/6243/change/) to zero.
- Upgrade the plan using the Yellow button in the bootcamp program component in the **Your Active Programs** section.
- After the upgrade, new consumables are going to be generated. This [one](https://breathecode-test.herokuapp.com/admin/payments/consumable/6244/change/) for this case.
- Tested.


https://github.com/user-attachments/assets/2ba977a9-4801-4998-9bb1-896f048bcbd8

**Comment by KonnorThatcher** [comment]
## Tests:
- [x] Go to the page /mentorship/schedule without a user, it should send you to the login page
- [x] Go to the page logged in, with a BootCamp user (A user with a cohort user of a availabla_as_saas=false cohort), it should let you schedule a mentorship of one of the mentorship services that you have access to
- [x] Go to the page logged in, with a saas user (A user from only an academy available as saas), and try to schedule a mentorship. If you have consumables it should let you schedule the mentorship.
- [x] Go to the page logged in, with a saas user (A user from only an academy available as saas), and try to schedule a mentorship. If you don't have consumables it should tell you that you don't have consumables and show you the modal to buy more consumables or upgrade plan.

**Comment by tommygonzaleza** [comment]
- [ ] Remember that all the pages should have a max-width of 1280px
<img width="1470" alt="Screenshot 2024-09-30 at 8 06 55 PM" src="https://github.com/user-attachments/assets/07c26cbe-9cfa-4c19-b70c-88bb3daf312a">
