### ISSUE TITLE
Create a proxy endpoint to create completion jobs

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7732]
## Backend

You should use the following endpoint to create the completion job: https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#e72a5f0a-d427-4500-81ff-6077db7b0823

You should use this endpoint to generate the rigobot token: https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#0060b86e-4d57-4f6d-ad26-89527c3357b7

The variables you should send in the body are:
- asset_type: (LESSON, EXERCISE, PROJECT, ARTICLE)
- asset_title
- syllabus_name
- asset_mardown_body (Send the entire markdown)

Here is the documentation to create the proxy endpoint: https://breatheco-de.github.io/linked-services-django-plugin/getting-started/services/

Then with the received information from the rigobot's endpoint, you should redirect them to: `https://ai.4geeks.com/?token=<generated_token>&purpose=<purpose_id>&completion=<completion_job_id>&action=generate`

The generated token will be generated with an endpoint created in this [issue](https://github.com/breatheco-de/breatheco-de/issues/7731)

The purpose_id should be fixed to 14.

The completion_job_id will be received from the other endpoint you used when creating it on rigobot.

**Comment by tommygonzaleza** [comment]
https://github.com/breatheco-de/breatheco-de/issues/7731

**Comment by gustavomm19** [comment]
https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#0060b86e-4d57-4f6d-ad26-89527c3357b7
