### ISSUE TITLE
25% of users don't see the CTA in pricing because it's not above the fold

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7741]
### Desktop (25%)

We should remove some space on top to move it to the second image point:

1.
![Screenshot 2024-08-21 at 4 11 30 PM](https://github.com/user-attachments/assets/5948d7fb-2c9d-466f-b45b-8d736dacc19d)

2.
![Screenshot 2024-08-21 at 4 12 22 PM](https://github.com/user-attachments/assets/42182b1b-cc9e-4f96-84b5-477b34e78201)

### Mobile (52.5%)

In mobile 52.2% of users are missing the CTA. We must move it to the area of what's above the fold.

![Screenshot 2024-08-21 at 4 14 12 PM](https://github.com/user-attachments/assets/c67da7bf-937e-4958-9dc6-ecd87a564b26)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12466-62638&t=rpT7JwcJSryvM1V7-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7756
