### ISSUE TITLE
The CTA of the bootcamp's landing should be above the fold in mobile

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7743]
![Screenshot 2024-08-21 at 4 30 11 PM](https://github.com/user-attachments/assets/b6481d33-d6f0-44da-97ac-a19e384b511e)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-51392&t=rpT7JwcJSryvM1V7-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7757
