### ISSUE TITLE
Hreflang to redirect

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7745]
1. Open this [article](https://4geeks.com/es/lesson/herramientas-para-la-prevencion-o-deteccion-de-intrusos-ids-ips).
2. Look at the Hreflang canonical US tag.
3. It points to slug [intruder-detection-system-tools](https://4geeks.com/lesson/intruder-detection-system-tools) but that is not the main slug, that is just an alias, it should be pointing to the real slug https://4geeks.com/lesson/intrusion-detection-system-examples

**Comment by MadamSagas** [comment]
Open this [article](https://4geeks.com/es/lesson/herramientas-para-la-prevencion-o-deteccion-de-intrusos-ids-ips).
Look at the Hreflang canonical US tag.
It points to slug [intruder-detection-system-tools](https://4geeks.com/lesson/intruder-detection-system-tools) but that is not the main slug, that is just an alias, it should be pointing to the real slug https://4geeks.com/lesson/intrusion-detection-system-examples
