### ISSUE TITLE
Design Rigobot's Chat

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7754]
Use as reference intercom's chat bot's design.

![image](https://github.com/user-attachments/assets/61d4aee2-014c-44eb-a2c9-2418b8d9049e)

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12992-58371&t=f0RwGaUJyIAkvQSt-1
