### ISSUE TITLE
Outside modal for Rigobot

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7755]
It should be similar to the final project's modal

- [ ] It should have the chat in the modal
- [ ] It should have a button for "Join me coding a project".
- [ ] It should have a button for "Let's read a lesson together".

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12992-58371&t=o6zafrYUv8XNFNo2-1
