### ISSUE TITLE
Change pricing design

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7756]
We are changing pricing design to include extra visibility.

Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12466-62638&t=rpT7JwcJSryvM1V7-1

![Screenshot 2024-08-26 at 4 50 24 PM](https://github.com/user-attachments/assets/3f0ff1a4-0548-449f-a046-00a7b63075b8)

You have the mobile design a side of it

---

```md
## Tests

- [ ] Make sure the design is looking fine in different languages, dark/light mode, and mobile/desktop
```

**Comment by KonnorThatcher** [comment]
In dark mode, the FAQ component retains the light-blue background color from light mode, which doesn't fit with the rest of the page and also causes the title of the component to be barely legible.

![Image](https://github.com/user-attachments/assets/a33df0be-599e-475a-9eba-4ea35c5e0843)

The background color should be dark grey like in this image:

![Image](https://github.com/user-attachments/assets/a6ee426d-53e0-4a48-b879-db3e752c10ec)

**Comment by KonnorThatcher** [comment]
## Tests

- [x] Make sure the design is looking fine in different languages, dark/light mode, and mobile/desktop
