### ISSUE TITLE
Redesign bootcamp's landing in mobile

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7757]
We need to increase the call to action's visibility so we have to use this design on mobile.

This design is used on interactive exercises as well, make sure you use the same component

Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=12782-51392&t=rpT7JwcJSryvM1V7-1

![Screenshot 2024-08-26 at 4 54 44 PM](https://github.com/user-attachments/assets/9fd307ef-10dc-4836-bea8-9f1b4a966354)

---

```md
## Tests

- [ ] Make sure the design is looking fine in different languages, dark/light mode, and mobile/desktop
```

**Comment by WinstonLesuT** [comment]
## Tests

- [x] Make sure the design is looking fine in different languages, dark/light mode, and mobile/desktop

**Comment by WinstonLesuT** [comment]
## The colors should change in dark mode

In the bootcamp page, this component doesn't change when the user selects the dark mode. It should be a contrast in the colors.

### Bootcamp page
![Light mode bootcamp](https://github.com/user-attachments/assets/a176d525-bc47-47e5-8961-78a8f16fd18e)
![Dark mode bootcamp](https://github.com/user-attachments/assets/e7306b3d-41cf-4325-aa63-e0518354e2e2)

### Attached a reference from the landing page

![Dark mode Landing](https://github.com/user-attachments/assets/c09934bd-8035-4617-b7c4-ff4e4bc16576)

**Comment by WinstonLesuT** [comment]
## Tests

- [x] Make sure the design is looking fine in different languages, dark/light mode, and mobile/desktop

**Comment by tommygonzaleza** [comment]
- [ ] It's not showing both buttons, only one the financing options one
- [ ] We should change the title to `Start a career in ${course name}`

**Comment by tommygonzaleza** [comment]
- [ ] The deployment failed
<img width="1466" alt="Screenshot 2024-10-11 at 12 48 48 PM" src="https://github.com/user-attachments/assets/baf3079c-28bf-4bba-a0a6-a5fbabccec4c">
