### ISSUE TITLE
Updates on the modal that shows to run a project/exercise locally

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7759]
- We will no longer use the markdown component for these instructions, we will have a new component just for this.
- The component will have a series of collapse steps that students will expand if needed with details on each step.
- The last 2 steps are related to the editor.agent and only one of them will show (depending on the agent).
- Only the steps titles will show, the details will be collapse and the student will have to expand if needed.
- There should be 4 steps max.
- There will be a video that the student can watch if needed.
- Only if the `cohort.is_available_as_saas = true` there will be a button to request help with a mentorship.
- Each step will have a link to learn more about the step.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/49995343?key=c6b4361bf95288d1a0187276732198b3&size=orig) 

---
**Source URL**:
[https://4geeks.com/syllabus/cybersecurity-fake/project/deploying-wordpress-site-debian](https://4geeks.com/syllabus/cybersecurity-fake/project/deploying-wordpress-site-debian)
 
Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=437-13552&t=XacIswkIMy6jLvCL-1

**Comment by gustavomm19** [comment]
Add config field json to serializer

**Comment by tommygonzaleza** [comment]
- [ ] Add `asset.agent` with a help_text="If value is vscode, then we recommend to open this exercise/project in vscode and instructions will be different. If it is standalone, then you can open it directly from the terminal"
- [ ] Make sure you are including the logic to fill this value as we do with `gitpod` and `external`

**Comment by tommygonzaleza** [comment]
- [ ] Remove the fixed height.
- [ ] Add a gray box where the video is supposed to be on the step where they choose the OS

**Comment by tommygonzaleza** [comment]
- [ ] It should allow receiving markdown on the descriptions of the steps:
<img width="1010" alt="Screenshot 2024-10-04 at 9 06 17 AM" src="https://github.com/user-attachments/assets/5f4ac5db-fffe-4958-8797-e726c2cfa17b">

**Comment by tommygonzaleza** [comment]
- [ ] The code blocks should be highlighted they should have a different background, currently it is hard to notice it's a code block when it's inline
<img width="1252" alt="Screenshot 2024-10-08 at 8 26 44 AM" src="https://github.com/user-attachments/assets/bb127831-0651-4f96-b6ed-0f0da7f4a55d">
