### ISSUE TITLE
The syllabus builder shouldn't allow adding an asset twice

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7783]
Currently I found a bug related to having two modules with the same project. That should never happened.

Once a project has been added to a module, then we should never allow including it in a different module. We should take this into account in the functionality when you try to move the project to a different module, it asks you if you want to move it or copy it, in the case of projects, it shouldn't include the option of copying it but only moving it.

---

## Tests: 

No tests for this issue as the syllabus builder doesn't have a dev server

**Comment by tommygonzaleza** [comment]
- [ ] Fix this error in the deployment
<img width="1252" alt="Screenshot 2024-10-07 at 6 54 06 PM" src="https://github.com/user-attachments/assets/9d98e1e8-2bfd-4f3f-ae00-5ef63bea6b4a">

**Comment by alesanchezr** [comment]
Actualizar dependencias para node v22

**Comment by alesanchezr** [comment]
Una nueva propiedad syllabus.languages determina que idiomas va a tener un syllabus, por ejemplo: `languages: ["us", "es"]`

Para llenar esa propiedad agregaremos un boton arriba en la barra de navegacion para "add language" que funciona muy similar al de add technologies: https://tinyurl.com/2cd6jnkn, se debe poder borrar un lenguaje tambien (pero confirmar con una modal)

Por otro lado, si syllabus.languages tiene mas de un language entonces la caja de label y descripcion del moduloe tantas vecxes como languge hay.

Por ultimo, validar todo con JS para evitar que hayan cajas sin llenar.

**Comment by tommygonzaleza** [comment]
No agregaste los botones como se pidieron, era un boton de agregar language que te permitia agregar otros languages y todo, no solo esos dos fijos
