### ISSUE TITLE
Error when rating a code revision using rigobot

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7785]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44482-5652193b5945c1604049c554b346bad9) 
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728x966</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by Charlytoc** [comment]
A esa vista no le he dado mantenimiento, los code reviews se hacen a través de 4geeks actualmente
