### ISSUE TITLE
If a plan has planoffer.suggested_plan, then it should show to upgrade the plan

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7787]
The basic plan can be upgraded to a premium plan, you can find it through the planoffer.suggested_plan

![Screenshot 2024-09-09 at 11 21 49 AM](https://github.com/user-attachments/assets/53894255-22d2-43c3-99ef-752b4d2a0efc)

**Comment by lumi-tip** [comment]
endpoint used during checking when a plan is canceled won't let me reactivate my subscription by paying again.
i think the answer from the backend is comming from here: https://github.com/breatheco-de/apiv2/blob/0e2498ccc4f14ea6d7d05d9ab9db2395e701d625/breathecode/payments/actions.py#L248

is there another endpoint to re-activate my subscription once i cancelled it so i can use it when the user clicks reactivate subscription?

**Comment by alesanchezr** [comment]
jeferson va a corregir el error de backend

**Comment by tommygonzaleza** [comment]
- [ ] Don't show more than one subscription/plan_financing of the same plan, and you should prioritize which one to show in the following order: `FULLY_PAID`, `ACTIVE`, `PAYMENT_ISSUE`, `EXPIRED`, `CANCELLED`, `ERROR`

**Comment by tommygonzaleza** [comment]
Check the comment I added in the PR
