### ISSUE TITLE
We must change the requirements.txt in all machine learning syllabus

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7791]
On all requirements.txt we should have pandas and numpy like shown on this one: https://github.com/4GeeksAcademy/realestate-datacleanup-exercise/blob/main/requirements.txt#L4

You should go through all the Data Science and ML syllabus and check that file for exercises and projects, and make sure they are showing the version with `>=` instead of only `=`

**Comment by Lorenagubaira** [comment]
https://github.com/4GeeksAcademy/connecting-to-a-sql-database-project-tutorial/pull/23
https://github.com/4GeeksAcademy/web-scraping-project-tutorial/pull/18
https://github.com/4GeeksAcademy/interacting-with-api-python-project-tutorial/pull/16
