### ISSUE TITLE
Add node.js as a possible language in the MarkdownParser (including code viewer)

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7792]
https://github.com/breatheco-de/app/blob/main/src/common/components/CodeViewer.jsx

if you wind a code block for "node" or "node.js", it should hightlight like javbascript but it needs to say "Node.js in the codeviewer tab

**Comment by tommygonzaleza** [comment]
![Screenshot 2024-10-01 at 12 28 19 PM](https://github.com/user-attachments/assets/28195668-51ea-4bc1-8eb6-4745c3260e3d)
