### ISSUE TITLE
Agregar disclosure a web de Chema

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7796]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44512-3358949b4b87deab3173f3ea9a668bbb) 
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1915x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2161
