### ISSUE TITLE
Rediseño de interfaz de learnpack para standalone desktop

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7797]
Learnpack siempre habia funcionado dentro de vscode y se veia asi. Ahora queremos dejar de usar VSCode para la edicion de codigo e incorporar nuestro propio (pero sencillo) editor que debe tener ls siguientes funcionalidades:

En el modo desktop:
- A la izquierda deberia aparecer el codigo que debo editar para completar el ejercicio.
- Se me ocurre re-utilizar el diseño que se planteo para el CodeViwer (las pestañas) y la terminal que este debjo como ocurre en el CodeViewer.
- Hice [este pequeño ensayo para darte una idea](https://tinyurl.com/2xuz87ky).
- Revisar como se veria en modo movil tambien.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44513-0c830a533a6822d1080559cfc70e3224) 

---
**Source URL**:
[https://rigobot.ai/#currentExercise=1](https://rigobot.ai/#currentExercise=1)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by alesanchezr** [comment]
Falta la version movil
Falta la terminal

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=406-2&t=ljo8ef7X9kzjmprq-1

**Comment by tommygonzaleza** [comment]
- [ ] Add the terminal search `macos terminal` to see an example

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=406-2&t=3tWp9yAjOZC2rtzd-1

**Comment by tommygonzaleza** [comment]
- [ ] Terminar de definir el lightmode y darkmode

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=960-1561&t=36KAbHk4hogTLWfM-1

**Comment by tommygonzaleza** [comment]
- [ ] add a version with the terminal on darkmode

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=406-2&t=GY2mMojeTsMD4sTK-1
