### ISSUE TITLE
Evitar que el scrollbar del code viewer se active si el codigo es pequeño

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7798]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/31459306?key=0177b05eab290cc7bd19292829dd6d33&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/31459306?key=0177b05eab290cc7bd19292829dd6d33

**Comment by MadamSagas** [comment]
Evitar que el scrollbar del code viewer se active si el código es pequeño.

Cuando reviso las guías de la lecciones, la parte que lleva el código en las lecciones, no tiene scroll bar.
