### ISSUE TITLE
New design for certificate landing page

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7811]
New 4Geeks branding

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44601-d9c8fd5aaaaeb091e033ea2e8a77b9d6) 

---
**Source URL**:
[https://certificate.4geeks.com/07d337ab332f79383002d1f7cf722e3642289a40](https://certificate.4geeks.com/07d337ab332f79383002d1f7cf722e3642289a40)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Add new facebook icon

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=1432-99915&t=CeeWJ6JDAhIngZAG-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7835
