### ISSUE TITLE
The recommended material should be organized

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7815]
The recommended material's assets should be sort in this order: LESSON, ARTICLE, EXERCISE, PROJECT

<img width="1098" alt="Screenshot 2024-09-19 at 1 23 48 PM" src="https://github.com/user-attachments/assets/e40bfb9f-eeaa-42fe-a0e2-9f185484a683">

**Comment by JennGuz** [comment]
Done in this PR: https://github.com/breatheco-de/app/pull/1625
https://github.com/user-attachments/assets/b8780494-a400-4e18-a4f8-422c2ec5e1fd
