### ISSUE TITLE
Arreglar listas y definir estrategia discovery leads

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7826]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44718-51a93646ee0e18f35999894d172e682d) 

---
**Source URL**:
[https://app.brevo.com/contact/list-listing](https://app.brevo.com/contact/list-listing)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1775x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Done:

![Screenshot 2024-09-26 at 11 48 07 AM](https://github.com/user-attachments/assets/b7998813-e2b4-4a2a-86b8-61770e26855e)
