### ISSUE TITLE
Modify the consumables balance logic for non saas students

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7831]
We should have a JSON file in the API where we can easily add the services that we want the BootCamp users (non-saas users) to have unlimited consumables.

The file should be named `non_saas_consumables.json` and it should have a structure similar to this:

```json
[
    {
         "service": 48,
         "mentorship_service_set": "",
         "event_type_set": ""
    },
    {
         "service": 52,
         "mentorship_service_set": 1,
         "event_type_set": ""
    },
    {
         "service": <service_id>,
         "mentorship_service_set": <mentorship_service_set_id | "">,
         "event_type_set": <event_type_set_id | "">
    },
]
```

Then we should use these services to generate the structure of service items with unlimited amount and that never expires, and when a non-saas user do a request to the endpoint `GET /v1/payments/me/consumables` it should include these services as consumables for them.

And we should take these services/consumables into account for the consumption logic

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1470

**Comment by tommygonzaleza** [comment]
- [ ] We shouldn't only bypass the consume but we should also include the consumables that we create in a JSON in the consumables object

**Comment by tommygonzaleza** [comment]
- [ ] Add consumption logic to avoid consuming if the user is non-available as saas and this service is one of the services in the JSON file.
