### ISSUE TITLE
Zapier - Trigger is not working: Student: Educational status updated 

### ISSUE THREAD

**Issue by ehiber** [breatheco-de/breatheco-de#7832]
### Bug description

El zap dejó de ejecutarse, he actualizado a la versión más actual, sin embargo , al testear obtengo este error, se puede "skipear" pero siguen sin ejecutarse el trigger. 

El error el zapier tras intentarlo testear
![image](https://github.com/user-attachments/assets/29d92a48-350e-4f97-b8b2-1cc5990ce003)

### Steps to reproduce

Probar el trigger en zapier y similar las condiciones para que se ejecute, en mi caso:

Status GRADUATED
Course status ENDED

**Comment by alesanchezr** [comment]
Pero que zap es este?
