### ISSUE TITLE
Use rigochat plugin on 4geeks.com

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7834]
Here is the documentation: https://www.npmjs.com/package/rigobot-chat-bubble

We need to initialize rigobot inside the services folder in a new file named `/common/services/rigobot.js`.

Here we are going to use a Singleton architecture in order to initialize it only once, but updating the context on the pages we need.

Here is the code to initialize Rigobot:

```js
window.rigo.init("0839749d0baa4a51ac165d40b98f95f3", {
  context: "",
});
```

Then when the session loads we should start updating the context using this code and providing all the information in text format:

```js
rigo.updateContext({
  override: true,
  payload: "",
})
```

We should share as much information as we can about the user. Roles, Academies, Cohorts, Syllabus they have access to, when they joined, etc.

**Comment by alesanchezr** [comment]
esperar por charly proque esta dando un bug y no abre bien

**Comment by tommygonzaleza** [comment]
- [ ] Change the purpose to this id `43`.
- [ ] It should be hidden or not working at all by default.
- [ ] We should be able to turn it on or off through querystring like this `?showRigobot=true|false`
