### ISSUE TITLE
Redesign of certificates landing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7835]
Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=1432-99915&t=CeeWJ6JDAhIngZAG-1

This is the repo: https://github.com/breatheco-de/documents

**Comment by JennGuz** [comment]
https://github.com/breatheco-de/documents/pull/46

**Comment by tommygonzaleza** [comment]
- [ ] In the mobile version the padding should be equal throughout the entire page
- [ ] The content should be inside a max-width of 1280px

**Comment by JennGuz** [comment]
https://github.com/breatheco-de/documents/pull/46
