### ISSUE TITLE
Redesign of cohort's dashboard with subcourses

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7836]

**Comment by tommygonzaleza** [comment]
- [ ] Agregar varios modulo adentro de cada micro curso desplegable.
- [ ] Utilizar colores diferentes por cada modulo

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=1741-88248&t=sI55kaB46faESjot-1

**Comment by tommygonzaleza** [comment]
- [ ] Add tooltip to check what the assignments are about as we removed the labels.
- [ ] Add version that shows the top smaller to show more modules

**Comment by tommygonzaleza** [comment]
Se va a desarrollar [aqui](https://github.com/breatheco-de/breatheco-de/issues/7592)
