### ISSUE TITLE
Why are we recomending Full Stack on this lesson instead of Data Science?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7841]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-44747-88d201a7a4d8fde4e6eac6d7220a43b8) 

---
**Source URL**:
[https://4geeks.com/lesson/how-to-train-ai](https://4geeks.com/lesson/how-to-train-ai)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1711x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>0.9</td></tr></table>

**Comment by tommygonzaleza** [comment]
we were missing some of those technologies in the course table
