### ISSUE TITLE
You can access the program even if the trial expired

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7845]
You can access the program even if the trial expires if you access the program link directly.

- [ ] If the cohort is saas, then we should validate that the user has an active subscription that gives them access to this cohort.

---

## Tests:

```md
- [ ] Join the full stack program using the free trial (You should have the free trial subscription active), it should let you access the program
- [ ] Get in the cohort with the paid plan financing with status active, it should let you access the program.
- [ ] Get in the cohort with the paid plan financing of a different plan with status active, it shouldn't let you access.
- [ ] Try getting into the cohort using the link of the cohort with the plan expired, it shouldn't let you access.
- [ ] Try getting into the cohort using the link to one of the lessons, it shouldn't let you access
```

**Comment by tommygonzaleza** [comment]
I added a code review

**Comment by WinstonLesuT** [comment]
## Tests

The user for testing was [WJL Tester](https://breathecode-test.herokuapp.com/admin/payments/subscription/1647/change/) and this is the [cohort](https://breathecode-test.herokuapp.com/admin/admissions/cohortuser/21159/change/)


- [x] Join the full stack program using the free trial (You should have the free trial subscription active), it should let you access the program
- [x] Get in the cohort with the paid plan financing with status active, it should let you access the program.
- [x] Get in the cohort with the paid plan financing of a different plan with status active, it shouldn't let you access.
- [x] Try getting into the cohort using the link of the cohort with the plan expired, it shouldn't let you access.
- [x] Try getting into the cohort using the link to one of the lessons, it shouldn't let you access

**Comment by tommygonzaleza** [comment]
- [ ] The error should be shown before we finish loading the content
