### ISSUE TITLE
Show a modal to connect to rigobot if you are not connected 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7846]
Show a modal to connect to rigobot if you are not connected in the guided experience, currently it gives you an error and logs you out

**Comment by alesanchezr** [comment]
Instead of taking you to the profile, we should handle the Rigobot connection directly from the modal window.

Also, the kodal should say to connect to github first and only show the connection to Rigobot if I'm already connected to github.

**Comment by alesanchezr** [comment]
If the new window that authenticates with rigobot is closed, we can detect and that and check for rigobot connection again.

```json
function openLoginWindow() {
    // Open the new window
    const loginWindow = window.open('https://login.example.com', 'Login', 'width=500,height=600');

    // Periodically check if the window is closed
    const checkWindowClosed = setInterval(() => {
        if (loginWindow.closed) {
            clearInterval(checkWindowClosed); // Stop checking once the window is closed
            console.log('Login window has been closed.');

            // Handle what should happen when the window is closed
            // For example, redirect the user, trigger an action, etc.
        }
    }, 500); // Check every 500 milliseconds (0.5 seconds)
}

```

**Comment by alesanchezr** [comment]
Epa!!! Pentiende de un memory overflow!!!
https://chatgpt.com/share/6719043b-db7c-800e-9a0f-106836251d21

**Comment by tommygonzaleza** [comment]
- [ ] There is a code commented, can we just remove it?
