### ISSUE TITLE
Change layout when applying discounts in checkout 

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7860]
It should look like this:
<img width="1242" alt="Screenshot 2024-10-08 at 4 56 54 PM" src="https://github.com/user-attachments/assets/51f73fd7-fa7e-4360-bb14-ffd59625cccd">

The layout is the same if it has one or two discounts applied

**Comment by tommygonzaleza** [comment]
Here is the new design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=Qi74iEUK73nWolSw-1

**Comment by tommygonzaleza** [comment]
- [ ] The dropdown should look like this:
![Screenshot 2024-11-05 at 12 45 15 PM](https://github.com/user-attachments/assets/f2c9997b-267f-4657-9b6d-5b0486b33981)

**Comment by Cristian2499** [comment]
working good

![image](https://github.com/user-attachments/assets/b15ca916-01cf-489b-96a0-925f8a5b9cd6)

**Comment by tommygonzaleza** [comment]
- [ ] All number should have two decimals on the subtotal and stuff
![Screenshot 2024-11-18 at 1 16 45 PM](https://github.com/user-attachments/assets/d2dac51d-f578-4f38-b244-b76ab5f9d4c8)

**Comment by tommygonzaleza** [comment]
- [ ] It should look like this when you select a financing option
![Screenshot 2024-11-19 at 11 06 37 AM](https://github.com/user-attachments/assets/eb807322-ab08-496a-ad59-42f301ac83e8)

**Comment by lumi-tip** [comment]
issue of allowing users to go back to paymentInfo after an error in the payment should be fixed here
reference: https://github.com/breatheco-de/breatheco-de/issues/8006
