### ISSUE TITLE
We should allow translations on syllabus modules

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7862]
Syllabus modules will now have the following structure for titles and descriptions:

```json
{
	"description": {
     		"es": "",
  		"us": ""
	},
	"title": {
     		"es": "",
  		"us": ""
	}
}
```

Anyway, if it doesn't have the "us" or "es" property, it will show the value directly instead of an object (Which is how it is at this moment), if that's the case we should still show the description or title value.

**Comment by alesanchezr** [comment]
corrigue el PR par aponer la funcion de fix y prueba modificando el json y me avisas.

**Comment by lumi-tip** [comment]
You can do the tests with `full-stack-pt-18w/v3` edited module is `HTML Forms`

test user token: [900db58abb60eed099038be05ab94b2be07062a9](https://breathecode-test.herokuapp.com/admin/authenticate/token/545013/change/)

**Comment by KonnorThatcher** [comment]
The title and description of the HTML Forms module is still in English when the user's language is "es". [This](https://breathecode-test.herokuapp.com/admin/admissions/cohortuser/21226/change/) was the cohort user I got this result with.

![Image](https://github.com/user-attachments/assets/870d0f52-43f0-4b01-941f-322c5be79bea)

**Comment by WinstonLesuT** [comment]
Only the "HTML Form" module changes the description and title to spanish when the user's language is "es"

![Screenshot 2024-10-17 213708](https://github.com/user-attachments/assets/7eeb2d3d-cd3f-4841-8e35-532145e1138e)

**Comment by lumi-tip** [comment]
That's the only module i changed in the development to do the tests the rest modules mantain the previous structure, it is good that still works.

**Comment by WinstonLesuT** [comment]
ohh, okay, sorry. I thought the changes have been applied to all modules when I tested the first time.
thanks for clarifying!
