### ISSUE TITLE
Error 400 plan already acquired

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7871]
- First, create a user witha basic plan
- Second, the user buys the plan with-feedback
- then, the user cancels the plan with-feedback
- the user tries to reactivate the plan with-feedback but it throws an error 400.

**Comment by jefer94** [comment]
There are so many errors inferred by the frontend, it could be more accurate using silent errors
![image](https://github.com/user-attachments/assets/3d6d07e7-d3b3-4ecf-80dd-f4361127c0ac)

For
![image](https://github.com/user-attachments/assets/db0d9f1a-f303-4d54-8201-2f9a374c5ad4)

It returns
![image](https://github.com/user-attachments/assets/f5389734-9c7d-45a2-9eff-de4e83a3517c)

And then cause
![image](https://github.com/user-attachments/assets/c55950dd-5517-4170-b88c-26f699238b99)
![image](https://github.com/user-attachments/assets/ae377298-ce1a-479c-823c-e562cee8b62e)

I'm looking for that error

**Comment by jefer94** [comment]
![image](https://github.com/user-attachments/assets/a2d49b66-a243-4930-a94f-601066ab34d5)

**Comment by jefer94** [comment]
Also the conditional was fixed `You already have a subscription to this plan`
