### ISSUE TITLE
Formato de cuenta regresiva es deberia decir solo los dias a menos que sea hoy

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7872]
Si es dentro de una semana entonces dice: `X` days and `Y` hours

Si es mañana dice:  2 days and `Y` hours

Si es en menos de 24 horas dice:  `X` hours and `Y` min

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45076-b8bd2474c739f3d83f80677376f2d2e9) 

---
**Source URL**:
[https://app-git-fork-gustavomm19-rigochat-geeksacademy.vercel.app/bootcamp/full-stack-development?internal_cta_placement=navbar-full-stack-development](https://app-git-fork-gustavomm19-rigochat-geeksacademy.vercel.app/bootcamp/full-stack-development?internal_cta_placement=navbar-full-stack-development)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1728x1117</td></tr><tr><td><strong>Viewport Size</strong></td><td>1708x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] It should show days and minutes instead of months and minutes. Check the other scenarios as well
<img width="1467" alt="Screenshot 2024-10-24 at 9 34 31 AM" src="https://github.com/user-attachments/assets/ee9b68c3-a113-40a4-ac28-8bf6a7a4da4e">

**Comment by WinstonLesuT** [comment]
When 2 or more months (**just the months with no days**) are left. It's saying the months and same in days.

- [ ] It should say how many months are left.

![image](https://github.com/user-attachments/assets/a83d8d7e-2e16-4cfe-92be-f96fdc602554)
