### ISSUE TITLE
Redesign when applying two coupons in the checkout view

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7891]
I thought on a solution like this one, but I think it is a bit overcrowded:
![image](https://github.com/user-attachments/assets/69b0eed3-4c9a-4113-aaaf-7c92b280fd11)

It should have a clear explanation of discounts applied, what the course original price and what the total with discount is

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563-3760&t=Qi74iEUK73nWolSw-1

**Comment by tommygonzaleza** [comment]
It will be developed here: https://github.com/breatheco-de/breatheco-de/issues/7860
