### ISSUE TITLE
En el proyecto de NAT de Ciberseguridad, falla la creación del codespaces del proyecto

### ISSUE THREAD

**Issue by marcogonzalo** [breatheco-de/breatheco-de#7900]
### Bug description

El contenedor del proyecto falla en la carga y se levanta en "Recovery mode". Pareciera que no logra descargar unos archivos.

Parece ser un error en la configuración del contenedor de Codespaces de este proyecto
<img width="1509" alt="Screenshot 2024-10-28 at 12 42 45" src="https://github.com/user-attachments/assets/eccf27d6-2234-4a33-9947-56a2d2f3564b">

### Steps to reproduce

Ir a https://4geeks.com/syllabus/spain-cs-pt-2/project/creating-nat-network-virtualbox y darle a Open in the cloud y esperar a que haga todo el proceso. 

### Anything else?

Revisar en el Creation log toda la traza

**Comment by alesanchezr** [comment]
Es porque debe abrirse en lcoalhost
