### ISSUE TITLE
agregarle model solution a los ejercicios del syllabus

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7907]

**Comment by rosinni** [comment]
- Crea porfa una rama solution a este ejercicicio para hacerle PR de lo mio: https://github.com/rosinni/exercise-landing-page-with-react/tree/solution
- Acepta este PR: https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/81
- Crea una rama solution a este ejercicico tambien para hacer este PR: https://github.com/rosinni/exercise-traffic-light-react/tree/solution
- Acepta es PR: https://github.com/breatheco-de/exercise-todo-list/pull/17

**Comment by rosinni** [comment]
- Acepta este PR: https://github.com/breatheco-de/exercise-simple-counter-react/pull/16

**Comment by rosinni** [comment]
- Hazle una Rama solution al repo original para hacer el PR: https://github.com/rosinni/python-flask-api-tutorial/tree/solution
- Acepta este PR: https://github.com/breatheco-de/exercise-starwars-data-modeling/pull/55
- Hazle una Rama solution al repo original para hacer el PR: https://github.com/rosinni/exercise-instagram-data-modeling/tree/solution

**Comment by rosinni** [comment]
- Hazle una Rama solution al repo original para hacer el PR: https://github.com/rosinni/exercise-starwars-blog-api/tree/solution

**Comment by rosinni** [comment]
- Hazle una Rama solution al repo original para hacer el PR: https://github.com/rosinni/exercise-contact-list-context/tree/solution
