### ISSUE TITLE
Remove captcha badge and add a banner in the bottom

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7912]
The banner should look like this one: <img width="1446" alt="Screenshot 2024-10-29 at 4 20 31 PM" src="https://github.com/user-attachments/assets/c49f6baf-fb4b-454b-823f-92b4edf1aa23">

**Comment by gustavomm19** [comment]
Instead of the proposed solution, Google requires us to include a link to their privacy policies. https://developers.google.com/recaptcha/docs/faq?hl=es-419#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
