### ISSUE TITLE
Create Public Technology view

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7920]
## Frontend:

Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=15476-14710&t=wIsC5B5bEXqUDyf4-1

## Backend

- [ ] Add field on AssetTechnology model:
     - MarketingInformation: JSONField, will have this structure:

#### If it has translation (It will have translation if the AssetTechnology doesn't have a lang)

```json
{
     "title": {
           "us": "Practice python",
           "es": "Practica python"
     },
     "description": {
           "us": "Practice python and the rest of the description",
           "es": "Practice python and the rest of the description"
     },
     "video": {
           "us": "videourl",
           "es": "videourl"
     }
}
```

#### If it DOESN'T have translation (It won't have translation if the AssetTechnology has a lang):

```json
{
     "title": "Practice python",
     "description": "Practice python and the rest of the description",
     "video": "URL"
}
```

- [ ] Add unit tests to this new field.
- [ ] Include this new field in the most specific serializer we have (Maybe you should create a new one, if there is no serializer for getting a specific technology).
- [ ] Add URL: `GET /v1/registry/technology/<tech_slug>`

**Comment by tommygonzaleza** [comment]
- [ ] I added some comments on the api's PR

**Comment by tommygonzaleza** [comment]
- [ ] Reuse the /workshops carousel component.
- [ ] Include the selected technology inside the technologies carousel, but keep first and with the color and name
- [ ] When clicking on the Request mentorship button if they're not logged in, we should send them to: `/pricing?plan={process.env.BASE_PLAN}`. If they are logged in, we should send them to `/mentorship/schedule`.
- [ ] The `{technology} roadmap` button should be added only if there is a course that includes that technology, and it should redirect you to that course's landing. Use this endpoint to check if there is a cohort: `GET /v1/marketing/course?technologies={technology}`. If there is no course then we are going to show only the button of Request a mentorship and with primary styles

**Comment by lumi-tip** [comment]
Technologies to see the big differences are: Python, flask and html

**Comment by tommygonzaleza** [comment]
- [ ] All the technology icons should have the same color and size
- [ ] Only show the technologies that have sort_priority=1, visibility=PUBLIC, is_deprecated=False
- [ ] When clicking on a different technology the slider should reset and take you to the first technology

**Comment by tommygonzaleza** [comment]
- [ ] The fontsize of the icons should be smaller
- [ ] Icons should be smaller as well
- [ ] There should be less space between the line, name and icon
