### ISSUE TITLE
Landing para resevar/pagar esta muy 

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7927]
Este es el diseño original: https://github.com/user-attachments/assets/844ccf74-3503-4bcb-8799-b785897b347e

Esta es la implementacion: https://github.com/user-attachments/assets/c59348dd-5561-448d-bad4-84ab25130516

Tienen que ser iguales.

**Comment by G-code7** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2189
