### ISSUE TITLE
Checkbox al momento de hacer deliver

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7934]
I confirm that this submission is entirely my own work, and I understand the consequences of violating the academy terms and conditions.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45338-8c997348e46e629a4d5cc43a76ffeb61) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-45/full-stack/v7](https://4geeks.com/cohort/miami-45/full-stack/v7)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1866x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1.1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] Make the entire text clickable
