### ISSUE TITLE
Evitar que el nombre del modulo se salga del contenedor con text-overlfow:elipsis

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7940]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45367-160d38f386bbf7450fe0653d96281e94) 

---
**Source URL**:
[https://4geeks.com/syllabus/4geeks-fs-1/practice/html-exercises](https://4geeks.com/syllabus/4geeks-fs-1/practice/html-exercises)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1883x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1.1</td></tr></table>

**Comment by tommygonzaleza** [comment]
Ya esta resuelto
