### ISSUE TITLE
Mejoras a estilos de boton "Start Exercise"

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#7947]
- [x] El boton va a decir "Start interactive exercise" o "Start interactive project" dependiendo del tipo de asset.
- [x] El boton debe tener una flechita
- [x] El mouse encime debe ser una manito (pointer)

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45370-5cb43724e98156d047a18cf23fc48da6) 

---
**Source URL**:
[https://4geeks.com/syllabus/4geeks-fs-1/practice/html-exercises](https://4geeks.com/syllabus/4geeks-fs-1/practice/html-exercises)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 126.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x942</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1.1</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] It's not showing the start interactive exercise button even if it has learnpack_deploy_url
![Screenshot 2024-11-07 at 10 58 42 AM](https://github.com/user-attachments/assets/fc1670d6-f317-4701-875b-6850dfb4e3f1)
