### ISSUE TITLE
The "open in the cloud" button is missing in some modules.

### ISSUE THREAD

**Issue by loveradrian28** [breatheco-de/breatheco-de#7957]
In the practice modules the button to open the codespaces directly in GitHub does not appear. 
I make the list:
-Learn the basics of HTML Interactively
![image](https://github.com/user-attachments/assets/3335b2e1-dd96-4039-8604-233ccc1cedea)

-Learn CSS Interactively
![image](https://github.com/user-attachments/assets/c9b04044-1fb7-4e46-a656-a1cdb36ca648)

-Build Website Layouts with CSS: In this module the "open in the cloud" button does appear in English, but not if the page is translated into Spanish.
![image](https://github.com/user-attachments/assets/09f0c7ff-651b-4c80-8977-8e77b9ec83ba)
![image](https://github.com/user-attachments/assets/ac44c9df-275a-499c-8750-d2233201d91b)

-Javascript Beginner Tutorial (interactive): In this module the "open in the cloud" button does appear in Spanish but if you have the page in English it does not.
![image](https://github.com/user-attachments/assets/b34360fa-26bd-4214-8f06-ebf7982f9830)
![image](https://github.com/user-attachments/assets/47f9235b-c407-479a-bbcb-7d9f6bd33276)

**Comment by tommygonzaleza** [comment]
Hello! It was solved this morning, let me know if you still have the issue
