### ISSUE TITLE
If there is a discount, apply it to all financing options

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7963]
These financing options should have the price with discount
<img width="1327" alt="Screenshot 2024-11-07 at 2 46 35 PM" src="https://github.com/user-attachments/assets/eca4f56c-9b55-4461-b600-3e58dafa5d35">

**Comment by tommygonzaleza** [comment]
- [ ] The discount could be a percentage or an amount, make sure it works for both

**Comment by tommygonzaleza** [comment]
- [ ] When the discount is an amount it shouldn't discount that amount on each month when financed. It should only apply that discount in the first month, or maybe apply it divided in all the financed options. We should ask Jeferson how it works on the backend

**Comment by WinstonLesuT** [comment]
### It's working as it should.

**Comment by Cris9898** [comment]
It's working good

**Comment by tommygonzaleza** [comment]
- [ ] Change the disclaimer to this text: Fixed price discounts will only be applied to the first month when financed for more than one month. Percentage discounts will be applied to all months.

**Comment by KonnorThatcher** [comment]
When the discount is PERCENT_OFF, the card is missing information to show that the current price is a discount and not the standard price.
![Image](https://github.com/user-attachments/assets/40ee389c-667b-469c-9dab-bfe6470e5883)

This is how it looks when the discount is FIXED_PRICE:
![Image](https://github.com/user-attachments/assets/57e7f5da-c3aa-4e82-bf90-13cd17d3ffd8)
