### ISSUE TITLE
Add changes to guided experience, it's different than the design

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7978]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=1139-7046&t=cevm6C5QJ1SL9I1y-1

![Screenshot 2024-11-12 at 1 10 32 PM](https://github.com/user-attachments/assets/c045991f-7c0a-4764-8914-741b68c1929a)

**Comment by lumi-tip** [comment]
i requested permission to enter the desing, but i will work with the guidelines in the picture

**Comment by WinstonLesuT** [comment]
The changes have been applied, I'm not sure about the arrow next to **Back to program** tag. I don't have the permission to enter the design but it looks clear!

![Screenshot 2024-11-17 issue 7879](https://github.com/user-attachments/assets/133ff9ae-918c-46d3-96e0-9ad39f66bfac)

**Comment by lumi-tip** [comment]
The "X" on "Back to Program" will be an `arrowLeft` 👍
