### ISSUE TITLE
Redesign learnpack quizzes

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7993]
Improve the style of the buttons, selected options, celebration, etc

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/d125akVdljVYGZ82DBarMx/Learnpack-New-UI?node-id=406-2&t=u8hC41y3aFNHx9Ti-1

**Comment by tommygonzaleza** [comment]
- [ ] The quizzes could be inside some instructions, add that version to make it obvious it can exist
