### ISSUE TITLE
Show instructions to open a project locally

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#8002]
Now the project's assets include a template_url value that will be the repository they should clone.

Then, use the property `asset.dependencies`, which will be comma-separated dependencies needed to run the project, they will look like this: python=3.10,node=16.0.

> The version could be unknown, if that's the case only specify to install the dependency without specifying the version.

We should have a step with fixed instructions for each dependency, and they will be just like we have them on learnpack where we have a step to install node.

## Steps:

The steps should be in this order:

- Clone repository locally. (Use the `asset.template_url` as the repo url)
- Install dependencies (Each dependency on a different step, and the text structure should be like the install node instructions step for learnpack).
- Read the readme carefully to understand how to run the project. You can include in the text to open the README.md in their language (README.es.md in Spanish), and that they can open it in preview mode instead of the md format.

## When to show these instructions:

- If the project doesn't have `asset.template_url`, we should remove the button that says `Open locally in your computer`, and change it to a button that says see instructions that take them to the readme below.
- If the project has `asset.template_url` but `asset.dependencies` are empty, then you will only show the modal with the steps to clone it locally and the step to read the readme.
- If the project has `asset.template_url` and `asset.dependencies`, then you show the instructions as described on top.

**Comment by tommygonzaleza** [comment]
- [ ] You should add an additional step that tells them to open the README.md file in their code editor to follow the instructions about what they should do to run that template correctly

**Comment by tommygonzaleza** [comment]
- [ ] It shouldn;t be inside the learnpack box as the project doesn't use learnpack. It should be only the button
<img width="1003" alt="Screenshot 2024-11-22 at 12 59 37 PM" src="https://github.com/user-attachments/assets/56dc0ec6-7cc3-402d-8d7d-81f8ac481bfa">

**Comment by tommygonzaleza** [comment]
- [ ] It's not showing the button to open it in the iframe mode.

**Comment by WinstonLesuT** [comment]
Tested with this [user](https://breathecode-test.herokuapp.com/admin/payments/subscription/1858/change/) as a saas student. The user is part of this [cohort](https://breathecode-test.herokuapp.com/admin/admissions/cohortuser/21392/change/). But the user doesn't have access to all privileges. 

- It shows the next message:

![image](https://github.com/user-attachments/assets/d921149e-f293-4d45-9a31-932007d358fb)

- It also doesn't allow to do the interactive or the practice exercises.

![image](https://github.com/user-attachments/assets/3797a1f4-96c1-44d5-809b-09898b4dab7b)

**Comment by Cristian2499** [comment]
working good
