### ISSUE TITLE
Payment with a card failed and "Try again" button doesn't work

### ISSUE THREAD

**Issue by WinstonLesuT** [breatheco-de/breatheco-de#8006]
### Bug description

If the user makes a mistake introducing the card information and the payment fail. It does not allow the user to try again another pay method or even try an introduce the card information again.

https://github.com/user-attachments/assets/c7522381-45ab-457c-b5e5-504b52b62df8

### Steps to reproduce

- Create a user with the basic plan (not testing with the user that has a free trial)
- Upgrade the subscription to the one with feed back
- Select card as a payment method
- Put an invalid expiration date in the field. Put a month number that doesn't exist
- Bug should be replicate

### Expected behavior

It should allow the user to introduce the card information again or at least give them the option to change the payment method.

### Anything else?

If you go back to your dashboard and try to buy the bootcamp is going to give you the same error.
Also, if the user goes to ".../profile/subscriptions" and click on **Upgrade subscription** the error will persist.

**Comment by KonnorThatcher** [comment]
After failing the payment and being brought back to the screen to fill in your card info, if you click on and then click off any of the input fields without making any changes to that field or if you completely ignore any of the fields you didn't need to fix, it will tell you "[Info] is required" even though it kept the information from when you previously filled it out.

https://www.loom.com/share/97decd83fe0945b8bb1311f79c80537d?sid=e233ed33-96fd-4a8c-8a6e-5d1292773092

**Comment by tommygonzaleza** [comment]
- [ ] This modal should open the card payment method when clicking on try again
<img width="1232" alt="Screenshot 2024-11-26 at 11 01 18 AM" src="https://github.com/user-attachments/assets/e5e7bfd6-9ce3-4e26-b413-95b29ca25e0f">

**Comment by Cristian2499** [comment]
![image](https://github.com/user-attachments/assets/be52ef15-043d-47a7-8c14-7cb969aa11a0)
when I press the try again button nothing happens. It does not redirect me to enter the card information again.

**Comment by lumi-tip** [comment]
Try again button should only close the modal

**Comment by KonnorThatcher** [comment]
Still getting the bug in which I get a "[Info] is required" error for a field that's already filled in after returning from a failed payment, except now it's only happening with the CVC input field.

![Image](https://github.com/user-attachments/assets/48e9795d-c2a2-4624-802a-3ef26197bfaf)

**Comment by lumi-tip** [comment]
that field will reset after the user click try again 👍
