### ISSUE TITLE
El material recomendado en `how-to-concatenate-strings-on-python` deberia ser el de python for beginners

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8036]
Habiamos acordado que los ejercicios de learnpack vienen primero porque convierten mas.

Entonces este deberia ser [este learnpack](https://4geeks.com/interactive-exercise/python-beginner-exercises) de python begiiners..

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45651-49cd054e260aad0e6a79ef3974567930) 

---
**Source URL**:
[https://4geeks.com/how-to/how-to-concatenate-strings-on-python](https://4geeks.com/how-to/how-to-concatenate-strings-on-python)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by rosinni** [comment]
Listo: https://github.com/breatheco-de/content/blob/master/src/content/how-to/how-to-concatenate-strings-on-python.md


A esta lectura le falta la traducción al español ¿Quieres que se la haga? @alesanchezr

**Comment by alesanchezr** [comment]
si de una, agreg ala traducicon

**Comment by alesanchezr** [comment]
falta agregar traduccion y asegurarse con el re-deploy que este sugiriendo python beginner

**Comment by rosinni** [comment]
resuelto y publicado: https://4geeks.com/es/how-to/como-concatenar-cadenas-en-python
