### ISSUE TITLE
Alinear botones de abrir en learnpack a la izquierda

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8040]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45683-d1f3bf5170fed8f70473a9671dc2cb12) 

---
**Source URL**:
[https://4geeks.com/syllabus/cybersecurity-prework/practice/installing-windows-on-virtual-machine](https://4geeks.com/syllabus/cybersecurity-prework/practice/installing-windows-on-virtual-machine)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by Cristian2499** [comment]
working good

**Comment by Cris9898** [comment]
It's working fine
