### ISSUE TITLE
Por que este ejercicio de "Introduction to Packet Tracer" tiene learnpack?

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8041]
[El learn.json](https://github.com/4GeeksAcademy/intro-packettracer/blob/main/learn.json#L11) tiene projectType: project que se usa cuando no son interactivos. Y el backend parece eestar bien porque asset.interactive = False

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45684-02fdf6a55f5f313dd8a7781bece038c4) 

---
**Source URL**:
[https://4geeks.com/syllabus/cybersecurity-prework/project/intro-packet-tracer](https://4geeks.com/syllabus/cybersecurity-prework/project/intro-packet-tracer)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by tommygonzaleza** [comment]
It has a conflict

**Comment by tommygonzaleza** [comment]
- [ ] On saas cohorts the button to open in LearnPack dissapeared
<img width="1470" alt="Screenshot 2024-12-02 at 10 24 34 AM" src="https://github.com/user-attachments/assets/47605149-b638-4829-8b78-b548ad9b8dcd">
