### ISSUE TITLE
Improve algorythm that decides which technology to show

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#8043]
Depending on how many technologies the course has, each technology will have less or more value. The sum of all the technologies' values should be 1. Then if the course has 2 technologies, each weights 0.5. If the course has 3 technologies each weights 0.33. If the course has only one technology, then the technology weights 1.

We should try to match the technologies of the asset with the technology of the course that has the most weight

**Comment by lumi-tip** [comment]
curso1: python, flask | curso2: python, base-de-datos, sql, flask ==> asset = flask, python ==> elijo curso 1,
curso1: python, flask | curso2: python, base-de-datos, sql, pandas ==> asset = sql, pandas, ==> python elijo curso 2,

**Comment by tommygonzaleza** [comment]
This asset should recommend full stack as it has more technologies in common: https://4geeks.com/lesson/python-api-flask-template

**Comment by tommygonzaleza** [comment]
This asset should recommend full stack or flask tutorial: https://4geeks.com/lesson/python-api-flask-template

full stack technologies: html-css,javascript,reactjs,python,flask,front-end,
