### ISSUE TITLE
Certificate's layout is not working fine for saas certificate

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#8054]
![image](https://github.com/user-attachments/assets/0d755651-9a47-46ac-97f3-231548c65533)

Full Certificate: https://storage.googleapis.com/certificates-breathecode/c6a94ae0dd8bdac807595e3523c900b3658633f1

We should align the items exactly how they are in the other certificate

**Comment by ali5uarez5** [comment]
https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3285-14836&t=oKEwDADsoAKUIynl-1
