### ISSUE TITLE
Lesson alias not working

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8075]
- The spanish lesson `linea-de-comandos-la-terminal` has an alias `the-command-line-the-terminal-es`. 
- All alias should redirect to the original lesson.
- Which means that this [old url](https://4geeks.com/es/lesson/the-command-line-the-terminal-es) should redirect to [this url](https://4geeks.com/es/lesson/linea-de-comandos-la-terminal).

Why is it not working?

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45890-86c6ca56cac1b123e4d329ee0ca8f3c7) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset/linea-de-comandos-la-terminal](https://admin.4geeks.com/media/asset/linea-de-comandos-la-terminal)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1923x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by lumi-tip** [comment]
In `alias-redirect.json` each item has thee following structure:

```
{
        "source": "/lesson/the-command-line-the-terminal-es",
        "type": "LESSON",
        "destination": "/es/lesson/linea-de-comandos-la-terminal"
    },
```

using https://4geeks.com/lesson/the-command-line-the-terminal-es will redirect to the [new url](https://4geeks.com/es/lesson/linea-de-comandos-la-terminal)

Should `source` have 'en' or 'es' at the beginning?
