### ISSUE TITLE
Se ven mal los quotes

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8083]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45901-124ba85a9eb14ca5f4f45c04294e530f) 

---
**Source URL**:
[https://4geeks.com/es/syllabus/4geeks-fs-1/read/what-is-debugging-code](https://4geeks.com/es/syllabus/4geeks-fs-1/read/what-is-debugging-code)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1923x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by lumi-tip** [comment]
There are 4 versions of the quotes, this versions are radomly shown to the user from one render to another, the one in the picture is version 4, what should I change from it?

**Comment by lumi-tip** [comment]
After a breaf conversation, v1 will be the one used.
