### ISSUE TITLE
El boton no tiene la manito

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#8084]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-45902-0261e889855f8b232926292ce8e1e1ed) 

---
**Source URL**:
[https://4geeks.com/es/syllabus/4geeks-fs-1/practice/bootstrap-exercises](https://4geeks.com/es/syllabus/4geeks-fs-1/practice/bootstrap-exercises)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 131.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1923x940</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>zoomLevel</strong></td><td>1</td></tr></table>

**Comment by lumi-tip** [comment]
solucionado en: https://github.com/breatheco-de/breatheco-de/issues/8082
