### ISSUE TITLE
The carousel shouldn't have that effect on dark mode

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#8096]
<img width="1470" alt="Screenshot 2024-12-12 at 4 54 15 PM" src="https://github.com/user-attachments/assets/601ad022-40a1-430d-b2ab-5870319e76ef" />

**Comment by Cristian2499** [comment]
when I try to enter the technologies I get this error. 
![image](https://github.com/user-attachments/assets/ab9cdf7c-8496-4356-b95e-89de966a72d1)

**Comment by lumi-tip** [comment]
Hi Cristian! That only happens on development server as there are no assets that has a technology related to them, it is an expected toast 🙌 👍
