### ISSUE TITLE
the button says to open locally but it should open it in iframe mode

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#8140]
![Screenshot 2024-12-19 at 3 48 05 PM](https://github.com/user-attachments/assets/894855bf-e82e-4960-afe2-f277012afc22)

**Comment by lumi-tip** [comment]
Looks like the spanish version of the asset does not have learnpack_deploy_url (looks like the one in the picture is the english version which does have learnpack_deploy_url and does not present the problem)

![Image](https://github.com/user-attachments/assets/a59f0a02-6d3e-4847-a6ca-1259f90885ae)

**Comment by WinstonLesuT** [comment]
### The button opens the iFrame mode

![image](https://github.com/user-attachments/assets/853ec276-8589-44ef-9ffa-1955398ce366)

![image](https://github.com/user-attachments/assets/964363d4-7cc1-46b0-b73f-db60976a76a6)

**Comment by WinstonLesuT** [comment]
The messages when you click on the buttons are in English, but the language is *ES*

![image](https://github.com/user-attachments/assets/6493af8c-1a18-4bc4-a497-ff59ec156d92)

**Comment by lumi-tip** [comment]
Hi Winston that is the expected behavior, the button should open in the iframe mode, the bug was happenning on production

**Comment by tommygonzaleza** [comment]
I reported this issue in order to be fixed on LearnPack: https://github.com/breatheco-de/breatheco-de/issues/8145, thanks @WinstonLesuT
